### ISSUE TITLE
Get original image size?  Very important!

### ISSUE THREAD

**Issue by Alexsmile2010** [kean/Nuke#102]
How get original image size, before compression?

**Comment by kean** [comment]
Could you elaborate? What are you trying to achieve?

**Comment by Alexsmile2010** [comment]
I load the image the same size 1080h1350 and put them in a smaller proportion to imageView compressed. After the image is loaded I need it to carry out additional actions, for example to draw the text. And I need to do on the original size and not compressed. 
Thank you)

**Comment by kean** [comment]
Ah, I see. Just create your [custom processor](https://github.com/kean/Nuke#processing-images) and replace the default `processor` on the `Request`:

```swift
var request = Request(url: ...)
request.processor = AnyProcessor(YourCustomProcessor())
```

**Comment by Alexsmile2010** [comment]
Thankx I will try it.

**Comment by Alexsmile2010** [comment]
Мы же можем говорить на понятном для нас обоих языке)

**Comment by kean** [comment]
Можно 😃 На английском лучше, потому что другие тоже смогут прочитать, если у них будет похожий вопрос.

**Comment by Alexsmile2010** [comment]
У меня с ним достаточно сложно так как боюсь не смогу объяснить суть вопроса и проблемы

**Comment by kean** [comment]
Спрашивай, конечно, на русском, если нужно.

**Comment by Alexsmile2010** [comment]
В общем суть в том что я когда загружаю картинку и сетю ее в таргет то она сжимается до размера таргета и это ок, но в дальнейшем мне нужно использовать эту картинку в ее оригинальном размере. Как получить оригинальный размер? И еще, иногда когда работаешь с большим количеством контента то некоторые ячейки начинают перезагружаться видимо после того как освобождается память, это можно как то предотвратить?

**Comment by kean** [comment]
> В общем суть в том что я когда загружаю картинку и сетю ее в таргет то она сжимается до размера таргета и это ок. 

Можно просто запросить оригинал отдельным вызовом. Картинка поднимется из дискового кеша (если он настроен).

И при желании практически все в Nuke можно кастомизировать. Например можно добавить обёртку на Decomprssor, которая будет проставлять в обработанную картинку оригинал, например ассоциативным объектом.

Вторую часть вопросов не до конца понял. Видимо зависит это про кеш в памяти. Его размер можно увеличить при необходимости. Или подставить кастомной.
