### ISSUE TITLE
Question regarding equatable of Processing Implementation

### ISSUE THREAD

**Issue by winkelsdorf** [kean/Nuke#104]
Hi,

Alexander, I wish you a Merry Christmas and thank you for all your support in 2016! 

I'm having some time to play around and refactor some Nuke related code in my projects.

I am using an UIImage Extension to remove (white) solid Backgrounds:
```swift
extension UIImage {

    fileprivate struct BackgroundRemovingUX {
        static let colorMask: [CGFloat] = [250, 255, 250, 255, 250, 255] // R, G, B start/end components 
    }

    /// Removes white background color from UIImage
    ///
    /// - Returns: UIImage with removed white background
    ///
    /// Heavily inspired by:
    /// 
    /// [http://darkcl.github.io/2015/01/10/background-removal/](http://darkcl.github.io/2015/01/10/background-removal/)
    func imageWithoutBackround() -> UIImage? {
        let rawImage = cgImage
        let imageRect = CGRect(x: 0, y: 0, width: size.width, height: size.height)

        guard let maskedImage = rawImage?.copy(maskingColorComponents: BackgroundRemovingUX.colorMask) else {
            return self
        }

        UIGraphicsBeginImageContextWithOptions(size, false, scale)

        guard let context = UIGraphicsGetCurrentContext() else {
            return self
        }

        // save the context so that it can be undone later
        context.saveGState()

        // put the origin of the coordinate system at the top left
        context.translateBy(x: 0, y: imageRect.size.height)
        context.scaleBy(x: 1.0, y: -1.0)

        // draw the image in the context
        context.draw(maskedImage, in: imageRect)

        // undo changes to the context
        context.restoreGState()

        let imageWithoutBackground = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageWithoutBackground
    }

}
```

Nothing fancy. Works as expected.

Until today I'd been using this by using your completionHandler: 
```swift
        Nuke.loadImage(with: url, into: productImageView) { [weak productImageView] response, isFromMemoryCache in
            guard let imageView = productImageView else { return }

            // keep previous image (dummy) if response is nil
            if case let .fulfilled(image) = response {
                // animate if not loaded from cache
                if !isFromMemoryCache {
                    let animation = CABasicAnimation(keyPath: "opacity")
                    animation.duration = 0.25
                    animation.fromValue = 0
                    animation.toValue = 1
                    imageView.layer.add(animation, forKey: "imageTransition")
                }

                imageView.image = image.imageWithoutBackround()
            }
        }
```

Of course this works fine. But I thought about simplifying the above code to:

```swift
        var request = Request(url: url)
        request.process(with: BackgroundRemoval())

        Nuke.loadImage(with: request, into: productImageView)
```

And `BackgroundRemoval` being implemented like this:
```swift
struct BackgroundRemoval: Processing {

    func process(_ image: UIImage) -> UIImage? {
        return image.imageWithoutBackround()
    }

    // `Processing` protocol requires `Equatable` to identify cached images
    // swiftlint:disable:next operator_whitespace
    static func ==(lhs: BackgroundRemoval, rhs: BackgroundRemoval) -> Bool {
        // return lhs.elementsEqual(rhs)
        return lhs.image.isEqual(rhs.image) // does not compile, how to equate the two?
    }

}
```

As far as I understood Nuke is going to cache the processed Images when using a `Processing` implementation (that would be great speaking of saving calculations in larger Tables!).

My problem: Making the `BackgroundRemoval: Processing` `Equatable`. I don't have access to the image or the underlying bitmap from `Processing`.

Do you know a trick I am missing to compare the processed images in `==`?

Btw: Do you see any performance bottlenecks in my `imageWithoutBackround`? I don't see a way to implement this directly into `func process(_ image: UIImage) -> UIImage` using CIImage Filters.. Probably you?

Cheers,
Frederik

**Comment by winkelsdorf** [comment]
You are very welcome! And thank you very much :)

Haha, ok I missed the obvious and now simply return `true`. Yes, the processor does the same with every image but I didn't knew about the internal keys taken into account (like url etc) - so a bit overthinking on my end to make sure your cache works.

Thanks for your help!

I am closing this, as there are no obvious performance issues. And if you stumble upon something for removing backgrounds with a Core Image filter, let me know :)

Cheers,
Frederik

**Comment by kean** [comment]
> Haha, ok I missed the obviou

It's just that the Equatable thing on the Processor is not that straightforward, and certainly not usual among image loaders. Any suggestions how to imporove this are welcome.

> performance 

Nuke performs all processing in the background. So if it feels fast enough I think you should be ok. I'm not using (big) computers till Jan 11th, can't suggest any alternatives atm :)

**Comment by winkelsdorf** [comment]
> It's just that the Equatable thing on the Processor is not that straightforward, and certainly not usual among image loaders. Any suggestions how to imporove this are welcome.

Actually I find this is a very clean approach (being protocol based). But you are right, it is a bit uncommon. It should be sufficient to include it in the docs/example at some later point. Currently the docs are a bit misleading regarding the implementation, but I was able to solve that quickly.

> Nuke performs all processing in the background. So if it feels fast enough I think you should be ok. I'm not using (big) computers till Jan 11th, can't suggest any alternatives atm :)

It's definitely ok and was solely based out of curiosity to improve my code and learn a bit more about what's possible.

So take your time and enjoy the holiday seasons 😀
