### ISSUE TITLE
Preheat Promise?

### ISSUE THREAD

**Issue by jnutting** [kean/Nuke#105]
I have a particular use-case where I need to know that a set of images either loaded (or failed to load) before proceeding. Without the images, there's no point proceeding, so I can't just have them loading in the background and not know. And because there's more than one image, I can't easily call `loadImage` on one and chain it to the next, at least not in any way that I can see.

I've tried various approaches to doing this, and none of them seemed to fit well with how Nuke works. After a while, the idea struck me: What if I could obtain a promise from a Preheat instance? I imagine using it something like this:

```
    preheater.promisePreheating(for: requests)
        .then { images in /* Success! Proceed with what we're doing */ }
        .catch { error in /* Failure! Retry or notify user or whatever. */ }
```
This looks pretty nice to me. The biggest problem for me here is that I, having never really worked with promises before, have no idea how to implement this. For inspiration, I tried looking at PromiseKit's methods that deal with collections, but I got completely lost. Thoughts, anyone?

**Comment by kaishin** [comment]
An easier, maybe stop-gap solution, would be to expose a property on `Preheater` to let the library user know when preheating is done. Either that or a `completionCallback`.

**Comment by kean** [comment]
Hey guys! I'm on a vacation till Jan 11th so it's short.
 
I think that you're don't need promises to do any of this. Just use a good ol counter:

```swift
func loadImages(for requests: [Request], completion: (...)) {
    var remaining = requests.count
    let cts = CancellationTokenSource() // cancels all requests, you can return if from fund / accept token as argument - it's flexible
    requests.forEach {
        Nuke.loadImage(for: $0, token: cts.token).compeltion {
            remaining -= 1
            if remaining == 0 {
                completion()
            }
       }
}

It's written from mobile, so take it with a grain of salt.

I'm actually soon going to add a convenience API on top of some of Nuke's functions that return promises. The users don't need to deal with extra complexity that comes with promises.

**Comment by kean** [comment]
And in case you were already using promises (which again is by no means necesssary) you could've probably got rid of this boilerplate. You could do something like wrap Nuke.Promise into PromiseKit.Promise (or analog) and use 'func when<T>(fulfilled promises: [Promise<T>]) -> Promise<[T]>' or something like this.

**Comment by jnutting** [comment]
I tried wrapping Nuke.Promise into PromiseKit.Promise, but couldn't really wrap my head around how to make it work. The solution you suggested above is simple enough, and I think is all I need. Thanks!

**Comment by kean** [comment]
Please be extra careful when updating to [Nuke 5](https://github.com/kean/Nuke/releases/tag/5.0), especially regarding [this change](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md#memory-cache-is-now-managed-exclusively-by-manager) (might be a controversial one as I think of it now). Let me know if you have any problems.

**Comment by kean** [comment]
If are updating to Nuke 5  use `Manager` to load images directly w/o targets. `Loader` no longer manages memory cache, only `Manager` class does.

```swift
func loadImages(for requests: [Request], completion: (...)) {
    var remaining = requests.count
    let cts = CancellationTokenSource() // cancels all requests, you can return if from fund / accept token as argument - it's flexible
    requests.forEach {
        Manager.shared.loadImage(for: $0, token: cts.token).compeltion {
            remaining -= 1
            if remaining == 0 {
                completion()
            }
            // add whatever error handling that makes sense for you app
       }
}
```

**Comment by kean** [comment]
[RxNuke](https://kean.github.io/post/introducing-rxnuke) (_**NEW!**_) provides a solution to this use case.
