### ISSUE TITLE
Why was the FLAnimatedImage Plugin deprecated?

### ISSUE THREAD

**Issue by mitchellporter** [kean/Nuke#106]
Hi Alexander,

Was just curious why the `FLAnimatedImage` plugin is listed as deprecated in the `README`, and what caused that decision? I checked the issues and release notes, but couldn't find any info.

Thanks.

**Comment by kean** [comment]
Hey! We've made a new [Gifu Plugin](https://github.com/kean/Nuke-Gifu-Plugin) which is a Swift alternative to FLAnimatedImage. I'm not removing FL plugin any time soon. From mobile, sorry it's short.

**Comment by mitchellporter** [comment]
@kean Thanks for letting me know Alexander cheers!
