### ISSUE TITLE
checking that the image url exists

### ISSUE THREAD

**Issue by sunjunkie** [kean/Nuke#107]
I want to take some action in my code if the image at a url does not actually exist. I've tried the following from Tips and Tricks but the 1st time through the code, the image property is always nil even when the image url does exist.

Nuke.loadImage(with: url, into: imageView)
if imageView.image == nil {
    imageView.image = UIImage(named: "placeHolder")
}

**Comment by kean** [comment]
Hi! Here's a similar question: https://github.com/kean/Nuke/issues/96

TL;DR: `loadImage(...)` with custom a handler requires _you_ to display an image; doesn't do anything by itself

**Comment by adougies** [comment]
```
if let checkedUrl = URL(string: "https://etc") {
Nuke.loadImage(with: checkedUrl, into: imageView)
}
```

This at least checks the URL is valid, if that helps?
