### ISSUE TITLE
resize gif

### ISSUE THREAD

**Issue by Albinzr** [kean/Nuke#109]
When I resized the gif it stopped animation .

**Comment by kean** [comment]
Hey!

In general, yes, you should not process gifs. If you process an instance of `UIImage` with an attached gif data, the associated data gets lost.

Are you using any of the [Gif plugins](https://github.com/kean/Nuke#plugins)? If yes, you may want to check out how Nuke managers are configured in them: https://github.com/kean/Nuke-Gifu-Plugin/blob/master/Source/AnimatedImage.swift
