### ISSUE TITLE
Nuke-Toucan-Plugin image resizing

### ISSUE THREAD

**Issue by adavan2107** [kean/Nuke#111]
Thanks for your help. Do we need to install both Nuke and  Nuke-Toucan-Plugin cocapods or only Nuke is enough?

I am getting this error

Unable to find a specification for `Nuke-Toucan-Plugin`

This is my pod file

target 'Woofy' do

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

use_frameworks!

pod 'Firebase'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'FSCalendar','~> 2.3.3'
pod 'Fabric'
pod 'Crashlytics'
pod 'LinkedinSwift', '~> 1.6.5'
pod 'FHSTwitterEngine', '~> 2.0'
pod 'Firebase/Storage'
pod 'Nuke', '~> 4.0'
pod 'SAConfettiView'
pod 'Wallet'
pod 'CTShowcase', '~> 2.0'
pod 'PeekPop', '~> 1.0'
pod 'Kanna', '~> 2.0.0'
pod 'Toucan'
pod 'Nuke-Toucan-Plugin'
end

**Comment by kean** [comment]
Does work on my machine:

```
~> pod install
Analyzing dependencies
Downloading dependencies
Installing Nuke (4.1.2)
Installing Nuke-Toucan-Plugin (0.2)
Installing Toucan (0.6.0)
Generating Pods project
Integrating client project
```

Podfile:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'test_nuke_toucan' do
	pod 'Nuke-Toucan-Plugin'
	pod 'Nuke'
end
```

Try this:
- update CocoaPods
- run `pod update` instead of `pod install`, maybe your specs are out of date
