### ISSUE TITLE
How to cache processed images?

### ISSUE THREAD

**Issue by swftvsn** [kean/Nuke#112]
Hi,

first of all, thank you for the excellent library! It is truly a pleasure to work with as the concerns are separated and I can override any bit I need! It allows me to integrate to multitude image sources not limited to http traffic, which is a requirement for me, and it also allows to tweak the caching to maximum. Thanks!

I have an app that displays a LOT of BIG images, that need to be zoomable to the full resolution. I have a list, that shows the thumbnails. Now, I would like to have the thumbnail images, that are processed from the multimegabyte full images, in the permanent disk cache to avoid loading (from disk) and processing the full images over an over again (after user has closed app).

So, I prepared a little hybrid cache: (I'm using DFCache as the second layer disk cache.)

```
class HybridProcessedCache: Nuke.Caching {
    
    let backingInMemoryCache: Nuke.Cache
    let backingDiskCache: DFCache
    
    public init(backingInMemoryCache: Nuke.Cache, backingDiskCache: DFCache) {
        self.backingInMemoryCache = backingInMemoryCache
        self.backingDiskCache = backingDiskCache
    }
    
    /// Accesses the image associated with the given key.
    public subscript(key: AnyHashable) -> Image? {
        get {
            if let val = backingInMemoryCache[key] {
                return val
            }
            if let val = backingDiskCache.cachedObject(forKey: String(key.hashValue)) as? Image {
                backingInMemoryCache[key] = val
                return val
            }
            return nil
        }
        set {
            backingInMemoryCache[key] = newValue
            backingDiskCache.store(newValue as Any, forKey: String(key.hashValue))
        }
    }
    
}
```
My goal is to have the processed images in disk cache for given url as well as the originals.

Are there any obvious problems with this implementation? Threading issues perhaps? 

~~What would be the best way to not store the original images twice? I think this happens when I request an image without any processors, so the outcome would be the same as the original image.~~
Edit: Actually I can just set `request.memoryCacheOptions.writeAllowed = false` and be done with it, awesome!

Also would you recommend to use the DFCache inmemory cache, or the Nuke one as in this example? I currently run the DFCache without inmemory cache.

**Comment by kean** [comment]
Hey! Thanks, I'm glad that it works well for you.

The use-case you are describing is a bit complicated. Here are couple of thoughts from the top off my head:
- Don't use `Caching`. It is used by `Manager` on the main thread and it's meant for memory caching only
- I don't have a clear answer what is the best way to solve this right now. I would probably suggest to wrap built-in `Loader` in a custom loader with a disk cache for thumbnails (implementation might be [similar to this](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Performance%20Guide.md#on-disk-caching), but for `Loader`). I don't think that you need memory cache on `Loader` / `DataLoader` level, just let `Manager` use `Nuke.Cache` which it's already using.
- Check out [Nuke 5 Migration Guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md), it might affect how you go about solving this

**Comment by kean** [comment]
And yeah, Nuke 5 is still work in progress. If you have any suggestions or any comments regarding current changes please share!

**Comment by swftvsn** [comment]
Thank you for the input!

I think the change in 5 to pass around the Nuke.Request is a good choice, as that gives more flexibility down the line.

My second iteration is this:

```
class ProcessedCachingLoader: Nuke.Loading {
    
    private let backgroundQueue = DispatchQueue(label: "com.example.image_cache_queue", qos: .userInteractive, target: nil)
    
    let backingLoader: Nuke.Loading
    let backingDiskCache: DFCache
    
    public init(backingLoader: Nuke.Loading, backingDiskCache: DFCache) {
        self.backingLoader = backingLoader
        self.backingDiskCache = backingDiskCache
    }
    
    public func loadImage(with request: Nuke.Request, token: Nuke.CancellationToken?) -> Nuke.Promise<Image> {
        return Nuke.Promise() { fulfill, reject in
            backgroundQueue.async {
                
                //Only cache processed images.
                if request.processor != nil, let key = request.urlRequest.url?.absoluteString {
                    if let val = self.backingDiskCache.cachedObject(forKey: key) as? Image {
                        fulfill(val)
                        return
                    }
                }
                
                self.backingLoader.loadImage(with: request, token: token).completion({ (resolution) in
                    if let error = resolution.error {
                        reject(error)
                    } else if let image = resolution.value {
                        if request.processor != nil, let key = request.urlRequest.url?.absoluteString {
                            self.backingDiskCache.store(image, forKey: key)
                        }
                        fulfill(image)
                    } else {
                        reject(Nuke.Loader.Error.processingFailed)
                    }
                })
                
            }
        }
    }
    
}
```

I think this approach will work with 5 too as is, save the change to closures. What do you think about this?

It would also be nice to provide hooks to get from cache, and cache, the processed image. Maybe have default implementations in 5 that do nothing, but pass the processed image forward?

**Comment by kean** [comment]
> I think this approach will work with 5 too as is, save the change to closures. What do you think about this?

Yeah, that seems reasonable. Just make sure that the `request.processor != nil` line does what you expect it does. Request has a default processor which is a `Decompressor` with default parameters.

> It would also be nice to provide hooks to get from cache, and cache, the processed image. Maybe have default implementations in 5 that do nothing, but pass the processed image forward?

Could you please elaborate? Regarding "get from cache, and cache, the processed image" - you can always use a default `Loader` to retrieve data from custom disk cache wrapped into custom `DataLoader` and then have the image decoded and processed automatically by that `Loader`. If that's what you mean. The default `Loader` in Nuke 5 no longer has a memory cache so it basically just reads data and processes it, and gives it to you.

**Comment by swftvsn** [comment]
Thank you, again, for the input and feedback! In the end the solution is actually pretty simple and elegant, which is a testimony of good architecture.

5 Looks to be awesome, and the upgrade process from 4 to 5 was painless.

Thanks!

**Comment by kean** [comment]
Awesome, glad that it worked for you! 🍻

**Comment by kean** [comment]
Update: it looks like something that [RxNuke](https://kean.github.io/post/introducing-rxnuke) (_**NEW!**_) should be able to handle in the future.
