### ISSUE TITLE
Nuke 5? What are the improvements?

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#113]
I just found out that you are implementing Nuke 5? (or have implemented?)

What are the improvements compared to Nuke 4?

**Comment by kean** [comment]
It's a small release. My main goals were to: a) make memory management simpler, b) make it easier to contribute to Nuke. Here's what I've come up with:

- [Nuke 5 Release Notes (Draft)](https://github.com/kean/Nuke/blob/master/CHANGELOG.md#nuke-50)
- [Nuke 5 Migration Guide (Draft)](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md#nuke-5-migration-guide)
