### ISSUE TITLE
When is Nuke 5 due for release?

### ISSUE THREAD

**Issue by KiGi** [kean/Nuke#114]
I'm working on a small overhaul to image management for a code base I'm working on - I am using Nuke for image management, I was wondering if I should use 5.0 even if not released quite yet?

I read that 5.0 was a small update so it may not matter using 4.2 vs. 5.0, but one of the things I did plan on working up was custom disk caching code  and it seemed like caching stuff changed a bit in 5.0.

**Comment by kean** [comment]
It's almost complete, I'll release it some time later today.

> I am using Nuke for image management, I was wondering if I should use 5.0 even if not released quite yet?

You can start using it from `master` branch, it's stable and there won't be any critical changes before the release.

> seemed like caching stuff changed a bit in 5.0.

It did, and I'll probably make some adjustments to the [new entry](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Performance%20Guide.md#on-disk-caching) about integrating third-party caching libs before the release.

**Comment by kean** [comment]
[Nuke 5](https://github.com/kean/Nuke/releases/tag/5.0) is out 🍾
