### ISSUE TITLE
undeclared type Response (loadImage)

### ISSUE THREAD

**Issue by YanisSOTO** [kean/Nuke#117]
Hi, i've update my pod and i'm performing this error:

`Use of undeclared type Response`

Here is the code :

`ABImageDownloader.sharedInstance`
                 `                    .nukeManager`
                 `   .loadImage(with: url, into: strongSelf, handler: { (response: Response, isFromMemoryCache: Bool) in `
`                        switch(response){`
`                        case .fulfilled(let image):`

I've tried to change `Reponse` by `DataResponse<Any>`  but still an error : 
`Cannot invoke 'loadImage' with an argument list of type '(with: URL, into: ABImageView, handler: (DataResponse<Any>, Bool) -> ())'`

If you have an idea what i have to change, thank's a lot

**Comment by kean** [comment]
Hey! Nuke 5 is a major release so it does contain some breaking changes.

Here's some information that aims at easing the transition from previous versions:
- [Nuke 5 Migration Guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md)
- [Nuke 5 Release Notes](https://github.com/kean/Nuke/blob/master/CHANGELOG.md#nuke-50)

Regarding to `Response` you should replace it with new `Result<T>`. Here's an example:

```swift
ABImageDownloader.sharedInstance.nukeManager.loadImage(with: url, into: strongSelf, handler: { (response: Result<Image>, isFromMemoryCache: Bool) in
    switch response {
        case let .success(image): // use image
        case let .failure(error): // handle error
    }
}
