### ISSUE TITLE
High memory usage (CG Raster Data)

### ISSUE THREAD

**Issue by vpanghal** [kean/Nuke#118]
I am using Nuke to display image in a collection view. This collection has many images that are downloaded from object store and resized to cell size. In the profiler, I see memory usage (CGRaster Data) keep growing. It seems Nuke(5.0.1) is retaining the strong reference to this data.

![screen shot 2017-02-14 at 11 18 37 pm](https://cloud.githubusercontent.com/assets/1855338/22964153/06e2a714-f30c-11e6-8b62-2cf03c331fca.png)

**Comment by kean** [comment]
Hey! Nuke has a built in memory cache that stores rasterized images (CG raster data. That seems about it.

The memory usage seems a bit too high for iPhone 5S though. Please let me know if you receive any memory warnings. I might need to reduce the cache size limit.

**Comment by vpanghal** [comment]
I am getting memory warning and app is terminating after this. I see Nuke is dropping its cache on receiving memory warning but CGRaster data usage is not dropping.

On side note - What is cached in Nuke default cache?  Is it network fetched data/ some intermediate representation/resized image?

**Comment by kean** [comment]
> I see Nuke is dropping its cache on receiving memory warning but CGRaster data usage is not dropping.

I would suggest to disable Nuke's memory cache and see if you still can reproduce the problem. You might have some image views that don't get deallocated. Every image view holds a strong reference to the raster that it's displaying. Make sure that all your view controllers and views get deallocated properly. You might want to use [visual memory debugger](http://useyourloaf.com/blog/xcode-visual-memory-debugger/) too.

> On side note - What is cached in Nuke default cache?

`Nuke.Cache.shared` is a default memory cache which is used by a default `Nuke.Manager`. To disable it you can create your own shared manager without a memory cache:

```swift
let manager = Nuke.Manager(loader: Nuke.Loader.shared, cache:nil)
```

> Is it network fetched data/ some intermediate representation/resized image?

No intermediate representations are stored, only processed images which get displayed in your image views.

P.S. I periodically perform [generational analysis](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/FindingAbandonedMemory.html) using the demo project. I create a new `Nuke.Manager` instance, push a screen with a collection view with some images, than pop the screen and check if everything get deallocated. I haven't seen any leaked Nuke objects yet, except for some UIKit related crap like UIFont caches, UIStatusBar icons, etc.

![screen shot 2017-02-14 at 21 36 20](https://cloud.githubusercontent.com/assets/1567433/22943580/121c08bc-f2ff-11e6-9443-c92b8833bcbc.png)

**Comment by vpanghal** [comment]
Hi Kean,

Thanks for these very useful pointers! I disabled Nuke memory caching but I still see that CGRaster usage is growing and eventually iOS is terminating app.

I think issue is Nuke is decoding the image in parallel and each thread race to allocates (30MB) separate mapped region to process the image . And from traces, it looks like there are seven threads. So that would initially allocate 210MB.

e.g. Here is the allocation happen on loading image in Collection view. There are seven memory mapped region of 30MB each allocated within 3 second time window

![screen shot 2017-02-14 at 10 55 55 pm](https://cloud.githubusercontent.com/assets/1855338/22963607/c9c665c6-f308-11e6-9215-5c9437608f00.png)

**Comment by kean** [comment]
I've just realized that the images that your are displaying are probably enormous in size. I use Nuke demo with 2000x3000px images and they result in only 22.89 MB rasters.

To fix the problem you should download images which are smaller in size and/or resize loaded image to fit your image views. If you still need to display full-size image, do it fullscreen, not in a collection view.

The best way to resize images is to replace default Decompressor with the one with a target size. This way only the resized rasters are created, never the full-size ones:

```swift
func makeRequest(url: URL, view: UIImageView) -> Request {
    var request = Request(url: url)
    request.processor = AnyProcessor(Decompressor(targetSize: targetSize(for: view), contentMode: .aspectFill))
    return request
}

func targetSize(for view: UIView) -> CGSize { // in pixels
    let scale = UIScreen.main.scale
    let size = view.bounds.size
    return CGSize(width: size.width * scale, height: size.height * scale)
}
```

I've tested this code in a demo again (2000x3000 images, 4 images per row) and now the memory usage never grows more than 40 MB:

<img width="1174" alt="screen shot 2017-02-15 at 10 30 43" src="https://cloud.githubusercontent.com/assets/1567433/22964709/03f1ae10-f36b-11e6-982c-ae2861793840.png">

P.S. The resizing API isn't very elegant at the moment. I'll add some convenience methods soon, and I'll also update [Performance Guide](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Performance%20Guide.md#resizing-images) based on your feedback. Cheers 🍻 

> I think issue is Nuke is decoding the image in parallel

decoding+processing are done on a serial background queue specifically to avoid using too much resources

**Comment by vpanghal** [comment]
Perfect! Decompressing/resizing images to target view size did help and I am not observing unbounded memory growth with in memory cache enabled in the Nuke.  App has around 2000s of images across multiple collection view. App is not getting memory warning and usage is capping around 200MB.

Right now these image are scaled down to low resolution for full view. But As you suggested, I would need to have another thumbnail of the image for collection view to reduce cpu usage in decompression/resizing. Hopefully that would make user experience little better.  Thanks for all your help! Let me know if I can help anyway. Cheers :beers:
