### ISSUE TITLE
Decompress with upscale

### ISSUE THREAD

**Issue by Unihilator** [kean/Nuke#119]
I have imageProcessor to do image upscale in order to upscale image to exact size. You are doing the same in `decompress` method but you are downscale images. My goal is to prevent automatic image scaling in UIImageView. So what do you think @kean  - it's important to make that kind of resizing(I mean my upscale)? Or it's reasonable to remove it?

**Comment by Unihilator** [comment]
Just found `resize` in documentation. But didnt find it in code
// As an alternative you can provide a target size (in pixels) yourself.
request.resize(to: CGSize(width: 150, height: 150), mode: .aspectFit)

**Comment by kean** [comment]
> So what do you think @kean - it's important to make that kind of resizing(I mean my upscale)?

I don't have a definitive answer. I would probably avoid upscaling unless there are some visible performance issues. I doubt that there are any on the recent hardware. I think I remember stumbling about upscaling issues back in 2012, but that was an extreme case of displaying ~20x20px images fullscreen.

> Just found resize in documentation. But didnt find it in code
> // As an alternative you can provide a target size (in pixels) yourself.
> request.resize(to: CGSize(width: 150, height: 150), mode: .aspectFit)

Sorry, this API isn't available yet, will be released soon with Nuke 5.1. And this method actually only downscales images. Any thoughts on that? Maybe I should rename it to `downscale` instead?

**Comment by Unihilator** [comment]
Resize means exact own definition. Definitely it should sounds like `downscale` 😄

**Comment by kean** [comment]
Yeah, makes sense.
