### ISSUE TITLE
Nuke using a lot of on disk memory

### ISSUE THREAD

**Issue by bmetitiri** [kean/Nuke#121]
I've been having an issue with the Documents & Data for my app growing very large, well over a GB even though I'm not explicitly storing anything. After downloading my application's package and examining the contents, it seems the Nuke library has an incredibly large Caches folder. I checked that the cache limit was around 200MB as expected, and I see no other configurations I can make. Why is Nuke storing so much in long term memory? How can I make it clear cached images I no longer need? I am already calling Nuke.Cache.shared.removeAll when I receive a memory warning, but that call has no effect on this stored data. Any tips?

**Comment by kean** [comment]
NSURLCache is infamous for [weird bugs](http://stackoverflow.com/questions/26260401/nsurlcache-does-not-clear-stored-responses-in-ios8) like this. If you want full control over disk caching you should use a third party caching library. [Here's a helpful guide](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Third%20Party%20Libraries.md#using-other-caching-libraries) to do that.

> I am already calling Nuke.Cache.shared.removeAll when I receive a memory warning

That method removes images stored in memory cache only. And you also don't have to it manually, `Nuke.Cache` does that automatically for you:

```swift
NotificationCenter.default.addObserver(self, selector: #selector(Cache.removeAll), name: .UIApplicationDidReceiveMemoryWarning, object: nil)
```

**Comment by bmetitiri** [comment]
Thanks, that's super helpful. One other question, the examples on that guide you linked have lines like `Nuke.Loader(loader: dataLoader)`, but `Loader` doesn't have any initializers that take just one argument. Should it be `Nuke.Loader(loader: dataLoader, decoder: Nuke.DataDecoder(), cache: nil)`?

**Comment by kean** [comment]
> Should it be Nuke.Loader(loader: dataLoader, decoder: Nuke.DataDecoder(), cache: nil)?

This stuff is actually new in Nuke 5. Here's some information for easing the transition from the previous versions:
- [Nuke 5 Migration Guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md)
- [Nuke 5 Release Notes](https://github.com/kean/Nuke/blob/master/CHANGELOG.md#nuke-50)

It's a small release, but make sure to go through the changes, especially [this one](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%205%20Migration%20Guide.md#memory-cache-is-now-managed-exclusively-by-manager).
