### ISSUE TITLE
EXC_BAD_ACCESS crash in Processor

### ISSUE THREAD

**Issue by andrew8712** [kean/Nuke#122]
After I switched to manual `Manager` initialization:

        let physicalMemory = ProcessInfo.processInfo.physicalMemory
        let ratio = 0.4
        let limit = physicalMemory / UInt64(1 / ratio)

        let cache = Cache(costLimit: Int(limit), countLimit: Int.max)
        manager = Manager(loader: Loader.shared, cache: cache)

I'm getting random `EXC_BAD_ACCESS` crashes on this line:

     ctx.draw(cgImage, in: CGRect(origin: CGPoint.zero, size: size))

in `Processor.swift`. Any thoughts how to fix that?

**Comment by andrew8712** [comment]
I use `master` branch version

**Comment by kean** [comment]
Your app might be using too much memory. Can you reproduce this with a default `Cache` settings (0.2 ratio)?

**Comment by andrew8712** [comment]
Nope, only with my custom settings.

**Comment by kean** [comment]
Using too much memory might result in CGContextDraw crashes like this one. AFAIK there is nothing Nuke can do to prevent this, so I'm closing this issue. The default cache ratio is already quite generous, I would suggest not to increase it.
