### ISSUE TITLE
Nuke Decompressor resizing quality

### ISSUE THREAD

**Issue by webmaster128** [kean/Nuke#123]
A default Request in Nuke without explicit image processing resizes images to the target size to reduce memory consumption and main thread usage, right?

I found that the resizing quality is not great compared to all three image resizing algorithms available in Gimp.

![overview](https://cloud.githubusercontent.com/assets/2603011/23460651/b35747d6-fe86-11e6-98ae-b2514af9c540.png)

[test_images.zip](https://github.com/kean/Nuke/files/810753/test_images.zip)

Is that expected or is there anything I am missing here?

**Comment by kean** [comment]
> A default Request in Nuke without explicit image processing resizes images to the target size to reduce memory consumption and main thread usage, right?

Default Request doesn't resize the original image (it doesn't know the target size), it just draws it into the CGContext. I wouldn't expect any regressions in quality.

Are you sure that you retrieved the image decompressed by Nuke correctly? It seems that it actually has `scale = 2` and `size = 48x48`, which means that its pixel size is 96x96. This is why it might seem edgy when compared to the image produced by Gimp - it has 2x pixel density.

**Comment by webmaster128** [comment]
I use a 24x24 point UIImageView on a 2x simulator (iPhone SE), which results in a 48x48 pixel screenshot.

Thanks! Now I see the default value for targetSize in Decompressor.

I tested setting the target size and added `ctx.interpolationQuality = .high` but this does not improve the quality.

**Comment by webmaster128** [comment]
I debugged my code and confirmed that I set targetSize to 48x48.

Using Tucan does not improve the quality as well. Maybe this is as good as possible using default iOS components.

**Comment by webmaster128** [comment]
Fixed it. I guess the issue was that `UIImageView.bounds.size` was not available by the time I created the request (after view construction but before layouting?). I get perfectly rendered images when I hardcode the target size in pixels in `_picturePixelSize` and do

```
var request = Nuke.Request(url: pictureUrl)
request.processor = Nuke.AnyProcessor(Nuke.Decompressor(targetSize: _picturePixelSize))
NukeManager.shared.loadImage(with: request, into: _picture)
```
with `NukeManager.shared` is my application's instance of Nuke.Manager

Thanks for pointing in the right direction.

**Comment by kean** [comment]
Great, I'm glad that you figured it out. 

> I get perfectly rendered images when I hardcode the target size in pixels in _picturePixelSize and do

That's good to know. Yeah, to me the results of CGContext.draw() seem perfectly fine, whatever interpolation algorithm they use by default is alright.

**Comment by HamzaGhazouani** [comment]
Hi @kean, I use Nuke of one of my project and I would like to take the image size from server, because now it's taking the size of the image view, and I have some quality problems because I don't have the same size in all the app
`Nuke.loadImage(with: imageURL, into:cell.trackImageView)`
There are an option to fix that without using Decompressor ? 
Thanks
