### ISSUE TITLE
CollectionViewCell reuse issue/question

### ISSUE THREAD

**Issue by sash83** [kean/Nuke#124]
I have a custom CollectionViewCell (registered and flowlayout set up), also use preheating. My CollectionView is created programmatically and has about 100 cells. The thing is that dequeuing cells does not seem to work. Every time I scroll up and down, cells get reloaded. I was expecting normal CollectionView behaviour like it is loaded just once. I want this image collection loaded once, then scrolling through them like photo library or Instagram CollectionView, not images that disappear and reload again.

Is there any additional set up to use to get this behaviour? Thanks for any help!

**Comment by kean** [comment]
Check out a preheating demo (part of this repo), it works just as you would expect.

And make sure that the `Preheater` is initialized with the same `Manager` that you use for loading images into your cells. This might be the reason why cached images aren't reused.

**Comment by sash83** [comment]
The images come from cache, though when cell goes off screen the cell content disappears. When coming back to screen, cell content gets reloaded from cache. But I want the cell content being consistent after loading view once.

I also use the Preheater as you suggest in demo.

**Comment by kean** [comment]
> Actually cached images are not always used for some reason. Apparently it depends on how many rows CollectionView has and how fast you scroll.

Memory cache in Nuke uses up to 20% of available RAM. Bitmaps are large, you can't fit many of them in memory on iOS devices.

Photos app is a bit different. Photos app on iOS stores small thumbnails alongside original images on disk. When you scroll your photo gallery, Photos app loads those thumbnails synchronously from disk before loading fullsize images. That's how even when you scroll really fast there is always a thumbnail ready to be displayed.

**Comment by sash83** [comment]
Do you have any advice how to accomplish such behaviour like Photos app?
I also tried it with DFCache, though it's even slower.

**Comment by kean** [comment]
There are many different strategies to load images in your app. It's really up to you. I would probably avoid anything too complicated really.

Anyway, you may find this discussion useful (I assume you are loading images from the web, aren't you?):
- https://github.com/kean/Nuke/issues/112 - swftvsn loads images from the web and has some custom code to store two copies of each image into the disk cache (original + thumbnail). You could adapt a similar strategy, but also add some custom code to read those thumbnails synchronously (like Photos app does).

**Comment by kean** [comment]
Or you may simple try to increase memory cache size / load smaller images / resize images to make them take less space in the memory cache. It's really up to what your goals are.

**Comment by sash83** [comment]
Thanks so much! I'll try different options. Yeah I load them from Firebase.
