### ISSUE TITLE
Gifu Plugin with Nuke used a lots of memory.

### ISSUE THREAD

**Issue by htarwara6245** [kean/Nuke#127]
I don't know if this was bug or not. I did exactly as you posted on example project of using gifu plugin.

Somehow, the memory keep rising and still not going down when I back to other view controller (navigation controllers)

Menu(Navigation Controller) <-> GIFU TableView (Navigation Controller) <-> GIF Detail

When I went back to Menu, the memory is keep rising up and then show me memory warning. I just load 10 GIF. When I went back from menu to GIF tableview, it rises again. But, due to it caches, the memory only exceed about  20MB.

So first time load = 178MB
After clicking back button = 178 ~ 179 MB
Then when I come back from menu to gif = 210MB [Images are already loaded]

Any Help?

**Comment by kean** [comment]
`AnimatedImage.manager` has a global memory cache. It stores only the first frame of each GIF + compressed data. Data gets decoded frame-by-frame on demand by Gifu when the GIF is displayed in an `AnimatedImageView`. I'm not entirely sure whether Gifu has any memory caches for decoded frames which might persist after the `AnimatedImageView` is deallocated.

Here are a couple of tips to approach this:
- [Profile memory usage](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/CommonMemoryProblems.html#//apple_ref/doc/uid/TP40004652-CH91-SW1), you may find some unexpected leaks / other issues
- Reduce memory usage. You might want to a) reduce GIFs size, b) reduce `AnimageImage.manager` cache size, c) clear shared `AnimatedImage.manager` cache when leaving the screen, d) create a separate `Nuke.Manager` per screen, `Manager` class is designed to be used this way if necessary.

GIF playback itself is extremely demanding in terms on CPU and RAM. It's hard to get right and you need to be very careful when adding it in your app! Hope this helps.

**Comment by htarwara6245** [comment]
Thanks for faster support!!! Appreciated it.

I just solved it by using this way..

```
override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        tblGIF.removeFromSuperview()
    }
```

Then it went back to normal
