### ISSUE TITLE
[Support - Questions] Clear image cache

### ISSUE THREAD

**Issue by htarwara6245** [kean/Nuke#128]
Is there anyway that I can clear nuke loaded image? I have to request one image url from the server and if they change the image, I need to clear my previous image cache which requesting from same url.

```
var request = Request(url: URL(string : imageURL)!)
request.memoryCacheOptions.writeAllowed = false
cell.mainImage.image = nil
Nuke.loadImage(with: request, into: cell.mainImage)
```

I made like this. But, I really don't understand 
`request.memoryCacheOptions.writeAllowed = false` 
that line. And was it clear image cache if the server image changed?

**Comment by kean** [comment]
Hey! I'm sorry I'm currently really busy at work so I don't have much time to support any of my frameworks. I'm also subscribed to a AlamofireImage so I've seen that you've asked the similar question there 😉 

Let me copy an answer on a similar question "How to add image to cache without downloading":

```swift
There are two cache layers in Nuke:
- mem cache
- disk cache

1. Writing to mem cache is easy:

Nuke.Cache.shared[request] = image

2. Writing to disk cache is trickier. Nuke uses URLCache by default. As of now you don't have access to that cache instance. To get access to disk cache you need to create a custom Manager with a custom DataLoader.

    private static var defaultConf: URLSessionConfiguration {
        let conf = URLSessionConfiguration.default
        conf.urlCache = URLCache(
            memoryCapacity: 0,
            diskCapacity: 150 * 1024 * 1024, // 150 MB
            diskPath: "com.github.kean.Nuke.Cache"
        )
        return conf
    }
```

As far as removing image from cache is concerned I see a couple of ways to do that:
1. Use HTTP validation. This way when the image changes on the server it would automatically change in your disk cache. The URL always stays the same, the content changes.
2. Change a URL when the image changes (this depends on where you get that URL).

I've written [a very detailed guide about HTTP caching](https://kean.github.io/blog/image-caching) (including validation).. Check it out if you want to get into HTTP caching.

**Comment by kean** [comment]
Sorry, I couldn't spend much time on this answer so it might be a bit confusing 😉

**Comment by htarwara6245** [comment]
+1 correct at confusing. So, I just used : https://github.com/onevcat/Kingfisher

I think you need to add support for this as well

**Comment by kean** [comment]
> I think you need to add support for this as well

Could you please elaborate? Nuke allows you do everything that the Kingfisher does in terms of caching.

**Comment by htarwara6245** [comment]
I am not saying you library wasn't great. You just share yours to make everybody easily at working with Image. Even I used yours for GIF loading inside UITableView. But, to compare it with Kingfisher, it explained how do we create imagedownloader and clean the cache (Both memory and disk)

Thanks for the support m8. I will not close this until I get the answer. I will try to elaborate well when I got enough knowledge of image caching and how your library work

**Comment by kean** [comment]
Nuke has different goals, it focuses on **simplicity** and **flexibility**. So you won't find as much convenience features as Kingfisher has. So in that sense Nuke is designed for a very specific set of users. I would say that for the majority of the users something like Kingfisher would be a better choice.

I would also say that manually removing specific images from cache is not something that I would normally do. I would instead always rely on HTTP validation to remove them automatically for me.

**Comment by kean** [comment]
Update: [Nuke 5.1.1](https://github.com/kean/Nuke/releases/tag/5.1.1) provides access to the  shared `URLCache` (`DataLoader.sharedUrlCache`).
