### ISSUE TITLE
Specs satisfying the `Nuke (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by smartsidd** [kean/Nuke#129]
Specs satisfying the `Nuke (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

![screen shot 2017-05-31 at 10 55 41 pm](https://cloud.githubusercontent.com/assets/1187989/26645012/50f639a6-4654-11e7-8b6a-0214ad3339be.png)

**Comment by kean** [comment]
Nuke's minimum deployment targets are:

```iOS 9.0 / watchOS 2.0 / macOS 10.11 / tvOS 9.0```
