### ISSUE TITLE
Temporarily display cached image, even if out of date, before displaying fresh one

### ISSUE THREAD

**Issue by boliverr** [kean/Nuke#130]
Hello,
I am fetching images from a server that has some delay before answering any request, even a small one (transfer times are ok though, this is just latency). Using Nuke, it will take quite some time to redisplay images that have already been fetched and are unchanged, because it will wait for the http response before deciding whether to display the cached image or fetch a new one.
In my use case, images will very rarely change, but if they do i need to get the fresh one immediately. So it would be appropriate to display the cached image while expecting the answer from the server, then display the fresh one if needed.
Is this feasible with Nuke's architecture ? Should I manually fetch the image from the memory cache and load it in the image view before launching the request (i have tried this unsuccessfully, but maybe it did it wrong) ? Should it switch from nsurlcache to a custom disk cache that i can query myself before launching the request ?
Thank you for your insights

**Comment by kean** [comment]
Hey!

Nuke doesn't have this built-in, but you can use existing features and built on top of them.

If you are relying on `Foundation.URLCache` for HTTP cache validation I'd suggest that you stick with it. AFAII there are no third-party networking+cache libraries that support cache validation out of the box. It certainly can be done, but it's really tedious plus it requires changes both on cache side and on networking side.

If you are using `Foundation.URLCache` you can take advantage of [`URLRequest.CachePolicy.returnCacheDataDontLoad`](https://developer.apple.com/documentation/foundation/nsurlrequest.cachepolicy) to serve stale response first and validate the responses later if necessary.

> Specifies that the existing cached data should be used to satisfy the request, regardless of its age or expiration date. If there is no existing data in the cache corresponding the request, the data is loaded from the originating source.

So I'd suggest that you send two separate requests: the first one that uses `.returnCacheDataDontLoad`, cache policy and then the second one that uses the default cache policy. I'm don't want to get into too much detail about how you can manage those requests in terms of concurrent, how you cancel them, how to handle the results. You can either use [Loading Images w/o Targets](https://github.com/kean/Nuke#loading-images-wo-targets) Nuke's API, or you can try to take advantage of [this strategy](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Tips%20and%20Tricks.md#show-a-low-res-image-first-and-swap-to-a-higher-res-one-when-it-arrives) for managing two requests. It's up to you.

To wrap up, I don't think that Nuke serves this particular use-case very well. I'd probably revisit it later to see what can be done to improve it. It looks like it should be very easy to implement using [RxSwift](https://github.com/ReactiveX/RxSwift). The direction that'd probably take: add reactive extensions to Nuke, document some of the comment scenarios.

I'd also suggest that you take a look at [Kingfisher](https://github.com/onevcat/Kingfisher). This framework has a different set of goals compared to Nuke which primary focus is on simplicity. I'm not familiar with Kingfisher's feature-set, but it should have much more built-in features then Nuke. It probably supports what you're looking for out of the box, but I don't know for sure.

Cheers.

**Comment by kean** [comment]
I've just released the initial [`RxNuke`](https://github.com/kean/RxNuke) version which provides a solution to this use case as well as for many-many more.

**Comment by boliverr** [comment]
Thank you for you answer, I'll have a look at the RxNuke solution. Wouldn't it send 2 requests when the image is loaded for the first time though ? (although the second one would not load the whole data). I will investigate :)

**Comment by kean** [comment]
It's very early stage, if you have any fixes/suggestions/comments please let me know!

From a quick glance the code from RxNuke readme does seem to do the trick:

```swift
let cacheRequest = URLRequest(url: imageUrl, cachePolicy: .returnCacheDataDontLoad)
let networkRequest = URLRequest(url: imageUrl, cachePolicy: .useProtocolCachePolicy)

Observable.concat(loader.loadImage(with: cacheRequest).orEmpty,
                  loader.loadImage(with: networkRequest).orEmpty)
    .observeOn(MainScheduler.instance)
    .subscribe(onNext: { imageView.image = $0 })
    .disposed(by: disposeBag)
```

The requests are executed serially. The first request has a `.returnCacheDataDontLoad` cache policy so it only checks whether the image is in the disk cache. It doesn't do any networking. The second requests has a `.useProtocolCachePolicy` (which is a default `URLRequest` policy), it does the networking.

The only downside that I see is that if the second requests validates the image and the server returns `304 Not Modified` Nuke would still retrieve the data from cache, decode it, and display the image (which we should've already retrieved with the first request).


> although the second one would not load the whole data

Could you please elaborate?

**Comment by kean** [comment]
P.S. I would also **not recommend** installing `RxNuke` if you don't already use `RxSwift` in your project. You can implement the same thing manually with just a bit of custom code.

**Comment by boliverr** [comment]
I am already using RxSwift in the app so nothing to worry here. You are right, I had overlooked that fact that with returnCacheDataDontLoad no networking will happen. 

> Could you please elaborate?

I was unclear. I meant that when the image is requested for the first time in the app's lifetime, if it is already cached then the request will stop at the 304 Not Modified, as you properly put it.
