### ISSUE TITLE
Transition for displaying image

### ISSUE THREAD

**Issue by ealymbaev** [kean/Nuke#132]
Do we have any transition setting for displaying image?
Also a transition for changing image would be great. Let's say we are switching from low res thumbnail to high res image

**Comment by kean** [comment]
Hey!

No, there are no transition settings. There are also no plans to add them, the idea is to keep framework and its API surface as small as possible and not introduce client-specific code. The default animations that are in use today might also be gone in Nuke 6.

In Nuke you can take advantage of [`loadImage(with:into:handler:)`](https://github.com/kean/Nuke#providing-custom-handlers) to implement any transitions that you might need.

And RxNuke doesn't have any of the UI specific code. You [manage the subscriptions and the way images are displayed yourself](https://github.com/kean/RxNuke#in-a-table-or-collection-view).
