### ISSUE TITLE
Question: caching an image generated in code

### ISSUE THREAD

**Issue by igorkulman** [kean/Nuke#136]
All the examples talk about fetching and image from an URL and caching it. In one of my use cases I am generating `MapKit` snapshots using `MKMapSnapshotOptions` (generates an `UIImage`) and I want to cache those. Is it possible somehow? 

I looked at writing a custom loaders but the loaders operate with a url request.

**Comment by kean** [comment]
Hey! Nuke 5 isn't designed to support this. It's basically just for loading images from URLs. I'd suggest to implement this by hand. If you already use Nuke you might want to take advantage of some of its components, for example (shared) `Nuke.Cache`.

I'm open to suggestions how Nuke can be improved to support more use-case :smh

**Comment by igorkulman** [comment]
So it is ok to directly manipulate `Nuke.Cache.shared`?  Will it be also ok to create another shared `Nuke.Manager` with a new cache instance so I can easily clear it without affecting `Nuke.Manager.shared`?

**Comment by kean** [comment]
> So it is ok to directly manipulate Nuke.Cache.shared? Will it be also ok to create another shared Nuke.Manager with a new cache instance so I can easily clear it without affecting Nuke.Manager.shared?

I've made `Nuke.Cache.shared` public for convenience. In general it's a good idea to configure your own manager with its own components.
