### ISSUE TITLE
How to Remove Blank Space in UIImageView when AspectFit ?

### ISSUE THREAD

**Issue by moryku** [kean/Nuke#138]
How to remove blank space in UIImageView after i load image from url using nuke with this code

`var request = Nuke.Request(url: URL(string: Constants.BASE_URL+feeds[position].photo.image!)!)
request.processor = Nuke.AnyProcessor(Nuke.Decompressor(targetSize: CGSize(width: cell.contentImage.frame.width, height: 0), contentMode: .aspectFit))
manager.loadImage(with: request, into: cell.contentImage)`

result with blank space 

![20689680_1432792080107248_8561660683099551746_o](https://user-images.githubusercontent.com/8121563/29200407-3ba13b06-7e7f-11e7-83d9-e7ce40a624ed.jpg)

**Comment by kean** [comment]
It seems that it is out of scope of Nuke. Have you tried looking for answers on SO?
