### ISSUE TITLE
Describe Nuke advantages/disadvantages vs Kingfisher

### ISSUE THREAD

**Issue by enjoiful** [kean/Nuke#139]
Kean mentioned in a previous comment: 

"Nuke has different goals, it focuses on simplicity, performance and flexibility. So you won't find as much convenience features as Kingfisher has. In that sense Nuke is designed for a very specific set of users. I would say that for the majority of the users something like Kingfisher would be a better choice. "

Can you describe which set of users Nuke is ideal for?  Why do you think the majority of users would benefit from Kingfisher instead of Nuke?

**Comment by kean** [comment]
Hey! Sorry, I'm not in a position to compare Nuke with Kingfisher - I haven't used the later myself and I'm not that familiar with it. If you'd like to point out something which is good/bad in Nuke, please welcome 😃

**Comment by MadeByDouglas** [comment]
So in 2024, how would you compare the libraries? Which is best (performant, easy to use) for swiftUI targeting the latest iOS?
