### ISSUE TITLE
Images first downloaded repeats before loading the actual ones

### ISSUE THREAD

**Issue by iadxworld** [kean/Nuke#143]
I am downloading images from firebase server. The images download quite quick, the only issue here is, as soon as the first image is downloaded, it is shown in all the cell having image views of the  TableView/CollectionView. I know its a caching mechanism, but How do I actually stop this from happening. I just want these images to download for their respective cells or else just show an empty blur view. 

Is there any fix to prevent duplication of images being downloaded.

**Comment by kean** [comment]
Hey! Do those other image views load the image with the same URL? Are you using Nuke6-beta1?

**Comment by iadxworld** [comment]
thanks for the prompt answer. No they have different URL. The download is asynchronous, so any image loads first. Also, Even if the image is loaded and the tableview is scrolled, the image in the new visible cell is the older one initially, a lot of times replicated and then after 1/2 secs the original image with the correct URL is displayed.  
And I haven't upgraded to Nuke 6 Beta 1.

**Comment by kean** [comment]
That's weird, I think you might be miss-using some of the APIs. Can you please share a snippet of the code which start the image load?

> the image in the new visible cell is the older one initially

You need to be clearing the view before setting a new URL:

```swift
cell.imageView.image = nil
Manager.shared.loadImage(with: url, into: cell.imageView)
```

**Comment by iadxworld** [comment]
Okay, maybe I am not clearing the view. I was just loading it. I'll give it a shot and update you.

**Comment by iadxworld** [comment]
Yes, You were right! I missed to clear the target. Well thank you for your quick response. Highly appreciate it!

Cheers!
