### ISSUE TITLE
RxNuke unavailable for Nuke 6.0 beta 1

### ISSUE THREAD

**Issue by iadxworld** [kean/Nuke#144]
Hey!

I am trying to install RxNuke for its progressive download feature. But when I install pods it gives me a error saying that RxNuke is only available for Nuke 5.x and not for 6.0 beta 1. 

Is there a way I can use it in the current version?

**Comment by kean** [comment]
Hey! Sorry for a late response. I've updated RxNuke in `master` branch. I'm going to release Nuke 6 and update the rest of the extensions soon.
