### ISSUE TITLE
Elements in accessible due to private level protection

### ISSUE THREAD

**Issue by iadxworld** [kean/Nuke#145]

**Comment by iadxworld** [comment]
I migrated to Nuke 6.0 from 5.0

Upon build I am constantly getting following errors!

`'CacheKey' is inaccessible due to 'private' protection level`
`'_ref' is inaccessible due to 'private' protection level`

These are the errors in the Request file. I am not quite sure how to deal with them. What is the fix for this.

**Comment by kean** [comment]
Nuke 6 requires Swift 4, it seems that you might be using an older version.

**Comment by iadxworld** [comment]
Thats right! I had to change the compiler language in Nuke Build settings to  swift 4 from swift 3.2.

Thank for the prompt response.

**Comment by andreaagudo3** [comment]
> Thats right! I had to change the compiler language in Nuke Build settings to swift 4 from swift 3.2.
> 
> Thank for the prompt response.

How did u do that? I changed it in the Build Settings of my project and didnt work

**Comment by adxworld** [comment]
Go to your Pods> Build Settings> search for "swift". > see Swift compiler Language option > select drop down and choose preferred language
