### ISSUE TITLE
Some Question about Cache Image

### ISSUE THREAD

**Issue by Lee827** [kean/Nuke#148]
1.Cache images from disk will expiry?
2.How to set expiry date to never?
3.How to remove the image from cache for key?

4.This is only cache memory? not disk?
Cache.shared.costLimit = 1024 * 1024 * 100 // 100 MB
Cache.shared.countLimit = 100

let request = Request(url: url)
Cache.shared[request] = image
let image = Cache.shared[request]

5.This code will auto storage in disk and memory? 
Manager.shared.loadImage(with: url)

Thank you

**Comment by kean** [comment]
Hey,

I'll try to document all of those features as nicely as possible in the future.

1, 2, 3 By default images are stored on disk using NSURLCache. The cache is controlled by HTTP headers. See more https://kean.github.io/post/image-caching

If you want to control disk cache from the client see https://github.com/kean/Nuke/blob/master/Documentation/Guides/Third%20Party%20Libraries.md#using-other-caching-libraries

4. Yes, this is memory cache only, it stores processed images which are ready for display.

5. In memory - yes. On disk - depending on HTTP cache control headers. See more See more https://kean.github.io/post/image-caching

**Comment by Lee827** [comment]
Thanks for your help!!!!

**Comment by edon2005** [comment]
Hi Guys,

I am still in misunderstanding. 

So if we make: 
`Nuke.loadImage(with: url, into: imageView)`
It will store image in Memory only? And if http response header will contain `Cache-Control:public`
so it will also be stored on Disk? 
And there is no possibility to store every images on disk? 
Thanks.
