### ISSUE TITLE
Disable Evaluation SSL Certificate

### ISSUE THREAD

**Issue by vas7n** [kean/Nuke#149]
Hello!

I made the appropriate settings. But the framework does not feel this. 

![1](https://user-images.githubusercontent.com/14210834/36718363-b11f10b2-1bcb-11e8-97cf-54c7c1546e5c.png)

Maybe in Nuke need to d

o differently?

Thank you!

**Comment by kean** [comment]
Hey!

AFAIK what `NSExceptionAllowsInsecureHTTPLoads` does is it allows you to use `http://` request, it doesn't disable SSL certificate evaluation. If you're using Alamofire for loading data, it seems to have a `ServerTrustPolicy` which allows you to configure that.

**Comment by vas7n** [comment]
OK. I do not use. I will try.
