### ISSUE TITLE
How to store,fetch and delete captured image by key using Nuke framework

### ISSUE THREAD

**Issue by EkambaramE** [kean/Nuke#150]

**Comment by EkambaramE** [comment]
I need to directly store image, fetch the image and delete image through a nuke.

**Comment by kean** [comment]
Hey!

By "captured image" do you mean images taken using the camera? If that's the case then one way to achieve that is to simply store those images in some predefined folder on disk and then fetch them using `Nuke.Manager`:

```swift
Nuke.Manager.shared.loadImage(with: URL("file://path_to_image")) { result in
   // Handle result
}
```

> [`URLSession`](https://developer.apple.com/documentation/foundation/urlsession) which is used under the hood is capable of loading images from disk.

**Comment by EkambaramE** [comment]
Thanks for reply Kean, yes I'm saying images taken from the camera If allowing storing in a disk with the key. It will be great!!! 


Because SDWebImage doing the same job:
[[SDImageCache sharedImageCache] storeImage:image forKey:imageKey] toDisk:YES];

**Comment by kean** [comment]
> [[SDImageCache sharedImageCache] storeImage:image forKey:imageKey] toDisk:YES];

There is no dedicated custom disk cache in Nuke, it relies on native `Foundation.URLCache` instead. The shared cache can be accessed like this: `Nuke.DataLoader.sharedURLCache`, however it doesn't have a dedicated API for storing images, you have to do it yourself.

Keep in mind, that the cache contents can get cleared automatically when it exceeds certain limit.

Like I mentioned in a previous message an alternative to using "cache" would be to actually store data on disk, it's pretty straightforward:

```swift
// Create image data.
let data = UIImageJPEGRepresentation(image, 0.8)

// Create URL for key.
let key = "ImageKey"
let url = URL(fileURLWithPath: "path/\(key).jpeg")

// Write data to disk. Make sure that the directory exists!
try data?.write(to: url)

// Remove data form disk.
try FileManager.default.removeItem(at: url)
```

**Comment by EkambaramE** [comment]
Thanks again @kean 
Can you tell me what is the usage of following code:
`<addr>`
let cache = Cache()
cache["key"] = UIImage(string: "****")
if let image = cache[key] {
            return image
}
`<addr>`

**Comment by kean** [comment]
It's memory cache only.
