### ISSUE TITLE
How to know image already downloaded or not, before downloading image

### ISSUE THREAD

**Issue by EkambaramE** [kean/Nuke#151]
How to know image already downloaded or not before proceed download

**Comment by prajyot-vit** [comment]
`let cachedResponse = NSURLCache.sharedURLCache().cachedResponseForRequest(imageRequest)`
I hope it helps.

**Comment by kean** [comment]
> let cachedResponse = NSURLCache.sharedURLCache().cachedResponseForRequest(imageRequest)
I hope it helps.

This is true in case you're using a custom `DataLoader` with `NSURLCache.sharedURLCache`. However, if you're using Nuke with default configuration here's how you can do that:

```swift
let request = Request(url: "image_url")
if Nuke.Cache.shared[request] != nil {
    // Image is in memory cache
} 

// I'd recommend to check `Foundation.URLCache` documentation before using this.
if Nuke.DataLoader.sharedUrlCache.cachedResponseForRequest(request.urlRequest) != nil {
    // Image is in disk cache
}
```

In general I'd recommend to avoid checking manually if the image is in cache or not - it might not actually be there by the time you make a request. It's ok however, to retrieve image synchronously from memory cache (see `Nuke.Cache.shared`) without making any requests.
