### ISSUE TITLE
On-disk caching question

### ISSUE THREAD

**Issue by jtressle** [kean/Nuke#152]
First off, great library!  

I had a question regarding on-disk caching.  From your previous posts, you say you're using Foundation.URLCache.  Are the cache keys being created using URLCache?

In your Nuke example app, I tested on-disk caching by first running the program with wifi on.  I then reran the example app with no connectivity.  On-disk caching worked and images were loaded.  The cache keys used in the example app container were parsed values of the image URL (as expected).

In my app, on-disk caching does not work.  I'm using Google Cloud Storage and providing a long URL with authentication token attached.  The URL + token however are static values.  When I do the above no-connectivity test, my images do not show up.  In my app container, the caching keys are not derivatives of my URL.  They also appear to be random from as I've reinstalled the app to find different caching keys for the same URL.  I believe the non-predictable caching keys are the reason why on-disk caching does not work.

Have you seen this?  Any recommendations?  Is it possible to provide an optional tag input to the Manager.shared.loadImage() function that could be used to label the caching key?  

Thanks,
Jan-Michael

**Comment by jtressle** [comment]
HI @kean,

You can probably close this request.  I was able to get my caching to work by doing the following:

`                    let urlRequest = URLRequest(url: url, cachePolicy: .returnCacheDataElseLoad, timeoutInterval: 60)
                    
                    Manager.shared.loadImage(with: Request(urlRequest: urlRequest), into: imageView)`

On-disk caching works as expected.  I believe the issue is that Google Storage uses HTTPS links.

Thanks again,
Jan-Michael

**Comment by kean** [comment]
Hey @jtressle,

I think it has to do with HTTP cache control. I have a starter guide [available here](https://kean.github.io/post/image-caching) with some useful links at the end.

I don't know exactly what kind of cache control headers are set by Google Storage, but my guess is that  HTTP cache tries to validate that the image in cache is not staled before serving it. This is why it can't serve images offline - can't validate them. There are at least two ways to disable validation:
- [on a server] Adjust HTTP cache control headers returned by the server to indicate that those resources do not require validation
- [on a client] Use `.returnCacheDataElseLoad` option which you already do. This option disables cache validation. Even if the image is "stale", it's still going to be served immediately.

I'm going to close this, if you have any other questions please let me know.
