### ISSUE TITLE
Swift warnings

### ISSUE THREAD

**Issue by sunjunkie** [kean/Nuke#159]
I am upgrading from Nuke 5 to 6.1.1. Xcode 9.3 is giving me Swift compiler warnings when I use Nuke.loadImage. 

_my code:_ 
Nuke.loadImage(with: url, into: imgView)

_compiler warning:_
'loadImage(with:into:)' is deprecated: loadImage(with:into:) is deprecated. Use Manager.shared.loadImage(with:into:) instead.

The Readme file usage guide uses Nuke.loadImage.

**Comment by kean** [comment]
Hey, @sunjunkie! The current README is already showing 7.0-beta3 APIs. Please open the [6.1.1 tag](https://github.com/kean/Nuke/tree/6.1.1) to see the README for version 6.1.1.

P.S. Nuke 7 has more new features and changes then all of the previous versions combined. I went out of my way to make it fully source compatible with Nuke 6.1.1, so there is no need to worry about migrating to not the soon-to-be-latest version.

**Comment by sunjunkie** [comment]
Does this mean that Nuke.loadimage will be the preferred function call in 7.0? If so, then I'll leave my code unchanged.

**Comment by sunjunkie** [comment]
Got it, thanks.
