### ISSUE TITLE
Disambiguating Result

### ISSUE THREAD

**Issue by edon2005** [kean/Nuke#164]
HI, 

Is it possible to solve a conflict with the Framework that has the same type Result?
https://github.com/antitypical/Result

Thanks

**Comment by kean** [comment]
Hey!

The `Result` type in was deprecated in Nuke 7.0 and I'm planning to remove it completely fairly soon.

There are ways to solve the conflict. The conflict only appears in the files in which you import both `Nuke` and `Result` at the same time - Swift compiler doesn't know which one to use. To disambiguate, you can explicitly select the module (e.g. `Nuke.Result` or `Result.Result`). I know this is not ideal, this is the primary reason why this type is now deprecated.

**Comment by kean** [comment]
@edon2005, `Result` was removed in [Nuke 7.5](https://github.com/kean/Nuke/releases/tag/7.5).

**Comment by kean** [comment]
TIL you can also do `import Result.Result` - importing specific declarations from frameworks take precedence.
