### ISSUE TITLE
Question: About cache for URL with the same host name and different options.

### ISSUE THREAD

**Issue by wxforgb** [kean/Nuke#166]
hello!
We are using an image service that can request a image with options of width and height  like ‘https://*****.jpg?width=100&height=100’, 
According to the frame size of the cell, we set the URL options.
But if we have a large size image in the cache(such as ?width=200&height=200), we would like to use it to display, instead of requesting a new image with weight=100&heigh=100.
Can we have a way of doing it?

**Comment by kean** [comment]
Hey,

I personally use [RxNuke](https://github.com/kean/RxNuke) for those kinds of tasks.

In case you're using native `URLCache` here's one way to do it:

```swift
let cacheRequest = URLRequest(url:
    URL(string: "...?width=200&height=200")!,
    cachePolicy: .returnCacheDataDontLoad
)
let networkRequest = URLRequest(
    URL(string: "...?width=100&height=100")!,
    cachePolicy: .useProtocolCachePolicy
)

Observable.concat(pipeline.loadImage(with: cacheRequest).asObservable(),
                  pipeline.loadImage(with: networkRequest).asObservable())
    .take(1)
    .subscribe(onNext: { (response, error) in
        // Use an image
    }).disposed(by: disposeBag)
```

This would run two requests serially. If the first one succeeded, the second one will not run.

The reason why this functionality isn't built in Nuke is that RxSwift (or any other reactive or promise library) already solves those kinds of problems in a very elegant way. With RxSwift you can do all sort of things. I've provided a couple more of examples in [README](https://github.com/kean/RxNuke#usage) for RxNuke.

But, if you're not using RxSwift already I probably wouldn't recommend installing it just to use RxNuke. RxSwift is really powerful, but if you need to implement just a single scenario like that I would recommend implementing it by hand.

**Comment by wxforgb** [comment]
Thank you for your quick reply. 
We will try the method you provided to us. 
Thank you again.
