### ISSUE TITLE
Regarding Disk Cache

### ISSUE THREAD

**Issue by edon2005** [kean/Nuke#168]
Hi Guys,

I am still in misunderstanding. 

if we use code: 
`Nuke.loadImage(with: url, into: imageView)`
It will store image in Memory only? And if HTTP response header will contain `Cache-Control:public`
so it will also be stored on Disk? 
And there is no possibility to say Nuke to store every images on disk? 
Thanks.

**Comment by kean** [comment]
Hey,

Yes, if you're using default `DataLoader` with a default native `URLCache` then the server that you're using need to enable HTTP cache.

As an alternative to HTTP cache, I'm currently working on bringing [custom aggressive disk cache](https://github.com/kean/Nuke#aggressive-disk-cache-experimental) in Nuke. There is already an experimental version available, but it's going to get a lot better soon - there is going to be a full-featured public API, default key encoder implementation, etc.

I hope that this helps. If you'd like to learn more about HTTP, there plenty of information online. My personal favorite resource about web technologies is [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).

I'm sorry if this is all a bit overwhelming. I hope to do a better job explaining those things in README and related guides.

**Comment by edon2005** [comment]
Hi,

Thank you for answer. 
So when we set in application only: 
`import Nuke`
and make only `Nuke.loadImage(with: url, into: imageView)`
what is default setting will be used? 

Thanks you

**Comment by kean** [comment]
By default this URLCache instance is going to be used:

```swift
// Shared url cached used by a default `DataLoader`. The cache is
/// initialized with 0 MB memory capacity and 150 MB disk capacity.
public static let sharedUrlCache = URLCache(
    memoryCapacity: 0,
    diskCapacity: 150 * 1024 * 1024, // 150 MB
    diskPath: cachePath
)
```

And URLCache uses HTTP cache control. So if the server enables it by setting `Cache-Control` header, the image data is going to be stored in URLCache.

I've written [a post](http://kean.github.io/post/image-caching) about this a couple of years ago that goes into a few more details. It should still be relevant today.

**Comment by edon2005** [comment]
Thank you, It is just a little unclear what an algorithm is. I mean how Nuke decide to store Image in Memory or on Disk. Or if it is possible it will store an image and in Memory and on Disk? I am a little confused, sorry. If I need to save an Images only once when application runnig for the first time and before showing? That is batch of images should be loaded before UIimageView change status to unhidden, is it possible with Nuke?

**Comment by kean** [comment]
Good question, I think it would be valuable to put a high-level overview of what the default image pipeline looks like and what does it do in the README.  I'm going add it soon.

If you were to put the pipeline configuration in one place it would look something like this:

```swift
let pipeline = ImagePipeline {
    // Shared image cache with a `sizeLimit` equal to ~20% of available RAM.
    $0.imageCache = ImageCache.shared

    // Data loader with a `URLSessionConfiguration.default` but with a
    // custom shared URLCache instance:
    //
    // public static let sharedUrlCache = URLCache(
    //     memoryCapacity: 0,
    //     diskCapacity: 150 * 1024 * 1024, // 150 MB
    //     diskPath: "com.github.kean.Nuke.Cache"
    //  )
    $0.dataLoader = DataLoader()

    // Maximum number of concurrent data task set to `6`.
    $0.dataLoadingQueue.maxConcurrentOperationCount = 6

    $0.imageDecodingQueue.maxConcurrentOperationCount = 1
    $0.imageProcessingQueue.maxConcurrentOperationCount = 2

    // Combine the requests for same original image into one.
    $0.isDeduplicationEnabled = true

    // Progressive decoding is disabled by default.
    $0.isProgressiveDecodingEnabled = false

    // Custom disk cache is disabled by default, the native URL cache used
    // by a `DataLoader` is used instead.
    $0.dataCache = nil
}
```

> Or if it is possible it will store an image and in Memory and on Disk?

Yes, by default there is both a memory cache and a disk cache enabled (those are two separate things, see code sample above).

> That is batch of images should be loaded before UIimageView change status to unhidden, is it possible with Nuke?

You'll need to write the logic of starting those requests and waiting for their completion by hand. It might be something worth putting into `ImagePreheater` though. And if you're using RxSwift you can implement this using `combineLatest` (see [RxNuke](https://github.com/kean/RxNuke#huc_load_multiple_display_once) for examples) and (optionally) [smart-retries](http://kean.github.io/post/smart-retry).

**Comment by edon2005** [comment]
Thank you for your answer! It is helpful!

**Comment by kean** [comment]
Hey, @edon2005. I've [added two sections](https://github.com/kean/Nuke#image-pipeline-1) in README: "Default Image Pipeline" and "Image Pipeline Overview". I hope that you'll find it useful.
