### ISSUE TITLE
DataCache won't sweep data

### ISSUE THREAD

**Issue by s4x** [kean/Nuke#171]
Hi! Testing Nuke for image caching. As Readme noticed url cache slow and we want to use disk cache. But as I can see size limit is not working now. Data in Settings grow with single new cached image and have no limit.
I may be wrong, but it seems that the method `_scheduleSweep` is not called at initialization.

**Comment by kean** [comment]
Hey, @s4x. Yeah, you're right, sorry about that!

The custom disk cache is still an experimental feature in Nuke 7.2. I'm glad that so many people are interested in it. I'm currently working on finishing it and making it public in 7.3 which I plan to release some time later this week. I'm going to address this issue as well.

The new `DataCache` is going to be much simpler and even faster than the one in 7.2 😎

**Comment by kean** [comment]
It seems to be a regression introduces in one of the later versions. As a workaround I would recommend downgrading to 7.0.1. I hope to release 7.3 soon.

**Comment by kean** [comment]
Hey, @s4x. I've decided to push back some features which were initially in scope for version 7.3 and focus on getting `DataCache` right first which I hopefully did. Please give the [new version](https://github.com/kean/Nuke/releases/tag/7.3) a try.
