### ISSUE TITLE
Would be nice to have a completion callback for DataCache.removeData(for:)

### ISSUE THREAD

**Issue by filipealva** [kean/Nuke#172]
Let's assume that you need to refresh a cached image, you'll need to remove it from memory and disk and then make a request to retrieve the new data. The issue is that today we don't have a way to know when `DataCache.removeData(for:)` has finished, it might avoid the request to retrieve the refreshed image to happen since we might still have the data of this image stored before `DataCache.removeData(for:)` finishes.

**Comment by kean** [comment]
Hey, you shouldn't need to know when the IO is finished. If you ask cache to remove data for a key, and then immediately try to read data for this key, you'll get `nil` in response:

```swift
cache.removeData(for: key)
let data = cache.cachedData(for: key)
// Data is guaranteed to be `nil` at this point.
```

**Comment by kean** [comment]
The only issue that I can see with this case has to do with deduplication (see `ImagePipeline.Configuration.isDeduplicationEnabled`) - other libraries have this issue as well. With deduplication enabled - which it is by default - there is no guarantee that when you request a new image, your request won't be handled by an already executing task.

You could disable deduplication all together, but this feature is crucial for prefetching. I had this in mind for a while now, but haven't yet come up with a final solution yet.

It might not be an issue at all depending on when and how you request these images. But please keep this in mind when removing images from cache manually.

**Comment by filipealva** [comment]
Thanks for the tips! I'm working with a user avatar, so it would be better to use HTTP Cache but since the server doesn't support it I have to deal with managing the disk cache and disabling deduplication. Even though I'm doing that, the issue is still happening. I have even tried `removeAll()` from `DataCache` but yet when I make a request after this call I have the cached image. I could not isolate the issue, it can be the server that is sending to me the old avatar or it can be the `DataCache` that is not clearing successfully the cache.

**Comment by filipealva** [comment]
Forget it, I found the real issue, when manually clearing the cache I was referencing `ImageCache.shared` but I have a custom pipeline configuration with a different instance of `ImageCache` so clearing the memory cache from `ImageCache.shared` would not clear this image. 

Thank you for the support 💯
