### ISSUE TITLE
How to access image Data using Nuke 7.3?

### ISSUE THREAD

**Issue by swftvsn** [kean/Nuke#176]
Hi,

I'm upgrading our app to 7.3 and parts of our app needs the raw Data of an image. I know the url of the image. What I don't know is if it has been loaded already to disk cache or not.

How can I use Nuke to give the Data of the image and if it isn't in the cache to download it, apply it to cache and then return it to me. I don't have any "into" target to give to Nuke.

Please advice how this should be done?

One option is to query the cache by hand and if it does not exists fire of request using urlsession and then push it to cache and return it, but is there any better way to do it?

**Comment by kean** [comment]
Hi @swftvsn,

>  I don't have any "into" target to give to Nuke.

You can use [ImagePipeline directly](https://github.com/kean/Nuke#image-pipeline) to load images without a need for a target.

> How can I use Nuke to give the Data of the image and if it isn't in the cache to download it, apply it to cache and then return it to me.

There are multiple built-in options:

- The default `ImagePipeline` [comes with `URLCache`](https://github.com/kean/Nuke#data-loading-and-caching) (native HTTP cache)
- If you're not happy with `URLCache` you can use a [custom aggressive disk cache](https://github.com/kean/Nuke#aggressive-disk-cache) (also built-in)
- You can also [integrate any custom disk cache](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Third%20Party%20Libraries.md#using-other-caching-libraries
) that you'd like pretty easily

**Comment by swftvsn** [comment]
I've used DFCache previously to cache images in different sizes. Is there any need to use DFCache anymore, or is the built-in way better?

**Comment by swftvsn** [comment]
And thank you for the 1) awesome lib 2) impressive time-to-answer :D 

So I can use directly `ImagePipeline.shared.loadImage(with:)`?

The more I play with 7 the more I like it!

**Comment by kean** [comment]
> I've used DFCache previously to cache images in different sizes. Is there any need to use DFCache anymore, or is the built-in way better?

`Nuke.DataCache` is faster - it allows for parallel reads _and_ it also writes in parallel with reads thanks to the staging area. And you don't need an extra dependency. It's pretty cool, I don't think there are any faster disk caching solutions available at the moment.

> The more I play with 7 the more I like it!

Thanks!
