### ISSUE TITLE
Nuke 7: warnings

### ISSUE THREAD

**Issue by agisilaos** [kean/Nuke#177]
Hello, Kean 👋 Recently I updated Nuke to 7.0 and as I read a lot of things changed/ got updated. Before writing this issue I tried to read through the guides and try to migrate the code myself but couldn't find a solution.

So I have this piece of code:

 ```swift
// MARK: Setup
    func loadPhoto() {
        if let user = self.user {
            guard let photoURL = user.photoURL, let url = URL(string: photoURL) else { return }
            Manager.shared.loadImage(with: url) {
                self.avatarView.photo = $0.value
            }
        }
    }
```
**P.s avatarView is a UIButton class.**

and I get these warnings:

<img width="758" alt="screen shot 2018-07-25 at 00 18 52" src="https://user-images.githubusercontent.com/10944108/43166835-633c721a-8fa0-11e8-8907-1966ba99e2d0.png">

How and what you believe is the correct way to update my code to support Nuke 7, so I can achieve the same functionality? 

Thanks in advance for your help and thank you for creating Nuke, it has been so useful for many of my projects

**Comment by kean** [comment]
Hi! 

This particular code sample can be replaced with:

```swift
func loadPhoto() {
        guard let photoURL = user?.photoURL, let url = URL(string: photoURL) else { return }
        ImagePipeline.shared.loadImage(with: url) { response, _ in
            self.avatar.photo = response?.image
        }
}
```

The main changes here are:

- A `Manager`, `Loader` classes with vague responsibilities and unnecessary protocols (`Loading`) were replaced with a single `ImagePipeline` class.
- The completion closure now gives you `ImageResponse` and `Error`

Yeah, there are quite a few changes in Nuke 7 but they had to be made to add all these new features and overall just make the framework more pragmatic - all the versions before 7 were kinda experimental.

**Comment by agisilaos** [comment]
Thank you so much for all the info @kean! Since my question was answered I’m gonna close this issue! Thanks again and hope you have a great day!
