### ISSUE TITLE
Authorization header?

### ISSUE THREAD

**Issue by shoaib-akhtar** [kean/Nuke#183]
Hi, 
How can i set authorization header? Will my caching still work if my authorization header keep changing on each request?

**Comment by kean** [comment]
Sorry, missed this question. 

> How can i set authorization header?
One way to pass an authorization header is to create it a [URLRequest with it](https://github.com/kean/Nuke#image-requests).

> Will my caching still work if my authorization header keep changing on each request?
Yes, memory cache will still work, custom disk cache will still work. I would check the native disk cache though (URLCache), I can't remember exactly how it handles auth headers.

**Comment by justingiffard-impact** [comment]
Hiya sorry to open this again. Was wondering if you could help me

I have tried the route of making a `URLRequest` and then making a `ImageRequest` out of it and then using `LazyImage(request: ImageRequest, content: Content)` and it seems to stripping the auth headers

From what I can tell (and please correct me if I am wrong) the `ImageRequest(urlRequest:)` initialiser packs the urlRequest into a Resource enum. I cannot tell if its there that the headers are lost or not though

If I look in lldb though the imageRequest looks like this:

`ImageRequest(resource: https://redacted.com/redacted/Logo, priority: normal, processors: [], options: Options(rawValue: 0), userInfo: [:])`

which doesn't really make it clear if it uses the headers or not

if I look at the urlRequest though I can see the headers are present

▿ Optional<URLRequest>
  ▿ some :  https://redacted.com/redacted/Logo
    ▿ url : Optional<URL>
      ▿ some :  https://redacted.com/redacted/Logo
        - _url : https://redacted.com/redacted/Logo
    - cachePolicy : 0
    - timeoutInterval : 60.0
    - mainDocumentURL : nil
    - networkServiceType : __C.NSURLRequestNetworkServiceType
    - allowsCellularAccess : true
    ▿ httpMethod : Optional<String>
      - some : "GET"
    ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
      ▿ some : 4 elements
        ▿ 0 : 2 elements
          - key : "Sec-CH-UA-Mobile"
          - value : "redacted"
        ▿ 1 : 2 elements
          - key : "Sec-CH-UA-Platform"
          - value : "redacted"
        ▿ 2 : 2 elements
          - key : "Authorization"
          - value : "Bearer redacted"
        ▿ 3 : 2 elements
          - key : "Sec-CH-UA"
          - value : "redacted"
    - httpBody : nil
    - httpBodyStream : nil
    - httpShouldHandleCookies : true
    - httpShouldUsePipelining : false

any ideas

**Comment by justingiffard-impact** [comment]
as mentioned in #790 problem solved
