### ISSUE TITLE
Progress feature doesn't seem to be working.

### ISSUE THREAD

**Issue by j531** [kean/Nuke#184]
First, thanks for your great work!

There seems to be a bug with the progress reporting feature. The progress block is only called once, after the entire image has been downloaded.

To replicate:

```
class PrototypeViewController: UIViewController {

    private let imageView = UIImageView()

    override func viewDidLoad() {
        super.viewDidLoad()

        view.addSubview(imageView)
        imageView.contentMode = .scaleAspectFit

        let url = URL(string: "https://apod.nasa.gov/apod/image/1809/Broom_Pickering_milne_APODw1200.jpg")!
        Nuke.loadImage(with: url, into: imageView, progress: { (_, completed, total) in
            print(completed, total)
        })
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        imageView.frame = view.bounds
    }
}
```

Cheers!

**Comment by kean** [comment]
Hey! I've just tested it and it works fine for me. It might be that you've already downloaded this image before and it's not being loaded from the disk cache. In that case you don't get progress reports, the block is only going to get called once.

**Comment by j531** [comment]
Hmm, strange. I'm clearing the caches now and still getting the same result. This progress block is only being called after the image has downloaded. If the image was cached and I don't get progress reports (which would be correct), should it not load instantly (I'm still having to wait for it to appear)?

Should this work?

```
class PrototypeViewController: UIViewController {

    private let imageView = UIImageView()

    override func viewDidLoad() {
        super.viewDidLoad()

        ImageCache.shared.removeAll()
        DataLoader.sharedUrlCache.removeAllCachedResponses()

        view.addSubview(imageView)
        imageView.contentMode = .scaleAspectFit

        let url = URL(string: "https://apod.nasa.gov/apod/image/1809/Broom_Pickering_milne_APODw1200.jpg")!
        Nuke.loadImage(with: url, into: imageView, progress: { (_, completed, total) in
            print(completed, total)
        })
    }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        imageView.frame = view.bounds
    }
}
```

For what it's worth, this on an iOS 11.4 iPhone 7 simulator. I'll come back to this and have a poke around if I get time.

**Comment by kean** [comment]
```
DataLoader.sharedUrlCache.removeAllCachedResponses()
```

AFAIU this would not remove the cached result instantly. It also doesn't seem to make much sense to clear the caches before loading the image.

>  should it not load instantly (I'm still having to wait for it to appear)?

No, this is a pretty large image, it takes a little bit of time to read it from disk and to decompress it (see `ImageDecompressor`). It won't appear instantly unless it's stored in memory cache (`ImageCache`).

**Comment by j531** [comment]
I'm going for the Nuclear Approach now and I'm wiping the simulator and firing the request off 10 seconds after I've cleared the caches to ensure the image will be retrieved via the network. Progress reports still don't seem to be coming through :(

For what it's worth the following function is only getting called once and the chunk is the entire image:

`private func _session(_ session: ImageLoadingSession, didReceiveData chunk: Data, response: URLResponse)`

Thanks for your help!

**Comment by j531** [comment]
Okay, it turned out that I had [netfox](https://github.com/kasketis/netfoxl) enabled and it was doing some black magic behind the scenes to interfere with the request and this somehow broke progress reporting. Disabling it makes it work again.

Thanks for your help regardless!

**Comment by kean** [comment]
Glad that you found an issue. I'd recommend using [Charles](https://www.charlesproxy.com) for network debugging 😉
