### ISSUE TITLE
Upgrading from 6 to 7: Migrating from DFCache to built-in caching

### ISSUE THREAD

**Issue by swftvsn** [kean/Nuke#185]
Hi,

I have an app that has decent user base and the app is out using Nuke 6. I'd like to upgrade to 7, and we'd like to drop DFCache in favor of the new build-in way.

However, we'd like to reuse the current, existing cache found in phones to avoid re-downloading all content.

The old cache caches three image sizes (original, medium and thumbnail). As the content is mostly photos taken using the phone's back camera, we resize the content in advance for all used sizes, but upload only the original one.

```swift
func cacheData(url: String, data: Data) {
        
        //Originals cache
        let request = URLRequest(url: URL(string: url)!)
        let response = URLResponse(url: request.url!, mimeType: "image/jpeg", expectedContentLength: data.count, textEncodingName: nil)
        originalsDiskCache.store(CachedURLResponse(response: response, data: data), forKey: url)
        
        //Medium && thumbnail cache
        if let image = decoder.decode(data: data, response: response) {
            if let processed = thumbnailProcessor.process(image) {
                thumbnailDiskCache.store(processed, forKey: url)
            }
            if let processed = mediumProcessor.process(image) {
                mediumDiskCache.store(processed, forKey: url)
            }
        }
        
    }
```
Where the caches are
```swift
    private func initializeThumbnailDiskCache() -> DFCache {
        let cache = DFCache(name: "thumbnails", memoryCache: nil)
        cache.diskCache?.capacity = UInt64(1024 * 1024) * UInt64(5000) //5Gigabytes
        return cache
    }
    
    private func initializeMediumDiskCache() -> DFCache {
        let cache = DFCache(name: "mediums", memoryCache: nil)
        cache.diskCache?.capacity = UInt64(1024 * 1024) * UInt64(7500) //7,5Gigabytes
        return cache
    }
    
    private func initializeOriginalsDiskCache() -> DFCache {
        let cache = DFCache(name: "originals", memoryCache: nil)
        cache.diskCache?.capacity = UInt64(1024 * 1024) * UInt64(15000) //15Gigabytes
        return cache
    }
```

So the question is: Can I use the existing data in phones, that is cached using Nuke 6 and DFCache with Nuke 7 and the new built-in caching subsystem?

To elaborate more, are the following the same?

```swift
   let cache = DFCache(name: "thumbnails", memoryCache: nil)
   dataCache = try! DataCache(name: "thumbnails", filenameGenerator: {
      return $0
   })
```

**Comment by kean** [comment]
Hey! That's an interesting question. I think this just might work. Technically both `DFCache` and `Nuke.DataCache` work with the same simple plain hierarchy of data on disk.

All you need to do is make sure that you use the same function to generate filenames from URLs. `DFCache` uses SHA1. `Nuke.DataCache` also uses SHA1 by default but this feature is only available on Swift 4.2. To make sure that the caches are compatible you need to create `Nuke.DataCache` with the same hashing function as the default `DFCache` one:

```swift
let cache = DFCache(name: "thumbnails", memoryCache: nil)
dataCache = try! DataCache(name: "thumbnails", filenameGenerator: {
    return sha1_same_as_dfcache($0)
})
```

Please make sure to test it cause I might be missing something.

**Comment by kean** [comment]
`DFCache` has `NSCoding` support out of the box (`CachedURLResponse` implements `NSCoding`). `DataCache` doesn't, it only knows how to work with raw data. It should be fairly straightforward to extend it with `NSCoding` support.

**Comment by kean** [comment]
Hey, did you finish migrating to Nuke 7 successfully?

**Comment by swftvsn** [comment]
Not yet, I'm doing some other work now and continue it later. (2-4 weeks probably.) 

I think we're going to move the problematic cache to this newer one by iterating the stuff in DFCache, inserting it to the new cache and then deleting the entry in DFCache. Sleep for 50ms and process the next one. Continue as long as there are entries, and start this process in background when the app starts. 

Then we'll remove the DFCache after couple of releases and call it a day.

**Comment by kean** [comment]
Ok, going to close this for now. If you have more questions or issues, please feel free to open another issue.

DFCache is not going away any time soon. Also, it seems that you might've been using DFCache as a storage option (you can't just throw it away). I personally would not recommend relying on anything provided in Nuke caching layer, or DFCache, as a permanent persistent storage solution.
