### ISSUE TITLE
Update Demo with UICollectionViewDataSourcePrefetching example

### ISSUE THREAD

**Issue by jtressle** [kean/Nuke#186]
Great library!

I ran across this post using Nuke with UICollectionViewDataSourcePrefetching and wanted to post it here as an example of using UICollectionViewDataSourcePrefetching with Nuke.

https://qiita.com/kz56cd/items/e90132bf9c44fd0f2c6d

I got it working by instantiating a preheater:

```swift
var preheater : ImagePreheater!

override func viewDidLoad() {
        super.viewDidLoad()
        
        collectionView?.prefetchDataSource = self
        preheater = ImagePreheater()
        ...
}
```

I then followed the link and used the preheater in the Prefetch Delegate as such:

```swift
extension ProjectsCollectionController : UICollectionViewDataSourcePrefetching
{
    func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath])
    {
        preheater.startPreheating(with: makeCacheRequests(indexPaths: indexPaths))
    }
    
    func collectionView(_ collectionView: UICollectionView, cancelPrefetchingForItemsAt indexPaths: [IndexPath]) {
        preheater.stopPreheating(with: makeCacheRequests(indexPaths: indexPaths))
    }
}
```

where the image requests were created by:

```swift
func makeCacheRequests(indexPaths : [IndexPath]) -> [ImageRequest]
    {
        return indexPaths.map({ (indexPath) -> ImageRequest in
            let url = ...
            return ImageRequest(url: url)
        })
    }
```

Thoughts?

Thanks!

**Comment by kean** [comment]
@jtressle thanks for putting this together, yes this looks good. I would also recommend reducing the priority of preheating requests:

```swift
var request = ImageRequest(url: url)
request.priority = .low
return
``` 

I have a ticket to add native prefetching in a demo project https://trello.com/c/mdFGmp6F/26-add-prefetching-demo-which-uses-native-prefetching-apis. If someone would like to add it, I would much appreciate it.

**Comment by jtressle** [comment]
@kean thanks for the tip!  I got it implemented.

**Comment by kean** [comment]
I've updated the demo to use `UICollectionViewDataSourcePrefetching` on iOS 10 (Nuke still supports iOS 9, so I'm keeping [Preheat](https://github.com/kean/Preheat) demo around for now.
