### ISSUE TITLE
Nuke is not allowing SSL pinning. 

### ISSUE THREAD

**Issue by shahzaibiqbal** [kean/Nuke#192]
Is there a way to access URLSessionDelegate methods to perform SSL pinning? I am in a situation where I have add custom SSL certificate but I am not able do it with current Nuke architecture. Thank you.

**Comment by kean** [comment]
Hey, @shahzaibiqbal. Existing `DataLoader` is designed to be a simple solution for most basic cases. If you need some more advanced features like SSL pinning, you have at least two options:

- Use [Nuke with Alamofire](https://github.com/kean/Nuke-Alamofire-Plugin)
- Implement your own custom loader and make it conform to `DataLoading` protocol

**Comment by freemansion** [comment]
@shahzaibiqbal I had the same issue. I solved it writing custom `DataLoading` class as @kean recommended. Below is the working code:

```
private class ImageDataLoader: Nuke.DataLoading {
    let manager: Alamofire.SessionManager

    init() {
        let servertTrustPolicies: [String: ServerTrustPolicy] = [
            "add you server address here": .disableEvaluation
        ]

        let configuration: URLSessionConfiguration = URLSessionConfiguration.default
        configuration.httpAdditionalHeaders = Alamofire.SessionManager.defaultHTTPHeaders

        let policyManager = ServerTrustPolicyManager(policies: servertTrustPolicies)
        let manager = Alamofire.SessionManager(configuration: configuration, serverTrustPolicyManager: policyManager)
        self.manager = manager
    }

    // MARK: DataLoading
    /// Loads data using Alamofire.SessionManager.
    func loadData(with request: URLRequest, didReceiveData: @escaping (Data, URLResponse) -> Void, completion: @escaping (Error?) -> Void) -> Cancellable {
        // Alamofire.SessionManager automatically starts requests as soon as they are created (see `startRequestsImmediately`)
        let task = self.manager.request(request)
        task.stream { [weak task] data in
            guard let response = task?.response else { return } // Never nil
            didReceiveData(data, response)
        }
        task.response { response in
            completion(response.error)
        }
        return task
    }
}

struct ImageLoader {
    static let `default` = ImageLoader()
    private init() {
        let pipeline = ImagePipeline {
            $0.dataLoader = ImageDataLoader()
        }
        Nuke.ImagePipeline.shared = pipeline
    }

    @discardableResult
    func loadImage(url: URL?,
                   options: Nuke.ImageLoadingOptions = Nuke.ImageLoadingOptions.shared,
                   into view: Nuke.ImageDisplayingView,
                   progress: Nuke.ImageTask.ProgressHandler? = nil,
                   completion: Nuke.ImageTask.Completion? = nil) -> Nuke.ImageTask? {

        if let url = url {
            return Nuke.loadImage(with: url, options: options, into: view, progress: progress, completion: completion)
        } else {
            view.display(image: options.placeholder)
            return nil
        }
    }
}

```

**Comment by kean** [comment]
Thanks, @freemansion!

I forgot to mention, there also an entry in [Third Party Libraries Guide](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Third%20Party%20Libraries.md#using-other-networking-libraries) about implementing custom data loaders.

It seems that SSL pinning is a frequently requested feature, I'm going to add it to backlog and see whether it feasible to make the build-in data loader to support it without making it to complex. The idea behind `DataLoading` protocol was that there is a very good chance that if someone need a relatively complex feature like that, they probably already have their own custom data layer anyway. Or they are using Alamofire.

**Comment by shahzaibiqbal** [comment]
@kean Sorry for the delayed response. Thank you for all information. Would be nice to see SSL pinning inside Nuke in future. 
@freemansion Thank you for sharing example code. it is really helpful.
