### ISSUE TITLE
Cache by URL path without query parameters

### ISSUE THREAD

**Issue by mb812** [kean/Nuke#196]
Hi, I'm using Nuke to load images from S3 presigned URLs.
Like this one: 
https://xxx.s3.amazonaws.com/folder/image-name.jpg?AWSAccessKeyId=XXX&Expires=1539436276&Signature=XXX

The query parameter 'Expires' change every time, Nuke does not understand it has already cache it.
How can I get this? I would like to cache images by path (https://xxx.s3.amazonaws.com/folder/image-name.jpg) not by query parameters.

Thanks

**Comment by kean** [comment]
Hey, @mb812. You can set a custom `cacheKey` (`Hashable`) for each `ImageRequest`. I also have an issue in backlog to add a first-class API to support these types of URLs.

**Comment by kean** [comment]
In Nuke 8 there is going to be an option to set `filteredURL` when creating requests https://github.com/kean/Nuke/pull/255.

Example:

```
let request = ImageRequest(
    url: URL(string: "http://example.com/image.jpeg?token=1")! ,
    options: .init(filteredURL: "http://example.com/image.jpeg")
)
```

This option affects both memory and disk caches.

**Comment by kean** [comment]
Shipped in [Nuke 8.0-rc.1](https://github.com/kean/Nuke/releases/tag/8.0-rc.1)

**Comment by drinkius** [comment]
@kean has this option been removed?

**Comment by kean** [comment]
The `ImageRequest` options were reworked a bit in Nuke 10. There is a migration guide that covers all of the breaking changes, including [this one](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%2010%20Migration%20Guide.md#imagerequestoptions).
