### ISSUE TITLE
DataCache default args

### ISSUE THREAD

**Issue by KyoheiG3** [kean/Nuke#199]
If build `Nuke` on the `Carthage`, it has to set `filenameGenerator` in `DataCache`.

- Nuke 7.5
- Swift 4.2
- Carthage 0.30.1

Thank you.

**Comment by kean** [comment]
It seems I haven't update the Swift version in pbxproj. Not sure how `Carthage` handles Swift versions yet, will do some research today and update. Thanks for reporting!

**Comment by kean** [comment]
Pushed version 7.5.1 which now uses Swift 4.2 by default https://github.com/kean/Nuke/releases/tag/7.5.1
