### ISSUE TITLE
Fade in even if in cache

### ISSUE THREAD

**Issue by gabzsa** [kean/Nuke#200]
Is there any way to make use loadImage with fade-in even if the image is in memory or disk?

I find having to check manually if an image is cached and doing the same fade animation as loadImage would be doing is a bit cumbersome. There could be an option to make completely transparent whether the image was loaded from cache or remote, and just do the transition.

**Comment by kean** [comment]
Hey, @gabzsa. I've considered this option, but I never needed anything like that in any of my apps and I couldn't come up with any potential use cases. I would recommend simply running the transition manually in your case.

**Comment by gabzsa** [comment]
For me, it feels strange that a UI effect is dependant on something that is completely behind the scenes for the UI, and that it has to peek behind the layers (check if an image is in cache or not) just to execute the proper effect.

**Comment by kean** [comment]
I think it's a good default not to run transition when an image is stored in memory cache. One example where you need it is when you are scrolling a collection of images - you wouldn't want each cell to be animated each time it appears on the screen. Same with `reloadData`.

I checked other frameworks, they also work this way. Some provide an option to run transition even if the image is stored in memory cache. I'm not against adding an option like that.

**Comment by gabzsa** [comment]
I agree, an option would be great.

**Comment by gabzsa** [comment]
Created PR
