### ISSUE TITLE
Turn of error messages in console

### ISSUE THREAD

**Issue by gaborcsontos** [kean/Nuke#203]
Hi, 

I want to ask where can i turn off the error message printed in console?
It's pretty annoying and I can't find anywhere in the code, where the line responsible to print out the errors.

Cheers xoxo

**Comment by kean** [comment]
Hey, @gaborcsontos! I assume you're talking about `URLSessionTask` messages? These ones are logged by the system, here's how to disable them:

> In Product>>Scheme>>Edit Scheme...>>Run add the following environment variable: Name:OS_ACTIVITY_MODE, Value: disable

P.S. Sorry, couldn't respond earlier, was on vacation.

**Comment by gabors** [comment]
Hi @kean, Thanks for the really cool image downloader/caching framework. Really like this one andI have tried a lot of them :)

I see these messages as well, all of them seem to be from cancelled tasks 
`_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <2DA11AFC-3362-4C12-A858-CEFB2C59382B>.<97>, NSLocalizedDescription=cancelled} [-999]`

Creating that `OS_ACTIVITY_MODE` scheme variable doesn't remove these messages.

Are these messages normal and can be ignored?  App seems to function normally, I think these are data tasks being cancelled when you scroll quickly in collection views.

 спасибо еще раз

**Comment by kean** [comment]
That seems like something worth investigating. Well, Nuke doesn't do any printing on its own. Are you app doing anything unusual in regards to image loading?

**Comment by gabors** [comment]
Nothing really unusual. 
WBTVD Screeners by Warner Bros. https://itunes.apple.com/ca/app/wbtvd-screeners/id1265331727?mt=8

Layout is similar to netflix. A lot of long horizontal collection views stacked in vertical table view. 

Current AppStore version uses AlamofireImage for downloading and caching but I wanted more control over caching and preloading that’s why I’m trying Nuke.

**Comment by DanielStormApps** [comment]
Can confirm that this is from cancelling prefetching, specifically `ImagePreheater.stopPreheating(with: _)`.

Setting `OS_ACTIVITY_MODE` to `disable` does remove the logs for me though:

<img width="1110" alt="screen shot 2018-12-24 at 3 04 09 pm" src="https://user-images.githubusercontent.com/10573489/50406118-4cb19380-078d-11e9-92f4-62d01941f36e.png">

**Comment by kean** [comment]
I also tested this a while back on an empty project (no Nuke, nothing). If you cancel _any_ `URLSessionTask`, you get this message in the console. As @DanielStormApps suggested, setting `OS_ACTIVITY_MODE` to disable does remove the logs.
