### ISSUE TITLE
Removing image isPrepareForReuse enabled

### ISSUE THREAD

**Issue by gabzsa** [kean/Nuke#204]
I am using Nuke to display images in tableview cells. I have isPrepareForReuse enabled, since that is what you would want dealing with cells, right?

I am cycling images in the cells. Crossfading them one after the other. However, since isPrepareForReuse is enabled, just before the next image is loaded, and starts to fade in, the previous image is removed at ImageView.swift:343

This leads to sudden change to black, and then the fade in. What would be the recommendation to achieve constant crossfading through images, without sudden changes to black?

**Comment by DanielStormApps** [comment]
@gabzsa can you share your code for fading in the new images?

**Comment by gabzsa** [comment]
```
override func awakeFromNib() {
  super.awakeFromNib()
  self.setRandomImage()
}

@objc private func getRandomImage() {
  //... getting the url
  var options = ImageLoadingOptions(transition: .fadeIn(duration: 1.0))
  Nuke.loadImage(with: url, options: options, into: self.imageView, progress: nil, completion: { (_, _) in
    self.perform(#selector(self.getRandomImage), with: nil, afterDelay: 3.0))
  })
}
```

**Comment by kean** [comment]
Hey, @gabzsa! This is a curious, I'm not entirely sure what the expected behavior might be in this case. 

Have you tried disabling `isPrepareForReuseEnabled`, does it produce the result you want? I'm note sure this option even makes sense with cross fade. Maybe it would be better if we ignore `isPrepareForReuseEnabled` when cross fade animation is selected.

P.S. Sorry, couldn't respond earlier, was on vacation.

**Comment by gabzsa** [comment]
No worries! Yeah, disabling it solves it, but of course that has some ill-effects on reusing the cells. I was not sure about the correct approach either, but my conclusion is same as yours. Ignore it when cross-fade.

Should I PR?

**Comment by kean** [comment]
Yep, I would appreciate a PR. I'd also suggest rethinking transitions a bit. I'm not entirely sure why I haven't added an explicit `crossFade` option, it seems that we need it to be smart about removing images on reuse.

Please, before you create a PR, describe the behaviour you want from cross fade.
