### ISSUE TITLE
[macOS] Nuke.loadImage image is not displayed when .fadeIn transition is used

### ISSUE THREAD

**Issue by gabors** [kean/Nuke#206]
Looks like on macOS this never displays an image if I use a fadeIn transition

`Nuke.loadImage(
                with: imageRequest,
                options: ImageLoadingOptions(
                    placeholder: placeholderImage,
                    transition: .fadeIn(duration: 0.33)
                ),
                into: imageView)
`
yet on iOS/tvOS it works great.
On macOS as soon as I remove the whole options parameter, images show up fine.

**Comment by kean** [comment]
Seems be an issue with fade transition on macOS, would appreciate an MR.

**Comment by gabors** [comment]
Простите а "MR" енто что?

**Comment by gabors** [comment]
Looked at your code for the macOS fade transition.
Will try to make it work.

**Comment by kean** [comment]
Sorry, I got used to the terminology we use at work (MR - Merge Request). PR - Pull Request.

Yep, seems perfect, I think that's what I'm using except that I forgot to display the actual image 😁

**Comment by gabors** [comment]
Lol. Happens.

**Comment by kean** [comment]
Fixed in [7.5.2](https://github.com/kean/Nuke/releases/tag/7.5.2)
