### ISSUE TITLE
Prefetching a large amount of images upfront

### ISSUE THREAD

**Issue by AdamBCo** [kean/Nuke#211]
At the moment, I have an application where I need to prefetch +200 images in the background. These images will eventually be shown to the user as they navigate the application. I am currently using the default Nuke configuration and the Image preheater to attempt this task, but noticing issues where images are removed from disk frequently and prefetching not happening.

What strategy/Nuke configuration would you advise to accomplish this task?

**Comment by kean** [comment]
Hi,

There are multiple cache layers in Nuke which are described in [README](https://github.com/kean/Nuke#memory-cache) and there is also [a blog post](https://kean.github.io/post/image-caching). I would suggest going through these. 

If the images are removed from cache, I would suggest:

- Reducing the size of the image on backend side
- Increasing the limits of disk cache
- Making sure that HTTP cache control headers are correct. If they are not, fix them, or switch to custom [Aggressive Disk Cache](https://github.com/kean/Nuke#aggressive-disk-cache)

There is also a new feature in [Nuke 7.4](https://github.com/kean/Nuke/releases/tag/7.4) which allows you to ask Nuke to put prefetched images only in disk cache, not in memory cache. It might make sense to use this option if you're prefetching so many images.

Please also take into the account that `ImagePreheater` is not really designed for this use case, it is designed to be used in table/collection views. For example, it only makes a single attempt to prefetch an image. You can't rely on it to prefetch the images no matter what - it doesn't perform any retries.

**Comment by AdamBCo** [comment]
Hey @kean,

Thanks for the help on this, I really appreciate it.

I was able to solve the issue by switching to an aggressive cache and having the ImagePipeline download the images on a background thread,

Maybe in the future, the ImagePreheater could function as a way to start downloading images in the background.

- Adam

**Comment by kean** [comment]
> Maybe in the future, the ImagePreheater could function as a way to start downloading images in the background.

Please elaborate.

**Comment by AdamBCo** [comment]
For example, if I have an application that knows all of urls for images to show throughout the application ahead of time. I could pass the ImageHeater that array and it would automatically start fetching them in the background and saving them to disk.

When using the current version of ImagePreheater and saving them to disk, I am not seeing the images appear in the disk cache as expected.

As you mentioned, the ImagePreheater was meant for table/collection views, so I might be using it incorrectly.
