### ISSUE TITLE
[mp4] direct url for cached file

### ISSUE THREAD

**Issue by sinarionn** [kean/Nuke#212]
Hi guys, i'm trying to use your framework with mp4, and it seems like your suggested flow with additional proxy storage for mp4 files "TemporaryVideoStorage" brings a solid overhead, because we are storing data, that probably already stored. 

Is there any way to get stored file url somewhere in ImageResponse or i don't know, maybe different methods that will perform request, cache it and callback with local url instead of an image?

**Comment by kean** [comment]
Hi,

> maybe different methods that will perform request, cache it and callback with local url instead of an image?

I've investigated a few ways to approach this. Ideally I think you would use URLSessionDownloadTask to download these videos directly in some cache - maybe extend Nuke.DataCache to support it - and then play the videos directly from cache.

Before you can start playing the video you can still create a temporary copy of a file and then delete it - APFS should be able to do it with no overhead.

Current demo is there just for an example. I haven't really investigated any further.

**Comment by sinarionn** [comment]
> Ideally I think you would use `URLSessionDownloadTask` to download these videos directly in some cache - maybe extend `Nuke.DataCache` to support it - and then play the videos directly from cache.

Yes, i can try to build custom **DataCache** (i can not extend or inherit yours - it is final and **'FilenameGenerator'** is private), fill it manually with mp4 and use same instance in **ImagePipeline** for other supported image types, but in this case i'm losing Deduplication feature of this library, and wouldn't share same download queue. (

**Comment by kean** [comment]
The framework isn't really designed to support videos. But it is possible to find some clever makes to make it work with them. If you will need to validate some ideas, please share, I can help. I don't currently have capacity to design a completion solution for mp4 support in Nuke though.

> and wouldn't share same download queue

You can share the same `dataLoadingQueue` between two pipelines, it was specifically designed to support this use case. You don't need deduplication across pipelines that work with different image types.

**Comment by sinarionn** [comment]
Well, looks like the only thing i need is sync version of DataCache. In this case when your code will finish it's part - i will be able to get local cached file url and pass it to player. This is the shortest way for me. I started ruining your async DataCache to feet my requirements, but maybe you already have some? )

**Comment by gabors** [comment]
Hi @sinarionn How are you making out with this?  I'm also looking for the best way to accomplish downloading and caching smallish mp4 files. Thanks!

**Comment by sinarionn** [comment]
Hi @gabors ,  I ended up with not perfect, but at least working solution.

1. I'm using my custom DataCache, that works in sync way, and stores files immediately.  Also it uses extended filename generator,  that saves original file extension. (we need our mp4 cached files to have mp4 extension in order to play them with AVPlayer) 
2. Custom ImageDecoder, that actually do nothing, except storing downloaded data to image's `animatedImageData` property.
3. Getting callback from ImagePipeline and based on content type i'm transforming data into YYImage and playing it with YYAnimatedImageView or (if data is mp4) i'm asking my DataCache to provide me with locally cached file url and passing it to AVPlayer.

**Comment by kean** [comment]
I'm planning to improve support for video in Nuke 8 but I'm not sure how to approach this yet. @sinarionn do you have any suggestions? I think your solution already gets us 90% there.

I'm a bit hesitant to tackle this problem. Nuke is for images. And these are not images. Video don't need data decoding (AVPlayer does it), processing, or in-memory caching – but that's 90% of what Nuke does. You could still use Nuke to fetch video previews. But using it just to load the data is probably not the best solution.

**Comment by kean** [comment]
In Nuke 8.5 - releasing soon - there is now an option to get direct access to files in `DataCache`.

```swift
let key = pipeline.cacheKey(for: request, item: .originalImageData)
// Flush data for the given key to disk; doesn't affect other items in the staging area
dataCache.flush(for: key)

let url = dataCache.url(for: key)
// Read from disk
```

`DataCache` is still asynchronous be default and doesn't lose any of its performance characteristics including parallel reads, and even the ability to read and write and parallel.

`flush(for:)`, as well as `flush`, perform synchronous I/O. It can be called from any thread if you want to do that in background.

I hope this helps. If not, you can always implement a custom data cache, like @sinarionn  did.

**Comment by kean** [comment]
There are going to be more improvements when it comes to directly working with image data coming in Nuke 9.

**Comment by yunustek** [comment]
Hi @kean have any upgrade for new usage?
