### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by puji26** [kean/Nuke#213]
how to  load image extention svg ?

**Comment by kean** [comment]
There is no SVG support built it.

**Comment by ajandrade** [comment]
I also needed it @puji26 . I went for https://github.com/SVGKit/SVGKit

**Comment by smhk** [comment]
Note that iOS will natively support SVG very soon.

**Comment by kean** [comment]
I'm going to close this since there are no plans to built SVG support into Nuke and it is possible too add such support without changing the framework.

**Comment by smhk** [comment]
yup, SVG is really not relevant to Nuke !  good call

**Comment by kean** [comment]
I reopened this briefly since I'm improving vector image support in Nuke. I made some changes to make it much easier to integrate with SVG rendering libraries.

There are some new APIs introduced in [this PR](https://github.com/kean/Nuke/pull/349) that make the following possible:

```swift
 ImageDecoderRegistry.shared.register { context in
     // Replace this with whatever works for. There are no magic numbers
     // for SVG like are used for other binary formats, it's just XML.
     let isSVG = context.urlResponse?.url?.absoluteString.hasSuffix(".svg") ?? false
     return isSVG ? ImageDecoders.Empty() : nil
 }

 let url = URL(string: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Swift_logo.svg")!
 ImagePipeline.shared.loadImage(with: url) { [weak self] result in
     guard let self = self, let data = try? result.get().container.data else {
         return
     }
     // You can render image using whatever size you want, vector!
     let targetBounds = CGRect(origin: .zero, size: CGSize(width: 300, height: 300))
     let svgView = UIView(SVGData: data) { layer in
         layer.fillColor = UIColor.orange.cgColor
         layer.resizeToFit(targetBounds)
     }
     self.view.addSubview(svgView)
     svgView.bounds = targetBounds
     svgView.center = self.view.center
 }
 ```

**Comment by avargaskun** [comment]
Nuke is an awesome library! Just ran into a requirement to load SVG images from a watchOS app and was having trouble getting SVGKit/SwiftSVG (as well as other libraries) to work. 

I was able to get it to work on watchOS 9.0 using CoreSVG (private) - sharing here for posterity, in case it may help others. Written as a modification to the example above:

```swift
ImageDecoderRegistry.shared.register { context in
     let isSVG = context.urlResponse?.url?.absoluteString.hasSuffix(".svg") ?? false
     return isSVG ? ImageDecoders.Empty() : nil
}

func fetchImage(url: URL) async -> UIImage? {
    let isSVG = url.absoluteString.hasSuffix(".svg")
    if (!isSVG) {
        return try? await ImagePipeline.shared.image(for: url)
    }
    return await withCheckedContinuation({ continuation in
        ImagePipeline.shared.loadImage(with: url) { result in
            var image: UIImage? = nil
            if let data = try? result.get().container.data {
                // SVG class from: https://gist.github.com/avargaskun/78a2888ee85bd7f8765599ccb4de72fa
                if let svg = SVG(data) {
                    image = svg.image()
                }
            }
            continuation.resume(returning: image)
        }
    })
}
```

**Comment by murad1981** [comment]
> Nuke is an awesome library! Just ran into a requirement to load SVG images from a watchOS app and was having trouble getting SVGKit/SwiftSVG (as well as other libraries) to work.
> 
> I was able to get it to work on watchOS 9.0 using CoreSVG (private) - sharing here for posterity, in case it may help others. Written as a modification to the example above:
> 
> ```swift
> ImageDecoderRegistry.shared.register { context in
>      let isSVG = context.urlResponse?.url?.absoluteString.hasSuffix(".svg") ?? false
>      return isSVG ? ImageDecoders.Empty() : nil
> }
> 
> func fetchImage(url: URL) async -> UIImage? {
>     let isSVG = url.absoluteString.hasSuffix(".svg")
>     if (!isSVG) {
>         return try? await ImagePipeline.shared.image(for: url)
>     }
>     return await withCheckedContinuation({ continuation in
>         ImagePipeline.shared.loadImage(with: url) { result in
>             var image: UIImage? = nil
>             if let data = try? result.get().container.data {
>                 // SVG class from: https://gist.github.com/avargaskun/78a2888ee85bd7f8765599ccb4de72fa
>                 if let svg = SVG(data) {
>                     image = svg.image()
>                 }
>             }
>             continuation.resume(returning: image)
>         }
>     })
> }
> ```

did you upload your app to Apple Review and did they accept it ?

**Comment by avargaskun** [comment]
> did you upload your app to Apple Review and did they accept it ?

Yes, I've been able to publish multiple versions with it
