### ISSUE TITLE
How to disable caching for images?

### ISSUE THREAD

**Issue by ameyavichare** [kean/Nuke#215]
Is there a way to disable caching entirely?

What I have tried so far

private let pipeline = ImagePipeline {
        $0.dataCache = nil
        $0.imageCache = nil
    }

**Comment by kean** [comment]
Hi, by default there is a native `URLCache` used by `DataLoader`. You need to disable it as well. One way to do that is to instantiate `DataLoader` with a custom `URLSessionConfiguration`.
