### ISSUE TITLE
PHAsset / PHImageManager support

### ISSUE THREAD

**Issue by larryonoff** [kean/Nuke#216]
Hello Nuke Community,

I recently started analysis of Image Caching libraries and really like Nuke frameworks. But the only thing that it misses is PHAsset / PHImageManager. So is there any plans to PHAsset / PHImageManager together with current functionality?

**Comment by vmartinelli** [comment]
Hi. I usually create custom (and private) URL schemes that work together with `URLProtocol` subclasses. This way I can access data from various sources using URL cacheable (Nuke cacheable as well) items. Hope this can help.

**Comment by larryonoff** [comment]
@vmartinelli this's really great advice. Thank you!
