### ISSUE TITLE
7.6.0 Release 

### ISSUE THREAD

**Issue by DanielStormApps** [kean/Nuke#218]
Is there anything else we'd like to get in prior to 7.6.0 release with Swift 5 support?

**Comment by kean** [comment]
There are two changes in the release:

- Add Swift 5 support
- Merge per-platform targets into one cross-platform one (note: it's not the same as a single framework supporting multiple platforms, it still produces the same frameworks as previous single platform targets)

Both already done. I already tested new cross-platform targets both using Carthage and CocoaPods. The solution seems to work well. I would appreciate if you could integrate the current iteration of `master` into your app and see if it works. 

The only thing left to do is to update CI config to support Swift 5 which I'm going to do some time this week.

**Comment by kean** [comment]
I will also need to update all of the "plugins" 😄

**Comment by DanielStormApps** [comment]
Sounds good. If there's anything I can do to help please let me know 😃

**Comment by kean** [comment]
The release is almost ready, will do the final testing tomorrow and push.

Some additional changes:

- Drop iOS 9, tvOS 9, watchOS 2.0, macOS 10.10 and macOS 10.11 support
- Drop Swift 4.0 and Swift 4.1 support
- Drop Xcode 9 support
- Replace deprecated OSAtomic functions with unfair_lock, there is no performance regression
