### ISSUE TITLE
Release CocoaPods update for Swift 5

### ISSUE THREAD

**Issue by bpisano** [kean/Nuke#223]
The code seems to be ready for Swift 5, but after a `pod update` in my project, I still have those Swift 4.2 warnings. Can you please release a CocoaPods version with the Swift 5 ready code please ?

**Comment by DanielStormApps** [comment]
@bpisano v7.6 added support for Swift 5. You may need to run `pod update`.

https://github.com/kean/Nuke/releases

**Comment by bpisano** [comment]
My bad, the project I was working on require iOS 9.3 as minimum version. Nuke removed support for iOS 9. That's why I didn't saw the update even when running a `pod update`.
