### ISSUE TITLE
Memory Leak on Nuke.loadImage()

### ISSUE THREAD

**Issue by denniskeithgaso** [kean/Nuke#234]
First of all, I would like to thank you for this amazing library. It works really well for me.

The method 'Nuke.loadImage(with:, options:, into:, progress:, completion:)' causes memory leaks when used on `UITableViewCell` or `UICollectionViewCell`, specifically in the `tableView(_:cellForRowAt:)`. The `UIImageView` in my `UITableViewCell` is already declared as a `weak` reference but doesn't seem to be released when passed in the `Nuke.loadImage()` method.

Even in the demo app, this leaks occurs.
![image](https://user-images.githubusercontent.com/15845598/57435925-36eec780-7271-11e9-980c-5be662146cc2.png)

Best regards!

**Comment by michaelnisi** [comment]
Which version are you using?

**Comment by denniskeithgaso** [comment]
I'm using version 7.6.3

**Comment by michaelnisi** [comment]
Not sure, but I can say that Leak Checks cannot be trusted with these quick profiling sessions, unless there’s an obvious flood. I recommend to keep an eye on your app’s Memory Use and if that doesn’t blow up, it’s probably fine. 

Leak Checks is the last thing I look at. 
1) Code Review
2) Memory Use
3) Memory Graph
4) Leak Checks

What’s your take?

**Comment by kean** [comment]
I've ran some quick diagnostics – including generation analysis – on Nuke 7.6.3 on the prefetching demo from the report. There is nothing pointing at Nuke, just a bunch of UIKit types which get reported even if I remove all Nuke calls from the demo.

I'm going to close the issue. If you find some evidence that Nuke types are leaking, please feel free to reopen.
