### ISSUE TITLE
A few crashes on load images when use preheater 

### ISSUE THREAD

**Issue by keynsianets** [kean/Nuke#238]
We have a few crashes, related to Nuke in our app. It's only crash for 0.5% of user. For set priority we use 
  ```
var request = ImageRequest(url: url)
request.priority = .veryHigh
```
and since we do it, count of crashes reduced. But it looks like still some problem with concurrency in code. I'm attaching screenshots from fabric.
![Снимок экрана 2019-05-14 в 10 50 07](https://user-images.githubusercontent.com/46818370/57681159-d7f5cd80-7637-11e9-8c63-2426bebcf192.png)
![Снимок экрана 2019-05-14 в 10 51 16](https://user-images.githubusercontent.com/46818370/57681160-d88e6400-7637-11e9-8b40-3e77d9013c8f.png)

**Comment by kean** [comment]
Thanks for reporting, @keynsianets!

Unfortunately, there might still be some concurrency issue in the ImagePipeline in Nuke 7. Fortunately, I already addressed all of the technical debt in [#235 ImagePipeline 2](https://github.com/kean/Nuke/pull/235) for Nuke 8 and made the logic in general and the concurrency much simpler so I could be sure that it works correctly and reliable in every possible scenario.

To help me investigate the crash, could you please provide a bit more context about how you set up the pipeline and how you use.

**Comment by keynsianets** [comment]
Thank you for great job. I guess, it's all context, that related to load images in app:
```
// Configure Nuke cache
        ImagePipeline.shared.configuration.dataLoadingQueue.maxConcurrentOperationCount = 30
        ImageCache.shared.costLimit = 1024 * 1024 * 600 
        ImageCache.shared.countLimit = 600
        ImageCache.shared.ttl = 60*60*24*30
        WebPImageDecoder.enable()
```
In most cases images load in table or collectionViews . 
Load image:
```
let options = ImageLoadingOptions(
                    placeholder: UIImage(),
                    failureImage: UIImage(),
                    contentModes: .init(
                        success: .scaleAspectFit,
                        failure: .center,
                        placeholder: .center
                    )
                )
                var request = ImageRequest(url: url)
                request.priority = .veryHigh
                Nuke.loadImage(with: request, options: options, into: self, progress: { _, completed, total in }, completion: { response, error in
                    self.loadingIndicator.stopAnimating()
                    let image = response?.image
                    callback?(image)
                })
```
And, for some of tableViews, we use prefetch. 
```
func tableView(_ tableView: UITableView, prefetchRowsAt indexPaths: [IndexPath]) {
        var urls: [String] = []
            for indexPath in indexPaths {
                    urls.append(imageUrl)
                }
            }
            LoadingImagesList.shared.putNewTasks(stringUrls: urls)
        }
    }
```

```
class LoadingImagesList {
    
    let preheater = ImagePreheater()
    
    static let shared = LoadingImagesList()

    func putNewTasks(stringUrls: [String]) {
        preheater.startPreheating(with: urls)
    }
```

**Comment by kean** [comment]
> ImagePipeline.shared.configuration.dataLoadingQueue.maxConcurrentOperationCount = 30

That seems way too much. It might be simply crashes on high memory usage.
