### ISSUE TITLE
Get local cached/disk image path, to upload to the server.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [kean/Nuke#249]
How can I get locally saved/cached image path?

I need to upload image to the server.

**Comment by kean** [comment]
Hi, it depends on which type of disk cache you are using. There is no direct access to files managed by the native `URLCache`. If you are using `Nuke.DataCache`, it has a public method to generate filenames.

In both of these cases, I wouldn't rely on images being stored in any of these caches at any point in time.
