### ISSUE TITLE
Ambiguous reference to member 'loadImage(with:progress:completion:)'

### ISSUE THREAD

**Issue by makinggainz** [kean/Nuke#256]
[I opened this question regarding this question.](https://stackoverflow.com/questions/56410129/ambiguous-reference-to-member-loadimagewithprogresscompletion-when-using)

This issue is that when I add the following lines:

    let task = ImagePipeline.shared.loadImage(//error here
                    with: selectedPost?.interimMedia[numberMedia].imageURLString,
                    progress: { response, _, _ in
                        mediaImage.image = response?.image
                },
                    completion: { response, _ in
                        mediaImage.image = response?.image
                }
                )

I get:

> Ambiguous reference to member 'loadImage(with:progress:completion:)'

**How can I fix this?**

**Comment by kean** [comment]
Hi, this method expects either `URL` or `URLRequest` as the first parameter. For the naming, It seems that you are passing a raw `String` and also an optional one. Please make sure you are passing non-optional `URL`.

**Comment by Jarred-Sumner** [comment]
I'm experiencing this issue as well.

Here's sample code:
```swift
let processors = [
      ImageProcessor.Resize(size: bounds.size, contentMode:  .aspectFit)
    ]

    let imageRequest = ImageRequest.init(url: url, processors: processors, priority: .normal, options: ImageRequestOptions())
    self.imageTask = Nuke.loadImage(with: imageRequest, options: .shared,  into: self,
    progress: { response, _, _ in
      SwiftyBeaver.info("Progress! \(response)")
    }, completion: { result, _ in
      SwiftyBeaver.info("Result! \(result)")
    })
```

> Ambiguous reference to member 'loadImage(with:options:into:progress:completion:)'
![image](https://user-images.githubusercontent.com/709451/66692121-33140680-ec50-11e9-87ee-921b048606f7.png)

**Comment by kean** [comment]
The signature is incorrect, the completion only have one argument, `result`.
