### ISSUE TITLE
init(memoryCapacity:diskCapacity:diskPath:)' is unavailable in UIKit for Mac

### ISSUE THREAD

**Issue by appfrilans** [kean/Nuke#260]
Using latest Xcode 11.0 beta building for mac I get the following build error:

init(memoryCapacity:diskCapacity:diskPath:)' is unavailable in UIKit for Mac

Would be awesome if that could be fixed! I am using Nuke 7.6.3

**Comment by kean** [comment]
I have Xcode 11 beta but not macOS Catalina yet so I can't use Catalyst. If someone is willing to takes this, PRs are welcome.

**Comment by appfrilans** [comment]
Apparently its not implemented yet, so not sure If we just wait for a fix by Apple or make a workaround.

Apple beta release notes says: "The new required URLCache initializer init(memoryCapacity:diskCapacity:diskPath:) is currently unimplemented. (50739637)" from https://developer.apple.com/documentation/macos_release_notes/macos_10_15_beta_release_notes

**Comment by bryan1anderson** [comment]
This is still not implemented I guess. A workaround would be awesome

**Comment by bryan1anderson** [comment]
@kean @appfrilans What workarounds would be available for this? Has anyone branched to make this work?

**Comment by kean** [comment]
Shipped in [Nuke 8.2.0](https://github.com/kean/Nuke/releases/tag/8.2.0), thanks @ JonathanDowning!
