### ISSUE TITLE
Improve Documentation Regarding Gifu and Nuke

### ISSUE THREAD

**Issue by gmogames** [kean/Nuke#268]
Hi There,

Sorry if this is not the best place, but I just wanted to try and get clarification on the use of Gifu with Nuke.

Nuke's documentation states:
`There is no built-in way to render those images, but there are two extensions available: FLAnimatedImage and Gifu which are both fast and efficient.`

But Gifu's documentation states:
`Deprecated: Gifu is still supported, but the plugin itself is no longer necessary - you can configure Nuke to work with Gifu with 8 lines of code.`

After reading these 2, I was wondering if adding Gifu as a dependency is still necessary or not.

Of course I will try it out and test it, but it would be awesome to have the documentation read more clearly to avoid confusion.

Cheers!

**Comment by gmogames** [comment]
I just noticed that links to Gifu from Nuke's README actually take users to the plugin extension that apparently was required by Nuke in the past and not the the Gifu framework Github page. 
So you actually still need to add Gifu as a dependency but no need to add an extra plugin/extension to make them both work together.

So my suggestion would be to improve the documentation regarding this connection between frameworks. But otherwise everything looks great. Thanks!

**Comment by kean** [comment]
Hi, @gmogames. Yes, your conclusion is exactly right. You don't need to install any of the plugins anymore, but you still need either one of these frameworks to render GIFs.

There is definitely room for improvement in the documentation. I think the links to the "plugins" should be removed to avoid confusion, and it should documented how to integrate with these frameworks in the main Nuke repo.

**Comment by kean** [comment]
I rewrote the related documentation section.


<hr/>

### Animated Images

To enable animated image support, set `ImagePipeline.Configuration.isAnimatedImageDataEnabled` to `true`. If enabled, Nuke will attach `animatedImageData` to the downloaded animated images. You going to need data to render the images.

There is no built-in way to render animated images, but there are multiple options available.

**Option 1**. Install [FLAnimatedImage Plugin](https://github.com/kean/Nuke-FLAnimatedImage-Plugin) and follow the instructions.

**Option 2**. Install [Gifu](https://github.com/kaishin/Gifu) directly. To configure Gifu to work with Nuke, all you need to do is add these lines in your project:

```swift
ImagePipeline.Configuration.isAnimatedImageDataEnabled = true

extension Gifu.GIFImageView {
    public override func nuke_display(image: Image?) {
        prepareForReuse()
        if let data = image?.animatedImageData {
            animate(withGIFData: data)
        } else {
            self.image = image
        }
    }
}
```

You can now start using Gifu.GIFImageView:

```swift
let view = Gifu.GIFImageView()
Nuke.loadImage(with: URL(string: "http://.../cat.gif")!, into: view)
```

<hr/>

I hope the updated version is clearer if the original. Please let me know if there any way to improve it.
