### ISSUE TITLE
Allow setting processors on the pipeline

### ISSUE THREAD

**Issue by vendruscolo** [kean/Nuke#269]
I'm really enjoying the new image processors feature of Nuke 8. I was thinking about having the  processors property also on the pipeline itself, allowing to set a "global" list of processors on the pipeline, so that every request would use that.

One advantage of this approach is that it would allow to create a dedicated pipeline for some tasks, and allow for easier reuse. Scenario:
* A pipeline to load images (e.g. to be used in a gallery) that performs no processing and has its caching rules (both in-memory and on-disk);
* A second pipeline optimized to load user avatars (e.g. to be used in a table view) that performs resizing and applies corner radii to the image. This pipeline might have different caching rules (e.g. in-memory only, as avatars change often).

As of today, the processors has to be set on a per-request basis. If there're two places that show avatars we have to remember the kind of processing we want (or we have to abstract that away in a factory). Having the processors property also on the pipeline itself makes it easier, because we would just have to pass around the pipeline (as we already do).

Of course, if processors are defined both on the pipeline and the image request, the latter should take precedence.

What's your opinion on this? Thank you!

**Comment by kean** [comment]
Thanks, I'm glad that you liked it!

This sounds really useful. I think I already have this feature in backlog.

> Of course, if processors are defined both on the pipeline and the image request, the latter should take precedence.

Yes, sounds reasonable.

> What's your opinion on this? 

I think it would be a valuable addition. This is not the first time this feature was suggested.

**Comment by vendruscolo** [comment]
Awesome! Do you need any help from me?
For which release do you plan to work the issue? 8.0? 8.1? (Just asking in order to plan things, not to rush you)

**Comment by kean** [comment]
> Do you need any help from me?

I was thinking maybe you could implement it 😃

> For which release do you plan to work the issue? 8.0? 8.1?

It will be 8.1. I'm planning to release Nuke 8.0-rc.1 as Nuke 8.0 without any modifications, will probably do that this weekend.

**Comment by vendruscolo** [comment]
Okay, great. Since it’ll end up in 8.1 there’s some time to do it. I’ll do my best to tackle it this week or the next one.

**Comment by vendruscolo** [comment]
Hi Alex, I finally have some time to get back on this issue. I've began to study Nuke's source code to plan the implementation of this feature.
A part from the obvious "add an `[ImageProcessing]` property to `ImagePipeline`", I think the best way to handle this is to copy such array to the `ImageRequest` parameter of the
```
func loadImage(with request: ImageRequest,
                   isMainThreadConfined: Bool,
                   observer: @escaping (ImageTask, Task<ImageResponse, Error>.Event) -> Void) → ImageTask
```
function, which appears to be the final method the pipeline calls before ultimately enqueuing a task.
In (not-so-much) pseudo code, it'll be something like:

```
if request.processors.isEmpty {
  request.processors = self.processors
}
```

Do you see something that I might be missing? Anything else to look out?
I'll obviously add the necessary tests, but before I start to blindly implement something I'd like to hear your opinions (since you know Nuke way better than me!)

**Comment by kean** [comment]
> ImageRequest parameter of the loadImage(with: isMainThreadConfined: observer:) -> ImageTask function

Yes, this seems like an optimal place to put it.

> Do you see something that I might be missing? Anything else to look out?

There is also this method that works with the requests:

```swift
public func cachedResponse(for request: ImageRequest) -> ImageResponse? {
```

You should also set the default processor in this method, otherwise cache isn't going to work. The user can also currently use `ImageCache` directly without going through `cachedResponse` method. And a single cache instance can potentially be shared between multiple pipelines. I'm not sure what is the best way to handle these scenarios.

**Comment by vendruscolo** [comment]
I'm sorry it took so long, but the last months have been stuffed with things for me. I'm still committed to complete this.

I'm setting default processors in that method too, as you suggested. I also need to add some unit tests, and I think it'll be fairly easy.

Regarding your last doubt: if clients are using the cache directly, bypassing the pipeline, I think it's up to them to manage the processors stuff. After all, if you're using the pipeline facilities, you either use them in full or you don't. It would mean that users create a request, load it using the pipeline and then try to load it again bypassing the pipeline. The solution, in this scenario is to load it the second time through the pipeline.
The best way to handle this scenario is to treat the update as major update (it has a breaking change) and warn users in the release notes.
