### ISSUE TITLE
[Question]How do I load the UIButton.setImage()？

### ISSUE THREAD

**Issue by son** [kean/Nuke#271]
I understand if it is imageView, what should I do with button?

**Comment by michaelnisi** [comment]
You would use the completion handler [ImagePipeline](https://github.com/kean/Nuke#image-pipeline) `loadImage(with:progress:completion:)`

**Comment by son** [comment]
thank you!

**Comment by kean** [comment]
As an alternative, you can add conformance to the `ImageDisplaying` (`Nuke_ImageDisplaying` in Nuke 8) protocol to `UIButton`. When you do that, you can start loading `Nuke.loadImage(into:with:)` method with `UIButton`.

**Comment by AndreiBoariu** [comment]
Here is an example of how to use it:
```
extension UIButton: Nuke_ImageDisplaying {
	public func nuke_display(image: Nuke.Image?) {
		self.setImage(image, for: .normal)
	}
}
```
I wrote it because I had an internal class model called `Image` and Xcode showed crazy errors. And `Nuke.Image?` solved the problem.

**Comment by kean** [comment]
I'm thinking prefixing and deprecating `Image` as well in the upcoming release. Otherwise there are going to be conflicts with `SwiftUI.Image`.

**Comment by sajjadsarkoobi** [comment]
> I'm thinking prefixing and deprecating `Image` as well in the upcoming release. Otherwise there are going to be conflicts with `SwiftUI.Image`.

Hi, so what will be the replacement for `Image` ? I want to use nuke to load image in button. 
it will be so good if there is a way that Nuke can give us `UIImage` without forcing us to insert it into the `UIImageView`  
Thanks

**Comment by sajjadsarkoobi** [comment]
ok, so now we can use ImagePipline for that:

>         ImagePipeline.shared.loadImage(with: url) { result in
>            switch result {
 >           case .success(let data):
 >              DispatchQueue.main.async {
 >                    self.sampleButton.setImage(data.image, for: .normal)
 >               }
 >               break
 >          case .failure:
 >               break
 >           }
 >       }
