### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by andriansergheev** [kean/Nuke#272]
Looks like the docs are either old or not right,
Can't find this in the source code anymore.
Thanks for the lib. It is awesome!
<img width="636" alt="image" src="https://user-images.githubusercontent.com/23578783/60797432-8701e180-a16f-11e9-8f72-bb21f115c88c.png">

**Comment by kean** [comment]
Hi, @andriansergheev. `ImageProcessor.Resize` is available in Nuke 8-rc.1. The documentation in master is for Nuke 8. Nuke 8 wasn't released yet. I was going to release it during the past weekend but didn't have enough time.

The latest documentation for Nuke 7.6.3 is available [here](https://github.com/kean/Nuke/tree/7.6.3).

**Comment by andriansergheev** [comment]
understood, thx.
