### ISSUE TITLE
[Question] Does Nuke store the downloaded images locally (on the user device) for offline use?

### ISSUE THREAD

**Issue by CraftizLtd** [kean/Nuke#273]
First of all, thank you for this great (!) library. I'm learning a lot both on the code architecture and especially how to approach async tasks.

One question that I'm not sure about. When using Nuke within UICollectionView with preheat enabled, does Nuke cache and store the images on the user device as well? I saw at the docs there's potentially two layers of cache:
1. RAM cache
2. 'HTTP Disk Cache' or 'Aggressive LRU Disk Cache'. 
As far as I understand the 'HTTP Disk Cache' counts on the URL-caching to return the request (with the cached URL image) without the need to store it locally.
I prefer that the downloaded images will be saved locally and rely on the user device (Document Directory etc') as an offline store. Does this what 'Aggressive LRU Disk Cache' means? Also, if possible, I'd like to save only one copy of the image (the original one).

Again, thank you so much for the great lib!

**Comment by kean** [comment]
I would recommend enabling custom disk cache and disabling the native URL cache:

```swift
ImagePipeline.shared = ImagePipeline {
    $0.dataCache = try! DataCache(name: "com.myapp.datacache")
         $0.dataLoader = DataLoader(configuration: {
                // Disable disk caching built into URLSession
                let conf = DataLoader.defaultConfiguration
                conf.urlCache = nil
                return conf
    }())
}
```

See the demo for an example: "Disk Cache: Aggressive disk caching enabled".

**Comment by CraftizLtd** [comment]
Awesome, thank you so much! :)
