### ISSUE TITLE
Unable to install Nuke 8 using cocoapods

### ISSUE THREAD

**Issue by CraftizLtd** [kean/Nuke#274]
Hey there,
first of all, just wanted to say thank you for the awesome lib.

I'm not sure why or if it's intended, but for some reason, I can't install Nuke 8 on my project.
I was using the demo project to do some testings, especially related to configurations such as `isDataCachingForOriginalImageDataEnabled` and `isDataCachingForProcessedImagesEnabled`.

When I create a new Xcode project and I ran `pod init` with `pod 'Nuke'` & `pod 'DFCache'` and imported them, `isDataCachingForOriginalImageDataEnabled` and `isDataCachingForProcessedImagesEnabled` didn't exist. For some reason on the Demo project, I'm getting a different (more updated) version of nuke, than on my new Xcode project.
Can't understand what I'm missing here, would love some help! 

Thanks! :)

**Comment by kean** [comment]
Nuke 8 is not yet available via CocoaPods. The latest pre-releaser version [Nuke 8-rc.1](https://github.com/kean/Nuke/releases/tag/8.0-rc.1) is available only via Carthage and Swift Package Manager. I'm releasing Nuke 8 soon.

**Comment by CraftizLtd** [comment]
Hey @kean , thank you for the fast response. Cool, good to know! I'll work with SPM for now :)
