### ISSUE TITLE
PDF assets not displayed

### ISSUE THREAD

**Issue by SocialKitLtd** [kean/Nuke#275]
Hey there,
Again, thank you for this awesome library, been working with it day and night the past couple of days.

We are trying to understand if it's possible to use Nuke to display PDF assets. Currently, our app content is shipped with the app bundle, stored in the Asset Catalog. We found that PDF is a very useful image format to store simple images, as it's scalable (vector) and weights nothing. Nowadays we are working on a big update, which will make the entire content dynamic from a server, that's where Nuke plays a part.

Trying to use Nuke with PDF failed, this is what we tried to do:

        let imageView = UIImageView()
        imageView.frame = view.bounds
        imageView.backgroundColor = .red
        view.addSubview(imageView)
        loadImage(with: URL(string: "https://uniq-content-test.s3.amazonaws.com/stam/Call+service.pdf")!, into: imageView)`

But the image doesn't show up. For other image formats like JPG, PNG it works perfectly.
Is it intended? If yes, Is there any possible workaround to use Vector Assets with Nuke?

Thank you again!
Roi

**Comment by kean** [comment]
Out of the box, Nuke only supports the image formats supported by `UIImage`. It doesn't support PDF. In order to display PDFs you'll need to use some framework which does. See `ImageDecoding` and `ImageDecoderRegistry` for more information about how to add support for custom image formats. See [Nuke WebP Plugin](https://github.com/ryokosuge/Nuke-WebP-Plugin) for an example.

**Comment by CraftizLtd** [comment]
Cool, I'll try to create a PDF decoder, will update if I succeed and we can even publish it as a side plugin!

**Comment by kean** [comment]
@CraftizLtd that's awesome. If you do, I will definitely add it to README.

**Comment by kean** [comment]
Hey, @SocialKitLtd, did you get a chance to implement a PDF decoder?

**Comment by kean** [comment]
I'm going to close this one, there are no plans to bake PDF support into Nuke. If someone were to create a "plugin/extension" with a respective decoder, please let me know, I would gladly add it to the list.
