### ISSUE TITLE
Load image straight to cache and collect from cache

### ISSUE THREAD

**Issue by Khondwani** [kean/Nuke#276]
Hello i love your library for it makes my life simpler thank you for it. I was wondering i am trying to get my images to just load from cache/variable instead of me first asking for a request then loading it into my imageview directly instead of that i want to load the image and save it into cache so that when i decide to load the image i load it from my cache or from a variable i saved it in. Please help

**Comment by kean** [comment]
Hi, you can use [`ImagePreheater` to prefetch images](https://github.com/kean/Nuke#image-preheating) in memory and/or disk cache. To load an image without a target view, use [`ImagePipeline` directly](https://github.com/kean/Nuke#image-pipeline)
