### ISSUE TITLE
Fetching JPEG images - processing failed. 

### ISSUE THREAD

**Issue by dziwiedz** [kean/Nuke#278]
Hello! 

I have problem with fetching JPEG images using `Nuke.loadImage method`. I've got error that image processing failed. Issue exists on 8.0.0 version, on the 7.6.3 everything works. 
We are using thumbor for resizing images. 
URL example:
https://d1z1smzgvvydhp.cloudfront.net/SDdUpg9Jku425KRhXlu51iFrpwU=/fit-in/375x375/filters:format(jpeg):quality(60)/https://connect-kc.appunite.com/api/media/5d30603cc9ff970001fbfb82

I would be grateful if you could help :)

**Comment by kean** [comment]
Hi, could you please share the pipeline configuration and the processors that you are using? The default configuration doesn't perform any additional processing.

**Comment by dziwiedz** [comment]
I'm using default configuration for shared pipeline. I've discovered what is wrong in my code. I was using `ImageRequest(url:targetSize:contentMode:)` to create image request, which I didn't know that is deprecated. It didn't shown me an error in my project, but I saw it when I was preparing example project. 

Thanks anyway :)
