### ISSUE TITLE
Image Cache Placeholder?

### ISSUE THREAD

**Issue by ZAPHIT** [kean/Nuke#28]
Hi, can you help me put some placeholder image before the image is downloaded?

**Comment by kean** [comment]
Hi

##### Using Nuke.ImageView
```swift
let imageView: Nuke.ImageView = <#imageView#>
imageView.prepareForReuse()
imageView.image = <#placeholder#>
imageView.setImageWithURL(<#imageURL#>) 
// or imageView.setImageWithRequest(<#request#>)
```

If you need to add some transition animations you can subclass Nuke.ImageView and override `public func imageTaskDidFinishWithResponse(response: ImageResponse)` method.

##### Create your own UI classes

Nuke makes it extremely easy. See Nuke.ImageView for an example.

**Comment by kean** [comment]
In version v1.0 (releasing soon) you would be able to set a placeholder using a built-in extensions:

```swift
let imageView = UIImageView()
imageView.nk_setImageWithRequest(ImageRequest(URL: <#imageURL#>), options: ImageViewLoadingOptions(placeholder: <#placeholder#>))
```

**Comment by ZAPHIT** [comment]
Hi can i add more.. how can i add a success failure closure on this??

**Comment by ZAPHIT** [comment]
i have success and failure closure now..  thanks..
