### ISSUE TITLE
ImagePipeline.shared.loadImage Error: Cannot convert value of type '(_, _) -> ()' to expected argument type

### ISSUE THREAD

**Issue by the-scott-davis** [kean/Nuke#286]
Using the following code I am getting an error, this code comes directly from the documentation [found here](https://kean.github.io/Nuke/reference/7.0-rc1/index.html#image-pipeline):

`let task = ImagePipeline.shared.loadImage(

    with: url,

    progress: { _, completed, total in

        print("progress updated")

    },

    completion: { response, error in

        print("task completed")

    }
)`

The error is on the completion line:

> Cannot convert value of type '(_, _) -> ()' to expected argument type 'ImageTask.Completion?' (aka 'Optional<(Result<ImageResponse, ImagePipeline.Error>) -> ()>')

**Comment by damianpiwowarski** [comment]
Learn about [Result](https://developer.apple.com/documentation/swift/result) value type in Swift.
Documentation isn't fully updated just yet. 

Instead of your code, you should use:

`
completion: { response in }
`

With switch block or by using response.get function with throwing closure.

**Comment by kean** [comment]
@the-scott-davis please use [Nuke 8 API Reference](https://kean.github.io/Nuke/reference/8.0/index.html). Please let me know if you see any outdated links in 8.0, I will update them.
