### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by michael-mckenna** [kean/Nuke#287]
Hi,
  [SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager. I didn't see it in your installation guide so I'm submitting this feature request.
  
  Here some articles about SwiftPM:
  
  * [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
  * [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
  * [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
  * [Swift.org: Package Manager](https://goo.gl/E01ufX)
  
  When your component is compatible with SwiftPM add on your `README.md` [![SwiftPM Compatible](https://camo.githubusercontent.com/52e3db230991dda10458295d71c859c34be466b6/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5377696674504d2d436f6d70617469626c652d627269676874677265656e2e737667)](https://goo.gl/E01ufX) badge on top and add a section for the installation with SwiftPM.

**Comment by kean** [comment]
Thanks, that's a great suggestion. The primary framework already supports but it's missing proper documentation (aka Installation Guide) and the extensions, e.g. Nuke Alamofire Plugin, don't support SwiftPM yet. It would be nice to add complete SwiftPM support before Xcode 11 ships.

**Comment by kean** [comment]
Updated the documentation, can be closed now.
