### ISSUE TITLE
Transition (crossfade) doesn't work if imageView.image is already set

### ISSUE THREAD

**Issue by rosem** [kean/Nuke#289]
I'm working on an "Edit Profile" view controller. I'm getting the user's photo url and displaying the remote image with nuke.

The user can then use an image picker to selected a new image. If they select a new image I update the image view's image directly.

If the user chooses to "Remove" the image, I revert the image view back to the nuke version of loading the URL. 

However, when the image switches back to the original it doesn't crossfade.

**Comment by kean** [comment]
Hi, @rosem. Did you manage to figure it out? I'm not sure I quite follow the question. I would suggest looking into ImageViewExtensions.swift and they way it performs animations, it should make it clear how it works in case it's not clear from the documentation (PRs with documentation improvements are welcome).

**Comment by rosem** [comment]
I have not had a chance to look into it yet. I believe the issue is if I modify .image directly on UIImageView and then use Nuke to load a remote asset into the same UIImageView it ignores the transitions that were set on the request.
