### ISSUE TITLE
Please Update Documentation..

### ISSUE THREAD

**Issue by ZAPHIT** [kean/Nuke#29]
use_frameworks!
platform :ios, "8.0"

pod "Nuke"

pod "Nuke-Alamofire-Plugin"
pud????? "Nuke-AnimatedImage-Plugin"

Also can you have clear instructions on installing it, i have errors, unable to find framework..

i just followed the instruction.. i just tried your framework on your sample project, by doing pod try "Nuke"..

thanks..!

**Comment by ZAPHIT** [comment]
ld: framework not found Alamofire
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ZAPHIT** [comment]
ld: framework not found Nuke
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kean** [comment]
> pud????? "Nuke-AnimatedImage-Plugin"

ok ;)

> i just followed the instruction.. i just tried your framework on your sample project, by doing pod try "Nuke"..

`pod try` does seem to work on my machine. It should automatically download a repo to a temp folder, resolve dependencies and open a created workspace.

**Comment by ZAPHIT** [comment]
Its working, using your own project and the sample Nuke, it create sample workspace,

but i have my app, and i am linking the pod file on it... seems have problems..

**Comment by kean** [comment]
I would recommend to:
- Update CocoaPods (`sudo gem install cocoapods`)
- Clean CocoaPods caches (`pod cache clean --all`)

Then try again. If it still doesn't work then please be more specific (show your Podfile, console output after `pod install`, full error message).

**Comment by ZAPHIT** [comment]
Pod Installation is complete no errors...  I tried creating another blank project and intergrate your framework.. same result..


ld: framework not found Nuke
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Or am i missing something, need to adjust xcode setting linker?

**Comment by kean** [comment]
I can't reproduce this problem. Have you tried installing other frameworks? Does that problem occur only with Nuke?

**Comment by ZAPHIT** [comment]
Yes its only in Nuke... can you try to create just a plain Swift.. not using cocoa pods... then integrate the project with Nuke using cocoa pods... it does not seem compatible...

**Comment by ZAPHIT** [comment]
I am using Haneke and other frameworks before.. I think the only option is to recreate my app to the one cocoa pods have produce.. using    try "Nuke" , but its not just easy, because it will require more time..

**Comment by ZAPHIT** [comment]
This is my podfile..

use_frameworks!
platform :ios, "9.0"
pod "Nuke"


target 'sampleProject' do

end

target 'sampleProjectTests' do

end

target 'sampleProjectUITests' do

end

**Comment by ZAPHIT** [comment]
I think i found it.. its fixed now...

**Comment by ZAPHIT** [comment]
The problem was opening the app on xcode.. just need to reopen the project using xworkspace

**Comment by kean** [comment]
Ok ;)
