### ISSUE TITLE
Message from debugger: Terminated due to signal 9

### ISSUE THREAD

**Issue by alvincrisuy** [kean/Nuke#290]
Hi I'm encountering this issue not sure what is happening when calling
```
    func makeRequest(with url: URL) -> ImageRequest {
        return ImageRequest(url: url)
    }
```

**Comment by kean** [comment]
Hi, could you please provide a little bit more context, maybe a crash log?

**Comment by alvincrisuy** [comment]
Hi! I'm using it on a feed page where it loads a lot of image like Instagram.

dyld: lazy symbol binding failed: Symbol not found: _$s4Nuke12ImageRequestV3urlAC10Foundation3URLV_tcfC
  Referenced from: /Users/user/Library/Developer/CoreSimulator/Devices/C8DFBEC1-19DD-43CA-A912-82459B71CE41/data/Containers/Bundle/Application/F746D003-A14B-411E-BAAA-BD2FA0086FD9/App.app/App
  Expected in: /Users/crisuy/Library/Developer/CoreSimulator/Devices/C8DFBEC1-19DD-43CA-A912-82459B71CE41/data/Containers/Bundle/Application/F746D003-A14B-411E-BAAA-BD2FA0086FD9/App.app/Frameworks/Nuke.framework/Nuke

dyld: Symbol not found: _$s4Nuke12ImageRequestV3urlAC10Foundation3URLV_tcfC
  Referenced from: /Users/crisuy/Library/Developer/CoreSimulator/Devices/C8DFBEC1-19DD-43CA-A912-82459B71CE41/data/Containers/Bundle/Application/F746D003-A14B-411E-BAAA-BD2FA0086FD9/App.app/App
  Expected in: /Users/crisuy/Library/Developer/CoreSimulator/Devices/C8DFBEC1-19DD-43CA-A912-82459B71CE41/data/Containers/Bundle/Application/F746D003-A14B-411E-BAAA-BD2FA0086FD9/App.app/Frameworks/Nuke.framework/Nuke

**Comment by kean** [comment]
How are you installing Nuke? It seems that the framework is not getting embedded in the app. It should be embedded using an special phase (see Build Phases).

**Comment by alvincrisuy** [comment]
I'm installing it using pods Nuke 8.0.1

**Comment by kean** [comment]
Sorry, it doesn't seem I'm going to be able to help you debug this issue. Please make sure, you are installing the dependencies correctly.
