### ISSUE TITLE
iOS simply totally MISSING?

### ISSUE THREAD

**Issue by smhk** [kean/Nuke#292]
![screenshot 1](https://user-images.githubusercontent.com/3938526/62836110-886a7200-bc25-11e9-9472-fcd805a23a40.png)

This fine Sunday morning I wanted to experiment with the wonderful Nuke.

The iOS library is completely MISSING

What to do?

If anyone's reading and can give me the quick fix, I'd appreciate for sure!

![screenshot](https://user-images.githubusercontent.com/3938526/62836078-40e3e600-bc25-11e9-98f5-6d9df60f099e.png)

**Comment by kean** [comment]
Hi, please consider using `Carthage` or `CocoaPods`. Manual installation guide seems to be outdated, previously Nuke had 4 targets – one per platform, and now there is only one target which supports all platforms.

**Comment by smhk** [comment]
Hi @kean , thanks for the super-quick reply - thank you.

By the way - where is the "Donate" button?  We always donate to libraries

(1) As you say it looks like it **works perfectly** in iOS with the one target (which is labelled "macOS") - thanks

(2) Do you happen to know .. Just as a curiosity, how the heck do you set that string (in gray in my image above) which says 'macOS'.  I just want to change it since I'm OCD (and it will confuse other team members!)

{Is it the "product hame" .. what is it?  i've never really seen that before!  thanks }

Thanks again!!!

**Comment by smhk** [comment]
Just FYI one group's opinion on packaging.  We should all be using SwiftPM ASAP hopefully.  Currently IMO the "correct" or "recommended" way to add embedded libraries to iOS projects is just .. add embedded libraries.  Carthage is OK .. but why?  (Nobody should touch "cocoapods", ever.  It will be and should be gone ASAP :O  )

thanks again!

**Comment by kean** [comment]
> where is the "Donate" button

Hah, I'm too lazy to set it up manually. I'm in GitHub Sponsors waiting list.

> which says 'macOS'

Weird, will add this to backlog. As well as updating Installation Guide.

> We should all be using SwiftPM

SwiftPM is also supported, but currently only for the main repo.

**Comment by smhk** [comment]
THANKS sorry to have bothered you - great stuff!

can always just have a trival "my paypal account is" for donates
