### ISSUE TITLE
Basic question: check if image at URL already exists in cache

### ISSUE THREAD

**Issue by smhk** [kean/Nuke#293]
Hate to ask a basic question, but have searched extensively

    let u = URL(string: "https:server.com/cat.jpg")

How to check if u has already been downloaded to the cache?  (TBC it was already completely downloaded, say, yesterday, and it's still there at this moment.)

How to check if u already exists in the cache, at this time?

Thanks, my last question ever!  :)

Couldn't find it anywhere in issues or the API, sorry

Note:  of course, obviously, cache is a transient thing.  If it's here "now" it may not be a short time later. But that's OK.

**Comment by kean** [comment]
Please, see the documentation https://github.com/kean/Nuke#lru-memory-cache. There is a memory cache, there is a default disk cache(shared `URLCache`).

**Comment by smhk** [comment]
Got it thanks
