### ISSUE TITLE
Deployment target does not go beyond 10.14 ?

### ISSUE THREAD

**Issue by smhk** [kean/Nuke#294]
For us, desire 12.0.  Popup only goes to 10.14 ?

![stul](https://user-images.githubusercontent.com/3938526/62865357-e786c000-bcd3-11e9-9d69-fef2a76e0326.jpg)

(FWIW I set it to 12 in the config file - I don't know if that's relevant or does anything.)

10.3 xcode, latest Nuke

**Comment by kean** [comment]
These seem like macOS deployment targets. The per-platform targets are defined in Nuke.xcconfig and can be overridden there or in Build Settings.

<img width="570" alt="Screen Shot 2019-08-12 at 20 29 24" src="https://user-images.githubusercontent.com/1567433/62888678-16d31680-bd40-11e9-96da-2506989f8f1c.png">

<img width="1056" alt="Screen Shot 2019-08-12 at 20 29 35" src="https://user-images.githubusercontent.com/1567433/62888687-1d618e00-bd40-11e9-93f8-3472f5a9628a.png">
