### ISSUE TITLE
How to load image without scaling in Nuke 8?

### ISSUE THREAD

**Issue by keynsianets** [kean/Nuke#295]
I have to load full size image. I use code: 
`ImagePipeline.shared.loadImage(with: urlPng, progress: nil) { (result) in
                switch result {
                    case let .success(response):
                    // handle response
                    let newImage = response.image
                    debugPrint("Source image size", newImage.size, newImage.scale)
                    case let .failure(error):
                    // handle error (non optional)
                    debugPrint(error)
                    return
                }
            }`
and get image with scale 2. ("Source image size" (145.0, 169.0) 2.0"). How to load image without scale, is it possible with Nuke?

**Comment by kean** [comment]
Hi, @keynsianets

By default, Nuke sets the scale to match the scale of the screen (look for this line `return UIImage(data: data, scale: Screen.scale)` in `ImageDecoder`). In order to change this behavior, you can write a custom decoder and register it with `ImageDecoderRegistry`. I also wouldn't mind extending the default decoder with some options.

**Comment by keynsianets** [comment]
@kean 
Thank you for answer and great work on this project.

**Comment by keynsianets** [comment]
I'm trying to implement your solution, but have faced with this problem: I can't initialize ImageDecodingContext structure cause its initializer has default protect-level 'internal'. I get error: "'ImageDecodingContext' initializer is inaccessible due to 'internal' protection level". This structure must has such code `public init() {}` for be available from external project. Can you add this, please?

**Comment by kean** [comment]
I don't think that you need to be able to instantiate it. All you need to do is instantiate your custom decoder and register it.

**Comment by kean** [comment]
Adding a public initializer wouldn't hurt though, I think I will add it.
