### ISSUE TITLE
OOM crashes

### ISSUE THREAD

**Issue by keynsianets** [kean/Nuke#296]
We have crashes with ImagePipeline for some user (0,5-1% of all users). All they have low free ram space. We use Nuke 8 with settings:
```ImagePipeline.shared.configuration.dataLoadingQueue.maxConcurrentOperationCount = 5
        ImageCache.shared.costLimit = 1024 * 1024 * 100 // 100 MB
        ImageCache.shared.countLimit = 50
        ImageCache.shared.ttl = 60*60*24*3 // Invalidate image after 3 day
        WebPImageDecoder.enable()
```
We use Nuke for download images (small copies for table\collectionViews and full images for detail screens) in a lot of screens.
We clean cache when app receive memory warning or if user have less than 100MB free ram. 
![Снимок экрана 2019-09-05 в 16 39 44](https://user-images.githubusercontent.com/46818370/64350108-c8dcc600-d000-11e9-9e9b-be04ec4077c8.png)

How we can avoid this crashes?

**Comment by kean** [comment]
Hi, I think it's most likely that the input image is too large. Please make sure that the images that you download have reasonable size.

There is no built-in mechanism to prevent the images that are too large from being decoded. You can add one by implementing a custom decoder.  See `ImageDecoding` and `ImageDecoderRegistry` for more info. See Nuke WebP Plugin for an example.

Resizing images might also help.

It also could be that there are too many images being decoded in parallel (WebP requires a lot of resources). But the `imageDecodingQueue` by default only allows 1 task at a time to run.

**Comment by kean** [comment]
Any updated on this one, @keynsianets?

**Comment by keynsianets** [comment]
Currently no, we try to fix it with some thicks and have no time for fix main issue - prevent decoding images if we have no free space for it. Maybe we will have time for this next month.

**Comment by kean** [comment]
I'm going to close this one since it seems to be related to the particular usage pattern. Nuke doesn't have any defensive mechanism in case images are too big to decode. If that's the case, you are going to need to add this logic on decoder / data loader level.

**Comment by AvdLee** [comment]
FWIW: We're still running into this issue (one of our biggest crashes) and I'm currently looking into solving this on our side. @keynsianets if you happen to find a fix for this, I'd love to know!
