### ISSUE TITLE
Max download size

### ISSUE THREAD

**Issue by jjnino** [kean/Nuke#297]
Hello!

I was wondering if there was a way to specify the max download size that an image can be?

**Comment by kean** [comment]
Hi, you can instantiate a data loader with a custom validation logic:

```swift
DataLoader(validate: { response -> Bool in
    response.expectedContentLength < 2_000_000
})
```

Validation logic runs as soon as you get response (`URLResponse`) and before the data is loaded. See this method for more info:

```swift
func urlSession(_ session: URLSession,
                    dataTask: URLSessionDataTask,
                    didReceive response: URLResponse,
                    completionHandler: @escaping (URLSession.ResponseDisposition) -> Void)
```

**Comment by jjnino** [comment]
Awesome thanks!
