### ISSUE TITLE
loading image that have large size

### ISSUE THREAD

**Issue by ahmadsallam** [kean/Nuke#298]
we have a problem we use nuke to loading the image from url in our app.
i use it in some cases in tableview cell but some times the image that return in the response it may be a very huge file size that be more that 2MB so when the dequeue in tableview cell happen and if i test it on old device such as iPhone 6 it will stuck or hang on some cell before showing the cell that have that image so the problem is from the loading of the image in cellForRow or should i resize the image before added in the imageView ?

**Comment by kean** [comment]
Hi, @ahmadsallam. You might want to use a [resizing image processor](https://github.com/kean/Nuke#resize). But the option would be to reduce the size of the images that you need to download, if possible.
