### ISSUE TITLE
How to update the cache

### ISSUE THREAD

**Issue by l101yakov** [kean/Nuke#301]
For example, chat tools, click on someone's profile to view the personal details page, at which point I want to update the user profile and apply it to the cache, how can I do that?

**Comment by kean** [comment]
Hi, @l101yakov. This is very general question. There are many ways to do that: update the cache manually, use HTTP cache control, you also need to clear memory cache somehow, etc. I would recommend going though the [README](https://github.com/kean/Nuke#caching) and [Image Caching Guide](https://kean.github.io/post/image-caching), and see what works for you.
