### ISSUE TITLE
Swift 5.1 Support

### ISSUE THREAD

**Issue by Rawnly** [kean/Nuke#302]
I was trying to update my app for iOS 13 but I've encountered the following:

(it's a *Carthage* project)
```
Compiled module was created by an older version of the compiler; rebuild 'Nuke' and try again: 
/Users/federicovitale/Code/SWIFT/StockPapers/Carthage/Build/iOS/Nuke.framework/Modules/Nuke.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

How can I go ahead?

I've tried by running:

```sh
	m -rf ~/Library/Developer/Xcode/DerivedData/ && carthage update --platform iOS --no-use-binaries
```

but nothing changed.

**Comment by kean** [comment]
Hi, @Rawnly. It seems like a Carthage related issue. Please make sure Carthage and Xcode both use the same toolchain.

**Comment by Rawnly** [comment]
Thank you, solved by changing `xcode-select` path destination.
