### ISSUE TITLE
Internet Speed Test

### ISSUE THREAD

**Issue by abdallahnh** [kean/Nuke#313]
Is there a way to get the internet speed while downloading the images to be used as a global variable in the app?

**Comment by kean** [comment]
Hi, could you please elaborate you question? At a glance, yes, it seems doable. I'm not sure I follow what you mean by threshold?

**Comment by abdallahnh** [comment]
Hi Kean,

Here is my scenario:
In our app we download images for stores, we need to do a logic that depends on the internet speed, so what I'm thinking of is to have a feature in Nuke library to always keep checking for the last speed calculated, like Nuke.SpeedManager.lastSpeed.
and according to the lastSpeed values I decide to use images sizes to download 1x, 2x, or 3x

**Comment by abdallahnh** [comment]
Hi again,

I opened the pull request https://github.com/kean/Nuke/pull/315, but it is failing on LintChek
I tested it from my branch and it works as i needed so it is nice if you can merge this request thanks

**Comment by abdallahnh** [comment]
Hi can you check the PR #316 , thanks

**Comment by kean** [comment]
Sorry, my schedule was busy. I will review it as soon as I can.

**Comment by DanielStormApps** [comment]
> Hi Kean,
> 
> Here is my scenario:
> In our app we download images for stores, we need to do a logic that depends on the internet speed, so what I'm thinking of is to have a feature in Nuke library to always keep checking for the last speed calculated, like Nuke.SpeedManager.lastSpeed.
> and according to the lastSpeed values I decide to use images sizes to download 1x, 2x, or 3x

This feels out of scope for Nuke IMO.

Also, internet speed doesn't tell the whole story. What if a user has "Low Data Mode" enabled on the current network?
