### ISSUE TITLE
SwiftUI support?

### ISSUE THREAD

**Issue by sjmueller** [kean/Nuke#314]
I see that SwiftUI integration is coming in January with Nuke 8.5 (on the trello board), but in the meantime can you share the best way right now to load remote images into a SwiftUI Image component using Nuke?

**Comment by kean** [comment]
Hi, @sjmueller. I haven't yet put too much though into this. It seems that a lot of people are excited about SwiftUI and are reading about it. Not a lot of people are actually using it.

I was thinking about adding an `ImageViewModel` to `Nuke`. As well as a view which knows how to bind to this view model. I could potentially simply rework the existing `ImageViewExtensions` + `ImageViewController` to use bindings instead of direct methods calls. Should be easy enough.

**Comment by sjmueller** [comment]
Thanks for the prompt reply @kean. The SwiftUI Image component has a few constructors that we might be able to use with the current version of nuke:
https://developer.apple.com/documentation/swiftui/image

Namely, passing in either a `UIImage` or `CGImage`. I tried using `Nuke.loadImage()` with a `UIImageView` but the internal `UIImage` is nil at first. Do you have an example of using Nuke that gives us access to `UIImage` (or `CGImage`) at the moment it's decoded and ready?

**Comment by kean** [comment]
You can use [`ImagePipeline` directly](https://github.com/kean/Nuke#image-pipeline) to do that. It gives you all the features that you might need. The `UIImageView` extensions are only that – extensions for making using Nuke with `UIImageView` easier.

**Comment by sjmueller** [comment]
Here's a quick and simple component that uses Nuke's `ImagePipeline` to load remote images. It might not be particularly robust, but perhaps it can help fill the gap until SwiftUI support officially lands:
``` swift
struct RemoteImage: View {
    var url: URL
    @State private var uiImage: UIImage?
    @State private var show = false
    
    var body: some View {
        if uiImage != nil {
            return AnyView(
                Image(uiImage: uiImage!)
                    .resizable()
                    .aspectRatio(contentMode: .fill)
                    .opacity(show ? 1 : 0)
                    .animation(.linear(duration: 0.15))
                    .onAppear {
                        self.show = true
                    }
            )
        } else {
            return AnyView(
                Rectangle()
                    .onAppear {
                        ImagePipeline.shared.loadImage(with: self.url) { result in
                            switch result {
                            case .success(let response): self.uiImage = response.image
                            case .failure(let error): print(error)
                            }
                        }
                    }
            )
        }
    }
}
```

**Comment by kean** [comment]
I made [`FetchImage`](https://kean.github.io/post/introducing-fetch-image) which makes it easy to use Nuke from SwiftUI. It is largely inspired by the snipper provided by @sjmueller.

**Comment by sjmueller** [comment]
@kean great work, excited to try `FetchImage` out!

**Comment by kean** [comment]
Thanks, I will appreciate any feedback! It's not battle-tested yet and I'm not sure about some of the design decisions. For example, `FetchImage` currently retains loaded images, which is something I'd like to avoid but I'm not sure how to.

**Comment by kean** [comment]
I'm also adding Low Data support to `FetchImage` which is going to be available some time tomorrow in the same gist file.
