### ISSUE TITLE
How to Handle Image Cache saving to Disk

### ISSUE THREAD

**Issue by ZAPHIT** [kean/Nuke#32]
Hi.. i have tried your awesome Framework, its probably better than haneke i think, but i have the same problem with haneke.. The cache seems on memory level only and its like a volatile cache..

Can you provide some snippet of how to save cache files to disk like an NSData.

Seems confuse with this codes:

let dataLoader: ImageDataLoading = <#dataLoader#>
let decoder: ImageDecoding = <#decoder#>
let cache: ImageMemoryCaching = <#cache#>

let configuration = ImageManagerConfiguration(dataLoader: dataLoader, decoder: decoder, cache: cache)
ImageManager.shared = ImageManager(configuration: configuration)

thanks!

**Comment by kean** [comment]
Check out [this guide](https://github.com/kean/Nuke/wiki/Image-Caching-Guide) please. On-disk caching is already handled by NSURLCache.

**Comment by ZAPHIT** [comment]
Hi kean.. thanks for all of your help.. Your framework is good, i have tried lots of framework, yours is the fastest but i have discover another framework that soothes this cache that i need..maybe you could be inspire by KingFisher.. its also swift version..

**Comment by kean** [comment]
Thanks, but Nuke focuses on pro users and HTTP caching is a way to go for them. Reasons: it's an industry standard that provides tools for cache revalidation, and it's already supported by most websites. I don't feel the need to implement and maintain a simplified cache just to appeal to a larger audience.

I would urge you to take some time and actually investigate HTTP caching, it is a knowledge which would proof useful even outside of the context of image loading.

**Comment by kean** [comment]
@ZAPHIT Nuke 4 will allow you to add custom on-disk cache into its pipeline. Releasing soon.

**Comment by joe528** [comment]
@kean  Is caching asynchronous for Nuke?

**Comment by kean** [comment]
@joe528 Actually Nuke 3 already has such a protocol:

```swift
/**
 On-disk storage for image data.
 
 Nuke doesn't provide a built-in implementation of this protocol. However, it's very easy to implement it in an extension of some existing library, for example, DFCache (see Example project for more info).
*/
public protocol ImageDiskCaching {
    /// Stores data for the given task.
    func setData(data: NSData, response: NSURLResponse, forTask task: ImageTask)
    
    /// Returns data for the given task.
    func dataFor(task: ImageTask) -> NSData?
    
    /// Clears the receiver's storage.
    func removeAllCachedImages()
}
```

As you can see It's synchronous, but the `Nuke.ImageLoader` calls methods from this protocol from the asynchronous `Foundation.Operation`.

On-disk caching in Nuke 4 is going to look more like this:

```swift
public protocol DataCaching {
    func response(for request: URLRequest, completion: (CachedURLResponse?) -> Void) -> Cancellable
    func setResponse(_ response: CachedURLResponse, for request: URLRequest)
}
```

It's asynchronous, the user would be responsible for scheduling.
