### ISSUE TITLE
add SWIFT VERSION in Nuke.pobspec

### ISSUE THREAD

**Issue by Musasshi90** [kean/Nuke#330]
Hello I'm getting this error :`Nuke` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Is it ok you add the SWIFT_VERSION in Nuke.pobspec?

**Comment by kean** [comment]
Hi, @Musasshi90. I don't currently specify a Swift version and I should. In the meantime, you can fix this by setting `SWIFT_VERSION` attribute in your project settings for `Runner` target.
