### ISSUE TITLE
Load image from AWS S3

### ISSUE THREAD

**Issue by saravr** [kean/Nuke#331]
Is there a way we can customize DataLoader such that the image can be loaded from S3 using credentials?

**Comment by kean** [comment]
Hi, @saravr. Yes, it should be possible. I know people are using Nuke with AWS. There are at least two ways to inject credentials:

1. Provide credentials every time you create a request:

```swift
var urlRequest = URLRequest(url: <#url#>)
urlRequest.allHTTPHeaderFields["authorization"] = <#credentials#>
let request = ImageRequest(urlRequest: urlRequest)
```

2. Create a data loader with a `URLSessionConfiguration` which has credentials:

```swift
let pipeline = ImagePipeline {
    let configuration = DataLoader.defaultConfiguration
   configuration.httpAdditionalHeaders["authorization"] = <#auth#>
   $0.dataLoader = DataLoader(configuration: configuration)
}
```

**Comment by majdkhadra** [comment]
What do I put in <#credentials#>

**Comment by kean** [comment]
I'm not familiar with AWS S3. I'm assuming you need to provide [authorization headers](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html). There also seems to be an option to get a [pre-signed URL](https://stackoverflow.com/questions/60166127/ios-app-how-to-use-kingfisher-sdwebimage-to-download-aws-s3-image) using their SDK. If you figure it out and post an answer for future references, that would be nice.

**Comment by majdkhadra** [comment]
Thank you, I'll do that, and if you have you know anyone that could possibly know this I would love if I could contact them 😀 thank you
