### ISSUE TITLE
Resizing local images fails on initial load

### ISSUE THREAD

**Issue by annca** [kean/Nuke#334]
I'm loading and resizing local images from my bundle as suggested in issue #66 
These images are set inside collection view cells.

When my screen first loads, visible cells do show any images and I receive `processingFailed` error in the completion handler. 

However, when I start scrolling, cells that were off-screen appear correctly and when I scroll back to initial cells, those images appear fine as well and the completion result is successful.

Is this a bug or am I missing something?

```
let request = ImageRequest(url: url,
                processors: [ImageProcessor.Resize(size: imageView.bounds.size, contentMode: .aspectFill)], priority: .normal)

Nuke.loadImage(with: request, options: .shared, into: imageView, progress: nil, completion: { response in
                print("completed")
            })
```

**Comment by kean** [comment]
Hi, I would suggest setting a breakpoint in `ImageProcessor.Resize` to see what's going on there. I would suggest first checking that `imageView.bounds.size` is not `.zero` by the time you start loading the images.

**Comment by annca** [comment]
Ah good instinct! I have confirmed that when the cell is dequeued for the first time, it hasn't yet gone though a layout cycle, so `imageView.bounds` are indeed `.zero`.
I changed my approach and passed the target size into the cell configuration method, so now it works! Thank you for the prompt response 😊
