### ISSUE TITLE
Render SVG to bitmap

### ISSUE THREAD

**Issue by kamil3** [kean/Nuke#335]
Hi,
I'm using custom decoder for decoding images' data:
```swift 
struct SVGImageDecoder: Nuke.ImageDecoding {    
    func decode(data: Data, isFinal: Bool) -> Nuke.PlatformImage? {
        //Converting from SVG to Image...
    }
}
```
```swift 
ImageDecoderRegistry.shared.register { imageDecodingContext -> ImageDecoding? in
            if imageDecodingContext.request.urlRequest.url?.isSVG ?? false {
                return SVGImageDecoder()
            } else {
                // it takes a default decoder implicitly
                return nil
            }
        }
```
I noticed that it's firstly getting original data from disk cache (assuming a memory cache is empty) and then it's decoding. My custom decoding takes some time and it's noticeable. Is it any convenient way to store in a disk cache already decoded data in order to speed up loading? I mean, not to convert images every time the app launches (just for the first time).

**Comment by kean** [comment]
Hi @kamil3,

That's an interesting use case. It is no directly supported, however, you achieve what you are describing by [using `DataCache` and storing processed images](https://github.com/kean/Nuke#aggressive-lru-disk-cache).

```swift
pipeline = ImagePipeline {
    $0.dataLoader = DataLoader(configuration: {
        let conf = DataLoader.defaultConfiguration
        conf.urlCache = nil // Disable disk caching built into URLSession
        return conf
    }())

    $0.dataCache = try? DataCache(name: "com.github.kean.Nuke.DataCache")

    $0.isDataCachingForOriginalImageDataEnabled = false
    $0.isDataCachingForProcessedImagesEnabled = true
}
```

The pipeline will load the image data, decode it, and then re-encode it (see `ImageEncoder`) and put it on disk.

But there is one issue. The "processed" images are the ones that have at least one processor applied. What you can do is create a processor which does nothing and use it for all your requests:

```swift
extension ImageProcessor {
    struct Empty: ImageProcessing {
        public let identifier = "EmptyProcessor"

        func process(image: PlatformImage, context: ImageProcessingContext?) -> PlatformImage? {
            return image
        }
    }
}
```

This is not ideal, but it should work and it's highly unlikely to break in the future.

**Comment by kamil3** [comment]
Hi @kean,
Thanks for you response, it looks like it's working. However to make it work completely I had to modify registering a decoder, like below:
```swift
ImageDecoderRegistry.shared.register { imageDecodingContext -> ImageDecoding? in
            if imageDecodingContext.request.urlRequest.url?.isSVG ?? false,
                //if it's received from cache it's not SVG data anymore since it was already converted to PNG
                ImageFormat.format(for: imageDecodingContext.data) == nil {
                return SVGImageDecoder()
            } else {
                // it takes a default decoder implicilty
                return nil
            }
        }
```
I'm using your `ImageFormat` enum to check the data format to return a proper decoder (I needed to copy it since it's not public).

**Comment by kean** [comment]
I think it would be better to extend `ImageFormat` and add an `.svg` case with the respective magic numbers.

```swift
ImageDecoderRegistry.shared.register { imageDecodingContext -> ImageDecoding? in
    if ImageFormat.format(for: imageDecodingContext.data) == .svg {
        return SVGImageDecoder()
    }
    return nil
}
```

I was [planning](https://trello.com/b/Us4rHryT/nuke) to release `ImageFormat` soon, but I haven't finalized the API for it yet.

**Comment by kamil3** [comment]
As far as I've been researching magic numbers for SVG do not exist, so probably I could implement another checking if it's SVG format (example thread: https://stackoverflow.com/questions/15136264/how-can-i-say-a-file-is-svg-without-using-a-magic-number).

**Comment by kean** [comment]
Here is how SDWebImage does it https://github.com/SDWebImage/SDWebImageSVGCoder/blob/master/SDWebImageSVGCoder/Classes/SDImageSVGCoder.m#L241

**Comment by kamil3** [comment]
Thanks. I'll test it. 

Now I have another issue, I noticed 3x more memory usage using this configuration:
```swift
pipeline = ImagePipeline {
    $0.dataLoader = DataLoader(configuration: {
        let conf = DataLoader.defaultConfiguration
        conf.urlCache = nil // Disable disk caching built into URLSession
        return conf
    }())

    $0.dataCache = try? DataCache(name: "com.github.kean.Nuke.DataCache")

    $0.isDataCachingForOriginalImageDataEnabled = false
    $0.isDataCachingForProcessedImagesEnabled = true
}
```
And instead of `EmptyProcessor` I'm using `Resize` one: 
```swift
let size = CGSize(width: 200, height: 200)
ImageRequest(url: url, processors: [ImageProcessor.Resize(size: size)])
```
It takes about ~5MB for each imageView (I'm rendering them in a collectionView). What is important, when using a default configuration a memory usage is stable. If it was a clue, whilst decoding I'm returning quite big images, about 1600x1600 px.

Do you have any idea what's causing it?

**Comment by kean** [comment]
Not really. In general, downsampling results in lower memory usage. I don't currently have ideas what might be causing this.

**Comment by kean** [comment]
Hey, @kamil3. Did you figure out what was the issue with resizing?

**Comment by kamil3** [comment]
Hi @kean, I haven't been available until today. For now, I'd probably abandon this solution due to this issue. I'd additionally use prefetching - user experience is slightly better, but still it's not what I would like to have. 
If I figure out what's causing the memory issue, I'll write it here.

**Comment by kamil3** [comment]
What I've investigated so far, encoding image data is causing memory issue: `let encodedData = encoder.encode(image: response.image)` (line `532` in `ImagePipeline`). Memory consumption increases and does not decrease. However, I don't know yet why this is happening.

**Comment by mkll** [comment]
Hi @kean,

```
pipeline = ImagePipeline {
    $0.dataLoader = DataLoader(configuration: {
        let conf = DataLoader.defaultConfiguration
        conf.urlCache = nil // Disable disk caching built into URLSession
        return conf
    }())

    $0.dataCache = try? DataCache(name: "com.vinilink.DataCache")

    $0.isDataCachingForOriginalImageDataEnabled = false
    $0.isDataCachingForProcessedImagesEnabled = true
}
```

This is strange, but it seems that such a configuration does not work at all. I see that the directory is being created, but it is empty both while the app is running and after its completion. At the subsequent launch, it is clearly visible that the images are again downloaded from the backend.

![7D7A1337-055E-4128-AA7E-B25C5DC598E7-1](https://user-images.githubusercontent.com/1652009/72470454-afdfef00-3802-11ea-8396-256b7a9027af.png)

Any ideas?

**Comment by kean** [comment]
Hi, @kamil3, any updates on this issue?

**Comment by kean** [comment]
Also, I'm wondering, how are you communicating the information about the size of the SVG to the decoder? I'm asking because SVG is something I'm considering to add soon. It seems that the decoder needs some of the additional information.

Answering my own question, each `ImageRequest` has `userInfo`. That's one of the options.

**Comment by kean** [comment]
I'm going to closes this issue since there is now a lot of outdated information here. I added "Add SVG -> Bitmap decoder" issue in a [Trello board](https://trello.com/b/Us4rHryT/nuke).
