### ISSUE TITLE
Memory Leak TableView

### ISSUE THREAD

**Issue by matthijsotterloo** [kean/Nuke#337]
Hi there!

I'm having a table view that shows data from a fetched data array.
When scrolling up and down fast it triggers a memory leak, (`Message from debugger: Terminated due to memory issue`).

When I remove the Nuke image loading the problem is gone, see my code below.
Any ideas on how to solve this?

````
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "categoryCell", for: indexPath) as! CategoryCell
        
        if cell.categoryImage.viewWithTag(99) == nil {
            let tranpView = UIView(frame: CGRect(x: 0, y: 0, width: cell.frame.size.width, height: cell.frame.size.height))
            tranpView.backgroundColor = UIColor.black
            tranpView.tag = 99
            tranpView.backgroundColor = tranpView.backgroundColor!.withAlphaComponent(0.3)
            cell.categoryImage.addSubview(tranpView)
        }

        cell.categoryImage.autoresizingMask = [.flexibleWidth, .flexibleHeight, .flexibleBottomMargin, .flexibleRightMargin, .flexibleLeftMargin, .flexibleTopMargin]
        cell.categoryImage.contentMode = .scaleAspectFill
        cell.categoryImage.clipsToBounds = true
        Nuke.loadImage(with: URL(string: (arrCategories[indexPath.row].image))!, into: cell.categoryImage)
        
        cell.categoryTitle?.text = arrCategories[indexPath.row].name
        return cell
    }`

**Comment by kean** [comment]
You might be downloading the images which are too big. If that's the case, you can resize them locally https://github.com/kean/Nuke#resize, but ideally the server should be providing images optimizing for the client.

**Comment by kean** [comment]
Please also make sure there are no leaks in the table cells 😉

**Comment by kean** [comment]
I'm going to close this, please reopen if you are still experiencing the issue and you think it is on the Nuke side. The only known leak so far which was on the part of the framework was [this one](https://github.com/kean/Nuke/issues/336) which is now fixed. But it doesn't seem like what you are experiencing.
