### ISSUE TITLE
Cancelling existing requests in favour of new ones

### ISSUE THREAD

**Issue by colcalex** [kean/Nuke#342]
I seem to have a very specific problem, caused by how the back end I access is setup. 

My issue is similar to [Opt out of cancelling current request](https://github.com/kean/Nuke/issues/147) but with a twist. So I look forward to your opinion & knowledge on the subject, while keeping in mind it is a different problem.

**Problem**

- When I download images, the back-end sends images formatted for the requirements (pixel scaling, size etc)
- First time for a new image back-end will need to run the formatting, causing a delay
- `Nuke` preventing duplication and being efficient with requests, only ever has 1 request live
- **!!!** the oldest request gets dropped to favour the latest one
- Back-end sees client request dropped and saves whatever it did so far on cache, leaving me with invalid and incomplete images for posterity.

**Solutions**

I have not setup `Nuke`, so my knowledge is very limited, if there is an existing solution to this problem, please let me know. And stop reading, as you won't be interested 😄. I have no intention of reinventing the wheel, just came across solutions that work for me.

1) Obviously fix back-end, but that's going to be done on a different time scale
2) Offer an option to the user of the framework to decide which requests to be dropped in preventing deduplication (latest or newest).
Specifically inside `ImageViewExtensions`, at `line 332: func loadImage(with request: ImageRequest,`, use a simple conditional to check the state of pipeline before deciding whether to cancel existing requests or to simply cancel this request if another exists.
```swift
    func loadImage(with request: ImageRequest,
                   options: ImageLoadingOptions,
                   progress progressHandler: ImageTask.ProgressHandler? = nil,
                   completion: ImageTask.Completion? = nil) -> ImageTask? {
        let pipeline = options.pipeline ?? ImagePipeline.shared // Moved up few lines
        if pipeline.configuration.deduplicateLatest && task != nil {
            return // Prevent interrupting existing task
        } else {
            cancelOutstandingTask()
        }
 // ....
    }
```

**Questions**
1) Is there already a solution to my problem
2) If (1) is negative and I make my solution on a fork, would you be interested to merge it? My expectation (haven't fully coded it yet, so could be wrong) is to add 1 more property to `ImagePipeline.Configuration` (`deduplicateLatest`? 🤷‍♂) and 4 lines of code as mentioned above ☝️.

**Comment by kean** [comment]
> use a simple conditional to check the state of pipeline before deciding whether to cancel existing requests or to simply cancel this request if another exists.

I'm not sure this is the best approach since cancellation makes sure that when the view is reused, e.g. when displayed in the context of table/collection view, the correct images are displayed.

### Suggested Workaround

I would suggest fixing the backend, and in the meantime what you can do is every time you call `Nuke.loadImage(with:options:progress:completion:)`, also call `ImagePipeline.shared.loadImage(with:)` and never cancel it to keep requests alive. As an alternative, you can add these requests to `ImagePreheater`. This way you can a bit more control, e.g. you will be able to cancel all of the requests when the user leaves the screen.

### Better Solution

A smarter solution would probably involve only _not_ cancelling tasks when the URL request is already in progress. I'm pretty sure all of the needed infrastructure to do that is already there in `ImagePipeline`. All you need to do is add a configuration option and use it on line `ImagePipeline.swift:753`:

```swift
if configuration.isPleaseComeUpWithAGoodNameEnabled {
    task.onCancelled = { [weak self] in
        guard let self = self else { return }

        log.signpost(.end, "Cancelled")
        dataTask.cancel()
        finish() // Finish the operation!

        self.tryToSaveResumableData(for: context)
    }
}
```

This will make sure that when we start a URL request, we never cancel it. The `ImageTask` _will_ get cancelled, but if deduplication will make sure that it will reuse the existing URL request from the pool.

I think it is OK to add a configuration option like this, it might be a desirable behavior for some people (see https://github.com/kean/Nuke/issues/147). I'm not sure it is a good practice though, see my comments in the thread.

**Comment by colcalex** [comment]
> I think it is OK to add a configuration option like this, it might be a desirable behavior for some people (see #147). I'm not sure it is a good practice though, see my comments in the thread. So if you are OK with a workaround I suggested, I would suggest sticking with it instead.

That's why I'm happy I raised this before taking a naive approach that fixes a small problem by creating others 😄. For me, your suggestion is perfect, although I'm not sure I follow its implementation correctly (looking at repo on master). 
The problem is that I've inherited this codebase, way too complex to easily fix the behaviour in the first place. I also don't have control on the backend myself (although someone on my team will eventually get to it), but would like to make sure this behaviour does not return whatever happens. 

So from my current position I can see how there would be a need for such a propriety, that may default to current behaviour. Sadly in commercial apps, after a ton of compromises, sometimes you end up in the wrong position with limited options 😆.

If you're sure you don't want to enable it in the main codebase, I'll fork and use SPM, attempting the fix you've suggested.

Side note: Generally not a fan of 3rd party frameworks, but this one is great. Great job making something so useful and simple to interact with at call site 👍.

**Comment by kean** [comment]
I think adding this option is fine, this is what configuration is for. I already exposed a variety of configuration option which are not advisable to turn off, but can be, if the default behavior just doesn't work for you for some reasons. For example, you can turn off deduplication completely if you want to using `isDeduplicationEnabled` (not suggesting it to you as a fix, it's just an example).

As a suggested name for this `isExecutingDataTaskCancellationEnabled` with a default value of `true`. Please feel free to suggest other options. I'm also going to need to document it.

**Comment by kean** [comment]
> Generally not a fan of 3rd party frameworks

Same here, but I think there is significant value in image loading frameworks, most app developers shouldn't reinvent it.

**Comment by kean** [comment]
Update: `isDataTaskCancellationEnabled`.

**Comment by colcalex** [comment]
This was the best documentation / name I could come up with. Quite verbose but I think it's on point. However, I might not realise correctly the call-site.
```swift
        /// `false` by default. Will only be relevant  if
        /// `isDeduplicationEnabled` is true.
        /// If `true` when a duplicate request is detected it will keep the oldest
        /// request and cancel the current request.
        /// If `false` when a duplicate request is detected it will cancel it and
        /// go ahead with the latest request instead.
        /// This prevents an ongoing request to the back-end from being
        /// finished prematurely by the client.
        public var isKeepingOriginalTaskIfDuplicate = false
```

> you can turn off deduplication completely
I've tried that first and it was not fun 💣💥 . Your implementation to prevent duplication is a god-send for this project. 

I take it you're doing this now? Or should I continue trying it?

**Comment by kean** [comment]
I'm not working on it, I would appreciate a PR. If you have time to add tests, that would also be appreciated. I understand if that's too much to ask, this is quite complicated to tests, but should be doable with the existing testing infrastructure in Nuke.

Please keep in mind I might change some of the aspects of this feature like naming/documentation/etc prior to release.

**Comment by colcalex** [comment]
Ah, my bad, it seems in version 8 it's already implemented. When working on it I realised the code you said is already in there 🤦‍♂. Cocoapods is so all over the place that you could only run it from **a** machine (plugins, environment variables, secrets...), which is long lost, so migrating it to SPM and getting the latest version accomplishes what we need. Previously in was stuck on 7.6.3.

Thanks for being so quick and knowledgeable on it 👍

**Comment by kean** [comment]
This new option that we were discussing isn't implemented. I assumed you had version 8.x.

**Comment by colcalex** [comment]
The code you've mentioned is already at `line 735` (suppose it was a typo in your message, took me a while to see it) and seems to solve my problem well, as you've said it would. I suppose my problem previously may have come from task not being cancelled correctly and getting dropped instead. Now all the work is completed correctly and the cached image generated by first request is always complete.

> I assumed you had version 8.x.
I'm so embarrassed, you'd think that's the first thing one would check. Failed to do a pod update few weeks ago and couldn't untangle it, so completely lost hope on that. Good for SPM and that Xcode prefers SPM first and Pod second (I'm left with `Nuke` duplicated until I can clean up the pods).

**Comment by kean** [comment]
Alright, let me know if you have any additional questions.
