### ISSUE TITLE
Nuke 8.4.2 doesn't run on iOS device or Mac Catalyst build

### ISSUE THREAD

**Issue by gabors** [kean/Nuke#355]
Nuke 8.4.2 doesn't run on iOS/tvOS device or Mac Catalyst build.

On Mac Catalyst app crashes complaining that the Nuke framework needs to be signed.
On iOS/tvOS the framework doesn't load as it is not found.

In my case Nuke is referenced into a Framework target which is then used by several app targets.
All releases prior to 8.4.2 worked great.

**Comment by kean** [comment]
Hey, thanks for reporting this. I'm experimenting with static vs dynamic libraries when distributing the framework via Swift Package Manager. In Nuke 8.4.2 the default is dynamic. It requires some changes in terms of how your are setting up the project. Is dynamic library going work for you? Do you need a static version instead?

**Comment by gabors** [comment]
Thanks! I was reading about how to integrate dynamic SPM libraries with Xcode yesterday.
Didn't see the option to embed and sign. Maybe I need to remove the Nuke package and try re-adding it. Haven't had a chance to try yet, just rolled back to 8.4.1 for now as I was doing a release.

All my other SPM packages I'm using don't have the type specified, so they must default to static.
Curious how can the target that imports a package specify if it wants a static and dynamic version, I think I read somewhere that it was possible, but maybe it was a nice to have.

Big thanks for this library BTW.

**Comment by vmartinelli** [comment]
Hi there!

I don't know if the issue @gabors reported is related only to Mac Catalyst builds as it appeared in my native macOS and iOS projects as well.

My question is, even if there was a way to specify in the Xcode UI which library type the user project needs when importing the library package, should this decision be made by the library or its user?

Both static or dynamic would work for me, but I haven't really found how to code sign it yet when the type is framework (and other packages usually specify that they are static).

I think that the effort to continue researching this is very important for learning purposes, but for the moment I believe that the safest way would be to revert the library type to static.

Oh, and thanks again for your excellent work, @kean. I have learned many interesting coding techniques from you.🙂

**Comment by kean** [comment]
As of Xcode 11.4, static libraries are not going to work anymore when you have multiple app extensions. Xcode forces you to integrate shared dependencies as dynamic libraries to avoid duplicating the binaries.

<img width="322" alt="Screen Shot 2020-04-04 at 09 20 11" src="https://user-images.githubusercontent.com/1567433/78451782-9f971d80-7655-11ea-9926-1c069a06ae1f.png">

Xcode is not smart enough to upgrade from static to dynamic libraries. You are going to need to do some additional work. For me, removing the package first, and then adding it again worked. Everything works perfectly, including the scenario with multiple targets.

I'm considering whether dynamic library should be optional. Static library is a better default if you have a single target. Dynamic library is a better default for apps with app extensions.

**Comment by kean** [comment]
> Both static or dynamic would work for me, but I haven't really found how to code sign it yet when the type is framework (and other packages usually specify that they are static).

Code signing is set up for you automatically by Xcode.

<img width="620" alt="Screen Shot 2020-04-04 at 09 27 27" src="https://user-images.githubusercontent.com/1567433/78451948-88a4fb00-7656-11ea-8259-ec35c0410294.png">

**Comment by kean** [comment]
The [recommendation](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescription.md) is to not explicitly define a type.

<img width="854" alt="Screen Shot 2020-04-04 at 09 31 33" src="https://user-images.githubusercontent.com/1567433/78452068-28fb1f80-7657-11ea-9931-b35c1d04d764.png">

Unfortunately, this doesn't seem to work. At all. Xcode 11.4 just fails in the scenario where dynamic linking is a better option.

**Comment by kean** [comment]
I removed the release Nuke 8.4.2 for now while I'm investigating it further.

**Comment by gabors** [comment]
Wonder if this works:

```.library(name: "LibraryDyn", type: .dynamic, targets: ["Library"]),  
.library(name: "Library", targets: ["Library"]),```

taken from https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892/3

**Comment by vmartinelli** [comment]
This may also help: https://github.com/renaudjenny/Swift-Package-Manager-Static-Dynamic-Xcode-Bug

I couldn't test it, but I tried a similar approach that worked for my particular scenario:

In my apps I have many frameworks, one for data access, one for business logic, one for presentation, etc. So I managed to make SPM libraries to be imported correctly and without duplications using an additional "empty" local helper framework, adding the SPM static library references to it and then referencing this framework in other workspace frameworks, without actually embedding it, and finally, referencing it in the main app target, this time embedding and signing this helper framework.

**Comment by kean** [comment]
I think the original problem is gone after I switched back to the default installation option (static libraries). If SPM provides more control in the future, I'll add support for it. But for now I think this can be closed.
