### ISSUE TITLE
Use of unresolved identifier 'ImageProcessors'

### ISSUE THREAD

**Issue by djdance** [kean/Nuke#356]
Im using swift4, Nuke version 8.4.1
imported Nuke, then
```
let request = ImageRequest(
                url: urlPathURL,
                targetSize: CGSize(width: 150*UIScreen.main.scale, height: 150*UIScreen.main.scale),
                processors: [ImageProcessors.Circle()],
                contentMode: .aspectFill)
```
...but it says no processors. What should I do?

**Comment by kean** [comment]
Hi, documentation for 8.4.1 is currently available at https://github.com/kean/Nuke/tree/8.4.1. `master` is for Nuke 9 which is currently in beta.

**Comment by djdance** [comment]
no problem, I've explored the docs from here https://github.com/kean/Nuke/tree/8.4.1/Documentation/Guides , but where should I get help with ImageProcessors? How to find/include them, in first? are they in some separate pod ? 

thanks

**Comment by djdance** [comment]
in particular,

![Untitled](https://user-images.githubusercontent.com/2269720/78530635-b4f28000-77ec-11ea-98ae-bc31f2e87f02.jpg)

**Comment by kean** [comment]
`ImageProcessors` is a new "namespace" available in Nuke 9, adopting naming conventions that Apple seem to be using with Combine and SwiftUI. In Nuke 8, this "namespace"/enum was named `ImageProcessor`. You can find all of the available processors under this namespace.

**Comment by djdance** [comment]
thank you! and let me disturb you once more (I honestly googled everywhere).
How to use it?
I've tried this below, but it crashes on 1st and doesn't like 2nd string.

![2](https://user-images.githubusercontent.com/2269720/78570780-1424b480-782e-11ea-9802-4dcb21bea6e3.png)

**Comment by kean** [comment]
There is nothing in Nuke that can crash on creating a request/processor.

**Comment by djdance** [comment]
**crying**

oh, just give me full working example please! both for Nuke 8 and 9.
because no any example on entire web.
Simply: how to upload and round my avatar? in one-two strings, without pipelines and complex options

thanks for advance

**Comment by kean** [comment]
The code that you have is correct.

```swift
ImageRequest(url: url, processors: [ImageProcessors.Circle()])
```

The only reason I could think of that it might be crashing, is it wasn't installed correctly. Do you see any messages in the console associated with the crash?

**Comment by djdance** [comment]
you were right.
as usual, restart XCode plus clean build folder helped me.
it works now!
