### ISSUE TITLE
Required to keep a reference to ImagePreheater

### ISSUE THREAD

**Issue by jeffreykuiken** [kean/Nuke#357]
Hi!

I ran into some (for me) unexpected behaviour with ImagePreheater today. I was creating an instance of `ImagePreheater`, and calling `startPreheating` on it, from a function, without keeping a reference to it anywhere else.

However, I noticed that this way, not all preheat tasks would be completed. After investigating, I found out that that's because `Operation`s are not capturing a strong reference to the `ImagePreheater` (https://github.com/kean/Nuke/blob/master/Sources/ImagePreheater.swift#L91)

Because of this, and because I was not keeping a reference to it either, `ImagePreheater` will be deinitialized before all `Operation`s are finished, which would prevent the tasks from being completed (https://github.com/kean/Nuke/blob/master/Sources/ImagePreheater.swift#L92). If `Operation`s would keep a strong reference to the `ImagePreheater`, all tasks would finish fine, after which the `ImagePreheater` would be deinitialized if they are no other references of it.

Is this behaviour intentional? I think at least it's incoherent with the example code in the Readme (https://github.com/kean/Nuke#image-preheating), where it looks like the preheater is initialized in a local variable.

(For others running into the same problem right now: I've fixed it in my implementation by adding an instance of `ImagePreheater` as a variable to my class, and calling `startPreheating` on that instance.)

**Comment by kean** [comment]
Hi, @jeffreykuiken.

> Is this behaviour intentional?

It is intentional, `ImagePipeline` operates the same way. In Nuke 9, `ImagePreheater` even goes as far as automatically cancelling all of the outstanding requests when deallocated. Thanks for pointing out an issue with documentation, it needs some work.

**Comment by jeffreykuiken** [comment]
Allright, thanks for clarifying!
