### ISSUE TITLE
Storing local image in the disk cache for a url

### ISSUE THREAD

**Issue by tkohout** [kean/Nuke#359]
Hello,
I have a simple use case in my app:

Video is recorded and uploaded to the server. Picture thumbnail of the video is generated in the app and should be shown temporarily in the video preview while it's getting processed on server. Once the video is fully processed the server generated image is downloaded from the server.

So what I would like to do is to send Nuke an UIImage and cache it for a certain URL. I was able to do something like this:

```
let request = ImageRequest(url: serverURL)
let response = ImageResponse(image: image)
    
// This stores the image in the in-memory cache
// Doesn't persist when you restart the app
    
ImagePipeline.shared.configuration.imageCache?.storeResponse(response, for: request)
```

But that only stores the image in the in-memory cache. I would like to make it persist after the app is terminated as well.

I think I might be use something like this:
```
DataLoader.sharedUrlCache.storeCachedResponse( ... )
```
but am not sure how to construct the URLResponse.

Could somebody point me in the right direction?
Thanks

**Comment by kean** [comment]
Hi,

Have you tried storing response in `URLCache`? I believe there are some (HTTP caching) rules associated with it. I haven't worked with it in a while, I don't quite remember what those are.

If you need more control over caching, you can always switch to a built-in custom [`disk cache`](https://github.com/kean/Nuke#aggressive-lru-disk-cache).
