### ISSUE TITLE
Nuke and Moya

### ISSUE THREAD

**Issue by TarekSalama** [kean/Nuke#362]
So I am using Moya which depends on Alamofire and it seems that there is a conflict between Alamofire and Nuke (Invalid redeclaration of Unfairlock).

I tried installing Nuke as an Alamofire plugin but I got this

```
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 5.1.0, ~> 5.0)

  In Podfile:
    Moya was resolved to 14.0.0, which depends on
      Moya/Core (= 14.0.0) was resolved to 14.0.0, which depends on
        Alamofire (~> 5.0)

    Nuke-Alamofire-Plugin was resolved to 0.1.0, which depends on
      Alamofire (~> 2.0)
```

Is there a way to use Nuke with Moya?

**Comment by kean** [comment]
I'm not sure there is a conflict, Nuke isn't declaring or using Unfairlock. However, there might be. problem with requirements. You are using a very old version of Nuke-Alamofire-Plugin. It requires Alamofire ~>2.0. Typically I would suggest to upgrade, but the latest version hasn't been updated to support Alamofire 5.0 yet. It should be a trivial change to update it, PRs are welcome. 

As a workaround, I would suggest dropping https://github.com/kean/Nuke-Alamofire-Plugin/blob/master/Source/DataLoader.swift file directly into your project without using a package manager.

**Comment by kean** [comment]
I updated Alamofire plugin to use Nuke 9 and Alamofire 5.
