### ISSUE TITLE
Usage with Struct 

### ISSUE THREAD

**Issue by LoopingLouieX** [kean/Nuke#363]
I've the following scenario:
A struct like this:
```
struct Sample{
    let name: String
    let image: ???
}
```
and later I want to use it:
`Sample(name: "Max", image: Nuke.loadImage(with: url, into: imageView))`

Is it possible to declare Nuke in a struct ?
How can I achieve this ?
Thanks!

**Comment by kean** [comment]
Hey, could you please clarify what you are trying to achieve?

**Comment by LoopingLouieX** [comment]
Well, I want to know if there's a possibility to declare Nuke in a struct like UIImage or String as example.
So in the construct above I wanted to show that I can use it in that way:
`struct Sample{
    let name: String
    let image: UIImage
}`
and use it with: Sample(name: "Max", image: UIImage(data: url ))
But with this way I use the default UIImage to display pictures.
Instead of using UIImage I want to use Nuke.
But how do I need to write my code in the above example that I can define Nuke in the struct and use it later with "Nuke.loadImage(with: url, into: imageView)" ?

**Comment by kean** [comment]
I see, there is no built-in synchronous APIs, since typically you want to avoid those. I would encourage you to look for a solution which doesn't involve the use of the synchronous APIs first.

However, if you do need a synchronous API, you can use an approach similar to this one with semaphores:

```swift
extension Future {

    /// Waits for the future's result. The current thread blocks until the result
    /// is received.
    ///
    /// - note: This methods waits for the completion on the private dispatch
    /// queue so it's safe to call it from any thread. But avoid blocking the
    /// main thread!
    public func wait() -> Result {
        let semaphore = DispatchSemaphore(value: 0)
        observe(on: waitQueue).on(completion: {
            semaphore.signal()
        })
        semaphore.wait()
        return result! // Must have result at this point
    }
}

private let waitQueue = DispatchQueue(label: "com.github.kean.future.wait-queue", attributes: .concurrent)
```

You are going to need to extend `ImagePipeline` with a synchronous API.
