### ISSUE TITLE
Load Base64 data to Disk Or Memory Cache

### ISSUE THREAD

**Issue by pravin955** [kean/Nuke#366]
Hi, I am getting a base64 data from a URL. I have manually converted this data into an image file. Now, trying to save this converted file into the Memory or Disk cache. Could you please assist me to achieve this saving part via Nuke.

**Comment by kean** [comment]
Hi, you can set up [custom disk cache](https://github.com/kean/Nuke#aggressive-lru-disk-cache) and store image data there.

The "storing" part is going to look somewhat like this.

```swift
let cache: DataCache
let request: ImageRequest
let key = ImagePipeline.shared.cacheKey(for request: request)
cache.storeData(data, forKey: key)
```

**Comment by pravin955** [comment]
Hi Kean

Thanks for your guidance. Its worked for me

1. Is there any way to store image into to memory cache 
2. I want to know is there a way to store into custom data cache as an image instead of data format.
3. Is there a expose api to check for the image is available in data cache or image cache

**Comment by kean** [comment]
Please refer to README

**Comment by pravin955** [comment]
Hi Kean
I am not clear how to load prebundled or Assets Image into given image view using the following Nuke Method 
loadImage(with: request, options: options, into: cell.countryImageView)

In load request i am giving the local image name as url.

It will great help if you could share an snippet of code to achieve this because i verified the readme document but i am unable to achieve it.
Thanks

**Comment by kean** [comment]
- If you are images are included directly in the bundle (which is rare these days), you can access files directly:

```swift
guard let url = Bundle.main.url(forResource: "image", withExtension: "jpeg") else { return }
Nuke.loadImage(with: url, options: options, into: cell.imageView)
```

- If your images are included in xcassets catalog, you are out of luck as it doesn't provide direct access fo files
