### ISSUE TITLE
BRAVO on Swift Package Manager

### ISSUE THREAD

**Issue by smhk** [kean/Nuke#367]
This is INCREDIBLE - can only say, thank you so much!

![Screen Shot 2020-05-17 at 1 36 53 PM](https://user-images.githubusercontent.com/3938526/82156899-c09d8180-9843-11ea-8e58-75f856a1773f.png)

Wow!!  Thanks!!  So well done.

Totally awesome.

**Comment by kean** [comment]
I'm glad you are excited, I can't tell for sure what WTF means though 😅

**Comment by smhk** [comment]
LOL !  just means "AMAZING - TOO GOOD TO BE TRUE!" in this case!  thanks again !!

Need a Nuke tip jar

**Comment by kean** [comment]
Haha, that's nice to hear. Yeah, I'm supporting Swift Package Manager across all of my frameworks.

> Need a Nuke tip jar
There is https://github.com/sponsors/kean,

**Comment by smhk** [comment]
great, say is there a **one-off** (paypal?) tip jar?  Our corporate account - I was not able to make a recurring ...

**Comment by kean** [comment]
I think what you can do is add yourself as a sponsor and cancel the subscription. Let me see whether I could set-up a tip jar as well.
