### ISSUE TITLE
How to download original image

### ISSUE THREAD

**Issue by Koosj** [kean/Nuke#376]
When using `loadImage` with `ImageRequest` loaded images has been down sized.

eg. 1080x1440 -> 540x720 (progressive JPEG)

```
private let pipeline = ImagePipeline {
    $0.isProgressiveDecodingEnabled = true
}

var options = ImageLoadingOptions()
options.pipeline = pipeline
options.transition = .fadeIn(duration: 0.25)
        
let imageRequest = ImageRequest(url: url, processors: [_ProgressiveBlurImageProcessor()], priority: .veryHigh) //url images size is 1080x1440

loadImage(with: imageRequest, options: options, into: imageView, progress: { (res, a, b) in
    print("\(a), \(b)")
}) { (result) in
    if let image = try? result.get().image {
        print("final image, size is \(image.size)") // file image, size is (540.0, 720.0)
    }
}
```

**Comment by kean** [comment]
Hi, @Koosj. By default, the decoded images are created with a `scale` set to match the scale of the display. When you print [`image.size`](https://developer.apple.com/documentation/uikit/uiimage/1624105-size), you are printing size in logical points, not pixels. 1080 pixels equal 530 points on 2x screens.
