### ISSUE TITLE
Image Size issue

### ISSUE THREAD

**Issue by manojkraftly** [kean/Nuke#380]
How can i get image after completion

**Comment by kean** [comment]
Please clarify your question and update the title.

**Comment by manojkraftly** [comment]
I need to get actual image size after uploading image using lazy loading...

cell.bannerImgView.sd_setImage(with: url, placeholderImage: nil, options: [], completed: { (downloadedImage, error, cache, url) in
                   // Like this downloadedImage
}

**Comment by kean** [comment]
`cell.bannerImgView.sd_setImage` – this is SDWebImage code, please make sure you are posting to the correct repo. Nuke `loadImage(into:)` APIs also have a `completion` closure argument where you can get the result of the download.

```swift
Nuke.loadImage(with: url, into: view, completion: { result in
     // switch over result
))

**Comment by manojkraftly** [comment]
How can i can get size of image using result in this SDK?
