### ISSUE TITLE
Images in wrong position for a couple of ms

### ISSUE THREAD

**Issue by martino-dot** [kean/Nuke#381]
I have a collection view and when I have more than 2 cells the images sometime get in the wrong position upon  loading, but then go to their corresponding cell afterwords. Sometimes they don't go in the right position and you'll see the same two images when they are supposed to be the same image. If you want to see an example of this when the scene loads, [https://youtu.be/Yr1Psj-PJM4](https://youtu.be/Yr1Psj-PJM4). When I have only have two cells the images are fine. If this isn't considered a bug is there any way I can prevent it from happening?

**Comment by kean** [comment]
Hi, could you please provide a sample of your collection view set up?

**Comment by martino-dot** [comment]
Sure! 
```
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "ProfileThumbCell", for: indexPath) as? ProfileThumbCell else { return UICollectionViewCell() }
        let Id: Int? = thumbs[indexPath.row].id
        let myUrl = URL(string: "http://localhost:3000/api/v1/thumbs/\(Id!).json")
        var request = URLRequest(url:myUrl!)
        request.httpMethod = "GET"
        let task = URLSession.shared.dataTask(with: request) { (data: Data?, response: URLResponse?, error: Error?) in
            if error != nil {
                return
            }
            
            do {
                let json = try JSONSerialization.jsonObject(with: data!, options: .mutableContainers) as? NSDictionary
                if let parseJSON = json {
                    let imageUrl: String? = parseJSON["thumbnail_url"] as? String
                    let Url = URL(string: "http://localhost:3000\(imageUrl!)")
                    DispatchQueue.main.async {
                        Nuke.loadImage(with: Url!, into: cell.thumbnailView)
                    }
                } else {
                    return
                }
            } catch {
                print(error)
                }
        }
        task.resume()
        return cell
    }
```

**Comment by kean** [comment]
There are some things you need to fix in your initial request that goes via `URLSession.shared.dataTask`.

Collection view cells are [reusable](https://developer.apple.com/documentation/uikit/uicollectionview). You need to add a mechanism that will keep track of your data tasks and make sure the completion doesn't update the reused cells that are no longer associated with the `indexPath` they were originally associated with. You can do that in many different ways, I'm can't help with that.
