### ISSUE TITLE
Loading multiple images into UIImage array

### ISSUE THREAD

**Issue by al3xios** [kean/Nuke#387]
Hi, thank you for creating such a powerful library!

I have a use case for this I can't find any existing issue for.

I am trying to load from multiple image URLs into UIImages for a slideshow and not sure how to best approach this. I tried with the loadImage(into: UIImageView..) and this works but I would like to handle the changing of the image myself.

I looked at the preheater and ImageRequest but don't think I'm on the right track. How can I best utilise the caching from Nuke to retrieve a collection of UIImages?

**Comment by kean** [comment]
Hi, @al3xios. This is the type of thing reactive frameworks are good at. Nuke has Combine ([ImagePublisher](https://github.com/kean/ImagePublisher)) and RxSwift ([RxNuke](https://github.com/kean/RxNuke)) integration just for that. Here is an example in Combine:

```swift
let iconImage = pipeline.imagePublisher(with: iconUrl)
let iconSelectedImage = pipeline.imagePublisher(with: iconSelectedUrl)

cancellable = iconImage.combineLatest(iconSelectedImage)
    .sink(receiveCompletion: { _ in /* Ignore errors */ },
          receiveValue: { icon, iconSelected in
            button.isHidden = false
            button.setImage(icon.image, for: .normal)
            button.setImage(iconSelected.image, for: .selected)
         })
```
