### ISSUE TITLE
nk_setImageWithURL not available on tvOS UIImageView

### ISSUE THREAD

**Issue by bassrock** [kean/Nuke#39]
nk_setImageWithURL is not working with tvOS UIImageView. The only method that actually shows up on it is the nk_targetSize(). I think it has to do with the where clause on the extension, but am not sure.

**Comment by kean** [comment]
I haven't made it available, because it's not tested on tvOS yet. See ImageLoadingViewExtensions.swift

**Comment by bassrock** [comment]
Good news tested it with my app. just need to add || os(tvOS) to the same iOS one in ImageLoadingViewExtensions.swift

**Comment by kean** [comment]
closed by dd752bdfc71dac0ad17304d65365f0db439ffb92
