### ISSUE TITLE
Inconsistent memory results

### ISSUE THREAD

**Issue by mralj** [kean/Nuke#390]
Hi,

Firstly I want to disclose that I am not iOS dev, and I have 0 experience developing iOS apps - so it is highly likely I am making some huge mistakes  & wrong assumptions.

What I wanted to do is to create wrapper for Nuke so that it can be used in [React-Native](https://reactnative.dev) projects.

In order to create wrapper for smth. like _image displaying component_ one must basically create `UIView`, I decided to go with solution which subclasses `UIImageView`. 

Here is my _work in progress_ solution:

```
class NukeView : UIImageView {
    var pipeline = ImagePipeline.shared
        
    override init(image: UIImage?) {
        super.init(image: image)
        self.pipeline = setupNukePipeline()
    }
    
    private func downloadImageAndDisplayIt (imageUrl: URL) {
        let request = ImageRequest(
            url:imageUrl,
            processors: [ImageProcessors.Resize(size: CGSize(width: 50, height: 50))],
            priority: .high
        )
        
        self.pipeline.loadImage(with: request,
                                completion: { result in
                                    if case .success(let imageResponse) = result {
                                        self.image = imageResponse.image

                                    }
        })
    }
    
    private func setupNukePipeline() -> ImagePipeline {
        
        return ImagePipeline {
            $0.dataCacheOptions.storedItems = [.finalImage]
        }
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    
    @objc var url: String = "" {
        didSet {
            if !url.isEmpty {
                downloadImageAndDisplayIt(imageUrl: URL(string: url)!)
            }
            
        }
    }

}
```

#### Image downsampling 
What troubles me is image downsampling part, if I am not mistaken, only thing I have to do, in order for image to be downsampled is to add this line `processors: [ImageProcessors.Resize(size: CGSize(width: 50, height: 50))],` to `ImageRequest`.

By adding this line Images will be downsampled immediately. And assuming following scenario:
1. I am sending from server image `1500 x 1500 `
2. My UIImageView _size_ is only `10 x 10`
3. I am downsampling to image which is `50 x 50`

Memory used for this image will be  `50 x 50 x 3` bytes(assuming 8 bits per RGB).

If I don't add this line, then memory used will be `1500 x 1500 x 3`.

Are my assumptions correct ? 

#### Xcode tests

I tried to test my _predictions_ via XCode, but I am getting some strange results. 
I am displaying 100 images, all of them pretty large, downsampling them to `50 x 50` per image into _container_ which is `10 x 10` (per image).

**1. Xcode memory report**

What I noticed is no matter if have `processors: [ImageProcessors.Resize(size: CGSize(width: 50, height: 50))],`  or not Xcode Memory report (displayed in Debug navigator) is pretty same - it peaks around 120MB and then uses ~110MB.  

But according [to this](https://developer.apple.com/forums/thread/52186) Xcode memory report isn't reliable way to measure actual memory usage

**2. Xcode memory graph**

After that I have exported `.memgaph` file and results were bit different

1. No downsampling version:

> Physical footprint:         97.5M
> Physical footprint (peak):  384.5M

1.1 No downsampling version, 2nd run

> Physical footprint:         104.1M
> Physical footprint (peak):  242.6M

2. Downsampling version
> Physical footprint:         105.0M
> Physical footprint (peak):  127.3M

2.2 Send run was completely same as 1st run

Even though difference in _peak_ memory is pretty big, still Physical footprint is pretty much the same - not sure if this is expected or not 🤷‍♂️

**3. Instruments > Allocations**

Finally here I saw some big (and expected) differences.

1. No downsampling version used ~ 700MB
2. Downsampling version user ~ 40MB

**4. Logging image size**

Final test was logging _image size_, which I have calculated as follows:

```
completion: { result in
                        if case .success(let image) = result {
                                 self.image = image.image
                                  
                                  let imageRef = self.image!.cgImage!
                                  let size =  imageRef.bytesPerRow * imageRef.height
                      }
```

And I have noticed big and expected differences in `size`.

### Finally, Question:

What is most accurate method to profile memory for displaying images ? 

Sorry for long post :) 
But I want to do this right way and hopefully understand as best I can what's happening "behind the scenes" especially because this is first time I am doing any iOS dev.

**Comment by lalkrishna** [comment]
why you getting shared instance of Pipeline and created anotherone in setupNukePipeline?

**Comment by kean** [comment]
Hey, there isn't much that Nuke is doing that might affect memory usage and thus there isn't much you can tweak in the framework.

- In general, yes, you always need to downsample images manually. You can use `ImageProcessors.Resize` to do that. In some cases, the impact is going to be dramatic.
- There are also some `ImageCache` (memory cache) options you might want to tweak to reduce total limits. However, the default limits should work fine for most apps.
- You might want to play with a number of concurrent processing/decoding operations by reducing/increasing maximum concurrent operation count on queue in `ImagePipeline.Configuration`. Again, the defaults should be fine for most apps.

As long as you downsample, I wouldn't worry too much about memory usage unless you are experiencing serious memory usage issues. Remember that while downsampling is great, it's even better to that processing on the server and save both bandwidth and processing power.

I haven't done any in depth memory profiling in a while so I can't answer your final question.

**Comment by mralj** [comment]
> why you getting shared instance of Pipeline and created anotherone in setupNukePipeline?

Error on my part :( 



> Hey, there isn't much that Nuke is doing that might affect memory usage and thus there isn't much you can tweak in the framework.
> 
> * In general, yes, you always need to downsample images manually. You can use `ImageProcessors.Resize` to do that. In some cases, the impact is going to be dramatic.
> * There are also some `ImageCache` (memory cache) options you might want to tweak to reduce total limits. However, the default limits should work fine for most apps.
> * You might want to play with a number of concurrent processing/decoding operations by reducing/increasing maximum concurrent operation count on queue in `ImagePipeline.Configuration`. Again, the defaults should be fine for most apps.
> 
> As long as you downsample, I wouldn't worry too much about memory usage unless you are experiencing serious memory usage issues. Remember that while downsampling is great, it's even better to that processing on the server and save both bandwidth and processing power.
> 
> I haven't done any in depth memory profiling in a while so I can't answer your final question.

Thank you very much for taking your time to answer my questions :) I'll be closing this issue!
