### ISSUE TITLE
Is there possibility to get image from local cached OR device memory after kill app

### ISSUE THREAD

**Issue by manojkraftly** [kean/Nuke#393]
First time url request will call and next time i need to load image from local cached every time, Right now tho library worked only for session then how we will manage it?

**Comment by manojkraftly** [comment]
I am waiting for response to save image in local storage then, I can get it again after end of current session.

**Comment by kean** [comment]
Please refer to the documentation on caching https://github.com/kean/Nuke#caching. There is also a respective guide you can find referenced there.

**Comment by manojkraftly** [comment]
I checked, can you please guide me which code i need to use to get image from cache after kill app.
