### ISSUE TITLE
Support for Xcode 12 and Swift 5.3

### ISSUE THREAD

**Issue by vsgopinath** [kean/Nuke#394]
@kean  I tried to build Nuke in Swift 5.3 version. The project failed to build. Can you please confirm the version which will work on Swift 5.3?

Thanks in advance
Gopi

**Comment by kean** [comment]
The latest version supports 5.3.

> The project failed to build. 

Hi, would you mind sharing an error message?

**Comment by vsgopinath** [comment]
Yeah, this is the error message:

![image](https://user-images.githubusercontent.com/31533327/93790169-05db2100-fc33-11ea-8af9-646c8f9ba2bf.png)

**Comment by kean** [comment]
Can you share an error message from xcodebuild please?

**Comment by vsgopinath** [comment]
The xcode build error has one more issue like this with another library which causes the failure and it cannot able to show the Nuke failure there. What do you suggest ?

**Comment by vsgopinath** [comment]
The issue is not related to Nuke. It is due to Carthage build for Xcode 12. Closing this issue
