### ISSUE TITLE
Loading images from Base64 JSON encoded data

### ISSUE THREAD

**Issue by ristkof** [kean/Nuke#397]
It would be great to get some feedback on this, since I can not find any good documentation.

A server I have to download images from encodes them in a JSON dictionary as ascii64 encoded strings. I am trying to use Nuke to download also those images, and have my first success. This is the code:

```
struct Base64Image: Codable {
    let base64image: String
}

struct Base64Decoding: ImageDecoding {
    func decode(_ data: Data) -> ImageContainer? {
        guard let base64 = try? JSONDecoder().decode(Base64Image.self, from: data)
        else { return nil }
        guard let base64Data = Data(base64Encoded: base64.base64image) else { return nil }
        guard let pi = PlatformImage(data: base64Data) else { return nil }
        
        return ImageContainer(image: pi,
                                type: ImageType(base64Data),
                                isPreview: false,
                                data: nil,
                                userInfo: [:])
    }
}

extension ImageLoadingOptions {
    static var base64Pipeline: ImagePipeline {
        var configuration = ImagePipeline.shared.configuration
        configuration.makeImageDecoder = { ctxt -> ImageDecoding? in
            Base64Decoding()
        }
        return ImagePipeline(configuration: configuration)
    }

    static var base64: ImageLoadingOptions {
        var options = ImageLoadingOptions.shared
        options.pipeline = base64Pipeline
        return options
    }
}
```

Then I load Images with ```Nuke.loadImage(with: url, options: ImageLoadingOptions.base64, into: imageView)```.

That seems to work. Is this a correct way to extend Nuke? Am I overlooking something? My understanding is that Nuke will cache the original data, maybe I should give the decoded data to the ImageContainer and it will cache that?

Any feedback appreciated!

**Comment by kean** [comment]
Hi @ristkof.

This looks like a perfectly fine way to extend Nuke.

For more information please refer to https://github.com/kean/Nuke/blob/master/Documentation/Guides/image-formats.md#image-decoding-infrastructure. I'm going to review this doc and see maybe I could improve it in some way. I think some inline documentation can be helpful.

Now, regarding `data` in `ImageContainer`. You can find some info in inline docs:

```swift
    /// Contains the original image `data`, but only if the decoder decides to
    /// attach it to the image.
    ///
    /// The default decoder (`ImageDecoders.Default`) attaches data to GIFs to
    /// allow to display them using a rendering engine of your choice.
    ///
    /// - note: The `data`, along with the image container itself gets stored in the memory
    /// cache.
    public var data: Data?
```

The short answer is, you only need to pass `data` to `ImageContainer` during decoding if you need it for rendering and you want it to be stored in memory cache `ImageCaching`. In your case, you don't need to pass it.

**Comment by ristkof** [comment]
I have a crash sometimes in Nuke, in symbol $s4Nuke13ImagePipelineC20imageDataLoadingTask33_64FA2D582EFB9D605832F3421CEE67ADLL_7context010didReceiveE08response3logyAA0G0Cy10Foundation0E0V_So13NSURLResponseCSgtAC5ErrorOG_AC08OriginalbeG7ContextAELLCAnpA3LogCtFTf4nnnnnd_n + 600

<img width="1276" alt="afbeelding" src="https://user-images.githubusercontent.com/211518/99499950-f13cb000-2979-11eb-9429-beedb671cda7.png">

I have three ideas about what might be going on:

- the base64 decoding has failed and somehow the foundation crashes on the append data call
- some memory corruption has happened due to unrelated code
- some threading issue that I don't see at the moment

Do you maybe have ideas that could shed light on this?

**Comment by kean** [comment]
Hi, @ristkof. Are you able to reproduce it and/or get the assertion message?

If you look at `InlineSlice` [implementation](https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/Darwin/Foundation/Data.swift#L1013), there seems to be at least one assertion:

```swift
assert(endIndex + buffer.count < HalfInt.max)
```

I don't think that Nuke has anything to do with this crash.

**Comment by kean** [comment]
Having said that, `HalfInt` is defined as `Int32` on [modern architectures](https://github.com/apple/swift/blob/887464b7b67d5202bfa7adc4e3f045ff1027a5a7/stdlib/public/Darwin/Foundation/Data.swift#L867). That's 2 GB.

**Comment by ristkof** [comment]
Hi, I can not reproduce it and it occurs infrequently. I will assume it's memory corruption elsewhere for now until I have further insights. Thanks for taking a look!

**Comment by kean** [comment]
It might be, sometimes memory issues lead to crashes in unexpected places.
