### ISSUE TITLE
Could you add example to readme how to load image from Cache using only CacheKey?

### ISSUE THREAD

**Issue by lolgear** [kean/Nuke#398]
Hi!

I've found that you use `CacheKey: Hashable` in your implementation in Cache.
Your examples use only URL that is not only one "hashable" type.

In my case, I could use only parts of URL ( `URLQueryItems` ), because of... legacy.
But since you define `CacheKey: Hashable`, it should be easy enough to use `[URLQueryItem]` as a key.

Could you add example for that?

**Comment by kean** [comment]
Hey, these are some legacy parts of the `ImageRequest` API. I'm planning to deprecate them and replace with something on the `ImagePipeline.Configuration` level.

What is the use case you are implementing?

**Comment by lolgear** [comment]
@kean I have a proxy server ( well, actually, it is our cross-platform library ) which do the following:

1. provides gateway url.
2. provides hash of images.

So, I even don't need full url to identify image, I only need hash.

Typical request to library would be:
```
gatewayURL/hash?width=<width>&height=<height>.
```

**Comment by kean** [comment]
To modify the URL, you can use `filteredURL` in `ImageRequestOptions`:

```swift
let request = ImageRequest(
    url: URL(string: "http://example.com/image.jpeg?token=123")!,
    options: ImageRequestOptions(
        filteredURL: "http://example.com/image.jpeg"
    )
)
```

You can replace the `filteredURL` with anything you'd like. It's used specifically for caching purposes. For example, in case you pass an authorization token as a query parameter, this is how you can remove it. I think it should also work for your scenario, assuming that you know the hash before you load the image.
