### ISSUE TITLE
How redownload image in the most optimal way?

### ISSUE THREAD

**Issue by Volodymyr-Ukraine** [kean/Nuke#401]
In my application the user can take photo, and upload it to server, and receive url with image. But the url may be the same as in the previous version of the photo. 
Is any mechanism to renew the photo in the cache?
I found
```
Nuke.Cache.shared.removeAll ()
Nuke.DataLoader.sharedUrlCache.removeAllCachedResponses ()
```
But this is not optimal way as for me. 
May be will be enough
```
Nuke.Cache.shared.removeCachedResponse (for: URLRequest)
Nuke.DataLoader.sharedUrlCache.removeCachedResponse (for: URLRequest)
```
But is any better way for direct command "anyway download this image again and refresh it in cache"?

**Comment by Volodymyr-Ukraine** [comment]
Update: found my info obsolete - I can't call `Nuke.Cache`, so will be  `Nuke.DataLoader.sharedUrlCache.removeCachedResponse(for: )`
enough for refreshing?

**Comment by kean** [comment]
Hi, it depends on the configuration. By default, there is an image cache `ImageCache.shared`, and the URL cache that you mentioned.

There is a similar feature request to add an option to add images in all these cache layers https://github.com/kean/Nuke/issues/385. I'm going to consider adding better tools for manipulating caches. Now you need to update all layers that you provide manually.

**Comment by kean** [comment]
I'm adding two new APIs in Nuke 9.2 to cover this use case.

You can remove an image from all cache layers:

```swift
let request = ImageRequest(url: url)
pipeline.removeCachedImage(for: request)
```

Another option is to keep the image in cache, but instruct the pipeline to ignore the cached data:

```swift
let request = ImageRequest(url: url, cachePolicy: .reloadIgnoringCacheData)
Nuke.loadImage(with: request, into: imageView)
```

> If you are manually constucting a `URLRequest`, make sure to update the respective cache policy.
