### ISSUE TITLE
Could not build Objective-C module 'MyFramework'

### ISSUE THREAD

**Issue by funzin** [kean/Nuke#415]
## Overview
When I tried to use Nuke in Carthage, I got the following error and it did not work
<img width="283" alt="Screen Shot 2020-12-01 at 19 22 17" src="https://user-images.githubusercontent.com/12893657/100728782-52996000-340b-11eb-9720-5c01a8acd9a4.png">

## Project Structure
The structure of the project depends on the `MyFramework.framework` to Nuke, as shown below

```
Sample App Target
  |_MyFramework.framework
    |_Nuke.framework
```

## Detailed Description
When I use Nuke in MyFramework and implement `func nuke_display(image: PlatformImage?)` and try to import `MyFramework`with AppTarget, I get the following error
<img width="283" alt="Screen Shot 2020-12-01 at 19 22 17" src="https://user-images.githubusercontent.com/12893657/100728782-52996000-340b-11eb-9720-5c01a8acd9a4.png">

```ImageLoadable.swift
import UIKit
import Nuke

public protocol ImageLoadable: Nuke_ImageDisplaying where Self: UIView {
    func loadImage(_ urlString: String?)
}

extension ImageLoadable {
    public func loadImage(_ urlString: String?) {
        guard let urlString = urlString,
              let url = URL(string: urlString) else { return }
        let request = ImageRequest(url: url)
        let options = ImageLoadingOptions(transition: .fadeIn(duration: 0.3))

        Nuke.loadImage(with: request, options: options, into: self)
    }
}

extension UIImageView: ImageLoadable {}

// Swift Compiler Error
// - DerivedData/Sample-detklhcpidarzmbytxqisnymktif/Build/Products/Debug-iphonesimulator/MyFramework.framework/Headers/MyFramework-Swift.h:191:9: Module 'Nuke' not foundI
// - could not build Objective-C module 'MyFramework'
extension UIButton: ImageLoadable {
    public func nuke_display(image: PlatformImage?) {
        setImage(image, for: .normal)
    }
}

```

Here is a validated project
[Sample.zip](https://github.com/kean/Nuke/files/5621883/Sample.zip)

https://github.com/kean/Nuke/blob/c96ff9fcaa78ee2774002d96aedbee5cf5306d57/Sources/ImageViewExtensions.swift#L27-L30
Perhaps the behavior is due to the `@objc` attribute of this file.

**Comment by kean** [comment]
Hi @funzin.

Thanks for providing a sample project. Nuke is a Swift-only framework. You are currently importing it in [a mixed](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift#overview) Objective-C and Swift framework. My understanding is that this is not supported by the compiler.

To fix this, you need to remove`MyFramework.h` from your framework target.

**Comment by kean** [comment]
As a side note, I noticed that you are embedding Nuke.framework into MyFramework.framework. I would recommend to embed Nuke.framework into the app target instead.

**Comment by funzin** [comment]
Hi @kean 
Thanks for the reply!
After a little more investigation, it looks like this and similar causes
SeeAlso: https://developer.apple.com/forums/thread/650935

>As a side note, I noticed that you are embedding Nuke.framework into MyFramework.framework. This isn't an issue per se, but I would recommend to embed Nuke.framework into the app target instead.

:+1:, I'll try to think of another way.
