### ISSUE TITLE
CGBitmapContextCreate: unsupported parameter combination

### ISSUE THREAD

**Issue by BryanJBryce** [kean/Nuke#416]
This is a new issue for my app after recently updating from the previous version of Nuke.

It appears that this bug has been seen before, but fixed at the time: https://github.com/kean/Nuke/issues/35

>CGBitmapContextCreate: unsupported parameter combination:
 	8 bits/component; integer;
 	24 bits/pixel;
	RGB color space model; kCGImageAlphaNone;
	default byte order;
	6624 bytes/row.
Valid parameters for RGB color space model are:
	16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedLast
	32  bits per pixel,		 10 bits per component,		 kCGImageAlphaNone|kCGImagePixelFormatRGBCIF10
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast|kCGBitmapFloatComponents|kCGImageByteOrder16Little
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast|kCGBitmapFloatComponents|kCGImageByteOrder16Little
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaPremultipliedLast|kCGBitmapFloatComponents
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaNoneSkipLast|kCGBitmapFloatComponents
 See Quartz 2D Programming Guide (available online) for more information.

**Comment by kean** [comment]
Hey, yeah, I slightly [changed](https://github.com/kean/Nuke/pull/408/files#diff-229d280b05b49507e0cfb10141e9317063cdf72ed6678b8b72ccd826f11eff46R783) the way the decompression/resizing works. It's based on the CGContext solution from [here](https://nshipster.com/image-resizing/). It needed to be changed to support extended color spaces, grayscale images with only 1 component, 8 bbp images, etc.

Unlike https://github.com/kean/Nuke/issues/35, there is now a fallback to the default parameter combination. So the only issue is the console error message. All the images should still get resized and displayed properly as it was in the previous Nuke versions.

I'm going to see whether it's possible to check the parameter combination before attempting to create the context or to suppress the warning message in some other way. If it's not, I think I'll probably just switch to `UIGraphicsImageRenderer` on iOS.

**Comment by BryanJBryce** [comment]
It feels like there's a performance hit along with the console log, but that could be the log itself and wouldn't manifest in a production build, I haven't tested that.

**Comment by kean** [comment]
Address in 9.2.1.
