### ISSUE TITLE
Can't use this framework on Objective-c project

### ISSUE THREAD

**Issue by daliborristic883** [kean/Nuke#418]
I tried to install this framework on Objective-c with using Cocoapods.
After install it, I can't build project.
![Screenshot 2020-12-14 at 8 33 55 AM](https://user-images.githubusercontent.com/65829381/102052920-34f2d000-3de7-11eb-8c1c-5f76ed98f752.png)

Please help me. 

![Screenshot 2020-12-14 at 8 29 40 AM](https://user-images.githubusercontent.com/65829381/102052641-a54d2180-3de6-11eb-8071-f52d8051af86.png)
![Screenshot 2020-12-14 at 8 30 09 AM](https://user-images.githubusercontent.com/65829381/102052650-aa11d580-3de6-11eb-8ff1-3c71d5e28bfc.png)
![Screenshot 2020-12-14 at 8 30 27 AM](https://user-images.githubusercontent.com/65829381/102052654-ab430280-3de6-11eb-95c0-fd8931097c72.png)

**Comment by kean** [comment]
Hi, @daliborristic883. Nuke is a Swift framework which can't be used from Objective-C. If you'd still like to use it, you can create and Objective-C compatible Swift wrapper.
