### ISSUE TITLE
[Question] Nuke 9 on iOS 10

### ISSUE THREAD

**Issue by superpeteblaze** [kean/Nuke#419]
Hi,

I see that Nuke 9 is iOS 11+. However, we would ideally like to use the latest version in a framework project which targets iOS 10. I've tested including the source files from Nuke 9 in the framework (which deploys to iOS 10), and it builds and runs in a sample app.

Is it possible I am missing something, or, is it possible to use Nuke 9 in a project targeting iOS 10.

Any help appreciated. Thanks!

**Comment by kean** [comment]
There is only around 0.5% of iOS 10 users. I would prefer to stick with iOS 11+. More reasons to drop support for older versions.

**Comment by superpeteblaze** [comment]
Great, thanks for getting back to me @kean. Sure, I understand the reasoning for dropping support, but it's good to know that there is nothing in particular preventing it's usage on iOS 10. 👍🏽
