### ISSUE TITLE
Building Nuke with Carthage fails

### ISSUE THREAD

**Issue by 1oo7** [kean/Nuke#420]
On Xcode 12, building Nuke with Carthage often fails for me. I get, 

> xcodebuild timed out while trying to read NukeDemo.xcodeproj 😭

I might recommend not building NukeDemo as part of the Carthage process.

**Comment by 1oo7** [comment]
I think I figured out why this is happening. 

NukeDemo has several remote SwiftPackage dependencies: alamofire, gifu, nuke, and swiftsvg. These all have to go through "package resolution" when Carthage is building the project. Still not sure why Carthage is trying to build the app, though. 

I made an issue about this on Carthage's github as well. Hope this helps.

**Comment by kean** [comment]
Thanks. I'm not sure why it's trying to build it. Are you using the latest Carthage version?

**Comment by 1oo7** [comment]
@kean Yeah 0.36.

**Comment by kean** [comment]
I believe this issues has to do with your local setup. I don't think there is anything I can do from my side.

There is a known issue with Carthage and Xcode 12. Please make sure to use the workaround https://github.com/Carthage/Carthage/issues/3019. It won't compile without it.

**Comment by 1oo7** [comment]
That's not the problem. It's because NukeDemo tries to build whenever we do a Carthage bootstrap. Please make Nuke not build its Demo app by default!
