### ISSUE TITLE
Add ImageRequestConvertible conformance to String 

### ISSUE THREAD

**Issue by jonfabris** [kean/Nuke#421]
`Nuke.loadImage(with: img, into: mainImage)`

produces error:
Argument type 'String' does not conform to expected type 'ImageRequestConvertible'

Swift 5

**Comment by kean** [comment]
`ImageRequestConvertible` was introduced just recently in [Nuke 9.2.0](https://github.com/kean/Nuke/releases/tag/9.2.0). One of the things I had in mind is to add `String` support too. I wasn't clear to me how to deal with `String` -> `URL` conversion failures at this point. PRs are welcome.

**Comment by kean** [comment]
Added in `cacheType` [Nuke 10 Beta](https://github.com/kean/Nuke/releases/tag/10.0.0-beta.1).
