### ISSUE TITLE
Getting black color background when resize an image to a circle

### ISSUE THREAD

**Issue by www0488** [kean/Nuke#422]
Hello guys!

Xcode version: Version 12.2
Nuke Version: 9.2.1

Just like the title says, I'm trying to load an Image with circle format and when the image was loaded, the background display as black color. I tried to change the UIImageView background color to clear but it still display as black. Does anyone have the same issue, how can I solve it?

This is how the image looks like after resize it to circle(for example):
<img width="72" alt="Screen Shot 2020-12-21 at 02 07 44" src="https://user-images.githubusercontent.com/11156233/102729644-d28f5780-4331-11eb-8444-2cb9f1315968.png">

Here is my code for loading an image and then resize to circle:
`

        let request = ImageRequest(url: URL(string: mDoctorList[indexPath.row].profileImage)!, processors: [
            ImageProcessors.Circle()
        ])

        Nuke.loadImage(with: request, into: cell.mImageView)
        cell.imageView?.backgroundColor = .clear
`

**Comment by kean** [comment]
Hey, which platform are you running on? Could you please provide the input image?

**Comment by kean** [comment]
Fixed in [Nuke 9.2.3](https://github.com/kean/Nuke/releases/tag/9.2.3)
