### ISSUE TITLE
Rounded Corners Regression with 9.2.1

### ISSUE THREAD

**Issue by michaelnisi** [kean/Nuke#424]
Starting with 9.2.1 there seems to be a regression regarding rounded corners that leads to a black background.

![image](https://user-images.githubusercontent.com/108903/103369781-546a4800-4acb-11eb-9be9-3d83c4085015.jpeg)

**Comment by michaelnisi** [comment]
☝️ Resulting from these Processors:

```swift
  private static func makeProcessors(id: FKImage.ID) -> [ImageProcessing] {
    guard !id.isClean else {
      return [ImageProcessors.Resize(size: id.size, crop: true)]
    }
    
    let r: CGFloat = id.size.width <= 100 ? 3 : 6
    
    return [ImageProcessors.Composition([
      ImageProcessors.Resize(size: id.size, crop: true),
      ImageProcessors.RoundedCorners(radius: r, border: .none)
    ])]
  }
```

**Comment by kean** [comment]
Right, it's Nuke [9.2.0](https://github.com/kean/Nuke/releases/tag/9.2.0) regression. I switch to Core Graphics in order to support macOS, didn't catch this in my testing I think because I was testing in dark mode. I think it has to do with CGContext not being cleared after initialization.

**Comment by michaelnisi** [comment]
9.2.0 is fine though.

**Comment by kean** [comment]
Really? Hmm, alright I need to investigate.

**Comment by kean** [comment]
Fixed https://github.com/kean/Nuke/releases/tag/9.2.3
