### ISSUE TITLE
Load failures for missing remote images get stuck in the cache

### ISSUE THREAD

**Issue by NathanLoring** [kean/Nuke#430]
Hi, thanks for Nuke. I ran into an issue, but I'm not sure whether it's a bug or not...

If Nuke tries to load an image that doesn't exist on the server, and the server returns a 404 (with payload), then the image load fails as expected. But then after placing the image on the server, subsequent loads also fail with statusCodeUnacceptable.

I worked around that behavior by checking DataLoader.sharedUrlCache before the load request is made, to see if a cached response already exists for the url, and has a HTTP failure code. If so, then I make the ImageRequest using a CachePolicy of reloadIgnoringCacheData. If I use that approach then the image loads successfully after it is placed on the server.

That workaround seems a little hacky and potentially fragile. Is there a better way? Or maybe the cached failure behavior can be fixed in Nuke?

**Comment by kean** [comment]
My understanding is that `URLSession` only stores cached responses for successful requests. One of [the criteria](https://developer.apple.com/documentation/foundation/urlsessiondatadelegate/1411612-urlsession) is the following: 

> - The request was successful (with a status code in the 200–299 range).

Maybe it's the documentation issue. If that's the case, the delegate method that I linked should allow you to customize the caching behavior. You'll need to provide a custom `DataLoader` and we can then think how this use case can be covered by the built-in one.

**Comment by kean** [comment]
Hey, @NathanLoring. I'm going to close this for lack of response, it's been a month. My assumption that is has to do with a misconfigured HTTP cache policy on the server. If you think there is an issue in Nuke, please feel free to add more detail and reopen.
