### ISSUE TITLE
Native Progressive WebP Support with Nuke (iOS 14+)

### ISSUE THREAD

**Issue by usman-wayfair** [kean/Nuke#432]
Hello, We would like to start using `Nuke` as our Remote Image Library provider. After doing the evaluation, we have following questions

- Our default image format is WebP. I understand Nuke provides WebP support with the wrapper `Nuke-WebP-Plugin`, however, I am not sure if this wrapper is currently compatible with SwiftPackageManager. We are currently migrating our dependencies away from Carthage to SwiftPM and not having the SPM support from this plugin dependency could be a roadblock for us.
- I read a comment for Native WebP support for iOS 14 on the Github page, it says `WebP is now supported natively. Nuke currently only supports baseline WebP (no progressive WebP support).` 
  - Does it mean if the app only targets iOS >= 14.0, we don't need that plugin at all? 
  - Also the distinction you made for baseline vs progressive WebP, do we get progressive WebP with this plugin?

We are looking forward to start using Nuke and get all the performance gains it provides. If you want to share some more information around WebP support , please do.

Thanks

**Comment by kean** [comment]
Nuke WebP Plugin has [an open PR](https://github.com/ryokosuge/Nuke-WebP-Plugin/pull/52) with Swift Package Manager support. Hopefully, @ryokosuge will merge it soon. 

> Does it mean if the app only targets iOS >= 14.0, we don't need that plugin at all?

Yes

> Also the distinction you made for baseline vs progressive WebP, do we get progressive WebP with this plugin?

The plugin supports progressive decoding.

I'm assuming the native decoding on iOS 14 also support progressive decoding. So adding support for it should only be a matter of updating the following part in the `ImageDecoders.Default`:

```swift
public init?(partiallyDownloadedData data: Data, context: ImageDecodingContext) {
    // Determined whether the image supports progressive decoding or not
    // (only proressive JPEG is allowed for now, but you can add support
    // for other formats by implementing your own decoder).
    guard ImageType(data) == .jpeg,
        ImageProperties.JPEG(data)?.isProgressive == true else {
        return nil
    }
}
```

**Comment by usman-wayfair** [comment]
Thanks for your prompt response. That's really exciting!

**Comment by MussaCharles** [comment]
Hi @kean , Thanks for such a great tool. 
I am following up on the previous discussions as  it seems like [SPM PR](https://github.com/ryokosuge/Nuke-WebP-Plugin/pull/52) was never merged and ```Nuke-WebP-Plugin``` repo is lagging far behind the latest Nuke version. 

Is natively supporting a little bit lower iOS versions  at least the minimum version which  latest Nuke version support  in the priority? 

Currently I am conditionally using Nuke for  iOS 14+ and fall back to use SDWebImage for lower iOS versions because all of our images are webP. It would be great to have support for lower versions as well if possible.

**Comment by kean** [comment]
I suggest for now forking the `Nuke-WebP-Plugin`. I don't have write access to this repo. I can contact the author and see what we can do to continue maintaining it.

**Comment by MussaCharles** [comment]
> I suggest for now forking the `Nuke-WebP-Plugin`. I don't have write access to this repo. I can contact the author and see what we can do to continue maintaining it.

Thanks for clarification :)  I will try to fork the repo as you have suggested  in the future.

**Comment by kean** [comment]
I'm going to close it because I have no plans to address it myself. If someone form the community is willing to take in on, contributions are welcome.
