### ISSUE TITLE
PhotosKit support

### ISSUE THREAD

**Issue by CPiersigilli** [kean/Nuke#434]

**Comment by kean** [comment]
Hi, are you referring to [PhotosKit](https://developer.apple.com/documentation/photokit)? PRs are welcome.

**Comment by CPiersigilli** [comment]
Yes. I would use Nuke for download image from photolibrary with PHAsset and not with NSURL.
For example:
`Nuke.loadImage(with: asset, into: cell.imageView)`

**Comment by kean** [comment]
Nuke currently requires you to work with `URL`. I believe I have a task somewhere in background to lift this limitation and allow other types of resource identifiers to be used.

Unlike AssetsLibrary, PhotosKit doesn't support URLs. However, you always come up with a custom URL scheme. [Here is](https://github.com/kean/DFImageManager/blob/master/Pod/Source/PhotosKit/NSURL%2BDFPhotosKit.m) how it was designed in DFImageManager.

**Comment by kean** [comment]
You can also attach any arbitrary options to `ImageRequest`:

```struct
public struct ImageRequestOptions {
   <...>

   /// Custom info passed alongside the request.
    public var userInfo: [AnyHashable: Any]
}
```

**Comment by CPiersigilli** [comment]
I tried using the code indicated in the link you provided, but I can't get it to work.
I tried with the code I found at the [link](https://stackoverflow.com/questions/38183613/how-to-get-url-for-a-phasset) and at the [link,](https://stackoverflow.com/questions/33858270/getting-url-for-phasset) but I can't use it, because I can't process a data structure that returns the URL to me.
Hope you can modify Nuke and especially FetchImage for use with SwiftUI to be able to use it with PHAsset.
Thank you.

**Comment by kean** [comment]
I'm sorry if I wasn't clear, yes, Nuke doesn't currently support PhotosKit. I outlined some of the potential options to add support for it.

**Comment by CPiersigilli** [comment]
Thank you for your time and I hope that update your Nuke (FetchImage) for support PhotoKit.

**Comment by d4rkd3v1l** [comment]
We're currently using the "url approach" to load PHAssets. This worked pretty well for us, until we discovered, that it completely fails for iCloud Photos :-(
Seems like urls are only returned, once the photos have been downloaded by iOS, which takes some time, may fail, etc.

Any clues or ideas on how to make this work? Or is there a timeline for PhotoKit support in Nuke? 
Thanks in advance.

**Comment by kean** [comment]
Hey. What is a scenario in which to want to use Nuke with PhotosKit?

It's generally best not to wrap its APIs. For example, when you request an image, it can return a thumbnail by calling a completion closure synchronously. This is designed to make sure there are no empty cells during scrolling. There is no way to accurately model this behavior.

The feature is in the backlog, but I'm reluctant to implement it because of the issue outlined above.

As a user, you can wrap PhotosKit API by implementing a custom DataLoader and passing PHAsset in the request userInfo.
