### ISSUE TITLE
Image Fetch Type

### ISSUE THREAD

**Issue by usman-wayfair** [kean/Nuke#435]
Hi Kean, 

I think someone has asked the same question before like an year back about if we can figure out in the completion block of loadImage call if the image is served from disk cache, memory cache or fetched from the server. This feature is also very important for us so I was just wondering if there is a way to get the information. The current Remote Image Library we use supply a enum in the completion block with cases like ImageResultTypeMemoryCache, ImageResultTypeDiskCache, ImageresultTypeDownload etc.

If the similar functionality like above is not available, is it possible to query the daia dictionary we have in both of our cache levels and if not found, then only make the loadImage call?

So like creating a request with the URL
`let request = ImageRequest(url: url)`

 and checking data stores like
 
```

 if let image = ImageCache.shared[request] { //Memory Cache
          //use image
} else if let image =  DataLoader.sharedUrlCache.cachedResponse(for: request.urlRequest) { //Disk Cache
        // use image
} else { //go to server
      // do loadImage
}

```

will that work?

**Comment by kean** [comment]
Could you please clarify what are the scenarios in which you need to know the source of the image? There might other options to implement them.

**Comment by usman-wayfair** [comment]
Sure, we have tracing around image fetch operation, we assign an attribute to our trace based on the source of the image.This helps us track and analyze the performance of each of the image fetch type separately and we can compare and contrast performance. Also helps us analyze the impact of any CDN optimization exclusively in the server trace. If there is no distinction, its really hard to get the real picture. e.g. memory cache is normally in microseconds so that mess up(in a good way) the overall median of our operation.

**Comment by kean** [comment]
Nuke had [performance metrics API](https://github.com/kean/Nuke/tree/7.4#performance-metrics-beta) in version 7. They seemed a bit over-complicated at the time, so they were replaced with [signposts](https://github.com/kean/Nuke/pull/250). Not as powerful, but much simpler and integrated into Xcode.

I have a ticket in the [backlog](https://trello.com/b/Us4rHryT/nuke) to add more logging options into Nuke. I wouldn't mind adding both the ability to check the image source and to add some new form of advanced performance metrics.

**Comment by usman-wayfair** [comment]
Thanks for the update! Is that something you are targeting in the near future? Also, is it possible to query the cache stores(mem and disk) with the url(key) to see if they exists before even making the loadImage. I was going over the docs and found this about loadImage `returns: An image task or `nil` if the image was found in the memory cache`. So based on this, can we differentiate between memory cache fetch and server fetch? if yes, how about the disk cache? I understand we have 2 types of Disk Caches, I was just wondering if it would be easier to query the key if we use `LRU Disk Cache` and dont use `HTTP Disk Cache`. 

Thanks for your help and support.

**Comment by kean** [comment]
>  So based on this, can we differentiate between memory cache fetch and server fetch?

Yes, you can differentiate between memory cache fetches this way.

Regarding disk cache, there are ways to check if the data existing for both types of caches.

For `DataCache`, you can do

```swift
let cache: DataCache // keep a reference somewhere
let pipeline = ImagePipeline {
    $0.dataCache = cache
}

let request = ImageRequest(...)
let key = pipeline.cacheKey(for: request, item: .originalImageData)
// Or .finalImage if you enabled storage for processed images

// Fetch data
cache[key] != nil
```

The downside is that it will require performing actual cache lookup.

**Comment by kean** [comment]
> Is that something you are targeting in the near future?

I don't really have any strict priorities, so I can focus on performance metrics next. This sounds interesting and can be a good differentiating factor between Nuke and other frameworks.

**Comment by usman-wayfair** [comment]
Thank you so much, appreciate your help. We are really excited about making this transition to Nuke. I will discuss the above solution with the team and will let you know if its working as expected. Let us know whenever you are done making this change. Thanks

**Comment by kean** [comment]
`cacheType`, and many other caching improvements, are available in [Nuke 10 Beta](https://github.com/kean/Nuke/releases/tag/10.0.0-beta.1).
