### ISSUE TITLE
could not find module 'Nuke' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by leechoohyoung** [kean/Nuke#436]
mac: m1 MacBook Pro
xcode: Version 12.4 (12D4e)
cocoapods: 1.10.1

I can install Nuke via cocoapods, and there's no error when I build my app project for Real Devices.
But, when I build for simulator, meet error.

**could not find module 'Nuke' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator**

any help?

**Comment by leechoohyoung** [comment]
ok, I found solution. 
As a result, the error not caused by Nuke.
The error produced by build setting from cocoapods.

Below is the solution.

1. open your app .workspace via xcode
2. in project navigatior, select Pods project
3. in editor, select Pods project
4. select Build Settings
5. Find 'Excluded Architectures'
6. add arm64 for Debug
7. done

clean & build & run

**Comment by kean** [comment]
Thanks for documenting the solution 👍

**Comment by JoeFerrucci** [comment]
Getting this error after installing Nuke via Packages. On Xcode 15.2 M2-chip.
Xcode asks me if I want to build using Rosetta.

**Comment by wazawoo** [comment]
+1. getting this issue via spm. very annoying.
