### ISSUE TITLE
Cannot fetch Nuke as a dependency on XCode 12

### ISSUE THREAD

**Issue by Bawenang** [kean/Nuke#437]
I'm trying to upgrade from XCode 11 to XCode 12, and when I tried updating the Carthage, it failed at opening NukeDemo.xcodeproj. When I manually opened the NukeDemo project, it fetched the `gifu` dependency endlessly from SPM. The completion indicator is stuck at 1/5 of the circle.

PS: I have succeeded adding Nuke using SPM so it's actually fine for me. But I still don't get how to fix the Carthage.

**Comment by kean** [comment]
Hi, yeah Carthage is not working great with Xcode 12. Please refer to their documentation, there is nothing that Nuke isn't doing.
