### ISSUE TITLE
How can I access non public images on AWS s3 using nuke?

### ISSUE THREAD

**Issue by majdkhadra** [kean/Nuke#438]
I need to access non public images in s3 bucket, is there a way to do so using nuke?

**Comment by kean** [comment]
Please see similar question https://github.com/kean/Nuke/issues/331

**Comment by majdkhadra** [comment]
So I would have to make a request? Currently I'm using nuke.loadimage without making a URL request, so I would have to make a URL request before I use nuke.loadimage? Thank you for your help, I am new to nuke :)

**Comment by majdkhadra** [comment]
Just a clarification, currently I'm using public s3 buckets with the nuke.loadimage ^^

**Comment by majdkhadra** [comment]
Or is there anywhere with a full example of this?

**Comment by kean** [comment]
Closing as dupe (see https://github.com/kean/Nuke/issues/331).
