### ISSUE TITLE
Toggling Signpost Enablement After Pipeline Creation

### ISSUE THREAD

**Issue by mlarandeau-wayfair** [kean/Nuke#443]
I'm not sure if this is intentional or not, but currently, signposts for any given pipeline can only be enabled if `ImagePipeline.Configuration.isSignpostLoggingEnabled` is set to `true` before a pipeline is created.  If the pipeline was created with signposts enabled, then toggling `ImagePipeline.Configuration.isSignpostLoggingEnabled` on and off also enables and disables the signposts for that pipeline as expected.

This seems to happen because a pipeline's `OSLog` is [set at initialization](https://github.com/kean/Nuke/blob/e2eb1b7b82983c6f6a2df496e850406a78cdef05/Sources/ImagePipeline.swift#L64) based on the current setting of `ImagePipeline.Configuration.isSignpostLoggingEnabled`.  When `false`, `log` is set to `disabled`.  The [internal signpost wrapper functions](https://github.com/kean/Nuke/blob/182bc69e2397fc1ad5bacb8d1f8fc0a7113beca6/Sources/Internal/Log.swift#L8) check `ImagePipeline.Configuration.isSignpostLoggingEnabled` every time it is called.  Therefore, if the supplied log is not `disabled`, then whether or not the signpost is recorded is dependent on `ImagePipeline.Configuration.isSignpostLoggingEnabled`.  However, if the log is `disabled`, it doesn't matter what `ImagePipeline.Configuration.isSignpostLoggingEnabled` is set to, the signpost will never be recorded.

So my question is, can the signpost support be updated so that signpost logging can be turned on or off at any time?  We ran into this issue while trying to implement an internal development toggle to allow us to enable or disable signposts without having to rebuild the app.

**Comment by kean** [comment]
That's a good idea. As a workaround, you can re-create the pipeline at any time.

```swit
ImagePipeline.shared = ImagePipeline()
```

**Comment by kean** [comment]
Updated in [Nuke 9.4.0](https://github.com/kean/Nuke/releases/tag/9.4.0)
