### ISSUE TITLE
Nuke is trusted by $1B+ apps.

### ISSUE THREAD

**Issue by RyPoints** [kean/Nuke#445]
The ReadMe says "Nuke is trusted by $1B+ apps."

Could you provide info on these apps.  Specifically, I have been using Nuke for around 7 years now, know it is great for what it does, and am working with a bank that has a generic distrust of libraries.  If you have info you can share on big financial services or other well-known apps using Nuke, please share.

**Comment by kean** [comment]
Hey,

I'm not collecting these stats, but it would be interesting to try and gather a list of some of the top apps using Nuke. I'm sure there are going to be at least some.

What I'm referring to in README is Clubhouse, which technically does have $1B+ evaluation at the moment. Someone did a quick peak into their app bundle and found the list of [frameworks they use](https://news.knowledia.com/US/en/articles/what-s-in-the-clubhouse-ios-app-denken-medium-997aacf5268653236bf053f45dd64faddc3aa82d). So I thought it would be fun to mention in on README. I know this is a strong statement, maybe I should reevaluate having it there.

**Comment by RyPoints** [comment]
Okay, thanks for the info and grats on creating an image library that professional software uses.  Dunno if Clubhouse makes a difference to them one way or the other, but will bring it up.

**Comment by kean** [comment]
I ultimately decided to remove it.
