### ISSUE TITLE
v.9.5.0. Image download not work.

### ISSUE THREAD

**Issue by nexusskv** [kean/Nuke#447]
Hi,

I tried to use your library with use manual but without successful.
1.
Nuke.loadImage(with: url, into: view) 
-> In result: All imageviews are empty

2.
let options = ImageLoadingOptions(placeholder:  UIImage(named: "noimage"),
                                          transition:   .fadeIn(duration: 0.33))
Nuke.loadImage(with: url, options: options, into: view) 
-> In result: All imageviews are empty

3. Nuke.loadImage(with: url, options: options, into: view, progress: { response, _, _ in
                if let image = response?.container.image {
                    // bannerImageView.image is nil here
                    view.image = image
                }
                
            }) { (result: Result<ImageResponse, ImagePipeline.Error>) in
                switch result {
                    case let .failure(error):
                        print(error.localizedDescription)
                        view.image = ImageLoadingOptions.shared.failureImage

                    case let .success(response):
                        view.image = response.image
                }
            }
-> In result: All imageviews are empty. The operation couldn’t be completed. (Nuke.ImagePipeline.Error error 0.)

What I did wrong ?

Also I tried to use 
ImagePipeline.shared.loadImage(with: loadRequest,
                                                  progress: { response, _, _ in
                                                    completion(response?.image)
                                                  }, completion: { result in
                                                    // Display the final image
                                                  })
It worked but I need to use options too.

**Comment by kean** [comment]
Hi, @nexusskv. Could you please provide a sample where I can reproduce the issue?

**Comment by kean** [comment]
I'm going to close it. Please feel free to re-open with more details
