### ISSUE TITLE
question about the disposed state 

### ISSUE THREAD

**Issue by zhangchao4706** [kean/Nuke#451]
Thank you for creating such a brilliant framework. And I think I draw lots of inspiration from the code.

I have a question that if a new ImageTask starts and it can subscribe to an existing task which was just disposed (either completed or cancelled).  In that case,  the return subscription is nil. It seems that no event will be published and the ImageTask will never has a callback. 

I am an newbie in swift language, and not sure if I understand it correctly.

**Comment by kean** [comment]
It should not be possible. When an internal task is terminated (completed or canceled), it is immediately removed from the pool. Did you encounter a situation where it doesn't happen?

**Comment by zhangchao4706** [comment]
No, I did not encounter the case, just thought of it when reading the code. 

I think you are right. It will not happen because relevant operations is synchronized with the serial queue.

Thanks for your reply

**Comment by kean** [comment]
Yes, the entire system is synchronized on a serial queue to ensure thread-safety. And you can find the relevant code in `TaskPool`:

```swift
if let task = map[key] {
    return task.publisher
}
let task = make()
map[key] = task
task.onDisposed = { [weak self] in
    self?.map[key] = nil
}
return task.publisher
```
