### ISSUE TITLE
CG raster Data grow

### ISSUE THREAD

**Issue by Dmitry-rman** [kean/Nuke#452]
Hi, Kean, I have a problem with memory managament.
My app have collection view with cells and I load images.
There are VM: CG raster data grow in my app.

<img width="1384" alt="Снимок экрана 2021-04-16 в 11 57 59" src="https://user-images.githubusercontent.com/4433263/114976184-c23a5400-9eaf-11eb-879b-cedda0cec4fe.png">

Why is XCode memory about one level, but instruments allocations is grow in my case?

I tried use size to download images and without it.
`
var request:ImageRequest = ImageRequest.init(urlRequest: imageUrlRequest, priority: .high)
            if let imageName = placeHolderImageName{
              ImageLoadingOptions.shared.placeholder = UIImage(named: imageName)
            }
            if let imageName = failureImageName{
              ImageLoadingOptions.shared.failureImage = UIImage(named: imageName)
            }
            
            DDLogDebug("disk cache usage \(DataLoader.sharedUrlCache.currentDiskUsage)")
            DDLogDebug("memory cache usage \(DataLoader.sharedUrlCache.currentMemoryUsage)")
            
            let size = targetSize ?? imageView.bounds.size
            request.processors = [ImageProcessors.Resize(size: size, contentMode: contentMode)]
   
            Nuke.loadImage(with: request, into: self.imageView) { (result) in
                completion?(true)
            }
`

I tried disable cache - no results. Allocations is grow...
` 
       DataLoader.sharedUrlCache.diskCapacity = 0
        DataLoader.sharedUrlCache.memoryCapacity = 0
        
//       let pipeline = ImagePipeline {
//          let dataCache = try? DataCache(name: "ru.activebc.portalda.datacache")
//          dataCache?.sizeLimit = 0
//          $0.dataCache = dataCache
//          $0.isProgressiveDecodingEnabled = false
//
//            // If `true`, the pipeline will store all of the progressively generated previews
//            // in the memory cache. All of the previews have `isPreview` flag set to `true`.
//            $0.isStoringPreviewsInMemoryCache = false
//        }
//        ImagePipeline.shared = pipeline
//
`

<img width="1154" alt="Снимок экрана 2021-04-16 в 12 05 07" src="https://user-images.githubusercontent.com/4433263/114976193-c5cddb00-9eaf-11eb-8d6c-411b34b0887d.png">

Do you can help me to resolve this issue?
Thanks.

**Comment by kean** [comment]
It most likely is the memory cache. See https://kean.blog/nuke/guides/caching#lru-memory-cache

**Comment by Dmitry-rman** [comment]
Thanks, Alexandr, I solved it. The "VM blocks" reserve memory by iOS virtual machine. So, we can see Allocations grow. Hope, it don't influence for app performance and memory management.
