### ISSUE TITLE
Xcode 12.5 Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

### ISSUE THREAD

**Issue by gabors** [kean/Nuke#454]
Nuke/Sources/DataLoader.swift:247:32: 

Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

**Comment by kean** [comment]
Fixed in https://github.com/kean/Nuke/releases/tag/9.5.1

**Comment by gabors** [comment]
Thanks so much. Спасибо 🤟
