### ISSUE TITLE
Big image flipped

### ISSUE THREAD

**Issue by Leeeeerich** [kean/Nuke#468]
Hey! I use a pipeline for download image:

```
ImagePipeline.shared.loadImage(with: URL(string: Paths().getGlobalFilePath(fileName: img.storageKey))!) { r in
                do {
                    let v = UIImage(cgImage: try r.get().image.cgImage!)
                    
                    view.images.append(v)
                } catch {
                    
                }
            }
```

But big files flipping.

For test use [image](https://user-images.githubusercontent.com/26391015/110929055-383b2080-8330-11eb-8d31-8fc517867694.jpg)

Same problem in Picasso for Android: https://github.com/square/picasso/issues/2201

**Comment by kean** [comment]
Some images v an orientation associated with them. `UIImage` keeps track of the orientation. When you initialize the `UIImage` with a `CGImage` (bitmap), the orientation information is lost and it might appear incorrectly when you display it.

**Comment by Leeeeerich** [comment]
Okay, I tried loadData and it good work now. Thanks!
