### ISSUE TITLE
Disk caching of URL redirects

### ISSUE THREAD

**Issue by diegostamigni** [kean/Nuke#475]
Hello!

I was playing with Nuke (9.6.0) (from FechImage [0.4.1] via iOS and SwiftUI) and I came across an issue where if I have a URL A that redirects to URL B for actual image download, then it would not be correctly stored in cache.

Not entirely sure whether is an actual issue or not though: the downloaded image(s) seem to be correctly cached throughout the lifetime of the app, but if I (force) close the app and re-open it, all the images will be re-downloaded again.

Is this an issue? Expected behaviour of the default HTTP URL cache used (I haven't changed/tweaked any config parameters anywhere)? Any way around this?

In my particular scenario, storing in cache both initial URL and the redirected URL would be an acceptable trade-off (disk space usage will be doubled for these, but it's a start at least).

**Comment by diegostamigni** [comment]
Actually, after some more digging in the Nuke internals, this seems to be the expected behaviour as the `ImageCaching` within the (default) pipeline is the LRU in-memory `ImageCache`. 

I guess fair enough then, I can write my own disk caching solution for images 👍 😄

**Comment by kean** [comment]
Nuke has a custom cache built-in, but it's disabled by default. To enable it, follow the respective guide https://kean.blog/nuke/guides/caching.

By default, it uses `URLCache `, which is an HTTP cache so it requires cache control headers to be present to work. I'm not entirely sure how URLSession/URLCache handles redirects. It's best to avoid them if possible.

There are also some massive improvements to the caching infra coming in [Nuke 10](https://github.com/kean/Nuke/pull/461).

**Comment by diegostamigni** [comment]
Nice thanks. Will take a look!

**Comment by diegostamigni** [comment]
Thanks @kean all good. Also, my whole issue was already explained in details here: https://kean.blog/nuke/guides/troubleshooting
