### ISSUE TITLE
How does work ImageProcessors.Resize?

### ISSUE THREAD

**Issue by yunustek** [kean/Nuke#480]
Hi, How does work the ImageProcessors.Resize? 
Does this save us time downloading pictures from the server? Even when I try to download a very large image, does it download it in a small size because I give it a small size, or does it change the size after downloading the original size?

`ImageProcessors.Resize(size: .., contentMode: ..)`

**Comment by kean** [comment]
It resizes the image after downloading it. The resizing should be pretty efficient. Unfortunately, it can't magically fetch the smaller image from the server. If you have a resizing service, you can use it and provide a custom URL.

**Comment by yunustek** [comment]
Ben de bu sekilde dusunmustum fakat bir resize servisi ile url resize edildikten sonra yeni bir url ile daha kucuk boyutlu image indirilebilir diye dusundum. Belki bu sihri yapiyorsunuzdur diye sormak istedim :) Detayli bilgi icin cok tesekkur ederim.
