### ISSUE TITLE
Receiving crash ImageProcessing.swift - Line 582

### ISSUE THREAD

**Issue by sajjadsarkoobi** [kean/Nuke#482]
Hi, 
Recently I'm receiving crashes for these lines:

> ImageProcessing.swift - Line 582
> ImageProcessingExtensions.byAddingRoundedCorners(radius:border:) + 582 

I just trying to make an image circle. It was working well but it is happening these days.

The trace is:

> Crashed: NSOperationQueue 0x1c023de20 (QOS: UNSPECIFIED)
0  libsystem_kernel.dylib         0x184bb92e0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x184d5a288 pthread_kill$VARIANT$mp + 376
2  libsystem_c.dylib              0x184b27d0c abort + 140
3  libsystem_c.dylib              0x184afc000 basename_r + 314
4  CoreGraphics                   0x186c78da8 CGPathCreateWithRoundedRect + 452
5  Nuke                           0x103771e3c ImageProcessingExtensions.byAddingRoundedCorners(radius:border:) + 582 (ImageProcessing.swift:582)
6  Nuke                           0x103775734 specialized ImageProcessing.process(_:context:) + 544 (ImageProcessing.swift:544)
7  Nuke                           0x103771a9c protocol witness for ImageProcessing.process(_:context:) in conformance ImageProcessors.Circle + 32 (<compiler-generated>:32)
8  Nuke                           0x1037901cc partial apply for closure #1 in closure #1 in closure #1 in TaskProcessImage.processImage(_:isCompleted:processor:) + 53 (TaskProcessImage.swift:53)
9  Nuke                           0x10377c5c4 closure #1 in ImageResponse.map(_:) + 185 (ImageTask.swift:185)
10 Nuke                           0x103790220 partial apply for thunk for @callee_guaranteed () -> (@owned ImageResponse?, @error @owned Error) + 24 (<compiler-generated>:24)
11 libswiftObjectiveC.dylib       0x104ff6cec autoreleasepool<A>(invoking:) + 4458835180
12 Nuke                           0x10378fc14 closure #1 in TaskProcessImage.processImage(_:isCompleted:processor:) + 184 (ImageTask.swift:184)
13 Nuke                           0x10376d078 thunk for @escaping @callee_guaranteed () -> () + 20 (<compiler-generated>:20)
14 Foundation                     0x185b5ae88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
15 Foundation                     0x185a9c8d0 -[NSBlockOperation main] + 72
16 Foundation                     0x185a9bcac -[__NSOperationInternal _start:] + 848
17 Foundation                     0x185b5c76c __NSOQSchedule_f + 404
18 libdispatch.dylib              0x184a24a60 _dispatch_client_callout + 16
19 libdispatch.dylib              0x184a2ce94 _dispatch_continuation_pop$VARIANT$mp + 424
20 libdispatch.dylib              0x184a2b7cc _dispatch_async_redirect_invoke$VARIANT$mp + 604
21 libdispatch.dylib              0x184a31cac _dispatch_root_queue_drain + 588
22 libdispatch.dylib              0x184a319fc _dispatch_worker_thread3 + 120
23 libsystem_pthread.dylib        0x184d57fac _pthread_wqthread + 1176
24 libsystem_pthread.dylib        0x184d57b08 start_wqthread + 4

thanks.

**Comment by kean** [comment]
Hey. Is this a release defect or an assertion? Is there an exception message? Can you reproduce it with a certain input? What system are you testing it on? xAre you using the default pipeline configuration?

**Comment by sajjadsarkoobi** [comment]
hey, thanks for your reply,
This is a release ver in AppStore. 

here is the code: 

```
var processors: [ImageProcessing] = []
processors.append(ImageProcessors.Circle())
 processors.append(ImageProcessors.Resize(size: CGSize(width: 25, height: 25)))
 let request = ImageRequest(url: URL(string: imgUrl)!, processors: processors)
            
Nuke.loadImage(with: request, options: options, into: imageContainer) { (result) in
                switch result {
                case .failure(let err):
                    print(err)
                    completionHandler(false)
                    break
                case .success:
                    completionHandler(true)
                    break
                }
}
```

**Comment by kean** [comment]
Thanks. In the meantime, please make sure to update to the latest stable version, [9.6.1](https://github.com/kean/Nuke/releases/tag/9.6.1), and see if it continues.

**Comment by kean** [comment]
Hey, @sajjadsarkoobi. Do you have any updates on this issue?

**Comment by sajjadsarkoobi** [comment]
> Hey, @sajjadsarkoobi. Do you have any updates on this issue?

Hey, thanks for following up, I updated all pods and released a new version, after that, I didn't see any kind of crashes like this up to now.
thanks

**Comment by kean** [comment]
I'm going to close it for now. Feel free to reopen if you see it again.
