### ISSUE TITLE
Nuke 10 cocoapods

### ISSUE THREAD

**Issue by MontakOleg** [kean/Nuke#483]
pod 'Nuke', '~> 10.0' currently can't be installed:

```
[!] CocoaPods could not find compatible versions for pod "Nuke":
  In Podfile:
    Nuke (~> 10.0)

None of your spec sources contain a spec satisfying the dependency: `Nuke (~> 10.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Do you plan to publish Nuke 10 to cocoapods?

**Comment by kean** [comment]
CocoaPods support is deprecated, but you can still install from a tag.

**Comment by MontakOleg** [comment]
Got it, thank you!
Do you think it's a good idea to add this information to docs?

Now docs looks like this, which fails with error above:
```
target '<Your Target Name>' do
    pod 'Nuke', '~> 10.0'
end
```

**Comment by kean** [comment]
Yes, I will update it. Thanks.
