### ISSUE TITLE
Loading image at Tab View with FetchImage instance

### ISSUE THREAD

**Issue by byunsangun** [kean/Nuke#486]
Hi I'm actually newbie of SwiftUI. I'm trying to implement TabView of image with url. If i use Nuke without TabView, it's working well. I think this error is related with my code because when i remove **.onDisappear(perform: image.reset)** this part, it's also working well... But i think it's not good solution.  Can you check my code? Thank you in advance!!

**Nuke Class**
`
struct RemoteImageView: View {
    
    let url: URL
    
    @StateObject private var image = FetchImage()
    
    
    var body: some View {
        ZStack {
            Rectangle().fill(Color.gray)
            image.view?
                .resizable()
        }
        .onAppear() {
            image.load(url)
            print("on Appear called")
        }
        .onChange(of: url) {
            image.load($0)
            print("on changed called")
        }
        .onDisappear() {
            image.reset()
            print("on disappear called")
        }
    }
}

`

**Usage**

```swift
TabView() {
    ForEach(0..<viewModel.photoUrls.count, id:\.self) { index in
        if let parsedUrl = URL(string: viewModel.photoUrls[index]) {
            RemoteImageView(url: parsedUrl)
                .frame(width: 400, height: 200) //FIXME: It should be changed into constant value
                .scaledToFit()
        } else {
             Rectangle()
                 .foregroundColor(.green)
                 .frame(width: 400, height: 200)
        }
     }
}
.tabViewStyle(PageTabViewStyle())
```

**Comment by kean** [comment]
I saw similar reports in other frameworks. It all depends on the view lifecycle of `TabView` subviews – I think it might be broken. I would suggest not calling `reset()` as a workaround.

You can add an option to `RemoteImageView` to configure the "on disappear" behavior the way I [done](https://github.com/kean/NukeUI/blob/1ffc9b5232cd4cbc29b4d12288a85d9290b39d2d/Sources/LazyImage.swift#L238) in `LazyImage`.
