### ISSUE TITLE
Disk caching

### ISSUE THREAD

**Issue by horcs** [kean/Nuke#488]
I have a usecase, when I want to retrieve persisted images from disk cache, while being (temporary) offline, but images are not in mem cache yet.
Current version (10.3) appears to ignore disk cache by using `Nuke.loadImage(with: ` and only checks mem cache.

**Comment by chosa91** [comment]
Caller site: 
https://github.com/kean/Nuke/blob/588de91dda85270eaa4aae4a445a371983c79458/Sources/UI/ImageViewExtensions.swift#L441

…but the `subscript` only touches directly the memory cache:
https://github.com/kean/Nuke/blob/588de91dda85270eaa4aae4a445a371983c79458/Sources/Core/ImagePipelineCache.swift#L27-L38

instead of using this:
https://github.com/kean/Nuke/blob/588de91dda85270eaa4aae4a445a371983c79458/Sources/Core/ImagePipelineCache.swift#L49-L63

@kean Is there any explanation as to why the subscript cannot access the disk cache?

**Comment by kean** [comment]
Hey, @horcs. Please refer to https://kean.blog/nuke/guides/caching and https://kean.blog/nuke/guides/troubleshooting#cached-images-are-not-displaying-offline.

**Comment by kean** [comment]
@chosa91, the idea is that the subscripts are typically fast, and methods can be slow. I can't come up with an example right now, but I saw APIs designed in a similar way. Did you find it confusing? I probably shouldn't have included the subscript in the first place.

**Comment by chosa91** [comment]
A bit confusing, but actually understandable. 
Although, it would be nice and convenient to set this behavior via the `ImageLoadingOptions`

**Comment by kean** [comment]
You can change it using [ImageRequests.Options](https://kean-org.github.io/docs/nuke/reference/10.2.0/ImageRequest_Options/).

**Comment by chosa91** [comment]
Our use-case is to use specific disk storage _(+ disable `NSURLCache`)_ and then if the client cold starts the app we'll provide the assets from the disk storage (and cache it simultaneously in the memory).

Our configuration looks like this:

```swift
extension ImagePipeline.Configuration {
    public static var withDataPersistence: ImagePipeline.Configuration {
        let dataLoader: DataLoader = {
            let config = URLSessionConfiguration.default
            config.urlCache = nil
            return DataLoader(configuration: config)
        }()

        var config = ImagePipeline.Configuration()
        config.dataLoader = dataLoader
        config.dataCache = try? DataCache(path: FileManager.default.document(named: "Images"))
        return config
    }
}

ImagePipeline.shared = ImagePipeline(configuration: .withDataPersistence)
```

Then we just compose the `ImageRequest` and fire the `Nuke.loadImage(with:options:into:completion:)`

**Comment by chosa91** [comment]
Ohh, my bad. As I see the `TaskLoadImage.start()` method does what we exactly want. 
With this in mind, I will re-examine our issue. I'm sorry to bother you

**Comment by kean** [comment]
I'm going to close this. If you have more questions about caching, please refer to the [docs](https://kean.blog/nuke/guides/caching) and feel free to open a new [discussion](https://github.com/kean/Nuke/discussions).
