### ISSUE TITLE
The merge #439 caused a compilation error.

### ISSUE THREAD

**Issue by Sloaix** [kean/Nuke#491]
![WX20210623-162550](https://user-images.githubusercontent.com/2627625/123067942-06b01600-d444-11eb-9ce9-919d2f13e7cb.png)
![WX20210623-162602](https://user-images.githubusercontent.com/2627625/123067964-0b74ca00-d444-11eb-8713-9f2dbcf56fcd.png)
![WX20210623-163015](https://user-images.githubusercontent.com/2627625/123067970-0c0d6080-d444-11eb-8b5a-80e9a46e060d.png)

I rolled back to the 9.3.0-beta.1, previous version of 9.3.0 , everything is fine.😂

my development environment is 

```
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
```

**Comment by Sloaix** [comment]
see this https://github.com/kean/Nuke/pull/439

**Comment by kean** [comment]
It seems to compile ok on my side.

```swift
class AdvancedImageView: NSView, Nuke_ImageDisplaying {
    @objc func nuke_display(image: PlatformImage?, data: Data?) {

    }
}

let view = AdvancedImageView()
Nuke.loadImage(with: Test.request, into: view)
```

If you cast to `Nuke_ImageDisplaying`, it will fail because it needs to be `Nuke_ImageDisplaying & NSObject` on macOS.

**Comment by Sloaix** [comment]
> It seems to compile ok on my side.
> 
> ```swift
> class AdvancedImageView: NSView, Nuke_ImageDisplaying {
>     @objc func nuke_display(image: PlatformImage?, data: Data?) {
> 
>     }
> }
> 
> let view = AdvancedImageView()
> Nuke.loadImage(with: Test.request, into: view)
> ```
> 
> If you cast to `Nuke_ImageDisplaying`, it will fail because it needs to be `Nuke_ImageDisplaying & NSObject` on macOS.

This is my first time to use Nuke. Thanks for the answer, it worked。: )
