### ISSUE TITLE
Outdated Podspec version

### ISSUE THREAD

**Issue by aaron-williamson-kr** [kean/Nuke#493]
When will the podspec be updated to the latest version? It's still sitting at 9.5.1

**Comment by kean** [comment]
Nuke 10.x only supports Swift Package Manager. Is it an option for you to use it to install Nuke?

**Comment by shmakovigor** [comment]
There are tons of projects which use cocoapods manager and can not switch to SPM for many reasons, so would be great if Nuke 10.x support cocoapods.

**Comment by muukii** [comment]
I noted a memo to install Nuke with CocoaPods locally.
It might help you.
https://www.notion.so/muukii/Nuke-9-5-1-has-dropped-CocoaPods-support-and-how-to-install-from-CocoaPods-from-now-e2920926b2be4c26b0dd863810536835

**Comment by haifengkao** [comment]
@aaron-williamson-kr  I have pushed a pod for nuke
https://github.com/haifengkao/NukePod

**Comment by kean** [comment]
I pushed the latest version in the trunk. CocoaPods support is deprecated and might not be available in the future. I would suggest to plan migration to SPM.
