### ISSUE TITLE
Video support for LazyImage or FetchImage

### ISSUE THREAD

**Issue by larryonoff** [kean/Nuke#495]
Hello!

I didn't find any ways to load data (generally I need video support) with LazyImage or FetchImage. I think that the first step is adding loadData support to FetchImage.

FYI. My video url doesn't have file extension like https://kean.github.io/videos/cat_video.mp4.

What's your thoughts?

**Comment by kean** [comment]
`FetchImage` and `LazyImage` already support video. You can see how it's implemented in https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/ImageView.swift#L158 and https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/VideoImageDecoder.swift.

The general idea is to:
1. Register a custom image decoder that for video files would generate a preview image and attach data to the image container (`ImageContainer`)
2. When `FetchImage` finishes loading it gives you an `ImageContainer` with you data attached
3. Use data to play the content

GIF rendering is implemented in a very similar way.

**Comment by larryonoff** [comment]
> `FetchImage` and `LazyImage` already support video. You can see how it's implemented in https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/ImageView.swift#L158 and https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/VideoImageDecoder.swift.
> 
> The general idea is to:
> 
> 1. Register a custom image decoder that for video files would generate a preview image and attach data to the image container (`ImageContainer`)
> 2. When `FetchImage` finishes loading it gives you an `ImageContainer` with you data attached
> 3. Use data to play the content
> 
> GIF rendering is implemented in a very similar way.

This's what I've expected. I've tried to load the following [video](https://instagram.fnic3-1.fna.fbcdn.net/v/t50.2886-16/217705605_3054706868187745_7853867499596545336_n.mp4?_nc_ht=instagram.fnic3-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=nmzSSMoRmd4AX8hqW1U&edm=AABBvjUBAAAA&ccb=7-4&oe=60F2CCE6&oh=7a5251c7ff78dcd22b31867d90b2740d&_nc_sid=83d603), but it doesn't work.

I wasn't able to find how Nuke detects when load data (video) instead of image. It never tried to load data.

**Comment by kean** [comment]
Here is how it does it https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/VideoImageDecoder.swift#L80. It's based on "magic numbers". It might be incomplete.

**Comment by larryonoff** [comment]
> Here is how it does it https://github.com/kean/NukeUI/blob/b3f04143bd137c7403aedb0a39498decd63faf63/Sources/VideoImageDecoder.swift#L80. It's based on "magic numbers". It might be incomplete.

thanks! I need to analyse this.

**Comment by larryonoff** [comment]
@kean looking at Nuke source code now. 

`LazyImageView` executes `ImageDecoders.Video.register()` on `isVideoRenderingEnabled = true`, see https://github.com/kean/NukeUI/blob/main/Sources/LazyImageView.swift#L254

`LazyImage` doesn't execute `ImageDecoders.Video.register()`, so [ImageDecoding](https://github.com/kean/Nuke/blob/master/Sources/Core/ImageDecoding.swift#L315) unable to decode video -> so data is not loaded for LazyImage

**Comment by kean** [comment]
Right, that's my bad. I changed `LazyImage` in one of the recent releases so that it no longer uses `LazyImageView` under the hood by forgot to move the decoder registration.

**Comment by kean** [comment]
Should be fixed in https://github.com/kean/NukeUI/releases/tag/0.6.4
