### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by marlowcharite** [kean/Nuke#5]
I believe that carthage support for this will help you get more users. A lot of devs, like me, have a project that does not allow for the use of cocoapods.

**Comment by kean** [comment]
going to be available soon https://twitter.com/RuiAAPeres/status/645009646630117376

**Comment by marlowcharite** [comment]
Sounds good. Thanks @kean

**Comment by kean** [comment]
Done 44e5e3b39757ab00b8d34c9b29798b931c1bd995. Carthage available in [Nuke 0.2.2](https://github.com/kean/Nuke/releases/tag/0.2.2)
