### ISSUE TITLE
iOS 13 - Failed to create an image from the image data (Nuke.ImagePipeline.Error decodingFailed)

### ISSUE THREAD

**Issue by kamil3** [kean/Nuke#501]
Hi,
I've got `decodingFailed` error in iOS 13.7 when loading image from url: `https://d3eyekaxnlzkcu.cloudfront.net/uploads/media/60f134b4b678830007839c88/d3JFY3FTSGFROGZrdEpkcHAyYVNpdz09`
In iOS 14 it's working fine.
I'm using `9.1.2` Nuke version, however I've tried the latest one and it's the same result.
```swift
let options = ImageLoadingOptions(
    placeholder: placeholder,
    transition: .fadeIn(duration: 0.33)
)
Nuke.loadImage(
    with: url,
    options: options,
    into: imageView,
    progress: nil,
    completion: { result in
        switch result {
        case .failure(let error):
            debugPrint(error)
        case .success:
            //
        }
    }
)
```

**Comment by kean** [comment]
Native WebP decoding was added in iOS 14. If you need to support earlier versions, you can install https://github.com/ryokosuge/Nuke-WebP-Plugin.
