### ISSUE TITLE
Error -17102 decompressing image -- possibly corrupt

### ISSUE THREAD

**Issue by pselok** [kean/Nuke#519]
Images with grayscale colour space appears as black when applying resize processor.

Examples:
https://cdn-st4.rtr-vesti.ru/vh/pictures/vhdr/318/444/7.jpg
https://cdn-st2.rtr-vesti.ru/vh/pictures/vhdr/318/444/5.jpg
https://cdn-st2.rtr-vesti.ru/vh/pictures/vhdr/318/446/5.jpg

without resize processor:
<img width="360" alt="Untouched" src="https://user-images.githubusercontent.com/16443790/142732829-a124aad6-adb3-48dc-bf7e-896bc4567fe7.jpg">

with resize processor:
<img width="360" alt="Resized" src="https://user-images.githubusercontent.com/16443790/142732824-797cabd0-7809-4a1c-bd63-f4e13500acc6.jpg">

console output:
<img width="360" alt="Screenshot 2021-11-20 at 18 54 24" src="https://user-images.githubusercontent.com/16443790/142732776-702de42a-9b6a-4a14-9fc1-09bc3a3f6960.png">

**Comment by pselok** [comment]
No issues with iOS 13.6, maybe it's something with new "preparingForDisplay"?

**Comment by kean** [comment]
Looks like it. I noticed a [difference](https://github.com/kean/Nuke/pull/512/files#diff-8729714d8d1a39f4a5feec83acb1f401827020b757798e1659959923522fcd95R32) in grayscale handling when adding `prepareForDisplay` support, but didn't pay close attention to it. It looks like this combination of parameters that `prepareForDIsplay` produces is not supported by CGContext. I suggest reverting to [Nuke 10.4.1](https://github.com/kean/Nuke/releases/tag/10.4.1) for now. If you have any suggestions how to fix it, I'd appreciate it.

**Comment by pselok** [comment]
Will revert for now, thanks. Currently, i have no idea how to fix it :)

**Comment by timonus** [comment]
I've been thinking of submitting a radar for this bug per [this comment](https://github.com/kean/Nuke/commit/6b8c0683aae35dc2b3c3ab71b8337ba4a64ef0cd#commitcomment-71199780), I whipped up a [sample project](https://www.dropbox.com/s/fkgvridkq8k0pe5/ImageDecodeRadarTestApp-ZMlP.zip?dl=0) and can't seem to repro the issue. Lemme know if you have any tips on what's causing this!

![IMG_3C2C61494E81-1](https://user-images.githubusercontent.com/522951/166073335-cda0a476-3586-4544-bd47-137768f63b16.jpeg)
