### ISSUE TITLE
Detect and download updated image

### ISSUE THREAD

**Issue by andreaslindahl** [kean/Nuke#52]
I'm having trouble getting Nuke to detect images that's been updated on the server - the cached image is used instead. It seems like Nuke doesn't check if the file has been updated on the server by default? Is there a way to force this functionality?

**Comment by kean** [comment]
Nuke uses NSURLSession's cache management without any modifications. It's most probably that your server sets a really long `max-age` in cache headers - cache responses are not revalidated until they are expired.

There at least two ways to adjust that behaviour:
1. Server should set a `max-age` value depending on how often do you want responses to be revalidated.
2. Server should set `must-revalidate` in `Cache-Control` header to force image to be revalidated each time it's requested.

There are also some ways to control it programatically. I've actually written an [entire guide](http://kean.github.io/blog/programming/2016/01/26/image-caching.html#references) on this topic. You might want to check it out.

**Comment by andreaslindahl** [comment]
I'm using Amazon S3 for storing files. The Etag header is set, but the max-age header is not set (if max-age is what Amazon refers to as Expiry date below):

Last Modified:	Wed Feb 03 08:00:12 GMT+100 2016
ETag:	8069ea92d9e4aff1db9d6ccb38899fdc
Expiry Date:	None

**Comment by kean** [comment]
`Cache-Control:must-revalidate` yeah that seems alright.

**Comment by kean** [comment]
Nuke also has a memory cache for fast access to processed images. It doesn't have any revalidation mechanisms (yet, it will in Nuke 2), because it gets cleared frequently. It might add some confusion, because images would not get revalidated if they are present in memory cache. I doubt that it's a problem, but just so you know.

**Comment by andreaslindahl** [comment]
After upgrading to 2.0 I'm having trouble getting updated images, even though I'm using NSURLRequestCachePolicy.ReloadIgnoringCacheData:

let cachePolicy : NSURLRequestCachePolicy = .ReloadIgnoringCacheData
let request = ImageRequest(URLRequest: NSURLRequest(URL: imageUrl, cachePolicy: cachePolicy, timeoutInterval: 360))
self.nk_setImageWith(request, placeholder: UIImage(named: "placeholder"))

Worked fine in the previous version.

**Comment by kean** [comment]
There a separate options for controlling memory cache now:

```swift
/** Defines constants that can be used to modify the way ImageManager interacts with the memory cache.
 */
public enum ImageRequestMemoryCachePolicy {
    /** Return memory cached image corresponding the request. If there is no existing image in the memory cache, the image manager continues with the request.
     */
    case ReturnCachedImageElseLoad
    
    /** Reload using ignoring memory cached images. Doesn't affect on-disk caching.
     */
    case ReloadIgnoringCachedImage
}
```

```swift
public struct ImageRequest {

/** The request memory cachce policy. Default value is .ReturnCachedImageElseLoad.
 */
public var memoryCachePolicy = ImageRequestMemoryCachePolicy.ReturnCachedImageElseLoad

}
```

**Comment by kean** [comment]
`NSURLRequestCachePolicy` no longer affects memory cache in any way, only `NSURLSessionTask`.

**Comment by andreaslindahl** [comment]
Oh, ok. thanks!

**Comment by kean** [comment]
That's pretty much the only change in the behaviour in Nuke 2. Everything else should work as expected.

**Comment by andreaslindahl** [comment]
I'm still having trouble getting updated images unless I set the memoryCachePolicy to ReloadIgnoringCachedImage however. It seems like the Etag is ignored. I have verified that the ETag header is updated when the image is updated on the server and the Cache-Control header is set to "must-revalidate" but this doesn't seem to matter - the old, cached image is used instead.

The Last-Modified header is also updated, by the way.

Setting the memoryCachePolicy to ReloadIgnoringCachedImage solves the problem, of course, but since this bypasses the cache entirely it doesn't seem like a good solution...

**Comment by andreaslindahl** [comment]
I probably shouldn't bother you with these questions, since they seem to be more about how NSURLRequest and NSURLCache works. :)

**Comment by kean** [comment]
Yeah, I'm sorry, I can't really help with debugging that :( 
I would recommend trying to set a  `max-age=0`. See http://stackoverflow.com/questions/1046966/whats-the-difference-between-cache-control-max-age-0-and-no-cache
You can't control server side, you can update 'Cache-Control` on the client in `optional public func URLSession(session: NSURLSession, dataTask: NSURLSessionDataTask, willCacheResponse proposedResponse: NSCachedURLResponse, completionHandler: (NSCachedURLResponse?) -> Void)`

**Comment by kean** [comment]
Or just ask on stackoverflow :)

**Comment by kean** [comment]
Actually, yeah, I might have misunderstood how `must-revalidate` works. I haven't used it myself.

**Comment by kean** [comment]
> I believe that must-revalidate means "once the cache expires, refuse to return stale responses to the user even if they say that they are acceptable". Whereas no-cache implies must-revlidate plus the fact the response becomes stale right away.
