### ISSUE TITLE
Loading images from CoreData or other custom storage

### ISSUE THREAD

**Issue by intonarumori** [kean/Nuke#520]
I've been playing around with Nuke and was wondering if it would be possible to have a custom loading logic for images besides the built in `urlSession` based approach.
There are some use cases where an image is not identified by a remote or local url but some custom identifier, ex. CoreData record id etc. I'd like to be able to load such images and process them with the built in image processors (ex. resize).

Is there a simple way to achieve that with Nuke? Alternatively what would be a good entry point to only use the image processors?

Thank you.

**Comment by kean** [comment]
Yes, you can do it with `Combine`-based APIs. See ["Sources"](https://kean.blog/nuke/guides/customizing-requests#sources).

**Comment by intonarumori** [comment]
@kean Thanks for the reply.

After more investigation I found that the url based approach can work in the case of CoreData since `NSManagedObjectID.uriRepresentation()` helps with getting urls for CoreData objects.

Then you can create a custom data loader conforming to `DataLoading` for the custom data retrieval.

With this approach I was able to achieve what I wanted, even though it involves creating and then parsing an URL I don't think it would affect performance too much.

I can imagine you could further generalise the loading layer with protocols for the request and response objects and thus making it even more customisable, but probably not worth the effort for the minimal benefit of breaking away from `URLRequest` and `URLResponse`.

Thanks for the Combine based suggestion I will look into that one as well.

**Comment by kean** [comment]
That's a great approach 👍
