### ISSUE TITLE
`didComplete` closure in `ImagePrefetcher` is not publicly accessible

### ISSUE THREAD

**Issue by winstondu** [kean/Nuke#527]
It seems that the `didComplete` closure is meant to be a publicly accessible api variable. But it has an internal protection level, even though no other internal module accesses it.

Since it is a very useful thing to have, I don't understand why its not accessible.

**Comment by kean** [comment]
I think it's only used for testing. PRs a welcome.

**Comment by winstondu** [comment]
https://github.com/kean/Nuke/pull/528
