### ISSUE TITLE
Crash when running on iOS 8

### ISSUE THREAD

**Issue by andreaslindahl** [kean/Nuke#53]
I get a crash when running my app, which uses Nuke, on iOS 8. The app crashes immediately, before any of my code is executed.

dyld: Symbol not found: _NSURLSessionTaskPriorityDefault
  Referenced from: /Users/[...]/Build/Products/Debug-iphonesimulator/Nuke.framework/Nuke
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
 in /Users/[...]/Build/Products/Debug-iphonesimulator/Nuke.framework/Nuke

**Comment by andreaslindahl** [comment]
I managed to solve it by adding CFNetwork to the Nuke target in my Cocoapods project. Should probably be added by default...

**Comment by kean** [comment]
Hmm, thanks for the report. Maybe I should just make priority optional to avoid the problem altogether

```swift
public var priority: Float?
```

**Comment by andreaslindahl** [comment]
I did some research and it seems to be a problem with XCode or some part of the SDK. Just adding CFNetwork as a requirement, or as a framework reference should fix it.

**Comment by kean** [comment]
Fixed in [Nuke 2.0.1](https://github.com/kean/Nuke/releases/tag/2.0.1). I decided to remove NSURLSessionTaskPriorityDefault, it's more reliable. I don't want to depend on CocoaPods. And from the look of things Carthage doesn't support that kind of dependencies at all.
