### ISSUE TITLE
App Store Connect Operation Warning

### ISSUE THREAD

**Issue by robm92** [kean/Nuke#531]
When uploading an archive to App Store Connect, the following warning appears:

App Store Connect Operation Warning
The app references non-public selectors in Payload/MyApp.app/MyApp: didEnterBackground 

Upon inspection, this appears to be referencing:
ImageCache.swift:176

This does not appear to cause a rejection however.

**Comment by kean** [comment]
Thanks for the report. Fixed in [10.7.0](https://github.com/kean/Nuke/releases/tag/10.7.0).
