### ISSUE TITLE
response.cacheType return nil

### ISSUE THREAD

**Issue by Ilgizzon** [kean/Nuke#535]
nukeImageLoader = ImagePipeline {
            $0.dataLoader = DataLoader(configuration: {
                let conf = DataLoader.defaultConfiguration
                conf.urlCache = nil
                return conf
            }())
            $0.imageCache = nil
            $0.dataCache = try? DataCache(name: "images")
            $0.dataCachePolicy = .storeEncodedImages
        }

            let imageProcessor = ImageProcessors.Resize(size: CGSize(width: object.width, height: object.height),
                                                       unit: .points,
                                                       contentMode: .aspectFit,
                                                       crop: false,
                                                       upscale: true)
            
            let request = ImageRequest(url: url,
                                       processors: [imageProcessor],
                                       priority: .veryHigh,
                                       options: [.disableMemoryCache],
                                       userInfo: [.imageIdKey: object.key])
            
            nukeImageLoader.loadImage(with: request) { [weak self] result in
                switch result {
                case .success(let response):
                    self?.mglMap.style?.setImage(response.image, forName: object.key)
                    print("\(response.cacheType)")
                case .failure(_):
                    self?.mglMap.style?.setImage(object.defaultImage, forName: object.key)
                }
                
            }

The first request returns nil in response.cacheType. How to fix this?

**Comment by kean** [comment]
> The first request returns nil in response.cacheType. How to fix this?

Could you please clarify what your expectation is? If by the first request you mean the request that fetched the image from the network, it's expected for cacheType to be nil.
