### ISSUE TITLE
Nuke.ImagePipeline.Error error 2.

### ISSUE THREAD

**Issue by nick70007** [kean/Nuke#536]
In my SwiftUI App i am having these error, not able to download image and display

Here is my code snippet:

                let request = try! URLRequest(url: obj.displayCoverLink, method: .post).asImageRequest()
               
                LazyImage(source: request) { state in
                    if let img = state.image {
                        img
                            .aspectRatio(contentMode: .fill)
                    } else {
                        Image("placeholder")
                            .resizable()
                            .frame(width: 25, height: 25, alignment: .center)
                            .scaledToFit()
                    }
                }
                .onFailure { err in
                    print(err.localizedDescription)
                }
                .frame(width: 80, height: 100)
                .transition(.fade(duration: 0.5))
                .cornerRadius(10)
                .shadow(color: Color.black.opacity(0.25), radius: 4, x: 0, y: 4)

**Comment by kean** [comment]
It seems to be [a NukeUI issue](https://github.com/kean/NukeUI/issues/36). I'm going to close it. For updates, please follow the issue I linked.

I'm not actively working on debugging it. PRs are welcome.
