### ISSUE TITLE
DataCache not working at all?

### ISSUE THREAD

**Issue by shaps80** [kean/Nuke#538]
I'm kinda lost on this one. I've written a back ported `AsyncImage` implementation for iOS 13+ and I wanted to add Nuke as a caching layer.

This is the entirety of the code I'm using (note its 100% SwiftUI):

```swift
// MyApp.swift
init() {
    ImagePipeline.shared = ImagePipeline(configuration: .withDataCache)
}
```

```swift
// AsyncImage.swift

// Returns `false` ALWAYS                <----- This is not what I'm expecting?
print(ImagePipeline.shared.cache.containsData(for: url))

imageTask = ImagePipeline.shared.loadData(with: url) { result in
    switch result {
    case let .success(result):
        if let image = UIImage(data: result.data, scale: scale) {
            withTransaction(transaction) {
                phase = .success(Image(uiImage: image))
            }
        } else {
            phase = .empty
        }
    case let .failure(error):
        withTransaction(transaction) {
            phase = .failure(error)
        }
    }
}
````

No matter what I try, I cannot seem to get the system to support a disk cache. So when I quit the app, go offline, relaunch, I'd expect any cached images to still be returned.

@kean any ideas?

**Comment by kean** [comment]
Hey, can you please provide a small sample?

If you are following [this guide](https://kean.blog/nuke/guides/caching), it should work. The existing sample you posted looks good.

**Comment by shaps80** [comment]
I knew you were going to ask for that haha! I'll need to prep a separate sample and re-test as well in case it just happens to work haha.

**Comment by shaps80** [comment]
Huh, so it works in a separate sample app which is interesting. I wonder if somehow my URL/cache-key is somehow not being reused (on my end), I'll investigate and get back to you.

**Comment by shaps80** [comment]
Right so I had to switch over to `loadImage` because when I use `loadData` there's not `cacheType` value to check, can I assume I was using the wrong API, and it doesn't support caching?

When I switch to `loadImage` I can see the caching works as expected. I do see on launch multiple progress view's but I think that's my end, I'm using async/await and I'm guessing I have some blocking tasks or something silly 👍

**Comment by shaps80** [comment]
Follow up:

So if I'm scrolling during the initial load of the screen/app it works fine, right up until the initial images load from `disk`. The scrolling halts and the whole UI locks up for a second or two.

Not sure yet if this is coming from your code, any thoughts on this? Not sure how else I could possibly dispatch any work to the background.

**Comment by shaps80** [comment]
Ok, apologies for any confusion, but its looking more like the UI blocking is an issue on my end. I'll verify shortly but I think its a piece of code I wasn't expecting to execute at all, but appears to be alongside the initial image load, hence why I thought this was an issue with Nuke.

**Comment by shaps80** [comment]
Ok, final message. Again, sorry for the confusion, this was absolutely on my end. 🙈

I've now fixed it and Nuke is amazing, as always 👍

**Comment by kean** [comment]
I'm glad that you got it working. 👍

This code has been in production for a long time now. It's safe to assume that unless you heavily customize the pipeline, it should work.
