### ISSUE TITLE
Updating cached image is not persisting

### ISSUE THREAD

**Issue by bhmahler** [kean/Nuke#54]
I am trying to update the cached image for specific request when updating an image.  My images are hosted on S3 and when the user updates their profile picture, there are 3 sizes that are uploaded to s3 and then I want to update the cache for these.  This is the code that I am using

```swift
let request = ImageRequest(URL: url)
let cachedResponse = ImageCachedResponse(image: image, userInfo: nil)
ImageManager.shared.setResponse(cachedResponse, forRequest: request)
```

This appears to update it, but when I quit the app and reload it, the old image is appearing.  I have verified that the image is updated on s3 when you hit the url.

Any thoughts? Am I just going about this wrong?

**Comment by kean** [comment]
Hi, that's a common question.

The code that you are using updates cached response in a memory cache. It doesn't update response into a disk cache.

```swift
/** Stores response into the memory cache.
 */
public func setResponse(response: ImageCachedResponse, forRequest request: ImageRequest) {
    self.cache?.setResponse(response, forKey: ImageRequestKey(request, owner: self))
}
```

The common way to update images in both in-memory and on-disk cache would be to configure HTTP cache headers on the server in a way that supports validation. I've written a guide on this (recurring) topic http://outscope.net/blog/image-caching, you should check this out.

There is also a similar question regarding validation of image hosted on S3 https://github.com/kean/Nuke/issues/52

**Comment by bhmahler** [comment]
Ohhhhh I didn't see that Issue for S3.  I will dig deeper.  Appreciate the quick response!

**Comment by kean** [comment]
Yeah, there is a lot of info both in the issue and in the guide. Also, feel free to ask more questions.
