### ISSUE TITLE
WebP plugin

### ISSUE THREAD

**Issue by makleso6** [kean/Nuke#541]
Hi! A create plugin for Nuke to decode webp images in swift (https://github.com/ryokosuge/Nuke-WebP-Plugin use obj implementation and min iOS v13)
Can you validate it?
what kind of tests should I write?

many thanks :)
https://github.com/makleso6/NukeWebP

**Comment by kean** [comment]
Hi, @makleso6. I went through the code and it looks great. I added it to the list of plugins in [README](https://github.com/kean/Nuke) and the docs.

> What kind of tests should I write?

I see commented out Nuke APIs in [NukeWebPTests.swift](https://github.com/makleso6/NukeWebP/blob/master/Tests/NukeWebPTests/NukeWebPTests.swift). I suggest focusing on testing your WebP decoders directly instead. Having a few tests with baseline and progressive WebP would be good.

I also suggest adding a bit more documentation to the README file. It's not clear what WebP features it supports, e.g. does it support progressive WebP?

Btw, `AdvancesWebPDecoder` - shouldn't it be named `AdvancedWebPDecoder`? Or maybe just `WebPDecoder`?

I'm going to close this issue, but feel free to continue posting here.
