### ISSUE TITLE
Error.decodingFailed is missing corrupted `Data`

### ISSUE THREAD

**Issue by freak4pc** [kean/Nuke#544]
Heya 👋 
We noticed in our logs a small wave of sporadic `ImagePipeline.Error.decodingFailed` error, but we don't have a way to debug those / add logs since the error doesn't include any additional information.

From what I checked it can fail for an empty Data, empty Response or an invalid image data. 
We'd like to know which one It is - but also, if it's the latter, know exactly what is the data that caused it to fail decoding.

Would you accept a PR that adds the `Data` as an associated value to the error? Or any other idea that comes to mind?

Thanks !

**Comment by freak4pc** [comment]
> A common reason for this is a misbehaving API, e.g. returning HTML instead of image data.
Yes, I definitely suspect this :) But without the data it's hard to know exactly what happened.

I'll put a PR soon. Thanks!

**Comment by kean** [comment]
Thanks for the PR. I'm planning to release it in the scope of Nuke 11*  with other major improvements to error handling. I want each error to have as much context as possible to localize a problem. For example, here is a [first related PR](https://github.com/kean/Nuke/pull/551) that makes  `ImageProcessing` throwing.

*It's technically a breaking change. Maybe if data had a default value, it could be source-compatible. But I'm not sure it's worth releasing it as is. I suggest installing from the main branch for now.

**Comment by freak4pc** [comment]
Is there a plan for v11? 
We have a nasty bug we want to investigate and have zero visibility about why decoding fails.

**Comment by kean** [comment]
[Nuke 11 (Beta 1)](https://github.com/kean/Nuke/releases/tag/11.0.0-beta.1) and I'm making error reporting much-much better, among many other changes.
