### ISSUE TITLE
Randomized tests fail to run on Xcode 14.0 beta 1

### ISSUE THREAD

**Issue by bielikb** [kean/Nuke#550]
# Problem
It's hard to digest even in my head. When I run app target, I got a compiler error from within `ThreadSafeyTests.swift` as shown on the pic.

I can provide more context if needed.

<img width="1477" alt="Screenshot 2022-06-07 at 11 27 11" src="https://user-images.githubusercontent.com/4924709/172346437-d1d1bbb3-d348-49b7-956c-09e15a68a8b6.png">

Environment: Xcode 14.0 beta 1
Nuke version: 10.3.3

**Comment by kean** [comment]
Looks like a SwiftLint bug (false positive).

**Comment by bielikb** [comment]
oh yeah. my bad :) Im closing this issue now :)
