### ISSUE TITLE
Reload image when it is requested with processors

### ISSUE THREAD

**Issue by thomasdao** [kean/Nuke#568]
Hi, thank you for this library!

I'm loading image with image processor like below, and it works great:
```swift
func loadImage(imageView: UIImageView, url: URL, limitSize: CGSize? = nil) {
    var processors = [ImageProcessing]()
    if let limitSize = limitSize {
        processors.append(ImageProcessors.Resize(size: limitSize))
    }
    let request = ImageRequest(url: url, processors: processors)
    Nuke.loadImage(with: request, into: imageView)
}
```

However I have difficulty with reloading the image. When the image is updated, I want to clear the cache so that next time it can be loaded with newer version. However, using documented method doesn't work:
```swift
func clearCacheForURL(url: URL) {
    let cache = ImagePipeline.shared.cache
    cache.removeCachedImage(for: url)
}
```

I guess since the request with processors are cached with different key, I must keep track of all requests with different options, then call `cache.removeCachedImage` for each request. I have tried that and it works fine.

However this is a bit troublesome and error prone, since I have to keep track of all requests in a dictionary and make sure that they're only called on main thread so the app won't crash because the dictionary is concurrently modified on different threads.

I may not be aware from the documentation, but is there a function to clear the cache for a specific URL, even if it is requested with processors?

Many thanks!

**Comment by kean** [comment]
Hi,

The cache keys include image processors. Otherwise, you won't be able to distinguish between two requests with the same URL, but with different processors. The `Resize` processors includes target size in its cache identifier.

There is no way to remove all cached images for a specific URL regardless of what processors were used.

What you can do is to implement [`cacheKey(for:pipeline:)`](https://kean-docs.github.io/nuke/documentation/nuke/imagepipelinedelegate/cachekey(for:pipeline:)-8k9a4) method from [`ImagePipelineDelegate`](https://kean-docs.github.io/nuke/documentation/nuke/imagepipelinedelegate) to customize how cache keys are created. For example, if you know that you are **only ever** going to apply the same processor to an image, you can ignore the processors "component":

```swift
func cacheKey(for request: ImageRequest, pipeline: ImagePipeline) -> String? {
    return request.url?.absoluteString
}
```

Then when you call `cache.removeCachedImage(for: url)` will remove the images regardless of what processors were used.

**Comment by thomasdao** [comment]
Hi, thanks for the super fast reply! Your suggestion probably does not work for my app since I use different resize processors for the same image based on the `ImageView` size.

Could you consider clearing all cached images for a specific URL? I believe that all images with processors are just derived from the original image, and if the original image changed, the images with processors should be updated as well. Although this is not required (I can already clear the cache using the current API), I think it would be very useful and all boilerplate code to keep track of image requests can be removed.

Thank you.

**Comment by kean** [comment]
I see. I had a similar scenario in one of my apps a few years back. What we ended up doing is specifying a predefined list of image sizes: small, medium, and large. And then calling "remove image from cache" three times per image. In our case, small image had its own URL. And medium and large images were produced from the same URL.

> Could you consider clearing all cached images for a specific URL?

Yes. I also have a potentially related feature in a backlog: clearing the in-memory cache when leaving the screen by removing only the images fetched on this screen. If there was a way to somehow group images and then remove all images from that group, that could also cover your scenario.

If you have any suggestions how to design this API, please let me know. PRs are also welcome. The development is happening in [nuke-11](https://github.com/kean/Nuke/tree/nuke-11) branch.

**Comment by thomasdao** [comment]
I really like the idea with the cache group! For your use case, when the app requests 3 images, the image requests can be added to a group with key as imageID, and when this image changes, we can clear the imageID cache group. That would be super convenient.

One way to do it is to specify a `groupCacheKey` on the `ImageRequest`. When the image is requested, keep track of `groupCacheKey`: one `groupCacheKey` can map to an set of request specific cache keys. Then on cache class, we can add a new function `removeCachedData(for groupKey: String)`. Would that be ok for you?

I would study the new development branch if you're ok with the approach :). Thank you.

**Comment by kean** [comment]
> When the image is requested, keep track of `groupCacheKey`

This should be relatively straightforward for the in-memory cache (`ImageCache`), but I'm not sure about disk cache (`DataCache`). It currently doesn't have an index of stored of items.

**Comment by thomasdao** [comment]
Would you consider saving request cache keys for a group to disk or do you prefer other approach? 

One way to do it is:
- Create a directory for each group cache key.
- For each request in this group, create an empty file with name derived from request key, and save to the group cache directory.

It would be easy to clear the cache for the whole group. However, if user only wants to clear the cache for a specific request, this approach requires going through all group folder and remove the file for that request.

**Comment by thomasdao** [comment]
I'm thinking that the above approach may become more complicated than necessary. If the requirement is just to clear all images for a specific URL, I think the solution may be simpler. For example, instead of saving the cache file to the root of the cache folder, first create a folder which name is generated from the URL, and then save the cache file to this folder. This makes it easy to clear the cache for a specific request or all requests associated with the URL. However this approach has a drawback that it might need migrating old cache files to the new structure.

**Comment by kean** [comment]
By default, a custom disk cache stores original images, not the processed ones. So, by default, there is only going to be one image to remove. But that of course, not the case with other [cache policies](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/configuration-swift.struct/datacachepolicy-swift.enum).

A proper solution would be to create an index, ideally a database. It can become useful for other things too.

A relatively simple solution which I think could work for now is to set groupId as an extended file attribute and search for files with this attribute when you need to remove an image. It will, of course, be slower than using an index, but it'll get the job done. And it won't affect any of the existing users.

**Comment by thomasdao** [comment]
Another possible solution is to use `UserDefaults` to keep track of the index, perhaps using a new `UserDefaults` with a unique `suiteName` to avoid conflicts with the client application. I think using `UserDefaults` has the advantage that it is thread safe, the implementation is similar to memory cache, and it won't affect existing users.

**Comment by kean** [comment]
I've done some spike work to implement this feature and I think it overcomplicates the framework. There is no clear way to do it.

This is a niche feature. You generally only have a couple of processors and know which ones you apply. It should be relatively easy to keep track of what images the client requests on the client side.

And the scenario where you remove all images when leaving the screen is different because you do it with a different goal – reducing memory usage – and you remove them only from the memory cache. For this scenario, it's also easy to keep track of the requests on the client side. It can be done without complicating the framework.
