### ISSUE TITLE
Image disappeared when app return from background

### ISSUE THREAD

**Issue by eccentricyan** [kean/Nuke#569]
Hi, thank you for the library! 

I use s3 signatured url witch time interval until expiration is one minute.

I have a paged collectionview and contains 12 images to display with the default `ImagePipline.shared`

if I scroll to the last images and enter background. 
one minutes later, return from background, scroll to the first images, the image disappeared.
(urls are fetched  only onece)

I found imageCache totalCount decreased to 10 when app enter the background.

use `request?.options = [.reloadIgnoringCachedData]`, image will not disappear, but cause some blinking...

is there any way to keep it from disappearing without using reloadIgnoringCachedData?

**Comment by kean** [comment]
Hi,

Yes, by default, `ImageCache` removes most least-recently used images when the app enters background to reduce the chances the app will get removed from memory.

If you must guarantee that the images are stored in memory for an extended period of time, I suggest using a custom cache (see [`ImageCaching`](https://kean-docs.github.io/nuke/documentation/nuke/imagecaching) protocol).

> `request?.options = [.reloadIgnoringCachedData]`

This is interesting. I'm not sure how this can affect the reload. Could you please share some more info about you use case: pipeline configuration, Nuke version, how you load images?

**Comment by eccentricyan** [comment]
@kean 
> If you must guarantee that the images are stored in memory for an extended period of time, I suggest using a custom cache (see [ImageCaching](https://kean-docs.github.io/nuke/documentation/nuke/imagecaching) protocol).

thank you for the response. I will try it. and for the low piority, i will close the issue.

I wrote the following because it may be useful. Ignore if you are busy



> some more info about you use case: pipeline configuration, Nuke version, how you load images

sorry for the wrong information. I load urls twice.
1. load the saved urls
2. immediately fetch the urls from api.
I found that urlCaches of images displayed?(which scrolled to the current page) before step 2 are not cached. (the image1, or if scrolled quickly then will be the image1 and image2)

if use `[.reloadIgnoringCachedData]` or only load the image url from api, the urlCaches are cached.

I use the default pipline configuration, nuke version is 10.7.1
```
var request = ImageRequset(url: url)
request[.imageIdKey] = "key"
ImagePipeline.shared.loadImage(with: request) {
    self.imageView.image = ...
}
```
