### ISSUE TITLE
How to make images placed by Nuke in green when Color Blended Layers is enabled?

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#57]
I download the images in the table view cells via Nuke as:

    imageView.nk_setImageWith(imageURL)

the images are in red when the Simulator has `Color Blended Layers` checked. How to make them green? (It will help the scrolling performance.)

PS. Earlier I use HanekeSwift, these images are in green by default. But with Nuke, they become all red.

**Comment by kean** [comment]
Bitmaps that created during decompression are in `32 bits per pixel, 8 bits per component, kCGImageAlphaPremultipliedLast` image format starting with v1.0.1 https://github.com/kean/Nuke/issues/35

I thought about supporting opaque contexts (use `32 bits per pixel, 8 bits per component, kCGImageAlphaNoneSkipLast`), but I haven't found enough evidence that it actually makes a difference yet. The memory usage is the same; the drawing performance might differ though.

**Comment by joe528** [comment]
I am not sure if it helps the performance or not. It's because I read an article about it: https://medium.com/ios-os-x-development/perfect-smooth-scrolling-in-uitableviews-fd609d5275a5

So I try to improve my table view performance through different angles.

**Comment by kean** [comment]
I would support opaque bitmaps in the next release, it certainly wouldn't hurt.

**Comment by joe528** [comment]
By the way, do you have any suggestion about Nuke configuration that might help the scrolling performance? 

I found Nuke has an option that might help performance but I don't quite understand. I set my image view as

    imageView.clipsToBounds = true
    imageView.contentMode = .ScaleAspectFill

and download images as

    var request = ImageRequest(URLRequest: NSURLRequest(URL: url!))
    request.targetSize = cell..imageView.frame.size
    request.contentMode = .AspectFill
    cell.imageView.nk_setImageWith(request)

but there are two problems after my experiment:
(1) I cannot get the same effect as `.ScaleAspectFill` via Nuke options if I don't set `imageView.contentMode`
(2) the targetSize is in pixel and setting it in the way above will make the images having lower-quality on screen.

**Comment by kean** [comment]
(1) `targetSize` and `contentMode` properties on `ImageRequest` merely describe how to resize loaded images:

```swift
private func decompress(image: UIImage, targetSize: CGSize, contentMode: ImageContentMode) -> UIImage {
    let bitmapSize = CGSize(width: CGImageGetWidth(image.CGImage), height: CGImageGetHeight(image.CGImage))
    let scaleHor = targetSize.width / bitmapSize.width
    let scaleVert = targetSize.height / bitmapSize.height
    let scale = contentMode == .AspectFill ? max(scaleHor, scaleVert) : min(scaleHor, scaleVert)
    return decompress(image, scale: Double(scale))
}
```

If you want resized image to fill the image view you should set `imageView.contentMode` to `.ScaleAspectFill`. That's the correct behavior.

(2) Yes, `targetSize` is in pixels. There was a long discussion here https://github.com/kean/Nuke/pull/42 about whether it should be in points or in pixels. Nuke is sticking with pixels.

Here's how I compute target size when you use `nk_setImageWith(URL: NSURL)` method:

```swift
public extension View {
    /** Returns image target size in pixels for the view. Target size is calculated by multiplying view's size by screen scaling factor.
     */
    public func nk_targetSize() -> CGSize {
        let size = self.bounds.size
        #if os(iOS) || os(tvOS)
            let scale = UIScreen.mainScreen().scale
        #elseif os(OSX)
            let scale = NSScreen.mainScreen()?.backingScaleFactor ?? 1.0
        #endif
        return CGSize(width: size.width * scale, height: size.height * scale)
    }
}
```

**Comment by kean** [comment]
> By the way, do you have any suggestion about Nuke configuration that might help the scrolling performance?

It's already really well optimized (images are decompress in a background, NSURLSessionTasks are created in a background, etc). I doubt that there's anything else that you can do on image loading side.

I can't give any concrete advice about scrolling performance. In general, I rarely encounter any GPU-related problems when it comes to scrolling (unless you use some `CALayer` features like `cornerRadius` or shadows). First thing to do should always be to use Instruments in profile your CPU usage.

**Comment by joe528** [comment]
Thank you very much for your detailed reply.

Yes, I can understand Nuke is doing a great job for the performance. That's why I switched to Nuke right after I saw RayWenderlich mentioned about you. The scrolling performance of my table view is pretty good already except a bit of jerkiness while scrolling fast. I have compared various apps, most of them have such jerkiness except Facebook's app. I am just trying to explore what I may have been missing. Thanks for the great job.

**Comment by kean** [comment]
Thanks for the feedback :)

**Comment by kean** [comment]
`ImageDecompressor` now uses `CGImageAlphaInfo.NoneSkipLast` for opaque images and `CGImageAlphaInfo.PremultipliedLast` for images that have alpha channel. I hope that it settles it. There are no more blended layers when displaying images without an alpha channel. I doubt that it improves performance in a measurable way, but it wouldn't hurt.

**Comment by joe528** [comment]
After a few days testing with Nuke & Haneke, my source code is the same, I can only feel from my eyes, it seems Haneke is performing better (less jerkiness). The difference is very slight, hardly detected, I am just being extremely picky.
I will test for the new release when it's out to see if it makes any difference. 
Another thing is... I found the images shown by Nuke has a alpha transition? (while Haneke doesn't). I like the alpha transition because it provides better UI feeling, however it might affect scrolling performance a bit? Can this transition be disabled by configuration so that I can test without it?

**Comment by kean** [comment]
Animations are expensive.

> Can this transition be disabled by configuration so that I can test without it?

See ImageViewLoadingOptions

**Comment by joe528** [comment]
Disabling animation does help.

Any other option I can try? Would `request.memoryCacheStorageAllowed = false` help?

**Comment by kean** [comment]
> Any other option I can try? 

Probably not. I'm going to release fix for blended layers today.

> Would request.memoryCacheStorageAllowed = false help?

It disables memory caching (more precisely, it prevents manager from storing images into memory cache). It doesn't disable memory cache lookup, you should set `memoryCachePolicy` to `ReloadIgnoringCachedImage` to do that. But if you really don't need a memory cache you should initialize ImageManager without a memory cache.

**Comment by joe528** [comment]
Thanks!  Just one more question... does it make any difference to specify the `targetSize`? (for UI performance)

    var request = ImageRequest(URLRequest: NSURLRequest(URL: url!))
    request.targetSize = imageView.nk_targetSize() 
    imageView.image.nk_setImageWith(request)

I am wondering if it consumes more CPU time or actually helps?

**Comment by kean** [comment]
It actually improves performance when images are larger than the target size. 

One of the key differences between Nuke and other frameworks (including Haneke) is how the images are decompressed. In Haneke images are first decompressed by drowning them into a bitmap that is the same size as the original image (`hnk_decompressedImage`), and only then that bitmap is resized by drawing it into an another bitmap (`hnk_imageByScalingToSize`). In Nuke images are decompressed *and* resized in a single pass. That makes a [dramatic difference](https://github.com/kean/DFImageManager/issues/64).

**Comment by kean** [comment]
> I am wondering if it consumes more CPU time or actually helps?

I don't have a complete answer. If you take a JPEG with 0.75 compression quality, than in general it consumes a significant amount of CPU time when the images are resized by 0.5-1.0 scale factor. And it   significantly reduces CPU usage when the images are resized by 0.0-0.5 factor.

**Comment by kean** [comment]
I've updated an answer above, hope it makes some sense now.
