### ISSUE TITLE
Ux 

### ISSUE THREAD

**Issue by scott-lydon** [kean/Nuke#575]
Having some ux issues.  Following the docs immediately gives errors, that require some tinkering to figure out how to work with the package.  Enough that it seems easier for me to make my own as much as I don't want that to be the case. 

<img width="652" alt="Screenshot 2022-07-13 at 12 45 59 PM" src="https://user-images.githubusercontent.com/4231144/178818794-f951a0f1-8ed9-4f5d-8af8-a45e74a832a0.png">
<img width="651" alt="Screenshot 2022-07-13 at 12 47 31 PM" src="https://user-images.githubusercontent.com/4231144/178818929-5a105ea0-095f-41dc-89d4-8f12278a6651.png">
<img width="682" alt="Screenshot 2022-07-13 at 12 47 48 PM" src="https://user-images.githubusercontent.com/4231144/178818969-bf18a484-108a-493a-8502-9216b51d0db1.png">

**Comment by kean** [comment]
Hi, the docs have been updated to Nuke 11.0. Nuke [11.0 RC](https://github.com/kean/Nuke/releases/tag/11.0.0-rc.1) is out and the full release will happen in about a week.

The code samples you attached are checked by a compiler with every release - see [DocumentationTests](https://github.com/kean/Nuke/blob/cb7be6d9ba8579b245cac71d7a863384502ecd89/Tests/NukeTests/ImagePipelineTests/DocumentationTests.swift#L44). As long as you are on Nuke 11.0, they should work perfectly.

**Comment by kean** [comment]
[Nuke 11](https://github.com/kean/Nuke/releases/tag/11.0.0) is now officially released.
