### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by Rag0n** [kean/Nuke#581]
Are you going to continue releasing lib for CocoaPods? Last CocoaPods release was made on January of 2022, since then you released several updates, but none for CocoaPods.

**Comment by kean** [comment]
CocoaPoads support is no longer available. Carthage should still work, but is not supported.

**Comment by Rag0n** [comment]
Thanks for the reply, I would like to know why did you take this decision to remove CocoaPods/Carthage support? I mean what are the pros? Is this something complicated to do? Is this something we can help with?
I mean for me it looks strange if library doesn't support most popular dependency managers. For example SDWebImage has [installation guide](https://github.com/kean/Nuke/issues/581#issuecomment-1202375861) with CocoaPods, Carthage, SPM or manual.

**Comment by kean** [comment]
It's hard to estimate just how much time I spent debugging weird CocoaPods issues over the years, while Carthage and SPM work perfectly.

CocoaPods isn't designed to scale well (see massive specs repo that has to be downloaded locally on every computer), so I'd say nobody should be using it anymore.

I'm not planning to include CocoaPods support. If SPM doesn't work for you for some reason, please consider using binary frameworks.

**Comment by Rag0n** [comment]
Thanks, I'll consider binary frameworks like you said, but maybe I'll help you to support CocoaPods if you're not against it. At first I need to research what's wrong with CocoaPods setup and how hard is to bring support back. 
To add a little bit more context, I'm thinking about making react-native library and CocoaPods in React-Native is default way to use and distribute 3rd party dependencies.

**Comment by kean** [comment]
I'm afraid I'm not planning to include CocoaPods support even if it's maintained by someone else. I don't support it in any of my frameworks moving forward.

**Comment by NikKovIos** [comment]
It's a pity. Cocoapods works well if know how to use it. Like Core Data :) Btw cocoapods now downloads from cdn so the repo is not needed to download on computer.

Our project don't use SPM because it's too automatic and rebuilds every time by his decision.

Binary frameworks is the only way to use Nuke for us.

However, thank you for your work on Nuke and a great lib.
