### ISSUE TITLE
nukeui: error "decompressing image"

### ISSUE THREAD

**Issue by swand0g** [kean/Nuke#587]
Has anyone run into this error message?
> [Decompressor] Error -17102 decompressing image -- possibly corrupt

Seems to be happening on each new image download (for different file types as well). Currently using version 11.0 but I've been trying other versions to see if it's a new bug.

My current implementation looks something like this
```swift
var body: some View {
  LazyImage(url: URL(string: someStringVar), resizingMode: .aspectFit)
    .frame(width: someCgFloat, height: anotherCgFloat)
}
```

PS, amazing library! ❤️

**Comment by kean** [comment]
It might be [preparingForDisplay](https://developer.apple.com/documentation/uikit/uiimage/3750834-preparingfordisplay). I decided to give it a try, but it seems to still be buggy. Do you know on what iOS versions you see this issue?

**Comment by swand0g** [comment]
Ahhh interesting, yeah I'm running on iOS 15.5 on simulator (specifically iPhone 13 Pro). I'll def take a look at the `preparingForDisplay` docs when I get a chance

**Comment by kean** [comment]
I disabled in by default in 11.1.1.

**Comment by swand0g** [comment]
oh cool! thanks so much for the help!
