### ISSUE TITLE
Local image is never cached.

### ISSUE THREAD

**Issue by WarWithinMe** [kean/Nuke#588]
According to the document, an image request with processors will be cached in `dataCache`, if `dataCachePolicy == .automatic`. However, in 11.1.0. Image with "file://" url is never cached.

This is because `shouldStoreFinalImageInDiskCache()` returns false too early, if it is `file://` or `data://` url 
https://github.com/kean/Nuke/blob/14b7cb6949ba9a2bca931ff6a7d9006d4b66c903/Sources/Nuke/Tasks/TaskLoadImage.swift#L257-L260

**Comment by kean** [comment]
Is there a scenario in which you'd like caching to be enabled?

**Comment by WarWithinMe** [comment]
Basically, I want to display images imported by the user, these images are stored in the local filesystem. Currently, I'm using `ImageProcessors.Resize` to size the image before displaying it. I'm expecting the product of the `Resize` should be cached in the dataCache.

**Comment by WarWithinMe** [comment]
Never mind, just find out that local file url in IOS might not be stable, and get changed during next application launch. So even if an image is cached with a key generated from local file url, the app will never find it again if it’s relaunched.

**Comment by WarWithinMe** [comment]
> I was going to suggest using one of the [data cache policies](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/datacachepolicy) that support caching processed images, but I'm now not sure if it works for local images.

No, it doesn't. As the code mentioned in this issue shows, when the URL is local URL, the policy is completely ignored.

**Comment by kean** [comment]
It's an issue. Processed images should be cached always.
