### ISSUE TITLE
By default, when adding Nuke from Xcode's Package Manager UI, it defaults to v9.6.1

### ISSUE THREAD

**Issue by soemarko** [kean/Nuke#593]
As titled. This maybe an odd one. I was confused why I can't import NukeUI. Turns out I was adding a very old version. I'll need to specifically select exact version, and typed in 11.1.1 while normally other packages defaults to the latest one.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/381585/185472906-e5658170-990a-498b-8bab-eef6e61c724b.png">

No NukeUI

<img width="654" alt="image" src="https://user-images.githubusercontent.com/381585/185473039-8712a50e-a28f-432b-b047-3b58dfd670d7.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/381585/185473153-32b26130-4d2d-4846-9104-3d63c9ca4ad1.png">

**Comment by kean** [comment]
It's an Xcode defect. I see the same issue with other frameworks that have versions greater than 9.x.

**Comment by kean** [comment]
Yeah, it's pretty annoying. I reported the bug and hopefully, it'll get fixed sometime soon. I've noticed it a while ago too.
