### ISSUE TITLE
NukeUI import causes 'Image' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by OgreSwamp** [kean/Nuke#594]
NukeUI package import messes with the SwiftUI Image:

```
import SwiftUI
import NukeUI

struct TestView: View {

    let image: Image // <- Error here: 'Image' is ambiguous for type lookup in this context

    var body: some View {
        Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
    }
}
```

Changing `Image` to `SwiftUI.Image` fixes the issue

**Comment by kean** [comment]
I thought about renaming it to void name clashes with `SwiftUI`, but I couldn't find a good name. It's mean to be an `Image` replacement. Suggestions are welcome.
