### ISSUE TITLE
iOS 16 methods unavailable

### ISSUE THREAD

**Issue by own2pwn** [kean/Nuke#595]
Having the [latest](https://download.swift.org/swift-5.7-branch/xcode/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-08-02-a/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-08-02-a-osx.pkg) dev snapshot I'm still unable to compile `DataLoader.swift`

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/7850039/187071128-da9755f2-21dd-4a14-9ceb-3ddd61f1c540.png">

https://github.com/kean/Nuke/blob/fbaf18311cf0544954034ec8fc51e014793c3c38/Sources/Nuke/Loading/DataLoader.swift#L166-L174

**Comment by kean** [comment]
Thanks, I'll keep an eye on it when the next beta is out. It compiles OK in the latest Xcode beta (6).

**Comment by gabors** [comment]
@kean this fails building once again with Xcode 14 RC 

Version 14.0 (14A309)

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3587589/189038362-31314fac-9d54-4adc-9ed0-daedcea545b8.png">

**Comment by kean** [comment]
Apparently, macOS 13.0 SDK was removed from Xcode in the RC. This should probably be removed on macOS for now. The iPhone version builds OK.

**Comment by gabors** [comment]
@kean can you please release an update Nuke when possible. 
We're unable to build for the time being.

**Comment by gabors** [comment]
@kean can you take care of this, thank you.

**Comment by kean** [comment]
Fixed in https://github.com/kean/Nuke/releases/tag/11.2.0

**Comment by gabors** [comment]
@kean your fix works for macOS but **not for Mac Catalyst** builds unfortunately 

<img width="201" alt="image" src="https://user-images.githubusercontent.com/3587589/189503326-272feacf-1acb-4567-aafb-05e1f86f2b8a.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3587589/189503317-380e61d6-c5eb-46e3-9eb2-239f2ee68a9b.png">

**Comment by kean** [comment]
Thanks for reporting, yeah, I don't test catalyst support right now. Fixed in [11.2.1](https://github.com/kean/Nuke/releases/tag/11.2.1).
