### ISSUE TITLE
Mocking LazyImage in SwiftUI Previews

### ISSUE THREAD

**Issue by martindaum** [kean/Nuke#596]
Not necessarily an issue with Nuke, but I am having troubles to mock data for SwiftUI previews. In my actual application my data models contain a url for images, which are displayed with LazyImage, which works perfect. For mocking in SwiftUI previews, I would like to use images from the Preview Assets. I am only able to access them via Image(named:) or UIImage(named:) and not via URL (at least I did not find it). So I have to switch in my view code if I am working with actual or mocked data, which I do not like. Any idea on how do solve this?

**Comment by kean** [comment]
`LazyImage` uses `ImagePipeline.shared` by default and the shared pipeline can be replaced in your app code. Alternatively , you can change the [pipeline](https://kean-docs.github.io/nukeui/documentation/nukeui/lazyimage/pipeline(_:)) on individual views. Another option is mocking networking on `URLSession` level, e.g. by using  https://github.com/WeTransfer/Mocker
