### ISSUE TITLE
Docs web page broken

### ISSUE THREAD

**Issue by own2pwn** [kean/Nuke#597]
e.g., https://kean.blog/nuke/guides/welcome

**Comment by kean** [comment]
Docs are now generated using DocC. You can open them in Xcode or use hosted HTML versions: [**Nuke**](https://kean-docs.github.io/nuke/documentation/nuke/getting-started/), [**NukeUI**](https://kean-docs.github.io/nukeui/documentation/nukeui/), [**NukeExtensions**](https://kean-docs.github.io/nukeextensions/documentation/nukeextensions/).

I did a quick scan and removed some of the references to nuke/guides.
