### ISSUE TITLE
Is it possible to specify ImageLoadingOptions?

### ISSUE THREAD

**Issue by harumidiv** [kean/Nuke#598]
I'm trying to update version from 10.11.2 to 11.1.1, but ImageLoadingOptions seems to be gone.
If you want to specify the transition of ImageLoadingOptions with the latest Nuke, how should you do it?

I would like to use the following code option in the latest version.
```
let options = ImageLoadingOptions(
    placeholder: nil,
    transition: .fadeIn(duration: 0.5),
    failureImage: errorImage,
    contentModes: .init(success: .scaleAspectFit,
                        failure: .scaleAspectFit,
                        placeholder: .scaleAspectFit)
)
```

**Comment by kean** [comment]
[`ImageLoadingOptions`](https://kean-docs.github.io/nukeextensions/documentation/nukeextensions/imageloadingoptions) is still there and with no changes to the API, but it is now part of a new `NukeExtensions` module that you need to import to be able to use.

**Comment by harumidiv** [comment]
Thank you for answering.
I want to pass ImageLoadingOptions to ImageRequest, but it seems I can't pass ImageLoadingOptions to ImageRequest.
How should I pass options when reading images with ImagePipeline?

**Comment by ykws** [comment]
For example using NukeExtensions.loadImage?

https://github.com/kean/Nuke/blob/14b7cb6949ba9a2bca931ff6a7d9006d4b66c903/Tests/NukeExtensionsTests/NukeExtensionsTestsHelpers.swift#L17-L25

**Comment by thannn** [comment]
I might be missing something obvious here, but with the latest version of the `NukeAlamofirePlugin` package, `import NukeExtensions` results in "No such module 'NukeExtensions'"...

**Comment by sj1914** [comment]
I am having this same issue I can't seem to be able to use `ImageLoadingOptions` and `Nuke.loadImage`. I fear I am missing something obvious as nothing is mentioned in the migration guide. NukeExtensions doesn't work either.
