### ISSUE TITLE
Can't import NukeUI

### ISSUE THREAD

**Issue by brightfuture** [kean/Nuke#600]
I'm using Xcode 14 and I just can't seem to import NukeUI
I've tried resetting package caches and so on 
and I'm sure I'm using the latest version 

but whenever I do 
`import NukeUI`
and error appears
> No such module 'NukeUI'

**Comment by brightfuture** [comment]
UPDATE: 
I solved this problem by specifically adding NukeUI 
in Frameworks, Libraries, and Embedded Content section of target General settings

**Comment by DanielStout5** [comment]
I'm having this same issue.. @brightfuture do you mean you installed https://github.com/kean/NukeUI ?

My impression is that that's outdated and we should be able to do `import NukeUI` after adding the main `Nuke` package..

**Comment by brightfuture** [comment]
@DanielStout5 no I installed this repo
I solved this problem by explicitly adding NukeUI in frameworks, libraries and embedded content section in the target setting
