### ISSUE TITLE
Why is @MainActor used on all views?

### ISSUE THREAD

**Issue by prochazkafilip** [kean/Nuke#601]
Is there any reason why is `@MainActor` used on all views? I'm trying to use `LazyImage`, but used `@MainActor` causes me problem to build the app. I've never seen to use `@MainActor` on view struct before and I don't know how to use it without using `@MainActor` on all my views.

Could you give me an advice please?

<img width="927" alt="Snímek obrazovky 2022-09-14 v 13 09 31" src="https://user-images.githubusercontent.com/23739465/190143243-55b673b8-019d-4f9b-a9bb-79b9e669a07d.png">

UPDATE:
I've found out that this issue can be solved by `nonisolated` keyword. I created custom wrapper which has implemented `nonisolated init` and this solution works. For this reason I would suggest to make view's initializers as `nonisolated`.

<img width="644" alt="Snímek obrazovky 2022-09-14 v 16 19 53" src="https://user-images.githubusercontent.com/23739465/190180286-957af681-a61a-402e-af5f-3486607cf8cf.png">

**Comment by kean** [comment]
As far as I know, all views are going to be marked with a `@MainActor` attribute moving forward, including UIKit and SwiftUI views.

<img width="424" alt="Screenshot 2022-09-14 at 4 16 21 PM" src="https://user-images.githubusercontent.com/1567433/190253582-878d84cb-e387-4e5e-8936-7a3f8e159935.png">
