### ISSUE TITLE
App Store Connect Operation Error

### ISSUE THREAD

**Issue by acushway** [kean/Nuke#604]
Hi, I'm using version 10.7.1 and got the following after uploading:

App Store Connect Operation Error

The app references non-public selectors in Payload/SquareLife.app/Frameworks/Nuke.framework/Nuke: removeAll

I noticed there was a similar report for didEnterBackground, I hit that, found your closed issue and updated to 10.7.1 and then hit this one.

This is using Xcode 14.

**Comment by kean** [comment]
Hi, is this a warning or an error? There is another [open issue](https://github.com/kean/Nuke/issues/605) that says it's a warning. I submitted a radar to Apple.

**Comment by acushway** [comment]
Hi, it is a warning. It said Error at the top of the dialog but warning in the subtext.

**Comment by kean** [comment]
Great, I hope it gets resolved soon. These things some times happen with new major Xcode releases. I suggest ignoring it for now.

**Comment by acushway** [comment]
Thanks. The release was approved BTW.

**Comment by kean** [comment]
Apple asks me to provide additional information: app ID, build number, upload date, etc. I would appreciate it if folks experiencing this issue would submit feedbacks on their own and provide it.

I don't see a lot of reports of this happening. So maybe it was an intermittent issue.

**Comment by martinmitrevski** [comment]
We've also had some customers using our Stream Chat SDK reporting this (we use Nuke as a dependency). We will let them know to submit feedbacks too.

**Comment by mtrezza** [comment]
Same here with a different error message:

> Distribution completed with warnings:
>
> App Store Connect Operation Error
> The app references non-public selectors in Payload/MyApp.app/Frameworks/Nuke.framework/Nuke: didEnterBackground

Xcode Version 14.0.1 (14A400)

**Comment by kean** [comment]
An issue with `didEnterBackground` was reported earlier https://github.com/kean/Nuke/issues/531 and because it was a private method, I simply renamed it. I'm surprised App Store still complains about it.

**Comment by mtrezza** [comment]
This was from Nuke 9.6.1, that's why, but the other complaints in this issue are different.
