### ISSUE TITLE
App Store Connect Operation Warning - removeAll

### ISSUE THREAD

**Issue by jordanwhitney** [kean/Nuke#605]
When uploading an archive to App Store Connect, Xcode Version 14.0 (14A309), the following warning appears:

App Store Connect Operation Warning
The app references non-public selectors in Payload/<My App>.app/Frameworks/Nuke.framework/Nuke: removeAll

This looks similar to #531

**Comment by kean** [comment]
It's part of the public API. I can't remove it. I hope Apple fixes App Store Connect validation. I'm going to submit a radar.

**Comment by jordanwhitney** [comment]
It did seem like common public API. Thanks for filing a radar.

**Comment by kean** [comment]
Closing as duplicate of https://github.com/kean/Nuke/issues/604#issuecomment-1256577301
