### ISSUE TITLE
NukeUI gone?!

### ISSUE THREAD

**Issue by arshiacont** [kean/Nuke#606]
We are getting errors on Package Dependencies concerrning NukeUI and I realized that it doesn't exist anymore?! https://github.com/kean/NukeUI 
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3298204/193402534-f583cc8f-c7d5-4287-a02f-0b865c3a76a1.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/3298204/193402555-f56fe9d2-3b64-4822-97a0-9ab25f0cee33.png">

**Comment by kean** [comment]
Should be fixed now https://github.com/kean/NukeUI, thanks for the report.

When you get a chance, please migrate to Nuke 11.x where NukeUI is included in the main repo (/Nuke).

**Comment by arshiacont** [comment]
Thanks & sorry we missed 11.x! Upgraded.. Thanks for the great work.
