### ISSUE TITLE
Question about ImageEncoding

### ISSUE THREAD

**Issue by haifengkao** [kean/Nuke#611]
The optional method doesn't seem to do anything. Why does it exist?
```
/// An image encoder.
public protocol ImageEncoding: Sendable {
    /// Encodes the given image.
    func encode(_ image: PlatformImage) -> Data?

    /// An optional method which encodes the given image container.
    func encode(_ container: ImageContainer, context: ImageEncodingContext) -> Data?
}

extension ImageEncoding {
    public func encode(_ container: ImageContainer, context: ImageEncodingContext) -> Data? {
        self.encode(container.image)
    }
}

```

**Comment by kean** [comment]
You can think of a `func encode(_ image: PlatformImage) -> Data?` as a convenience API that you can implement if you don't need anything beyond an image itself to perform the encoding.

I think it's a bit overcomplicated and I'd like to reverse this decision, but I'm trying to reduce the number of breaking changes every release and this change was never a priority.
