### ISSUE TITLE
ImagePrefetcher.didComplete non-obvious behavior

### ISSUE THREAD

**Issue by kattouf** [kean/Nuke#616]
Expected behaviour:

`didComplete` will be called after prefetch process has completed in cases:
1. if image is not found in cache - `didComplete` calls after loading
2. if image is found in cache - `didComplete` calls immediately

Actual Behavior:

`didComplete` will be called after prefetch process has completed in cases:
1. if image is not found in cache - `didComplete` calls after loading
2. if image is found in cache - `didComplete` **will not be called**

I think ImagePrefetcher would be better if it called callback in all completion cases
Thank You!

**Comment by kean** [comment]
I agree, the current behavior is incorrect. And this property isn't documented.

This property (`didComplete`) was initially internal and used only for unit testing. It was later made `public` in one of the PRs, but looks like this scenario wasn't considered. I would expect the completion to be called even in case of cache lookup.

**Comment by 0xceed** [comment]
Kinda critical issue for company where I work at the moment, thought you might appreciate the fix as well.
