### ISSUE TITLE
DownSampling Image 

### ISSUE THREAD

**Issue by piggy-park** [kean/Nuke#617]
HI, I have a question about downsampling in Nuke
Now i'm currently simple testing downsampling
I think, Nuke downsample with device scale
And.
The scale is known as the number of pixels that can be processed per point.

My Question is  why the image size is smaller on a larger device.
I thought I could handle more pixels in the case of large-scale devices.

Thanks to Nuke, I am learning a lot. Thank you
### image Size
image 0 2500 x 2500
image 1 1280 x 857
image 2 300 x 300
|iOS14 scale x3|
|------|
|<img width="1052" alt="스크린샷 2022-10-26 오전 11 34 36" src="https://user-images.githubusercontent.com/111336385/197920906-3827ef86-b49d-4d98-84d3-e76674786a72.png">|

|iOS8 scale x2|
|----|
|<img width="814" alt="스크린샷 2022-10-26 오전 11 35 25" src="https://user-images.githubusercontent.com/111336385/197921024-8233b17c-4cdd-4fa5-aaa0-5f90369e5a72.png">|

**Comment by kean** [comment]
By default, `ImageProcessors.Resize` uses points. You can [use pixels instead](https://kean-docs.github.io/nuke/documentation/nuke/imageprocessing/resize(height:unit:upscale:)) if that's what you are looking for.
