### ISSUE TITLE
AVPlayer.seek(to:): Maybe a feature proposal

### ISSUE THREAD

**Issue by tscdl** [kean/Nuke#618]
Hi Alexander, your library works like a charm. Thanks! 

In my SwiftUI / macOS environment I need to access the **AVPlayer.seek(to:)** method in my cached videos which are currently loaded through **LazyImage(source: String)**.

I was hoping to get access to your player instance by writing a little extension which gets your player through the SwiftUI view hierarchy via **.onCreated { view in }**. I believe my problem is, that your AVPlayer instance is scoped in your **playerLayer.play()** method - if I get it correctly. 

Do you have a quick tip maybe? Or would you consider that as a feature idea?

Regards
Timo

**Comment by kean** [comment]
Hi, there is no particular reason why `AVPlayer` is private. The components based on UIKit, such as `ImageView`, are designed to be open. Adding `seek(to:)` seems like a good idea as well.

You can also register a custom view for playing video if the default one doesn't work for you: [registerContentView(_:)](https://kean-docs.github.io/nukeui/documentation/nukeui/imageview/registercontentview(_:)).

**Comment by tscdl** [comment]
Hi, thanks for the answer and adding the feature label. Could you give a quick example where and how to to `registerContentView(_:)`?

**Comment by kean** [comment]
```swift
ImageView.registerContentView { image in
    if let type = image.type, type.isVideo {
        // Return custom player
    }
    // Return nil for other scenarios
}
```

**Comment by tscdl** [comment]
Thank you, will try.
