### ISSUE TITLE
The app references non-public selectors Nuke.framework/Nuke: removeAll

### ISSUE THREAD

**Issue by abinhho** [kean/Nuke#627]
Hi, I got this error when build release. What should I do?

`The app references non-public selectors in Payload/MyApp.app/Frameworks/Nuke.framework/Nuke: removeAll`

<img width="277" alt="Screenshot 2022-11-22 at 18 15 27" src="https://user-images.githubusercontent.com/9253378/203300627-1744d43e-e243-4a92-9240-ce827276ba66.png">

XCode: 14.1

**Comment by abinhho** [comment]
Sorry, it's duplicated. So close now.

**Comment by vitalii-tym** [comment]
The issue is still here as of Xcode 14.2 and Nuke 10.7.1

@abinhho , the referred repo is not about Nuke, but from a completely different project, which is not responsible for Nuke's code. Therefore I'm not sure it is a duplicate. Could you please double-check and consider reopening the issue.
