### ISSUE TITLE
onCreate modifier is not call on LazyImage

### ISSUE THREAD

**Issue by IssaMansour** [kean/Nuke#629]
The onCreate modifier is not called when using LazyImage with this constructor
`public init(url: URL?, @ViewBuilder content: @escaping (LazyImageState) -> Content)`.

It is only working when using the simple one:
`public init(url: URL?) where Content == Image`

Is there any reason?

My goal was to avoid gif animation by using .isAnimatedImageRenderingEnabled = false in onCreate.

**Comment by IssaMansour** [comment]
Any news @kean?

**Comment by kean** [comment]
If I understood the question correctly, it's by design. When you use `content: @escaping (LazyImageState) -> Content)`, `LazyImage` doesn't know what kind of views you return and when. It can't call `var onCreated: ((ImageView) -> Void)?`.
