### ISSUE TITLE
2 error when installing with cocoapods in swift 2 and xcode 7.2.1

### ISSUE THREAD

**Issue by bagwanshoaib** [kean/Nuke#63]

**Comment by kean** [comment]
[Nuke 3.0](https://github.com/kean/Nuke/releases/tag/3.0.0) requires Swift 2.2 and Xcode 7.3. Please use [Nuke 2.3.0](https://github.com/kean/Nuke/releases/tag/2.3.0) before you update to Xcode 7.3.
