### ISSUE TITLE
ImageIdKey only works for memory caches, but not for disk

### ISSUE THREAD

**Issue by Zimoondo** [kean/Nuke#630]
New to the package, loving it so far. As suggested in the documentation, I am using the "imageIdKey" option in "UserInfoKey" to eliminate access tokens that fluctuate the URL. This is working as the app is running: different urls with the same key are cached to the same image. However, once I close and reopen the app, the old imageIdKey doesn't seem to be working anymore. Requesting for the same "imageIdKey" returns no caches - this is leading me to believe that the imageIdKey is only usable for storing images in memory but not on disk. The following is my code that retrieves and caches the image:

```swift
init(url: String, widthProcess: CGFloat, urlRaw: String) {
        self.request = ImageRequest(
            url: URL(string: url),
            userInfo: [.imageIdKey: urlRaw]
        )
        if let cache = pipeline.cache.cachedImage(for: request) {
            _image = State(initialValue: cache.image)
        }
        else {
            print(" i haven't found it")
        }
    }
```

**Comment by kean** [comment]
Hi, [`imageIdKey`](https://kean-docs.github.io/nuke/documentation/nuke/imagerequest/userinfokey/imageidkey) is used for both memory and disk cache, but it only works with [custom disk cache](https://kean-docs.github.io/nuke/documentation/nuke/cache-layers) (not `URLCache` which is a default). I suggest trying using the custom disk cache.
