### ISSUE TITLE
[Question] Extract GIF to images

### ISSUE THREAD

**Issue by abinhho** [kean/Nuke#631]
For example I have a link GIF file like 
https://i0.wp.com/www.printmag.com/wp-content/uploads/2021/02/4cbe8d_f1ed2800a49649848102c68fc5a66e53mv2.gif?fit=476%2C280&ssl=1

I want to fetch gif image and get list of images frame from gif. Is Nuke supporting to do something like that?

**Comment by kean** [comment]
No, but you get original image data in the response (see [`ImageContainer/data`](https://kean-docs.github.io/nuke/documentation/nuke/imagecontainer/data)). I think you can extract the frames relatively easily using the native SDK.
