### ISSUE TITLE
Handling redirects

### ISSUE THREAD

**Issue by jkelol111** [kean/Nuke#632]
Is there a way to handle redirects for purposes such as adding headers in Nuke/NukeUI? I have overridden the DataLoader URLSessionTaskDelegate by using the code mentioned in https://kean-docs.github.io/nuke/documentation/nuke/dataloader/delegate but it looks like the redirection handling delegate method isn't being called.

**Comment by kean** [comment]
The delegate was designed to support [Pulse](https://github.com/kean/Pulse) and supports only a subset of methods that are needed for logging. Your best bet is to implement a custom data loader (see `DataLoading`). But it's worth extending the delegate though. It's a bit confusing (and undocumented) which methods are and are not supported.

**Comment by kean** [comment]
Starting with [Nuke 11.5.0](https://github.com/kean/Nuke/releases/tag/11.5.0) all delegate methods now get called.
