### ISSUE TITLE
Is Nuke 11 going to be available on CocoaPods?

### ISSUE THREAD

**Issue by iwc** [kean/Nuke#634]
I see that the latest version available on Cocopods is 10.7.1. My project is getting bitten by the validation glitch in #604, so I was looking to upgrade. Is a patched version or Nuke 11 going to be available there? 

Thanks.

**Comment by kean** [comment]
No plans for CocoaPods support, sorry. Duplicate: https://github.com/kean/Nuke/issues/581.
