### ISSUE TITLE
CornerRadius not working for LazyImage

### ISSUE THREAD

**Issue by gurhub** [kean/Nuke#636]
Hi,

easy-to-use library, thank you all for your efforts.

 Is there any reason the code below is not working? Or **how to make a corner radius with the LazyImage image.**

```
LazyImage(url: URL(string: "https://picsum.photos/1024/512")!, resizingMode: .center)
    .cornerRadius(8.0)
    .frame(height: 360, alignment: .center)
```

Best

**Comment by LePips** [comment]
I tested with the snippet and the issue isn't with `cornerRadius`, it's with the size of the photo and the overall container view. The frame is too big for the provided photo and given `resizingMode: .center`, the image is centered while the actual `LazyImage` container has the applied `cornerRadius` value.

The `cornerRadius` has a more noticeable effect if instead given `resizingMode: .aspectFill`.
