### ISSUE TITLE
NukeUI not working from Nuke 11

### ISSUE THREAD

**Issue by tommassbrand** [kean/Nuke#638]
Hello,

I am new with this library. I tried to use package for Nuke 11 for using `LazyImage` and I have got error `not found in the scope` and it needs to use `import NukeUI`. So I am not sure how it could be part of whole Nuke 11 library if it still wants to another import.
BTW: I tried many times reset package cache, update to latest version in Xcode but still not working properly. So I have to use just NukeUI but it is deprecated. Is there anything wrong with my setup?

Thank you in advance.
Tomas

**Comment by kean** [comment]
The main Nuke repo has three modules starting from version 11.0: Nuke, NukeUI, and NukeExtensions. If you'd like to use NukeUI, you need to add both Nuke and NukeUI to your project.

NukeUI used to be a separate package in a separate repo, but it's archived and will be removed in the future.

**Comment by alexacz** [comment]
How to add NukeUI to a project in Xcode? Xcode doesn't offer the option to add NukeUI
