### ISSUE TITLE
CarPlay support?

### ISSUE THREAD

**Issue by raymondwelch33** [kean/Nuke#639]
I've noticed '`KingFisher`' library has `CarPlay` support. 

How about this library? Can we add this before the new year or is that too soon of a deadline?

**Comment by kean** [comment]
I believe it should already compile for CarPlay. If you are thinking about adding `CPListItem` support to `NukeExtensions`, PRs are welcome.

**Comment by kean** [comment]
I'm going to close it because there are no plans to add CarPlay support. But if someone opens a PR, it'll get merged. The best place to add it is `NukeExtensions.
