### ISSUE TITLE
NukeExtensions is not recognized by carthage 

### ISSUE THREAD

**Issue by dabeltranCS** [kean/Nuke#640]
Hi, nice SDK :) 

I'm having problems with nuke compatibility, I have a SDK that supports cocoaPods and Carthage, but depending on the method of implementation I have to handle the NukeExtensions module differently. 
For Carthage I have to add the NukeExtensions .xcFramework, do the NukeExtensions import and call the methods as follows : NukeExtensions.loadImage(..)

However for Cocoa pods it does not recognize the NukeExtensions import, and the methods are called only with Nuke.loadImage(..) 

Can I fix this somehow ?

**Comment by kean** [comment]
> However for Cocoa pods it does not recognize the NukeExtensions import, and the methods are called only with Nuke.loadImage(..)

CocoaPods is no longer supported, sorry.

**Comment by dabeltranCS** [comment]
oh thanks :)
