### ISSUE TITLE
Deprecated ImageRequestConvertible

### ISSUE THREAD

**Issue by gabors** [kean/Nuke#645]
Hi @kean 

I have this utility function that loads images into UIImageView, and now that ImageRequestConvertible is deprecated, how do I refactor the code so that I can load into an image view?
I was trying to follow the docs, but could not find anything relevant.

FWIW your demo app is also referencing the same method here: https://github.com/kean/NukeDemo/blob/faec71f06306566219af9d81d2a43220a1a6df14/Sources/BasicDemoViewController.swift

Thanks!

<img width="800" alt="image" src="https://user-images.githubusercontent.com/3587589/209629291-9c10d8db-6e9d-4138-8f30-8de2071d3329.png">

**Comment by kean** [comment]
Hey, I didn't realize it was still used in `NukeExtensions`. It's been deprecated in most of the rest of the APIs since v11.0.

I'll the v11.6 release for now and release it when it's ready, with a few more additions to the framework. You should not see this warning then.

**Comment by gabors** [comment]
Hey @kean thanks for the amazing framework!
So I'll roll back to 11.5.1 then for now and check out the new stuff when it's ready.
