### ISSUE TITLE
Partially downloaded image

### ISSUE THREAD

**Issue by mperovic** [kean/Nuke#65]
In some situations nk_setImageWith does not download image successfully. After that nuke always presents partially downloaded image.

![img_0268](https://cloud.githubusercontent.com/assets/182573/14528710/23dea0d6-0251-11e6-912e-3b76b453bd75.PNG)

Is there any solution for this case.

**Comment by kean** [comment]
Do you use custom image cache (`ImageDiskCaching`)?

**Comment by mperovic** [comment]
This is my code for setup ImageManager:

	func setupImageManager() {
		self.previousManager = ImageManager.shared
		var managerConf = self.previousManager.configuration
		var loaderConf = (managerConf.loader as! ImageLoader).configuration
		loaderConf.cache = DFDiskCache(name: "Home")
		managerConf.loader = ImageLoader(configuration: loaderConf)
		ImageManager.shared = (ImageManager(configuration: managerConf))
	}

**Comment by kean** [comment]
There is a problem with custom disk cache - it allows partially loaded image data to be stored on disk.

I've already implemented a fix and I'm going to release it soon. For now on, please, avoid using custom disk cache.

**Comment by mperovic** [comment]
Thanks.

**Comment by kean** [comment]
Fixed https://github.com/kean/Nuke/releases/tag/3.1.0
