### ISSUE TITLE
Loading issue with wrong ext of the URL

### ISSUE THREAD

**Issue by KimiChiu** [kean/Nuke#651]
My user has a image link, [https://i.imgur.com/5TjxopD.png](https://i.imgur.com/5TjxopD.png).
But the actual link is [https://i.imgur.com/5TjxopD.gif](https://i.imgur.com/5TjxopD.gif).
Imgur is able to response the correct image no matter what the extension you're using.
The problem is that `Nuke` will show nothing when the extension is not what it should be.
If it's a `GIF` but the file of the url is `PNG`, it will show nothing, if it's a `PNG` but the file of the url is `GIF`, it will show nothing too.
It works well when I was using `Nuke 8`.

```
    weak var previewImage: LazyImageView?
    weak var progressView: CircleProgressView?
    weak var failedView: CircleFailedView?

    func build() {
        isOpaque = true
        clearsContextBeforeDrawing = false

        let previewImage = LazyImageView()
//        previewImage.clipsToBounds = true
        previewImage.imageView.resizingMode = resizingMode
//        previewImage.transition = nil

        let progressView = CircleProgressView()
        let failedView = CircleFailedView()

        previewImage.placeholderView = progressView
        previewImage.failureView = failedView

        addSubview(previewImage)

        self.previewImage = previewImage
        self.progressView = progressView
        self.failedView = failedView
    }

    func load(url: URL) {
        guard let previewImage = previewImage else { return }

        progressView?.level = 0
//            customView.previewImage.image = nil
        previewImage.url = url
        previewImage.onProgress = { [weak self] progress in
            if progress.total < 0 {
                self?.progressView?.level = 10000.0
            }
            else{
                self?.progressView?.level = CGFloat( (Float(progress.completed) / Float(progress.total)) * 10000.0 )
            }

            DispatchQueue.main.async { [weak self] in
                self?.progressView?.setNeedsDisplay()
            }
        }
    }
```

Nuke: 11.5.0
NukeWebP: 1.0.2
XCode: 14.2

**Comment by kean** [comment]
Nuke determines image type based on the magic numbers. The file path is ignored. It recognized the following image https://i.imgur.com/5TjxopD.png as GIF. NukeUI supports GIF playback and it's enabled by default*. If you disable GIF rendering, it displays the images correctly:

```swift
LazyImage(url: URL(string: "https://i.imgur.com/5TjxopD.png"))
    .onCreated { $0.isAnimatedImageRenderingEnabled = false  }
    .frame(width: 120, height: 120)
```

I suggest disabling animated images if you want to enable previous behavior. As for the GIF playback itself, I suggest opening an issue in the original [Gifu](https://github.com/kaishin/Gifu) repo.

> *I'm reevaluating this decision for Nuke 12
