### ISSUE TITLE
Placeholder can't apply ImageProcessors?

### ISSUE THREAD

**Issue by Jyhwenchai** [kean/Nuke#652]
I try to load an image and add `ImageProcessors.Circle()` processor, but processors can't apply to placeholders. So I must adapt the placeholder to a circle style using `layer.cornerRadius`. 

Nuke: 11.5.3

**Comment by kean** [comment]
It works as designed. Placeholder is something you control locally. I suggest using `ImageProcessors.Circle()` directly on the placeholder image.
