### ISSUE TITLE
GIF keeps running in the background

### ISSUE THREAD

**Issue by KimiChiu** [kean/Nuke#653]
I'm using `LazyImageView` right now. I have called `reset` in the `prepareForReuse` of `UITableViewCell`. And it did set `imageContainer` to nil to trigger the `reset` int the `ImageView`.
But I found it only set `_animatedImageView?.isHidden = true` and `_animatedImageView?.image = nil`. It does not call `prepareForReuse` nor `stopAnimatingGIF`. So when it displays a high resolution GIF file, it makes the scrolling stuttering even if the `prepareForReuse` was called.

**Comment by kean** [comment]
Thanks for the report.  Fixed in [version 11.6.1](https://github.com/kean/Nuke/releases/tag/11.6.1).
