### ISSUE TITLE
About the playback count of Gif images

### ISSUE THREAD

**Issue by harumidiv** [kean/Nuke#656]
I want to disable Gif image looping, but I specified false for `isLooping` , `isVideoLooping`, and `videoLoopingEnabled (_ isEnabled: Bool)`, but the Gif image loop did not stop.
Is there a way to stop looping Gif images?

**Comment by kean** [comment]
I don't think this API is currently exposed. I suggest using a framework for displaying GIFs, such as [Gifu](https://github.com/kaishin/Gifu), directly. You can return a custom view in a `LazyImage` [initializer](https://kean-docs.github.io/nukeui/documentation/nukeui/lazyimage/init(request:content:)).

I'm going to close this, as there are no plans to extend/improve GIF support in Nuke itself. On the opposite, I'm planning to remove it and provide a separate Gifu plugin and document some of the ways to customize how images are displayed.
