### ISSUE TITLE
Cache thumbnails of the locally stored images

### ISSUE THREAD

**Issue by storix** [kean/Nuke#66]
I've read the Nuke's docs but I'm still not entirely sure whether it's possible to achieve the following goals using this library:

- Create thumbnails of the locally stored images (in the Documents directory);
- Cache these thumbnails (on disk and in memory);
- Populate the collection view with the thumbnails from the cache using the technique that is described in this [Nuke guide](http://outscope.net/blog/image-preheating).

Thanks in advance for your answer.

**Comment by kean** [comment]
> Create thumbnails of the locally stored images (in the Documents directory);

Create `ImageRequest` with `NSURL` that points to the local image, and provide desired `targetSize` and `contentMode`. Nuke will load image data and resize the image. Images are resized during decompression (see `ImageDecompressor`) so it should be effective (you might want to profile it to make sure).

> Cache these thumbnails (on disk and in memory);

Resized image are stored in memory. There is not straightforward way (that I know of) to store resized images on disk. In my opinion memory cache should be enough, it depends on the specifics or you app though.

> Populate the collection view with the thumbnails from the cache using the technique that is described in this Nuke guide.

Image preheating in Nuke supports image filters (including resizing). All you need to do is to make sure that `targetSize` and `contentMode` in preheating requests match those of the requests that you create for collection view cells.

Hope that makes sense :)

**Comment by storix** [comment]
Thanks for the detailed comment! I think, I got the idea. I'll try it and if everything's working fine I'll close the issue.
