### ISSUE TITLE
_ProgressiveBlurImageProcessor scanNumberKey meaning and value?

### ISSUE THREAD

**Issue by AlXMichL** [kean/Nuke#663]
Hi!

I try to use Nuke for Progressive jpegs display and so implemented a class conforming with the `ImageProcessing` protocol.

That involves implementing the `func process(_ container: ImageContainer, context: ImageProcessingContext) throws -> ImageContainer` method and in the NukeDemo the implementation is based on a `scanNumber` value (`let scanNumber = container.userInfo["com.github/kean/nuke/scan-number"] as? Int`). 

What does the `scanNumber` stands for and which value should we give it in an implementation inspired by the one in the Demo project?

Thanks in advance.

**Comment by kean** [comment]
A progressive image usually contains several scans where the first one is the smallest preview and the last one is the final image. This value is set automatically by the framework as it decodes an image: see [UserInfoKey.scanNumberKey](https://kean-docs.github.io/nuke/documentation/nuke/imagecontainer/userinfokey/scannumberkey). If you want to achieve a similar effect as in the demo, I suggest starting with the `_ProgressiveBlurImageProcessor` implementation and modifying it for your needs.

P.S. It'll probably be great to also add an expected number of scans. Contributions are welcome.
