### ISSUE TITLE
How to retry LazyImage?

### ISSUE THREAD

**Issue by haze** [kean/Nuke#665]
Is there any way to retry fetching a `LazyImage` in NukeUI? My application's server is prone to `429`'ing users (and I have no control over the server), and I'd like to add a button to attempt to refetch the image after some period, or when the user presses a button.

**Comment by kean** [comment]
Unfortunately, no, but it would be nice to add configurable retries.

I suggest two options:

- Use [`FetchImage`](https://kean-docs.github.io/nukeui/documentation/nukeui/fetchimage/) directly. You can think of it as a ViewModel for an image view. It has a [`load()`](https://kean-docs.github.io/nukeui/documentation/nukeui/fetchimage/load(_:)-9f9hu) method that accepts and async function that returns `ImageResponse`. You can leverage it to implement retries.
- [Initialize](https://kean-docs.github.io/nuke/documentation/nuke/imagerequest/init(id:datapublisher:processors:priority:options:userinfo:)) `ImageRequest` with a retrying data publisher
- Implement a custom [`DataLoader`](https://kean-docs.github.io/nuke/documentation/nuke/loading-data) that automatically retries failed requests.

I think the latter is the best option.

**Comment by kean** [comment]
I just wanted to add that for folks who might be looking for ways to retry on network connectivity issues, there is a [waitsForConnectivity](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/2908812-waitsforconnectivity) option on `URLSession` just for that.

**Comment by kean** [comment]
> Update: remove the previous answer because I misunderstood the question.

Yes, if you use `LazyImage` directly, you can do that by re-creating it using `id` to change the view's identity:

```swift
struct ContentView: View {
    @State var imageViewId = UUID()

    var body: some View {
        VStack {
            LazyImage(url: url)
                .id(imageViewId)
            Button("Retry") { imageViewId = UUID() 
        }
    }
}
```

I added it to `LazyImage_Previews` in `nuke-12` branch as well – it's a useful trick.

Alternatively, you can use [`FetchImage`](https://kean-docs.github.io/nukeui/documentation/nukeui/fetchimage) directly. You can think of it as a ViewModel where you have full control over how and when to start the download.
