### ISSUE TITLE
Image AspectFill always center ? but top alignment needed

### ISSUE THREAD

**Issue by jgodonQobuz** [kean/Nuke#666]
Hi Kean !

First of all, thanks a lot for this great Image library, one of the best available nowadays on iOS to fetch / cache / process images (including SwiftUI) 👏

I've a question that I didn't figure out : I'd like to display an Image (with the `LazyImage` from NukeUI) with a `ResizingMode` set to `.aspectFill` in order to extend it on all view but keeping its ratio. This works well except that the resized Image is centered but I would like to be aligned to its top instead of center... For example, if it's a portrait image, the head of the person could be cut and this is a little problematic 😅

Do you have any idea about how to manage this center resizing mode with Nuke/NukeUI ?

Thank you very much for your answer and once again congrats for your great projects (I also enjoy using Pulse Pro 👍)

Best regards

Jeremie

**Comment by kean** [comment]
Hi, have you tried `ImageResizingMode.topRight`? Not sure if that's what you are looking for though. But you can always leverage the [`init(url:content:)`](https://kean-docs.github.io/nukeui/documentation/nukeui/lazyimage/init(url:content:)) initializer to display the image any way you want.

**Comment by kean** [comment]
> I also enjoy using Pulse Pro

I'm glad you do. I'm working on version 3; it's going to be amazing.

**Comment by jgodonQobuz** [comment]
Hi Kean 👋

Just a quick word to tell you how I've fixed my issue about image top alignment for aspectFill... Not sure that this is the best way to do it but it works wall ;)

```swift
LazyImage(url: url) { state in
              if let image = state.image {
                  // by default aspectFill image is aligned on the center but here we want to be aligned on top
                  if resizingMode == .aspectFill, let image = state.imageContainer?.image {
                      Image(uiImage: image).cropped(alignement: .top)
                  }
                  else {
                      image.resizingMode(resizingMode)
                  }
              }
```

```swift
extension Image {
    
    public func cropped(alignement: Alignment) -> some View {
        GeometryReader { proxy in
            self.resizable()
                .scaledToFill()
                .frame(width: proxy.size.width, height: proxy.size.height, alignment: alignement)
                .clipped()
        }
    }
}
```

Have a great week-end 

Cheers 🤙

Jeremie
