### ISSUE TITLE
Bump the version number

### ISSUE THREAD

**Issue by Havhingstor** [kean/Nuke#668]
Hi!

I wanted to ask if it would be possible to bump the version number to 11.6.2 to allow dependent repositories to update their dependency easily without having to reference the specific commit or the whole branch.

Thanks

**Comment by kean** [comment]
Absolutely, I'll push a patch release shortly.

**Comment by kean** [comment]
Version [11.6.2](https://github.com/kean/Nuke/releases/tag/11.6.2) is out.
