### ISSUE TITLE
NukeUI - How to install?

### ISSUE THREAD

**Issue by alexacz** [kean/Nuke#676]
How to add NukeUI package to a project in Xcode?

**Comment by kean** [comment]
Hi, @alexacz. You can use Swift Package Manager or, starting with Nuke 12, it'll also provide precompiled xcframeworks.

**Comment by alexacz** [comment]
Did someone try to add NukeUI via Xcode 14?
There are no option to select NukeUI product. Xcode always add Nuke product only.

Here an example how to add Firebase to Xcode: https://github.com/firebase/firebase-ios-sdk/blob/master/SwiftPackageManager.md

Why don’t I see the product selection option while adding Nuke library?

**Comment by kean** [comment]
It should look something like this:

![Screenshot 2023-02-24 at 8 30 12 AM](https://user-images.githubusercontent.com/1567433/221190666-9d063bcb-a307-4898-964b-078e170b9ff7.png)

Try clearing the Derived Data. It might be showing cached data from the previous versions. NukeUI framework was added fairly recently in Nuke 11.

**Comment by x-creates** [comment]
Using an explicit version helps here.

![20230327@071153@2x](https://user-images.githubusercontent.com/64649350/227867033-bb28921b-5e05-4518-ae43-c50c8918a92e.png)
