### ISSUE TITLE
Migration guide link in Nuke 12.0 GitHub release is incorrect

### ISSUE THREAD

**Issue by sebj** [kean/Nuke#679]
Small thing, but [the link to the migration guide](https://github.com/kean/Nuke/blob/nuke-12/Documentation/Migrations/Nuke%2012%20Migration%20Guide.md) in the [Nuke 12.0 GitHub release notes](https://github.com/kean/Nuke/releases/tag/12.0.0) is incorrect/broken – seems like it should perhaps point to https://github.com/kean/Nuke/blob/main/Documentation/Migrations/Nuke%2012%20Migration%20Guide.md

**Comment by kean** [comment]
Yes, wrong branch. Thanks for pointing it out. Fixed.
