### ISSUE TITLE
UICollectionViewCell Images displayed are incorrect

### ISSUE THREAD

**Issue by bryan1anderson** [kean/Nuke#68]
I've been having an issue and haven't found a solution. Hoping I'm doing something obviously wrong and someone might know how I can fix this.

Issue:
I have a UICollectionView with roughly 20 cells. I'm using Nuke to load an individual image on each cell from a URL.

Images are repeated, and sometimes just completely wrong. I've verified that the correct image URL is being used for each cell, but the actual image that shows up is definitely not the right one in the URL.

Here is an example of my code:
 inside `    func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell `

     cell.imageView.image = nil
     if let urlString = data["photoURL"] as? String, 
     url = NSURL(string: urlString) {
                    cell.imageView.nk_setImageWith(url)
                } else {
                    cell.imageView.image = UIImage(named: "empty-image")
                }

**Comment by kean** [comment]
`nk_setImageWith(:)` method cancels previous task registered with the cell. If you don't call this method on a cell (like you do in `else`) the previous task won't get cancelled and the "empty-image" will be replaced with the loaded image. This might be causing the issue. Try calling `nk_cancelLoading` on your cell before setting an 'empty-image'.
