### ISSUE TITLE
How do I play video in Nuke 12?

### ISSUE THREAD

**Issue by JasonYHZ** [kean/Nuke#683]
```
 LazyImage(request:.init(url: URL(string: "https://kean.github.io/videos/cat_video.mp4")) ) { state in
            if state.error != nil {
                Text(state.error!.localizedDescription)
            }   
        }
```

error: 
The operation couldn't be completed.

(Nuke.lmagePipeline.Error error 2.)

**Comment by vovander** [comment]
Also have same error. Demo app uses master branch and its wotking, but last changes in release breaks video displaying

**Comment by JasonYHZ** [comment]
> Also have same error. Demo app uses master branch and its wotking, but last changes in release breaks video displaying

Should I wait for the version update or switch directly to the master branch?

**Comment by kean** [comment]
The video support was removed from the main Nuke module in [Nuke 12](https://github.com/kean/Nuke/releases/tag/12.0.0). You and find some rationale in the release notes. There is a new `NukeVideo` module you could use. It's not fully-fleshed out yet, and PRs are welcome. I'm not using it myself, which is also why I want to separate it from the main module.

**Comment by JasonYHZ** [comment]
> The video support was removed from the main Nuke module in [Nuke 12](https://github.com/kean/Nuke/releases/tag/12.0.0). You and find some rationale in the release notes. There is a new `NukeVideo` module you could use. It's not fully-fleshed out yet, and PRs are welcome. I'm not using it myself, which is also why I want to separate it from the main module.

Thank you for your reply. I have selected NukeVideo when using Nuke12, and then I judge the file type in LazyImage and play it according to the usage described in "Nuke12 Migration Guide". But when I use mp4 files, I will directly report an error and prompt me "(Nuke.lmagePipeline.Error error 2.)"

In the same scene, I showed that gif was successful.

**Comment by kean** [comment]
> (Nuke.lmagePipeline.Error error 2.)

This error happens because the video decoder no longer gets registered by default. I updated the [migration guide](https://github.com/kean/Nuke/blob/main/Documentation/Migrations/Nuke%2012%20Migration%20Guide.md#nukevideo) to reflect that. You can also check the updated [NukeDemo](https://github.com/kean/NukeDemo), in which I fixed the video support. Please also make sure you use [Nuke 12.1](https://github.com/kean/Nuke/releases/tag/12.1.0).
