### ISSUE TITLE
LazyImageView failure Image property does not use the set image processors

### ISSUE THREAD

**Issue by gtokman** [kean/Nuke#685]
### Desc
I set a `RoundedCorners` processor on the `LazyImageView` and if the image is downloaded successfully it works well but on error, the processor is not applied to the failure image property.

```swift
    @objc var borderRadius: NSNumber? = nil {
        didSet {
            lazyImageView.processors = [
                ImageProcessors.RoundedCorners(radius: CGFloat(borderRadius?.intValue ?? 0)),
            ]
        }
    }
    
   @objc var failureImage: String? {
        didSet {
            guard let failureImage else {
                return
            }
            DispatchQueue.global(qos: .userInteractive).async {
                let image = UIImage(blurHash: failureImage, size: .init(width: 32, height: 32))
                DispatchQueue.main.async { [weak self] in
                    self?.lazyImageView.failureImage = image
                }
            }
        }
    }
```

### Example
<img src="https://user-images.githubusercontent.com/12258850/227811182-2f62470a-b19c-4142-9b79-7b348b700e21.gif" width="300px" />

**Comment by kean** [comment]
The processors are applied only to the fetched image, which is a good default for most users. I suggest using `ImageProcessors.RoundedCorners` directly when preparing a failure image.

Related: https://github.com/kean/Nuke/issues/652
