### ISSUE TITLE
v11.3.1 compiler warning: heterogeneous collection literal 

### ISSUE THREAD

**Issue by paulz** [kean/Nuke#689]
Thank you for the awesome library!

We are getting this warning while compiling Xcode project with 

StreamChatSwiftUI - https://github.com/getstream/stream-chat-swiftui @ 4.30.0

```
.../build/derivedData/SourcePackages/checkouts/Nuke/Sources/Nuke/Internal/Graphics.swift:328:19: heterogeneous collection literal could only be inferred to '[CFString : Any]'; add explicit type annotation if this is intentional
    let options = [
                  ^
```

has this been already fixed in v12?

**Comment by kean** [comment]
Yes, it's fixed in version 12.

**Comment by paulz** [comment]
Thank you @kean, our root issue is this: https://github.com/GetStream/stream-chat-swiftui/issues/301
