### ISSUE TITLE
Resize LazyImage

### ISSUE THREAD

**Issue by tanlucvo** [kean/Nuke#691]
I try to make image fill in frame, but this image when display has size 500x500
` LazyImage(url: URL(string: "https://picsum.photos/500/500"))
            .frame(width: 100, height: 100)
            .aspectRatio(contentMode: .fill)
`

**Comment by kean** [comment]
The underlying `Image` is not resizable by default, which matches how the native `AsyncImage` works. Please check [the examples](https://kean-docs.github.io/nukeui/documentation/nukeui/lazyimage) to see how to make the image resizable.

Here's an example:

```swift
LazyImage(url: URL(string: "https://example.com/image.jpeg")) { state in
    if let image = state.image {
        image.resizable().aspectRatio(contentMode: .fill)
    } else if state.error != nil {
        Color.red // Indicates an error
    } else {
        Color.blue // Acts as a placeholder
    }
}
```
