### ISSUE TITLE
New 12.x ImageDecoders.Default scale behaviour

### ISSUE THREAD

**Issue by AgapovOne** [kean/Nuke#692]
Hello. We are using your library in our code and found a changed behaviour.
commit https://github.com/kean/Nuke/commit/81504b7b2ac8a567632007defd179618ec238fed led to change where our images are scaled by device scale when we actually want to get size@scale (like 320@3x), but we get 960*3 when we request a photo of 960 width/height.

I changed a demo a little to show the change that we have.
We don't use a custom content for LazyImage yet.

<details><summary>Screenshot showing an issue</summary>
<img width="1000" alt="Screenshot 2023-04-14 at 15 29 49" src="https://user-images.githubusercontent.com/4246455/232023264-e940eb7b-2437-4d94-b98a-d7c185187563.png">
</details>

1. We request an image of 320*screen scale (960)
2. We get an image that is 960 w/h, but the library thinks it's scale is 1, so it gives us 960 image with a bad quality.
3. We can't fit it into our LazyImage without any changes like using `.aspectRatio(.fill)`

---

That changes a behaviour of our loaders so we have to adapt.
I just want to make sure that this isn't some bug and it was intended change.

If so, there is an issue with another function too.
Now we have to always provide any raster (jpg, png) image request with a `scaleKey` userInfo. Vector images are fine.
```swift
try await ImagePipeline.shared.image(for: ImageRequest(
  url: url, // image with requested scaled size
  userInfo: [
    .scaleKey: UIScreen.main.scale
  ]
))
```

---

That also means the [documentation for scaleKey](https://github.com/kean/Nuke/blob/92359a6eec89dca6d9c01e5523bf4c72477b958a/Sources/Nuke/ImageRequest.swift#L353) isn't true: 

>  The image scale to be used. By default, the scale matches the scale of the current display.

Default now is 1, we have to provide a proper scale every time for raster images.

--- 

[The Migration Guide](https://github.com/kean/Nuke/blob/main/Documentation/Migrations/Nuke%2012%20Migration%20Guide.md) doesn't mention this change, but we had to investigate what happened.

I think this change deserves a mention in Migration Guide :)

---

So the question is:

Will this behaviour remain, and we have to adapt our code?
1. wrap LazyImage with our own `.resizable()` behaviour
2. provide scale every time we download raster image

Ready to help with tests, reproduction code, updating documentation.

**Comment by kean** [comment]
> I just want to make sure that this isn't some bug and it was intended change.

The previous behavior was to set the scale of _every_ image to the device scale by default, which doesn't make sense. So, yes, it was an intentional change, and it now matches how other frameworks and the native `AsyncImage` work.

> I think this change deserves a mention in Migration Guide 

Absolutely, updated. It has been mentioned in the release notes as well.

It might also be worth providing a global configuration option to revert to the previous behavior to ease the migration.
