### ISSUE TITLE
Is it possible to support animated webp?

### ISSUE THREAD

**Issue by KimiChiu** [kean/Nuke#694]
I'm using NukeWebP plugin.
I have this url: https://media1.giphy.com/media/AOgwrHx4o49v2ZisoR/giphy.webp
It's showing a static image by Nuke, but an animated image by Fresco(an Android library).
Is it possible to add support of animated webp files in the future?

**Comment by kean** [comment]
Hi, Nuke does not provide a built-in solution for displaying animated images. For example, the recommended solution for displaying GIFs is [Gifu](https://github.com/kaishin/Gifu). I haven't done any research in terms of WebP, but I'm sure there are libraries that support it. It's out of the scope of the framework itself. You can learn more in [Supported Image Formats](https://kean-docs.github.io/nuke/documentation/nuke/supported-image-formats).
