### ISSUE TITLE
Add async methods that support progress

### ISSUE THREAD

**Issue by larryonoff** [kean/Nuke#697]
It would be great having Swift Concurrency method that supports progress reporting.

Please see some concept below.

```swift
public enum ImageRequestEvent<Value> {
  case progress(completed: Int64, total: Int64)
  case result(Value)
}

extension ImagePipeline {
  public func image(
    for request: ImageRequest
   ) -> AsyncThrowingStream<ImageRequestEvent<PlatformImage>>
}
```

**Comment by kean** [comment]
Hey, have you tried using the new `imageTask(with:)` method introduced in version 12?

```swift
    func loadImage() async throws {
        let imageTask = ImagePipeline.shared.imageTask(with: url)
        for await progress in imageTask.progress {
            // Update progress
        }
        imageView.image = try await imageTask.image
    }
```

**Comment by larryonoff** [comment]
> Hey, have you tried using the new [`imageTask(with:)`](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/imagetask(with:)-6aagk) method introduced in version 12?
> 
> 
> 
> ```swift
> 
>     func loadImage() async throws {
> 
>         let imageTask = ImagePipeline.shared.imageTask(with: url)
> 
>         for await progress in imageTask.progress {
> 
>             // Update progress
> 
>         }
> 
>         imageView.image = try await imageTask.image
> 
>     }
> 
> ```

Wow. Thanks! Didn't see it at once.
