### ISSUE TITLE
Problem on LazyImage.swift

### ISSUE THREAD

**Issue by kellvembarbosa** [kean/Nuke#698]
Hello,

I would like to express my gratitude for the excellent package.

However, I'm facing a bug during compilation for debug on watchOS. When trying to run the application in debug mode on a WatchOS device, it doesn't work due to the use of "ImageProcessors.GaussianBlur()" at line 249. Unfortunately, this function is not available for WatchOS, which hinders testing during development.

```swift
.processors(isBlured ? [ImageProcessors.GaussianBlur()] : [])
```

**Comment by kean** [comment]
Hi, it uses [CoreImage](https://developer.apple.com/documentation/coreimage) framework which is not available on watchOS. You'll need to use conditional compilation:

```swift
#if !os(watchOS)
.processors(isBlured ? [ImageProcessors.GaussianBlur()] : [])
#endif
```
