### ISSUE TITLE
Synchronous loading

### ISSUE THREAD

**Issue by yonaskolb** [kean/Nuke#699]
Hello, thanks for the project.

This is being used in an app I'm helping out with. I'm implementing snapshot tests, and would like to be able to load the images synchronously so they are included in the snapshot. I know ideally we'd be pointing to local images, but we have a lot of existing mocks to deal with. Do you have any guidance about how to best achieve this within Nuke? Perhaps providing a custom pipeline, synchronously prefetching, or loading outside of the framework and stuffing images in the cache?

**Comment by kean** [comment]
Hi,

Most of the views provided by the framework – `NukeUI.LazyImage`, `NukeExtensions`, etc. – load images synchronously if they are available in the memory cache. The easiest option would be removing the `ImageCache` limits and pre-populating it with images. It will require minimal code changes.

> I have a task in the backlog to add a `permanent` parameter to `ImageCache` entries to allow disabling eviction on a per-entry level. It's not yet implemented.

There is another option. While `ImagePipeline` is not a protocol, `ImageCaching` is. You can create a custom `ImageCaching` that would synchronously fetch images from disk or even network.

**Comment by yonaskolb** [comment]
Great, thank you for your suggestions @kean
