### ISSUE TITLE
Race condition with cancelLoading()

### ISSUE THREAD

**Issue by adomanico** [kean/Nuke#70]
We were seeing an issue where the previous image task wasn't being cancelled (at the correct time?) on nk_setImage causing incorrect images to be loaded on the imageView.

I think the culprit may be the dispatch_async block in ImageViewLoadingController

```swift
 /// Cancels current task.
    public func cancelLoading() {
        if let task = imageTask {
            imageTask = nil
            // Cancel task after delay to allow new tasks to subscribe to the existing NSURLSessionTask.
            dispatch_async(dispatch_get_main_queue()) {
                task.cancel()
            }
        }
    }
```

Calling .nk_imageTask?.cancel() directly has fixed the issue for us as a workaround.

Let me know if you need any other details

**Comment by kean** [comment]
That's for pointing that out. I agree that it was not a particular good idea and the `async` should be removed.
