### ISSUE TITLE
How to provide credentials for URLAuthenticationChallenge?

### ISSUE THREAD

**Issue by aruffolo** [kean/Nuke#703]
Hi, I could not find and example where I can provide credentials for the method

`optional func urlSession(
    _ session: URLSession,
    task: URLSessionTask,
    didReceive challenge: URLAuthenticationChallenge,
    completionHandler: @escaping @Sendable (URLSession.AuthChallengeDisposition, URLCredential?) -> Void
)`

that should be implemented by a UrlSessionDelegate.

From what I can see I'd have to implement a DataLoader from scratch, isn't it?

Thanks

**Comment by kean** [comment]
`DataLoader` has a [`delegate`](https://kean-docs.github.io/nuke/documentation/nuke/dataloader/delegate) property that lets you override any of the `URLSession` delegate methods.
