### ISSUE TITLE
LazyImage loading issue

### ISSUE THREAD

**Issue by alexoverseer** [kean/Nuke#704]
Greetings,
We have integrated NukeUI into our SwiftUI application, and a few customers have contacted us regarding an issue with image loading. According to them, certain photos are not being fully loaded.
Our integration process is simple and did not involve any customized options. Unfortunately, none of our team members have been able to replicate the problem, even when using NetworkLinkConditioner on a device.

Do you have any suggestions or ideas that we could explore to resolve this matter?
Current SDK version: 12.1 and observed since 10 version

Many thanks!

 ![github](https://github.com/kean/Nuke/assets/16474768/1e9247d1-64c7-409e-9257-dbd771e45ce2)

```
public struct ImageView: View {
    ...

    private static let pipeline = ImagePipeline {
        $0.dataLoader = DataLoader(configuration: {
            DataLoader.defaultConfiguration
        }())

        $0.imageCache = ImageCache()
        $0.dataCache = try? DataCache(name: "com.custom.name")
    }

    ...

    public var body: some View {
        ZStack {
            Rectangle()
                .fill(backgroundColor)
            LazyImage(
                url: URL(string: source),
                transaction: .init(animation: .easeIn)
            ) { state in
                if let image = state.image {
                    GeometryReader {
                        image
                            .resizable()
                            .aspectRatio(contentMode: contentMode)
                            .frame(width: $0.size.width, height: $0.size.height)
                            .clipped()
                    }
                } else if state.error != nil {
                    // Error
                    Color.gray
                } else {
                    // Placeholder
                    ZStack {
                        ProgressView()
                            .progressViewStyle(
                                CircularProgressViewStyle(tint: progressColor)
                            )
                    }
                }
            }
            .pipeline(ImageView.pipeline)
        }
    }
}
```

**Comment by kean** [comment]
Hi, it may be server-specific. There are a couple of scenarios I can think of:

- Server completes the request without sending full data; incorrect content size
- Incorrect [resumable downloads](https://kean.blog/post/resumable-downloads) support on the server
- HTTP caching proxy issue

There are no known related issues in the framework.

**Comment by alexoverseer** [comment]
Thank you for the tips. Will have a sync with our backend team. 

p.s. Great library!
