### ISSUE TITLE
Add visionOS support

### ISSUE THREAD

**Issue by theedov** [kean/Nuke#706]
<img width="1409" alt="Screenshot 2023-06-22 at 10 32 30 am" src="https://github.com/kean/Nuke/assets/30866972/e3713a95-6c37-43bb-8878-bdc689ec8060">

**Comment by barnard-b** [comment]
There are two build errors for visionOS: This one in Graphics.swift and another in ImageDecoders+Video.swift

As a temporary solution you can open those files in Visual Studio Code and edit them (you will need to select overwrite when saving). To be clear, this is only a temporary solution and the scale value is just a guess, but it should allow it to compile.

```swift
struct Screen {
    #if os(xrOS)
    /// 2 is just a guess, do not depend on it.
    static var scale: CGFloat { 2 }
    #elseif os(iOS) || os(tvOS)
    /// Returns the current screen scale.
    static var scale: CGFloat { UIScreen.main.scale }
    #elseif os(watchOS)
    /// Returns the current screen scale.
    static var scale: CGFloat { WKInterfaceDevice.current().screenScale }
    #elseif os(macOS)
    /// Always returns 1.
    static var scale: CGFloat { 1 }
    #endif
}
```
(UIScreen is not available in xrOS)

```swift
private func makePreview(for data: Data) -> PlatformImage? {
    #if os(xrOS)
    return nil
    #else
    let asset = AVDataAsset(data: data)
    let generator = AVAssetImageGenerator(asset: asset)
    guard let cgImage = try? generator.copyCGImage(at: CMTime(value: 0, timescale: 1), actualTime: nil) else {
        return nil
    }
    return PlatformImage(cgImage: cgImage)
    #endif
}
```
(copyCGImage is not available in xrOS)

**Comment by kean** [comment]
I wonder if there is a way to ship it without introducing warnings on Xcode 14.

![Uploading Screenshot 2023-06-21 at 10.07.20 PM.png…]()

I'll create a branch for now.

**Comment by theedov** [comment]
They might even change it to `visionOS` in the upcoming betas.

**Comment by kean** [comment]
Do you know if SPM is supported? I can't get the package manifest to compile after adding `.xrOS(.v1)` – doesn't recognize it.

**Comment by kean** [comment]
Preliminary xrOS support is now available in `xcode-15` branch.
- PR: https://github.com/kean/Nuke/pull/707
- Version: https://github.com/kean/Nuke/releases/tag/12.2.0-beta.1

**Comment by frlefebvre** [comment]
The last Xcode beta seems to have introduced a few more issues. At first glance, they seem to mostly be due to using AppKit instead of UIKit. Like here:

<img width="885" alt="Screenshot 2023-08-10 at 12 02 19" src="https://github.com/kean/Nuke/assets/6973873/c27927ef-1e1e-47ad-a5c2-98b647bf7581">

**Comment by drmarkpowell** [comment]
Just putting it out there that the prompt attention you are giving this issue encouraged me to become a sponsor! Keep up the great work :) Looking forward to using Nuke in my visionOS app soon.

**Comment by kean** [comment]
I appreciate it, @drmarkpowell. It is in the works. I already have the latest Xcode beta and was planning to push the new pre-release version soon.

**Comment by kean** [comment]
[Version 12.2 (Beta 2)](https://github.com/kean/Nuke/releases/tag/12.2.0-beta.2) fixes the new compilation errors in Xcode 15 Beta 6.

The plan for the future version is to remove as many of the `#if os(...)` checks as possible and replace them with `#if canImport(...)`. 

I'm yet to figure out how to add SPM support, especially in a way that won't break Xcode 14 compatibility. Any information on that is welcome.
