### ISSUE TITLE
Documentation is obsolete

### ISSUE THREAD

**Issue by Gargo** [kean/Nuke#712]
For example:
https://kean-docs.github.io/nukeextensions/documentation/nukeextensions/imageviewextensions/
This code doesn't work:
`Nuke.loadImage(with: url, into: cell.imageView)`

The following code works only:
`NukeExtensions.loadImage(with: url, into: cell.imageView)`
or
`loadImage(with: url, into: cell.imageView)`

**Comment by kean** [comment]
Thanks for the report. Fixed!
