### ISSUE TITLE
ImageRequest with async URL block

### ISSUE THREAD

**Issue by Sam-Spencer** [kean/Nuke#714]
Love the improvements and new initializers in Nuke 12! I noticed there's a new-ish initializer on `ImageRequest`:

```swift
public init(
    id: String,
    data: @Sendable @escaping () async throws -> Data,
    processors: [any ImageProcessing] = [],
    priority: Priority = .normal,
    options: Options = [],
    userInfo: [UserInfoKey: Any]? = nil
)
```

Is it possible to create a similar initializer which accepts a `URL` as the return instead of `Data`? I have some asynchronous overhead for generating image URLs, but still want to take advantage of Nuke's amazing built-in networking and caching pipelines.

Perhaps something like this:

```swift
public init(
    id: String,
    url: @Sendable @escaping () async throws -> URL,
    processors: [any ImageProcessing] = [],
    priority: Priority = .normal,
    options: Options = [],
    userInfo: [UserInfoKey: Any]? = nil
)
```

I can't quite setup my own initializer, it seems — short of forking the repo — because some of the initialized values (e.g. `ref`) are private (makes sense). A custom `DataLoader` seems like one viable solution, but is really overkill. Any suggestions on how to go about doing this with the current version of Nuke? Or is this something that might need some deeper changes?

**Comment by kean** [comment]
Hey,

I would suggest fetching the URLs outside of Nuke and then using some of its APIs. Here's a rough prototype; almost pseudocode:

```swift
func getURL() async throws -> URL {
    fatalError()
}

struct YourImageView: View {
    @State var url: URL?

    var body: some View {
        LazyImage(url: url)
            .task {
                self.url = try? await getURL()
            }
    }
}
```
