### ISSUE TITLE
Nuke's UserDefaults value with key containing app path

### ISSUE THREAD

**Issue by Pash237** [kean/Nuke#717]
Nuke stores last sweep interval in UserDefaults and uses full path as a key.  
But since iOS 8(?) app data path changes every re-install. This causes creating a new key for each install.

It's not that critical for production since re-installs didn't happen very ofter, but annoying while developing:
<img width="500" alt="image" src="https://github.com/kean/Nuke/assets/277626/edef222e-d92c-444f-81a9-7aed094f8d77">

**Comment by kean** [comment]
Great catch, thanks! It didn't feel right, and now it's clear why. 

In the light of the [policies](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) on the use of these APIs, it a makes even more sense to rework it. I'll push an update later today.

**Comment by kean** [comment]
I opened a PR with a fix https://github.com/kean/Nuke/pull/718 and would appreciate a quick review.
It's exactly how it's implemented in [Pulse](https://github.com/kean/Pulse); not sure why I even went with UserDefaults.

**Comment by kean** [comment]
Fixed in [version 12.1.5](https://github.com/kean/Nuke/releases/tag/12.1.5).
I appreciate the report, thanks!
