### ISSUE TITLE
Images are not being cached

### ISSUE THREAD

**Issue by adamvnovak** [kean/Nuke#719]
The following code is printing "Contains false" for me. How is this even possible? This is the simplest possible example, where I load an image into an imageView using the NukeExtension on the shared pipeline.

```
let request = ImageRequest(url: photo.url)
var options = ImageLoadingOptions.shared
options.pipeline = .shared
NukeExtensions.loadImage(with: request, options: options, into: photoImageView) { result in
    print("Contains", ImagePipeline.shared.cache.containsCachedImage(for: request))
}
```

The image does properly load, but it's not being saved to the cache. When I refresh the tableview and run this exact same code, the image is reloaded again.

I don't do any other configuration for Nuke anywhere else in the app.

**Comment by kean** [comment]
Hey, how large is the image? By default, the default memory cache (`Nuke.ImageCache`) and the default disk cache (`Foundation.URLCache`) won't store images that are too large. So that's one possible explanation.

**Comment by bryan-vh** [comment]
How large is too large @kean?

**Comment by bryan-vh** [comment]
I've been seeing issues with LazyImage and images continuously reloading in my app as well. I'm using the standard configuration that comes with the package. Any help here would be great!

**Comment by kean** [comment]
For `ImageCache`, it's 10% of the cost limit, which is [configurable](https://kean-docs.github.io/nuke/documentation/nuke/imagecache/entrycostlimit). For `Foundation.URLCache`, I can't find it right now but it's also documented that it ignored the responses that are to large.

**Comment by bryan-vh** [comment]
The images I'm loading right now are ~500 kb, is that large enough to get ignored?

**Comment by kean** [comment]
> The images I'm loading right now are ~500 kb, is that large enough to get ignored?

No, it should be good.

> I've been seeing issues with LazyImage and images continuously reloading in my app as well.

Check out the caching guide. The `Foundation.URLCache` (used by default) relies on HTTP caching, which means that the server has to provide the correct HTTP cache control headers in order for it to work. I'd suggest trying [.withDataCache](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/configuration-swift.struct/withdatacache) pipeline configuration. More details are available in the linked articles.

There is only one memory cache and it's pretty simple. As long as the URLs and the [processors](https://kean-docs.github.io/nuke/documentation/nuke/imagerequest/processors) are the same,

**Comment by bryan-vh** [comment]
And then I can just pass that pipeline to the LazyImage API, correct?

**Comment by kean** [comment]
Yes, but I find it easier to change the shared [pipeline](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline):

```swift
ImagePipeline.shared = ImagePipeline(configuration: .withDataCache)
```

**Comment by bryan-vh** [comment]
Awesome, thanks!
