### ISSUE TITLE
a crash with 3.1.2

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#72]
I saw a crash with Nuke 3.1.2 today. I cannot reproduce it but this crash has never been seen before. I wonder if it is newly introduced?

I didn't do much of a thing but just started my app and the app was trying to load some images for its tableView. I have started my app hundreds of times before and this is the first time I saw it happen.

I attached a screenshot for the crash stack.

<img width="1853" alt="nuke312_crash" src="https://cloud.githubusercontent.com/assets/5201083/16880244/e071a382-4ae6-11e6-84f4-4612a443a54b.png">

**Comment by kean** [comment]
Yeah, I guess it was introduced in 3.1.2. There were some changes in `ImageViewLoadingController` - it now cancels tasks registered with it synchronously. Apparently, I've missed something and changed the previous behaviour.

**Comment by joe528** [comment]
I actually have no completion handler. My call to Nuke to set images is very simple as below:

    let request = ImageRequest(URLRequest: NSURLRequest(URL: nsurl))
    cellBase.postView.image.nk_setImageWith(request)

**Comment by kean** [comment]
I found a serious problem in an implementation of `loader(loader: ImageLoading, task: ImageTask, didCompleteWithImage image: Image?, error: ErrorType?, userInfo: Any?)` method in `ImageManager`. It was overwriting `response` of `ImageTask` without synchronization and without checking current task's state. This seems like the only possible reason that could lead to EXC_BAD_ACCESS that you reported. It's hard to reproduce since it's a synchronization problem.

I'm going to release Nuke 3.1.3 today. If you see this problem again, please let me know.

I hope I didn't miss anything and I hope I would be able to refactor most of it for Nuke 4.

**Comment by joe528** [comment]
Sure, I will keep an eye on it after I updated to 3.1.3

So there is a plan for Nuke 4? What would be the main difference/improvement?

**Comment by kean** [comment]
Yeah, I'm going to start working on Nuke 4 when Swift 3 it out. I'm actually not programming in Swift at all until Swift 3 is out :)

I'm not planning a lot of major changes. Just update for Swift 3; probably adoption of new Swift API Design Guideline; a couple of small, but breaking changes to make things more simple. I keep it all in a private (it's a total mess) Trello board.

I would also like to investigate making Nuke more generic. The "pipeline" that is implemented in Nuke might be useful not just for images, but for some other resources as well (like small videos). There is at least some demand ([#1](https://github.com/Alamofire/AlamofireImage/issues/113), [#2](https://github.com/kean/Nuke/issues/62)) for this feature. If it fits nicely in a current design, I'll implement it.

**Comment by kean** [comment]
`ImageManager` guarantees that there is a `response` by the time it's needed. It's just a private logic check, nothing to worry - it already used force unwrap before. In the meantime, I'll try to refactor it away in v4.

**Comment by kean** [comment]
Actually, I've started working on it and realised that it needs a complete rewrite because my Swift seemed to evolved a lot 😄 btw, asserts are already gone https://github.com/kean/Nuke/tree/nuke4
