### ISSUE TITLE
iOS 17 Crash - UIImage.draw(inCanvasWithSize:drawRect:)

### ISSUE THREAD

**Issue by lucasecf** [kean/Nuke#725]
Seems like there's a new crash exclusive on iOS 17 inside CoreGraphics, in a code used by Nuke. iOS 16 and below users are not affected.

Even though it's not extremely significant (affects ~0.2% of our app users), it's enough to bother.

Would anyone have any suggestion on how to fix or avoid the issue (maybe some configuration option to avoid the code causing problems?) until we wait for Apple to fix it (if ever)?

Not sure if relevant, but the image format we are using is `avif`.

[This is the line of code/place inside Nuke](https://github.com/kean/Nuke/blob/81b8b5281b40e5f2281ffc426a8b0ab2db898d25/Sources/Nuke/Internal/Graphics.swift#L140C1-L140C1) where the crash happens:

![Screenshot 2023-09-26 at 12 16 37](https://github.com/kean/Nuke/assets/1894401/c9eebf2d-3601-46b1-902e-1466820eec86)

Here's a stack trace example:

```
Crashed: com.apple.coremedia.decompressionsession.pendingframequeue
0  VideoToolbox                   0x30e25c __VTDecompressionSessionRemote_DecodeTile_block_invoke_2 + 60
1  libdispatch.dylib              0x4300 _dispatch_client_callout + 20
2  libdispatch.dylib              0x136b4 _dispatch_lane_barrier_sync_invoke_and_complete + 56
3  VideoToolbox                   0x30e0e0 VTDecompressionSessionRemote_DecodeTile + 696
4  CMPhoto                        0x15b70 VTTileDecompressionPluginClass_decode + 376
5  CMPhoto                        0x1b974 _decodeItem + 6008
6  CMPhoto                        0xb78c _applyDecodeStrategy + 396
7  CMPhoto                        0x7055c _decodeImage + 452
8  CMPhoto                        0x6c418 _createImageForIndex + 472
9  CMPhoto                        0x273b0 CMPhotoDecompressionContainerCreateImageForIndex + 280
10 ImageIO                        0x1cbe74 HEIFReadPlugin::copyImageBlockSetImp(InfoRec*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 2208
11 ImageIO                        0x1ce2dc HEIFReadPlugin::decodeImageImp(IIODecodeParameter*, IIOImageType, __IOSurface**, __CVBuffer**, CGImageBlockSet**) + 616
12 ImageIO                        0x3955c IIOReadPlugin::callDecodeImage(IIODecodeParameter*, IIOImageType, __IOSurface**, __CVBuffer**, CGImageBlockSet**) + 800
13 ImageIO                        0x38e90 IIO_Reader::CopyImageBlockSetProc(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 688
14 ImageIO                        0x38af8 IIOImageProviderInfo::copyImageBlockSetWithOptions(CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 744
15 ImageIO                        0x38728 IIOImageProviderInfo::CopyImageBlockSetWithOptions(void*, CGImageProvider*, CGRect, CGSize, __CFDictionary const*) + 804
16 CoreGraphics                   0x5cdd8 imageProvider_retain_data + 92
17 CoreGraphics                   0x47098 CGDataProviderRetainData + 80
18 CoreGraphics                   0x470e0 provider_for_destination_retain_data + 28
19 CoreGraphics                   0x47098 CGDataProviderRetainData + 80
20 CoreGraphics                   0x46d64 CGAccessSessionCreate + 124
21 CoreGraphics                   0x43fec img_data_lock + 2400
22 CoreGraphics                   0x43640 CGSImageDataLock + 1324
23 CoreGraphics                   0x4ea54 ripc_AcquireRIPImageData + 848
24 CoreGraphics                   0x4e290 ripc_DrawImage + 832
25 CoreGraphics                   0x4ddc8 CGContextDrawImageWithOptions + 1120
26 ourApp                         0x74dbf0 UIImage.draw(inCanvasWithSize:drawRect:) + 141 (Graphics.swift:141)
27 ourApp                         0x74e1cc UIImage.decompressed(isUsingPrepareForDisplay:) + 157 (Graphics.swift:157)
28 ourApp                         0x765bdc specialized ImagePipelineDelegate.decompress(response:request:pipeline:) + 10 (ImageDecompression.swift:10)
29 ourApp                         0x781ffc closure #1 in TaskLoadImage.decompressImage(_:isCompleted:isFromDiskCache:) + 202 (TaskLoadImage.swift:202)
30 ourApp                         0x75895c thunk for @escaping @callee_guaranteed () -> () + 4346923356 (<compiler-generated>:4346923356)
31 Foundation                     0x49c00 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
32 Foundation                     0x7b0ec -[NSBlockOperation main] + 104
33 Foundation                     0x78974 __NSOPERATION_IS_INVOKING_MAIN__ + 16
34 Foundation                     0x77a64 -[NSOperation start] + 648
35 Foundation                     0x7a57c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
36 Foundation                     0x7a2e8 __NSOQSchedule_f + 172
37 libdispatch.dylib              0x13250 _dispatch_block_async_invoke2 + 148
38 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
39 libdispatch.dylib              0x77b8 _dispatch_continuation_pop + 600
40 libdispatch.dylib              0x6dd4 _dispatch_async_redirect_invoke + 584
41 libdispatch.dylib              0x15be4 _dispatch_root_queue_drain + 392
42 libdispatch.dylib              0x163ec _dispatch_worker_thread2 + 156
43 libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
44 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```
<img width="572" alt="Screenshot 2023-09-27 at 17 04 13" src="https://github.com/kean/Nuke/assets/1894401/8f5e35da-8e61-45d8-abe6-bffb81b68ccb">

**Comment by kean** [comment]
Hey, thanks for the report! 

> Not sure if relevant, but the image format we are using is avif.

If you find a way to reproduce it, that would be fantastic.

> until we wait for Apple to fix it (if ever)?

A Feedback report may help.

**Comment by lucasecf** [comment]
Thanks for you reply!

> If you find a way to reproduce it, that would be fantastic.

 I spent hours on it, but unfortunately could experience the crash only once (when I took the screenshot). It's not a deterministic crash, i.e., the exact same place/image that caused the crash wouldn't do so on next runs.
Seems like some kind of random memory corruption, so really hard to reproduce, otherwise numbers would be higher.

For now I guess it would help to know if there's any way to avoid this call, or if it's something mandatory in the download pipeline

> A Feedback report may help.

yeah, will open a radar

**Comment by kean** [comment]
One more thing you can try is enabling [`isUsingPrepareForDisplay`](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/configuration-swift.struct/isusingpreparefordisplay). It then switches to use the native [prepareForDisplay](https://developer.apple.com/documentation/mapkit/mkannotationview/2921514-preparefordisplay) method for decompression. It's disabled by default because there've been multiple reports of it causing issues in earlier iOS versions. It's probably a good time to revisit it and see if it can be enabled by default. Apple recently added a bunch of error logs when you use it for formats that don't require decompression, so it makes it very hard to use now.

**Comment by lucasecf** [comment]
> But I see HEIFReadPlugin::decodeImageImp in the crash log, so it may actually be HEIF that's causing the issue.

Interesting, haven't noticed before. That's weird, because I'm quite positive we don't load HEIF images on our app (checked content types of all network request). I can only imagine that under the hood this code is shared when the image data is from another format and/or the image data is mis-categorised. Since the code is private, I wonder if there's any easy way to check/confirm that.

<img height=250 src="https://github.com/kean/Nuke/assets/1894401/4b2a1996-85b3-4ede-82cd-6a0b4cba0d43">

----

> One more thing you can try is enabling [isUsingPrepareForDisplay](https://kean-docs.github.io/nuke/documentation/nuke/imagepipeline/configuration-swift.struct/isusingpreparefordisplay). It then switches to use the native [prepareForDisplay](https://developer.apple.com/documentation/mapkit/mkannotationview/2921514-preparefordisplay) method for decompression. It's disabled by default because there've been multiple reports of it causing issues in earlier iOS versions. It's probably a good time to revisit it and see if it can be enabled by default. Apple recently added a bunch of error logs when you use it for formats that don't require decompression, so it makes it very hard to use now.

That sounds great and seems like what I was looking for. Since it avoids the the `CoreGraphics` code it should fix our issue, and I can also report here if any other issue happens or not.

PS: I also filed the bug report with Apple, can post here if there's ever any feedback, but we know how this things goes...

**Comment by lucasecf** [comment]
Update: we tried to release a version with the `isUsingPrepareForDisplay` and seems like it still has issues 😓 .

It's not super significant as well, but seems to happen twice as much as the original one (so it's affecting ~0.4% users).

I tried now setting the `isDecompressionEnabled` to `false`, which avoids both crashes. There seems to be no much difference in CPU usage, but looks like the memory consumption increases quite drastically.

Any other advices?

---------



```
14 ourApp                         0x7676d0 UIImage.decompressed(isUsingPrepareForDisplay:) + 151 (Graphics.swift:151)
15 ourApp                         0x77fb58 specialized ImagePipelineDelegate.decompress(response:request:pipeline:) + 10 (ImageDecompression.swift:10)
16 ourApp                         0x79b830 closure #1 in TaskLoadImage.decompressImage(_:isCompleted:isFromDiskCache:) + 202 (TaskLoadImage.swift:202)
17 ourApp                         0x772004 thunk for @escaping @callee_guaranteed @Sendable () -> () + 4341030916 (<compiler-generated>:4341030916)
```

full stack trace:
```
NSOperationQueue 0x13cbc8b60 (QOS: UNSPECIFIED)
0  libsystem_kernel.dylib         0x1b7c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0xfd4 _pthread_cond_wait + 1228
2  CoreMedia                      0x2540 WaitOnCondition + 20
3  CoreMedia                      0x2484 FigSemaphoreWaitRelative + 164
4  VideoToolbox                   0x30e068 VTDecompressionSessionRemote_DecodeTile + 576
5  CMPhoto                        0x15b70 VTTileDecompressionPluginClass_decode + 376
6  CMPhoto                        0x1b974 _decodeItem + 6008
7  CMPhoto                        0xb78c _applyDecodeStrategy + 396
8  CMPhoto                        0x7055c _decodeImage + 452
9  CMPhoto                        0x6c564 _createImageForIndex + 804
10 CMPhoto                        0x273b0 CMPhotoDecompressionContainerCreateImageForIndex + 280
11 UIKitCore                      0xa361ec -[_UINewCGImageDecompressor waitForImageRef] + 160
12 UIKitCore                      0x85acdc -[_UIImageCGImageContent contentPreparedForDisplay] + 84
13 UIKitCore                      0x9f7638 -[UIImage imageByPreparingForDisplay] + 28
14 ourApp                         0x7676d0 UIImage.decompressed(isUsingPrepareForDisplay:) + 151 (Graphics.swift:151)
15 ourApp                         0x77fb58 specialized ImagePipelineDelegate.decompress(response:request:pipeline:) + 10 (ImageDecompression.swift:10)
16 ourApp                         0x79b830 closure #1 in TaskLoadImage.decompressImage(_:isCompleted:isFromDiskCache:) + 202 (TaskLoadImage.swift:202)
17 ourApp                         0x772004 thunk for @escaping @callee_guaranteed @Sendable () -> () + 4341030916 (<compiler-generated>:4341030916)
18 Foundation                     0x49c00 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
19 Foundation                     0x7b0ec -[NSBlockOperation main] + 104
20 Foundation                     0x78974 __NSOPERATION_IS_INVOKING_MAIN__ + 16
21 Foundation                     0x77a64 -[NSOperation start] + 648
22 Foundation                     0x7a57c __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 16
23 Foundation                     0x7a2e8 __NSOQSchedule_f + 172
24 libdispatch.dylib              0x13250 _dispatch_block_async_invoke2 + 148
25 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
26 libdispatch.dylib              0x77b8 _dispatch_continuation_pop + 600
27 libdispatch.dylib              0x6dd4 _dispatch_async_redirect_invoke + 584
28 libdispatch.dylib              0x15be4 _dispatch_root_queue_drain + 392
29 libdispatch.dylib              0x163ec _dispatch_worker_thread2 + 156
30 libsystem_pthread.dylib        0x1928 _pthread_wqthread + 228
31 libsystem_pthread.dylib        0x1a04 start_wqthread + 8
```

**Comment by lucasecf** [comment]
We released a version using [skipDecompression](https://kean-docs.github.io/nuke/documentation/nuke/imagerequest/options-swift.struct/skipdecompression) option and now all the crashes are gone, since it avoids the CoreGraphacs problematic code. 

Like said above, unfortunately this has the side effect of increased memory consumption, so we will keep an eye to revert this change if/when Apple ever fixes the issue.

I'm closing this issue to avoid it hanging forever in the repo. Thanks @kean for the support!
