### ISSUE TITLE
Add onStart callback to SwiftUI.LazyImage

### ISSUE THREAD

**Issue by larryonoff** [kean/Nuke#727]
Please add `onStart` to `SwiftUI.LazyImage`.

See an example below.

```swift
  @State private var isLoading: Bool = false

    Button {
      viewStore.send(.tapped)
    } label: {
        LazyImage(url: viewStore.imageURL) { state in
           ...
        }
        .onStart { isLoading = true }
        .onCompletion { _ in isLoading = false }
    }
    .disabled(isLoading)
```

**Comment by kean** [comment]
Hey, @larryonoff. I've been focusing my energy elsewhere, but I like the suggestion, and I would merge and release it quickly if the PR is made.

**Comment by urbaneewe** [comment]
Hey @kean. Is it alright if I take this? I'm looking to contribute and this seems like a nice task to get myself familiar with the framework.

**Comment by kean** [comment]
Sure, you are more than welcome.

**Comment by larryonoff** [comment]
Sorry everyone. I was unable to make PR.

@urbaneewe thanks for the [PR](https://github.com/kean/Nuke/pull/736)!
