### ISSUE TITLE
Cocoapods support 🙏🏻 

### ISSUE THREAD

**Issue by NikKovIos** [kean/Nuke#729]
Hello and thank you for great lib! I know, that there already exist issues about cocoapods supporting, but decide to create a new one.

I know at least 3 big projects that not going to support SPM and use only cocoapods. Reason:
- When switching between branches, SPM getting crazy and rebuild all project;
- Security resons. We can clone cocoapods CDN repo, but cannot do it with SPM;
- Flexible way to setup cocoapods if you have multiple targets and different supported ios versions;
- A LOT of people still using cocoapoads;
- https://medium.com/m/global-identity-2?redirectUrl=https%3A%2F%2Fbetterprogramming.pub%2Fwhy-cocoapods-is-still-a-thing-in-2022-b1478f03852 and https://www.codementor.io/blog/swift-package-manager-5f85eqvygj
- Easy cocoapods support by maintainer. (I have multiple public libraries too (the biggest one is https://github.com/Yummypets/YPImagePicker), and know that is takes some time to update cocoapods version. But it's not so hard if you have a guide how to do it)

**Comment by kean** [comment]
I'm sorry to disappoint, but it will not be available via CocoaPods.

>  We can clone cocoapods CDN repo, but cannot do it with SPM;

You can clone the repo and use it as a local dependency.

I would also recommend looking into XCFrameworks. Every Nuke release ships with pre-compiled binaries. It solves many of these issues and, in some ways, better than CocoaPods.
