### ISSUE TITLE
Other types of media.

### ISSUE THREAD

**Issue by hifall** [kean/Nuke#73]
I understand Nuke is for images -- but does it also happen to support caching other types of media? Like audio (mp4/m4a)? Thanks!

**Comment by kean** [comment]
Yeah, Nuke is built exclusively for images. 

However, the "pipeline" used for loading images might as well be used for loading other types of media. It shouldn't be too hard to support it. I had this in mind for Nuke 4 (which I'm working on).

My only concern is that audio and video are "streaming" media in their nature. They might require a different approach.
