### ISSUE TITLE
Validate error

### ISSUE THREAD

**Issue by UriyDevyataev** [kean/Nuke#732]
I'm trying to load an image using LazyImageView.request = ...
And I'm getting a validation error and therefore a status Cancelled. 
Although when opened in a browser, the link is valid.
Example link:
https://worker1.retailcrm.tech/c/144x144/https://sun6-21.userapi.com/impg/Nmha7HmxcNhb5o9BCEHoLtv8XD-Uy4lb2G1pWA/IDNddKhmo8g.jpg?crop=0,0,1,1&size=0x400&quality=95&sign=169cc184409efc69235702b585b5fe5a&c_uniq_tag=fXri2ISUcyj--rlMD_aw8yW5KyjjZgeWPskekurbRLE

https://worker1.retailcrm.tech/c/144x144/https://s3-s1.retailcrm.tech/ru-central1/retailcrm/scandilandia-6a5bc239380804e9378db4dc4fdc8144/product/64d5ea870fcc4-photo_2023-08-11_10-59-25.jpg

The first error is loaded with a validation error and the second without

**Comment by kean** [comment]
The common cause of "cancelled" errors is the App Transport Security validations. Make sure the URLs use acceptably strong security by following the Apple's guide https://developer.apple.com/documentation/security/preventing_insecure_network_connections. There is a tool you can use to test it.

**Comment by UriyDevyataev** [comment]
I found a bug. It is not associated with your library. Thanks for the quick response
