### ISSUE TITLE
Image Cache issue with Encoded Image Url

### ISSUE THREAD

**Issue by dampyrai** [kean/Nuke#734]
Please check the image cache issue with the encoded image URL

https://stage-image.nexgtv.com/eyJrZXkiOiJuZXhndHZcL2ltZ1wvbGl2ZXR2XC9DSE44OTU2MTA4NlwvNjU0NDg2NzkxOTU5Ni01OTc2MC5wbmciLCJidWNrZXQiOiJkaWdpLWZpbGUtaW1nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoxMzIsImhlaWdodCI6MTMyLCJmaXQiOiJmaWxsIn0sInRvRm9ybWF0IjoicG5nIn19

Please help me in cache issue

**Comment by kean** [comment]
Please provide more details: the version you are using, the steps, and the expected and the actual result.

**Comment by dampyrai** [comment]
HI kean,

I have used Nuke Libray for swift ui,
  LazyImage Class for image loading and image remote url encoding url but the image did not enable cache.

image url : https://stage-image.nexgtv.com/eyJrZXkiOiJuZXhndHZcL2ltZ1wvbGl2ZXR2XC9DSE44OTU2MTA4NlwvNjU0NDg2NzkxOTU5Ni01OTc2MC5wbmciLCJidWNrZXQiOiJkaWdpLWZpbGUtaW1nIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoxMzIsImhlaWdodCI6MTMyLCJmaXQiOiJmaWxsIn0sInRvRm9ybWF0IjoicG5nIn19

thanks

**Comment by kean** [comment]
Please, go through the documentation on caching https://kean-docs.github.io/nuke/documentation/nuke/cache-layers. It sounds like it might be HTTP cache control issue.
