### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by chrs1885** [kean/Nuke#737]
Hi there,

We recently became aware that, according to the new Apple privacy regulations, third-party SDKs will also be required to provide a Privacy Manifest to ensure compliance with privacy policies in the future.

Do you have any plans to deliver a Privacy Manifest with the library?

**Comment by gabors** [comment]
Any update on this please?

**Comment by kean** [comment]
I went through [the list of the APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393) that have to be declared in a privacy manifest, and I haven't found any of them in Nuke.

- `DiskCache` use `.contentAccessDate` and `.totalFileAllocatedSize`, which are not on the list
- It never uses `UserDefaults` or any of the other APIs

I think it's safe to close. If someone still receives a warning from Apple regarding the use of these APIs, please re-open it.
