### ISSUE TITLE
Swift 2.3 Support

### ISSUE THREAD

**Issue by adomanico** [kean/Nuke#74]
As Xcode 8 is approaching, we will need a release compatible with Swift 2.3 and Xcode 8

**Comment by adomanico** [comment]
Looks like there is already a branch https://github.com/kean/Nuke/tree/swift2.3

**Comment by kean** [comment]
Yep, I maintain a Swift 2.3 branch. It supports all latest Xcode 8 betas, including Beta 6.

In the meantime, I'm working on Nuke 4 in `master` branch. It's rewritten in idiomatic Swift 3 and features some other major changes.

**Comment by adomanico** [comment]
Awesome thanks, will point our carthage to the swift 2.3 branch for now.

Can you make a separate release that targets swift 2.3 when it hits GM?

**Comment by kean** [comment]
Absolutely. My plan is to continue releasing Nuke 3 that works with Swift 2.3 for a while. And release Nuke 4 that works with Swift 3 when it's finished.

**Comment by joe528** [comment]
@kean What should I be expecting for Nuke 4? I mean what major improvement will it have? Besides, would the performance be even better? Exciting to see Nuke 4 but I am not sure what I am expecting :)

**Comment by kean** [comment]
@joe528 My main goals for Nuke 4 were to effectively make it a micro framework - that should be Nuke's distinctive feature. It means smaller code base (it now has 785 lines of code compared to Kingfisher's 2357); principle of least astonishment; more and simpler ways to extend existing functionality. I hope it's going to be a pleasure to use 😃 I'm also keeping almost all of the existing features (except for progress reporting, I'm still not decided on this one).

I don't have a complete list of changes (there are too many). If you are interested, you might want to check new APIs for yourself. I'm working in a `master` branch. Example project, tests, playgrounds, docs are all up to date.

> Besides, would the performance be even better?

I believe so. The core performance characteristics are going to be the same. There is almost 0 work made on the main thread; there are no String manipulations whatsoever - you won't find this in any of the other frameworks that I'm aware of. Preheating now also works in a background, that's going to be a new performance win. I also do use more structs, finals, etc which means less memory usage, less dynamic dispatch.

Thanks for your interest 😄

**Comment by kean** [comment]
> Besides, would the performance be even better?

@joe528 it is now, check out [Nuke 4.1](https://github.com/kean/Nuke/releases/tag/4.1)!
