### ISSUE TITLE
Status on video support

### ISSUE THREAD

**Issue by lschaupp** [kean/Nuke#740]
What is the current status on .mp4 (H265 / VP9) support?
The demos are 9 months old saying "do not use in production".
On the official website, it states videos are supported.
On the github repository, there is no info at all about video support.

This is all very confusing....

**Comment by kean** [comment]
Hey, thanks for bringing this up. These resources need to be updated, which I'll do if time allows.

To answer your question, yes, videos are supported via a `NukeVideo` module. I believe there are at least a few apps that use this feature in production, but video support has never been prioritized, so you may find it a bit limited. The main goal was to provide a replacement for (inefficient) GIFs.

**Comment by lschaupp** [comment]
Dear Kean, thank you for getting back. Yes, indeed a GIF (outdated) replacement is heavily needed. Other libraries do not support modern video codecs out of the box (for GIF purposes). So thank you for your work!
