### ISSUE TITLE
Support for LazyVStack

### ISSUE THREAD

**Issue by lschaupp** [kean/Nuke#744]
I am using NukeVideo with support on LazyVStack.
However when scrolling through the VStack, the placeholder view keeps re-appearing while loading the videoView.
I would like to have a support with LazyVStack, that the videoView is not getting reloaded from scratch but rather continues playing from where it last disappeared (like in Kingfisher).

**Comment by kean** [comment]
It'll require a bit of the architecture re-think. There definitely needs to be more control in terms of the playback. I can't invest time into this feature, but I'm open to suggestions in that area and to eventually releasing this feature.

**Comment by kean** [comment]
I will close it because there are no plans to expand the video support, but the previous comment still stands, and contributions are welcome.
