### ISSUE TITLE
Animation triggers every time

### ISSUE THREAD

**Issue by icedice** [kean/Nuke#745]
Not sure what I'm doing wrong but when adding .animation(.default) to my LazyImage in my very basic SwiftUI app the animation triggers ever time the image is shown (its in inside a VStack tht is inside a List)... Also the animation is some weird bouncy animation not a basic fade-in which was what i was expecting. What am I doing wrong?

**Comment by icedice** [comment]
Figured it out. This had nothing to do with Nuke. Its my SwiftUI knowledge that is lacking.

**Comment by michaldrabik** [comment]
@icedice WOuld you remember what was it? I currently also struggle to get why my LazyImage is loading with animation even if memoryCache is being used.

**Comment by fabianfabian** [comment]
@icedice I have this too, but only with SwiftUI views within UICollectionView / UITableView via UIViewRepresentable, I'm curious what your problem/solution is. (Mine here: https://stackoverflow.com/questions/77031575/uicollectionview-animation-problem-when-cells-appear-during-scrolling )

**Comment by icedice** [comment]
I honestly do not remember the issue or how I solved it.. I think it was something about the SwiftUI lifecycle and how events are triggered...

**Comment by icedice** [comment]
Looking at my code I seem to have solved it by only animating if     self.shouldAnimate = response.cacheType == nil  not sure if that is the best way to do it...
