### ISSUE TITLE
Use GIF with NukeUI

### ISSUE THREAD

**Issue by bl791** [kean/Nuke#753]
Hi.
Thanks for creating this library. How can I use GIF in SwiftUI?
Thanks!

**Comment by bl791** [comment]
Note: I'm trying to load quite a large GIF, so it can't be directly loaded using Data

**Comment by kean** [comment]
Hey, I'm afraid it doesn't support the use-case with large GIFs that require streaming. I would suggest looking elsewhere because it needs a system with a completely different design for networking and caching, which is not what Nuke can or will support.

**Comment by fakerybakery** [comment]
Oh, ok. Thanks!
