### ISSUE TITLE
Custom CacheKey like SDWebImage

### ISSUE THREAD

**Issue by naingminoo99** [kean/Nuke#754]
Is there anyway to do custom Image cache key like SDWebImage. 

`let filter = SDWebImageCacheKeyFilter { url in
    guard let absoluteString = url?.absoluteString else {
        return nil
    }
    let items = absoluteString.components(separatedBy: "?")
    guard let trimUrl = URL(string: items.first ?? "") else {
        return nil
    }
    return trimUrl.absoluteString
}

SDWebImageManager.shared().cacheKeyFilter = filter
`

**Comment by kean** [comment]
There are two ways to customize cache keys (that I remember):

- [ImagePipelineDelegate/cacheKey(for:pipeline:)](https://kean-docs.github.io/nuke/documentation/nuke/imagepipelinedelegate/cachekey(for:pipeline:)-8k9a4) on a per-pipeline level
- [ImageRequest/UserInfoKey/imageIdKey](https://kean-docs.github.io/nuke/documentation/nuke/imagerequest/userinfokey/imageidkey) on a per-request

They are designed for two slightly different use-case. See the documentation for more info.
