### ISSUE TITLE
Include Privacy Manifests for the SDK

### ISSUE THREAD

**Issue by v3trax** [kean/Nuke#757]
Can a privacy manifests be included into the SDK? https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

I'm hearing that this will be required very soon for every new release.

**Comment by kean** [comment]
Hey, I [looked into](https://github.com/kean/Nuke/issues/737) it and my assessment is that it's not needed because the framework doesn't use any of the APIs that are on the list.

**Comment by flopshot** [comment]
@kean We are still on version 10 of Nuke. Do you know off hand if there _were_ privacy api's used in those older versions? We just need to know if we need to prioritize our version upgrade to 12 before May 1

**Comment by kean** [comment]
Hey, @flopshot. I briefly checked it, and it looks like you should be good, but I can't say with any degree of certainty. I wish Apple could provide an automated tool to analyze the code and generate the manifest if needed. Having said that, I would recommend updating. If the need for the manifest arises, I'll add it shortly. So far, I haven't seen any reports of App Store upload warnings or errors for apps that include Nuke.

**Comment by flopshot** [comment]
Thank you for your help
