### ISSUE TITLE
decompress: contentMode & targetSize

### ISSUE THREAD

**Issue by taviscaron** [kean/Nuke#76]
Are `contentMode` & `targetSize` designed to do the same as `UIViewContentMode`'s `scaleAspectFit`/`scaleAspectFit` ? If yes - they seem not doing it.

If `targetSize` has a different from the source image aspect - you never get result image sized in `targetSize`. `contentMode` just affects on what side is fit `targetSize` and what is changes in order to save aspect.

In my view, there: https://github.com/kean/Nuke/blob/master/Sources/Processor.swift#L129 you need to construct CGContext using `targetSize` (not `size`) and there: https://github.com/kean/Nuke/blob/master/Sources/Processor.swift#L132 you need to draw not from CGPoint.zero but with positive offset for `aspectFit` and negative for `apsectFill` (simply `(targetSize - size)/2`)

Sorry can't try this change at the moment, I hope a bit later I'll be able to test my idea and send PR.

**Comment by kean** [comment]
> If `targetSize` has a different from the source image aspect - you never get result image sized in `targetSize`. 

Yeah, that's how it was designed to work. `targetSize` works together with `contentMode`, image aspect is always preserved.

For example, let say you have input image which size is 200x100 px
- targetSize = 50x50, contentMode = .aspectFill will produce 100x50 image
- targetSize = 50x50, contentMode = .aspectFit will produce 50x25 image

Hope that makes sense.

**Comment by kean** [comment]
`targetSize` is a size of a target (see `Nuke.Target`), not output image
