### ISSUE TITLE
Add mandatory privacy manifest

### ISSUE THREAD

**Issue by frankois1234** [kean/Nuke#761]
Nuke is not (yet?) listed in the mandatory SDKs, but better to do it earlier :)

The details :
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Cheers

**Comment by kean** [comment]
Duplicate https://github.com/kean/Nuke/issues/737. If you have additional information, please provide it in the linked thread.
