### ISSUE TITLE
Upgrade to Swift 3.0 without moving to Nuke 4.0?

### ISSUE THREAD

**Issue by bdolman** [kean/Nuke#78]
From what I can tell, the only way to upgrade to Swift 3.0 is to use the 4.0 beta, but this includes API-breaking changes. Is there a Swift 3.0 branch somewhere that keeps the existing API?

**Comment by kean** [comment]
I haven't planned Nuke 3 version updated to Swift 3 yet. I was hoping that migration to Nuke 4 should be straightforward (maybe that's too much to ask though?). It wouldn't hurt be a good idea to include some deprecated backward-compatibly methods to make transition to Nuke 4 smoother. I'll add them in 4.0-beta3.

**Comment by kean** [comment]
And yeah, I should probably just update Nuke 3 to Swift 3. I think I'll wait till Xcode 8 release, because migrating between Xcode 8 betas was extremely painful (breaking changes in Swift 3 with each release).

**Comment by kean** [comment]
I've written an in-depth [Nuke 4 Migration Guide](https://github.com/kean/Nuke/blob/master/Docs/Nuke%204%20Migration%20Guide.md) to simplify the transition.

**Comment by bdolman** [comment]
Thanks. From my perspective, changing to a new API and internals while simultaneously having to migrate all my code to Swift 3.0 isn't the best approach. It's introducing too many changes at once -- Swift 3 migration is painful enough by itself!

Instead, I switched to [PINRemoteImage](https://github.com/pinterest/PINRemoteImage) (which was an easy change given the way I was using Nuke), and then began my Swift 3 migration.

Thanks for your hard work on Nuke, maybe I'll be back in the future :)

**Comment by kean** [comment]
Yeah, I completely understand. I tried to migrate Nuke 3 to Swift 3 (just like you suggested) recently but it was such a pain that I ultimately decided against it since I already have Swift 3 compatible version (Nuke 4) which I've spent enormous amount of time on.

Compared to alternatives (SDWebImage) PINRemoteImage seemed pretty good at the time. Hope that it works for you! I would also *really* like to know whether there were some critical points preventing you from using Nuke 4 instead? I might be missing something obvious that I'm simply not aware of. To me PINRemoteImage seems very similar feature-wise (expect for progressive jpeg support).

**Comment by bdolman** [comment]
I like that you have implemented an LRU cache -- that was definitely something I wanted in Nuke 3. In my tests, it also seemed that PINRemoteImage was a bit faster loading images from the disk cache, but I haven't done any controlled tests, so that could be very subjective.

Another big factor for me is that I'm looking seriously at using AsyncDisplayKit and it has built-in support for PINRemoteImage, so that kind of sealed the deal.

I definitely like the idea of a native Swift image loading framework thought. I'm sure that with you keeping up on Swift changes, your API is going to be much nicer to use from Swift as time goes on. But knowing that PINRemoteImage is Objective-C means that I'm not going to have to worry about these Swift migrations in the future.

Again, thanks for your work. I don't in any way mean to be critical of the hard work you're putting into this for the community!

**Comment by kean** [comment]
> In my tests, it also seemed that PINRemoteImage was a bit faster loading images from the disk cache, but I haven't done any controlled tests, so that could be very subjective.

Yeah, PINRemoteImage uses [PINCache](https://github.com/pinterest/PINCache) out of the box which is noticeably faster than `URLCache` used by `URLSession` (for multiple reasons). Nuke also has a `DataCaching` protocol which you can use to integrate PINCache (or any other caching library for that matter). I plan to add a plugin that would do just that, I just haven't decided on a particular library yet.

> Another big factor for me is that I'm looking seriously at using AsyncDisplayKit and it has built-in support for PINRemoteImage, so that kind of sealed the deal.

`AsyncDisplayKit` has a `ASNetworkImageNode` built in as well.

> ... means that I'm not going to have to worry about these Swift migrations in the future.

I'm glad that I currently have 0 lines of Swift code in production. That was the smartest decision I've ever made 😆

Thanks for your feedback!

**Comment by bdolman** [comment]
> AsyncDisplayKit has a ASNetworkImageNode built in as well.

Didn't realize that -- nice.

> I'm glad that I currently have 0 lines of Swift code in production. That was the smartest decision I've ever made 😆

Boy, you were much smarter than me. The last few days have sucked!
