### ISSUE TITLE
Error -17102 decompressing image -- possibly corrupt

### ISSUE THREAD

**Issue by prabhuamol** [kean/Nuke#799]
See this error in the console sometimes. Is this expected?
<img width="1421" alt="Screenshot 2024-07-25 at 12 06 15 PM" src="https://github.com/user-attachments/assets/32a98333-ea17-4bdd-ab30-953a5ab6d2d0">

**Comment by Saafo** [comment]
Because of https://github.com/kean/Nuke/commit/6c2542848b178b4bc23f7bd56eae2a708eb15007，

![f87a6c3a-50e1-403f-a725-e61f147511ba](https://github.com/user-attachments/assets/667f2977-1e08-4861-a240-b6abff6165b1)

Hi @kean I'm just wondering why we revert this check? Does this log mean anything?

**Comment by prabhuamol** [comment]
> #788

I see, so its something that apple just throws at us when preparingForDisplay is used on PNGs? I'll close this then if we can safely ignore this error

**Comment by prabhuamol** [comment]
Looks like similar issue was observed here and radar to Apple was filed https://github.com/SDWebImage/SDWebImage/issues/3365#issuecomment-1186105083
