### ISSUE TITLE
Question: Task cancellation

### ISSUE THREAD

**Issue by prabhuamol** [kean/Nuke#801]
Hi,
We are noticing that even after task cancellation the task remains in running state. Is this accurate? The doc does say 
/// The pipeline will immediately cancel any work associated with a task
    /// unless there is an equivalent outstanding task running.

Not sure what this means. Is there no guarantee that the task will get cancelled. We are seeing some slow loads in our scroll view with images. We currently cancel tasks as images go off screen but looks like the actual task never gets cancelled

**Comment by kean** [comment]
Hey, can you share the sample code that I could use to reproduce the issue?

**Comment by prabhuamol** [comment]
This was a bug on our side
