### ISSUE TITLE
Request for Nuke 11+ Support in Cocoapods

### ISSUE THREAD

**Issue by sangam11** [kean/Nuke#805]
I'm currently using Nuke 10.7 in my project, managed through Cocoapods. I've noticed that newer versions of Nuke (11+) are available, which offer NukeUI for SwiftUI.

I would like to request support for Nuke 11+ in Cocoapods. This would allow me to take advantage of the latest features and improvements offered by the library.

**Comment by kean** [comment]
Hi, there are currently no plans to bring back the CocoaPods support. The preferred installation option is SwiftPM, and Nuke also [ships](https://github.com/kean/Nuke/releases) with precompiled XCFrameworks for projects that don't use SwiftPM yet.
