### ISSUE TITLE
Potential leak in ImagePipelineDelgate

### ISSUE THREAD

**Issue by prabhuamol** [kean/Nuke#807]
Hi
Should the ImagePipelineDelgate be declared as weak var. We are seeing a leak in the app regarding this.

We have ImagePipeline declared as a lazy var in a Class, this results in a retain cycle and a leak

```
   lazy var imagePipeline: ImagePipeline = {
        return .init(configuration: configuration, delegate: self)
   }()

```
I have a PR open here https://github.com/kean/Nuke/pull/806 

Thanks in advance!

**Comment by prabhuamol** [comment]
Looks like tests will fail as ImagePipelineDefaultDelgate wont hang around since its now weak. Hmm guess you cant have self as delegate like we are doing in order to avoid retain cycle

**Comment by kean** [comment]
The design matches `URLSession` where the delegate is also retained. It doesn't necessarily have to be, but it's more convenient for some scenarios.

**Comment by prabhuamol** [comment]
Fair enough, we'll change our implementation accordingly. Maybe worth mentioning this in the doc

**Comment by prabhuamol** [comment]
wonder if my other change here makes sense https://github.com/kean/Nuke/pull/806
