### ISSUE TITLE
Starting with 12.6, custom data loader is not called

### ISSUE THREAD

**Issue by jaanussiim** [kean/Nuke#813]
Basic setup for data loader

```
 let pileline = ImagePipeline {
     $0.dataLoader = AskDataLoader()
}
        
ImagePipeline.shared = pileline
```

Using LazyImage from NukeUI. Custom DataLoader is not called

**Comment by kean** [comment]
I wonder if it might be related to the following change https://github.com/kean/Nuke/pull/779?

**Comment by jaanussiim** [comment]
Yes, adding `$0.isLocalResourcesSupportEnabled = false` fixes it.

I'm using `data://` scheme for files that I want to load from local database.
