### ISSUE TITLE
Recent change with NukeUI: LazyImage no longer plays videos?

### ISSUE THREAD

**Issue by AndrewSB** [kean/Nuke#816]
hey, i'm kind of lost with this change: 

previously, i had a UIKit LazyImage loading and playing a mp4 version of a giphy URL.

some time in the last 2-3 months i upgraded Nuke versions, and that stopped working: now the LazyImage just shows a still image version of that video file.

can you help me understand what's changed, and what i might need to do to get gif videos playing again?

**Comment by kean** [comment]
Hey, `NukeVideo` was extracted to a separate module in [v12.0](https://github.com/kean/Nuke/releases/tag/12.0.0) in an effort to keep the core modules as lean as possible.

I suggest following the migration guide, which [covers this area](https://github.com/kean/Nuke/blob/main/Documentation/Migrations/Nuke%2012%20Migration%20Guide.md#nukevideo), to upgrade.

**Comment by AndrewSB** [comment]
yup, that did it. thanks @kean 

as an aside: i tried to email you at your mastadon email address for a Pulse Pro support issue, is that email not monitored? how can i contact you?

**Comment by kean** [comment]
Sure, you can reach me at studio(at)kean.blog which I monitor daily.

> mastadon email address for a Pulse Pro support issue, is that email not monitored? 

Hmm, I didn't know there was one.

**Comment by kean** [comment]
Hey, @AndrewSB, I just wanted to let you know that I haven't received any new messages. Please feel free to send me a private mention at https://mastodon.social/@a_grebenyuk so I can give you more options.

**Comment by ElectricS01** [comment]
Does anyone know of a way of handling GIFs on macOS now?
