### ISSUE TITLE
Updating to Nuke 4.0

### ISSUE THREAD

**Issue by markhoyt84** [kean/Nuke#82]
Hey man first of all I would like to say great Pod!  Using it in several projects and it has been extremely useful and worked very well for me!  I am currently trying to update to the new beta version as I migrate apps to Swift 3.  I have tried:

- pod update
- pod update Nuke
- removed Nuke from podfile, pod update, added Nuke back in and it will still not update past version 3.2 for me
- added the github url with a tag even

Any help would be greatly appreciated thank you.  Here is my podfile.

# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’
# source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
target 'Industree' do

pod 'Alamofire', '~> 4.0'
pod 'Branch'
pod 'KTCenterFlowLayout'
pod 'JSONJoy-Swift'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'HockeySDK', '~> 3.8.6'
pod 'Mixpanel-swift'
pod 'SZTextView'
pod 'SwiftLoader'
pod 'PhoneNumberKit'
pod 'CocoaAsyncSocket'

pod 'Nuke'
pod 'Onboard'
pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope', :branch => 'swift3'
pod 'Siren'

end

**Comment by kean** [comment]
Hi, glad that it works for you!

CocoaPods doesn't install beta versions until explicitly told to. Here's how to do that:

```
pod 'Nuke', '~> 4.0-beta'
```

Cheers 🍻

**Comment by nico75005** [comment]
What about `Nuke-Alamofire-Plugin` & `Nuke-AnimatedImage-Plugin`?

**Comment by taviscaron** [comment]
@kean, what's the reason of updating deployment target to 9.0 ?

**Comment by kean** [comment]
@taviscaron, discussed a little bit here #83.

**Comment by lubos08** [comment]
@kean, I have tried to pull pod 'Nuke', '~> 4.0-beta', but I got this error.

```
[!] Unable to satisfy the following requirements:

- `Nuke (~> 4.0-beta)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Nuke (~> 4.0-beta)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```
Why does this happen to me?
Thanks

**Comment by kean** [comment]
@lubos08 did you try `pod repo update` (see error message)? Also, make sure that you have the latest CocoaPods version.

**Comment by lubos08** [comment]
@kean Thank you for your help! `pod repo update` worked for me.

**Comment by kean** [comment]
@lubos08 I would recommend to wait just couple of hours till Nuke 4.0 is released though :)

**Comment by lubos08** [comment]
@kean will you merge it to main branch?

**Comment by kean** [comment]
If you install from 'master' you should be fine. Just avoid last tagged 'Nuke 4.0-beta3' build.

**Comment by lubos08** [comment]
Great, thx @kean
