### ISSUE TITLE
Can nuke 4.0 keep support iOS8?

### ISSUE THREAD

**Issue by derek-chim** [kean/Nuke#83]

**Comment by kean** [comment]
Hey!

Technically yes, Nuke 4 compiles (and *probably* works) on iOS 8. However, current iOS 9 + iOS 10 adoption rate is [already at 95%](https://mixpanel.com/trends/#report/ios_10) which leaves little reasons to still support iOS 8.

![screen shot 2016-09-16 at 10 29 34](https://cloud.githubusercontent.com/assets/1567433/18578445/06d77182-7c01-11e6-95fd-2f56186e06ba.png)

If you absolutely need iOS 8 support you could fork Nuke and drop the deployment target.

**Comment by derek-chim** [comment]
Just set the cocoapods minimum target to iOS 8 is ok, should I make a pull request for that?

**Comment by kean** [comment]
I've added a [Podspec with iOS 8](https://gist.github.com/kean/7ffdae2526b4e503a95c5e971320e9f9) support for you.

Here's how to use it:

```
// Podfile
pod 'Nuke', :podspec => 'https://gist.githubusercontent.com/kean/7ffdae2526b4e503a95c5e971320e9f9/raw/a90dbd8ba34981a0e43ab7544afdc12b6b000553/Nuke.podspec'
```

I've smoke tested it on a clean project.

**Comment by derek-chim** [comment]
Thanks! I hope this will help for those needed for supporting on iOS8
