### ISSUE TITLE
Add convenience 'cancelRequest(for:)' function

### ISSUE THREAD

**Issue by jeffd** [kean/Nuke#88]
With Nuke 4 installed via Carthage using Swift 3, the example function for cancelling requests after cells are done displaying does not work. Calling `Nuke.cancelRequest(for: cell.imageView)` gets the compiler error `Module 'Nuke' has no member named 'cancelRequest'`

**Comment by kean** [comment]
Hey! There is no such function yet (forgot to add it in Nuke 4.0). Please use `Manager.shared.cancelRequest(for: cell.imageView)` instead. Btw, in many cases you don't have to [cancel requests manually](https://github.com/kean/Nuke/issues/87#issuecomment-249207057).
