### ISSUE TITLE
[Question] Doesn't load Image into Target

### ISSUE THREAD

**Issue by nico75005** [kean/Nuke#89]
This is the code I have:

```
Nuke.loadImage(with: imageURL, into: questionView.imageView, handler: { (response, cached) in
	loadingIndicator.stopAnimating()
	if case .rejected(let error) = response {
		print(":(")
	} else if case .fulfilled(let image) = response {
		print(self.questionView.imageView.image)
	}
})
```

I must miss something as `print(self.questionView.imageView.image)` prints `nil` while the image in `.fulfilled(let image)` is ok.

`questionView.imageView` is a `UIImageView`.

Do I do something wrong? By using `loadImage(with:into:handler)`, shouldn't load the image inside my target which is a `UIImageView`?

**Comment by kean** [comment]
Hey! The `loadImage(with:into:handler:)` method doesn't do anything when the image is loaded. This makes it useful in more scenarios than if it did.

Here's an example of how to use it (I'll add in a `Usage` section of README for the next release):

```swift
let indicator = activityIndicator(for: cell)

indicator.startAnimating()
Nuke.loadImage(with: request, into: imageView) { [weak imageView] in
    imageView?.handle(response: $0, isFromMemoryCache: $1)
    indicator.stopAnimating()
}
```

**Comment by nico75005** [comment]
Ok thanks for the reply. But then I'm confused. What's the point to have a parameter `into` if it doesn't do anything when there is a `handler`?

**Comment by nico75005** [comment]
Got it! Thanks a lot!
