### ISSUE TITLE
NSProgess explodes inside Alamofire

### ISSUE THREAD

**Issue by maheshmobile** [kean/Nuke#9]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '/Users/accel_imac/Library/Developer/CoreSimulator/Devices/6631CF6C-F944-454E-B3F7-FD6AB2A672AC/data/Containers/Data/Application/2E85B42A-8B80-4386-A68F-B788AB572CF4/Library/Caches/org.cocoapods.demo.Nuke-Example/com.github.kean.nuke-image-cache: An -observeValueForKeyPath:ofObject:change:context: message was received but not handled.
Key path: fractionCompleted
Observed object: <NSProgress: 0x7fc3fbd1c6e0> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 31038 of 31038  
Change: {
    kind = 1;
    new = 1;
}
Context: 0x0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001005a5f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010223adeb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001005a5e9d +[NSException raise:format:] + 205
	3   Foundation                          0x0000000100a09e0a -[NSObject(NSKeyValueObserving) observeValueForKeyPath:ofObject:change:context:] + 73
	4   Foundation                          0x0000000100936b30 NSKeyValueNotifyObserver + 347
	5   Foundation                          0x0000000100935d5b NSKeyValueDidChange + 466
	6   Foundation                          0x000000010093a560 -[NSObject(NSKeyValueObserverNotification) didChangeValueForKey:] + 118
	7   CoreFoundation                      0x00000001004d4ad2 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	8   CoreFoundation                      0x00000001004d424f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 335
	9   Foundation                          0x0000000100b2dd34 -[NSProgress _setValueForKeys:settingBlock:] + 722
	10  Foundation                          0x0000000100b2e41e -[NSProgress setCompletedUnitCount:] + 138
	11  Alamofire                           0x00000001002b2db0 _TFCC9Alamofire7Request16DataTaskDelegate10URLSessionfS1_FTCSo12NSURLSession8dataTaskCSo20NSURLSessionDataTask14didReceiveDataCSo6NSData_T_ + 1360
	12  Alamofire                           0x000000010028ea1a _TFCC9Alamofire7Manager15SessionDelegate10URLSessionfS1_FTCSo12NSURLSession8dataTaskCSo20NSURLSessionDataTask14didReceiveDataCSo6NSData_T_ + 586
	13  Alamofire                           0x000000010028eac4 _TToFCC9Alamofire7Manager15SessionDelegate10URLSessionfS1_FTCSo12NSURLSession8dataTaskCSo20NSURLSessionDataTask14didReceiveDataCSo6NSData_T_ + 100
	14  CFNetwork                           0x0000000102d85f6d __67-[NSURLSession delegate_dataTask:didReceiveData:completionHandler:]_block_invoke220 + 38
	15  Foundation                          0x0000000100a16873 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	16  Foundation                          0x00000001009525d5 -[NSBlockOperation main] + 101
	17  Foundation                          0x0000000100935556 -[__NSOperationInternal _start:] + 646
	18  Foundation                          0x0000000100935167 __NSOQSchedule_f + 194
	19  libdispatch.dylib                   0x0000000103a7c49b _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x0000000103a62988 _dispatch_queue_drain + 2215
	21  libdispatch.dylib                   0x0000000103a61ea9 _dispatch_queue_invoke + 601
	22  libdispatch.dylib                   0x0000000103a64af2 _dispatch_root_queue_drain + 1420
	23  libdispatch.dylib                   0x0000000103a64561 _dispatch_worker_thread3 + 111
	24  libsystem_pthread.dylib             0x0000000103dc4a9d _pthread_wqthread + 729
	25  libsystem_pthread.dylib             0x0000000103dc23dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kean** [comment]
Thanks, seems like an Alamofire issue, I'll take a look later.

**Comment by kean** [comment]
Fixed, ImageTask no longer uses NSProgress #19
