### ISSUE TITLE
isFastResponse equivalent API?

### ISSUE THREAD

**Issue by toshi0383** [kean/Nuke#92]
Hi,  in Nuke4, is there any API which is equivalent to Nuke3's `isFastResponse`?
I'm not using it anymore, but just wondering.

**Comment by kean** [comment]
Hey, @toshi0383.

`Loader` (which loads images) callbacks are now always asynchronous, `isFastResponse` was removed.

`Manager` (which manages image loading into targets)  operates with a `Target` protocol which does have `isFromMemoryCache`.

```swift
public protocol Target: class {
    func handle(response: Response, isFromMemoryCache: Bool)
}
```

If you are using `Loader` directly and you need an analog of `isFastResponse` then just read from memory cache directly. It's very easy in Nuke 4:

```swift
let request = Request(url: url)
let image = cache[request]
```

**Comment by toshi0383** [comment]
Thanks for instruction!! 😃
