### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by dtrevino15** [kean/Nuke#93]
Im trying to update my current project, but current image loader is not working with Swift 3. Would appreciate some help. My app is a video streaming app that loads videos from a plist file. The video thumbnail is loaded into a placeholder image view. Can you help me configure this to use Nuke please?
Everything is loading into a table. Here is the cell configuration.

```swift
let urlString: NSString = ((videoArray.object(at: (indexPath as NSIndexPath).row) as AnyObject).value(forKey: "ImageUrl")) as! NSString
cell.videoImage.loadMIImageLoaderFromURLString(urlString as String, placeholderImage: UIImage(named: "image_thumbnail")) {
    (finished, error) in
    if finished { }
    else if error != nil {
        print("error occurred with description: \(error?.localizedDescription)")
    }
}
print(urlString)
```

**Comment by kean** [comment]
Hey!

If you are using Swift 3 you should be using Nuke 4.x (most recent version).
If you are updating from Nuke 3 and lower please check out a [migration guide](https://github.com/kean/Nuke/blob/master/Documentation/Migrations/Nuke%204%20Migration%20Guide.md).

Here's an example how to load an image with a placeholder (this case is documented in [Tips and Tricks](https://github.com/kean/Nuke/blob/master/Documentation/Guides/Tips%20and%20Tricks.md#display-a-placeholder)):

```swift
cell.videoImage.image = UIImage(named: "placeHolder")
Nuke.loadImage(with: url, into: cell.videoImage)
```

There is a bunch of other documentation available including [usage guide](https://github.com/kean/Nuke#usage), [API reference](http://cocoadocs.org/docsets/Nuke/4.0/), inline documentation in code, and [more](https://github.com/kean/Nuke/tree/master/Documentation). Please refer to those.
