### ISSUE TITLE
Fetch from disk instead of remote url

### ISSUE THREAD

**Issue by rakeshpethani** [kean/Nuke#94]
Hi,

I have been trying to load image from documents directory but it gives me "Unsupported url" error.

Is it supported by the library to load image from file (local) url rather than from remote (server) url ?

**Comment by kean** [comment]
Hey,

Yes, it is supported. Nuke uses NSURLSession under the hood and it [supports `file://` scheme](https://developer.apple.com/reference/foundation/urlsession) which works with local files:

> The NSURLSession class natively supports the data, file, ftp, http, and https URL schemes

I've just tested it to make sure:

```swift
func testFileUrl() {
    let bundle = Bundle(for: LoaderTests.self)
    let url = bundle.url(forResource: "Image", withExtension: "jpg")!

    expect { fulfill in
        Loader.shared.loadImage(with: url).completion { response in
            print(response)
            fulfill()
        }
    }
    wait()
}
```

Make sure that your urls has a valid format (including scheme).

**Comment by AlexLee9986** [comment]
Hi. 
Please help me.

```
Loader.shared.loadImage(with: urlVal)
.then({ (image) in
....
})
```

error: missing argument for parameter 'token' in call

i inserted "CanecllationTokenSource().token", but it not work

Thanks!

**Comment by kean** [comment]
Hi, check out [Usage guide](https://github.com/kean/Nuke#usage). You can use all the same APIs that you use for loading remote images for fetching images from disk.
