### ISSUE TITLE
How to use Preheat correctly?

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#97]
I see you introduced a new way to use `Preheat` in Nuke 4,

However, the introduction in Nuke 4 and Preheat document seems not matched: https://kean.github.io/blog/image-preheating (still the old way by using `PreheatController`?)

additional info:
I couldn't make it work until I found that I had to set `.enabled = true` as well, which was not seen in the introduction. It is seen in the document which doesn't match the new Preheat introduction.

**Comment by kean** [comment]
Thanks, I'll update that doc, not promising how soon though. 

[Preheat](https://github.com/kean/Preheat) readme has more up to date info.

I find that fast that you have to enable `Preheat.Controller` manually a bit confusing too, maybe I'll refactor it in a next version.

**Comment by kean** [comment]
I've marked the https://kean.github.io/blog/image-preheating as outdated, I simple don't have time to update all the posts. The general ideas described there still apply though.
