### ISSUE TITLE
How to clean up all cache files?

### ISSUE THREAD

**Issue by joe528** [kean/Nuke#98]
If I want to manually clean up the cache (delete all temporary files), is this the correct way to do it?

`Cache.shared.removeAll()`

The users sometimes want to manually delete all temporary files because they don't like to see an app occupies too much space in their iPhone.

**Comment by kean** [comment]
> Cache.shared.removeAll()

That's memory cache only.

Cleaning disk cache isn't that trivial. Disk cache is whatever `DataLoader` uses. Default `DataLoader` creates and uses an instance of `URLCache`:

```swift
 private static func defaultConfiguration() -> URLSessionConfiguration {
    let conf = URLSessionConfiguration.default
    conf.urlCache = URLCache(memoryCapacity: 0, diskCapacity: (200 * 1024 * 1024), diskPath: "com.github.kean.Nuke.Cache")
    return conf
}
```

In the current Nuke version you don't have access to that `URLCache` instance. You'll have to initialize your own `DataLoader` with your own `URLCache` to have access to it.

**Comment by joe528** [comment]
Disk cache will be cleaned up automatically & periodically by Nuke or by iOS?

**Comment by kean** [comment]
Yes. And the default 'URLCache' created by Nuke has a 200 Mb limit. If you find it to be to large, just use a custom 'DataLoader'.
